### ISSUE TITLE
Usage of Scaffold-DbContext -Schemas and -Tables parameters could be clearer

### ISSUE THREAD

**Issue by cnicho** [dotnet/EntityFramework.Docs#1090]
I understood from the documentation that -Schemas to be used to indicate which schemas to include and -Tables to be those tables to be scaffolded within those schemas. What I got was scaffolding for ALL tables in the named schemas AND the table(s) named. To get desired result, -Schemas parameter omitted and table names qualified with schema name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [EF Core tools reference (Package Manager Console) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by waynejohn** [comment]
That did the trick. Thank you for posting this.
