### ISSUE TITLE
Missing note with the EF Core version the feature was introduced on

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#1102]
For example:

[!NOTE] This feature was introduced in EF Core 2.0.

It is probably missing in other topics as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c9bd3e-4b99-9acf-48d8-e47bc53eb54e
* Version Independent ID: 220e0a6c-d227-956a-d27a-7c88804f770c
* Content: [Global Query Filters - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/filters)
* Content Source: [entity-framework/core/querying/filters.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/filters.md)
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **divega**

**Comment by Rick-Anderson** [comment]
@maumar  given that anything below 2.1 is out of service, can I close this issue?

**Comment by roji** [comment]
Yeah, we generally do this when introducing docs for new features, and remove the note a couple of releases later. Definitely no use in going back to stuff introduced a long time ago.
