### ISSUE TITLE
Clarify what happens in relationship fixup

### ISSUE THREAD

**Issue by adisazhar123** [dotnet/EntityFramework.Docs#1235]
In reference to this sentence 

> Note that blog will also be inserted into the database because it is a new entity that is referenced by the navigation property of an entity that is already tracked by the context (post).

What happens to the old `Blog` entity? Let's say that only the current post is in the collection of `Blog.Posts`, and I change the current post's blog to a new Blog entity. Will the old blog entity be removed from DB? Do I have to explicitly call `Remove` function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f0fb981-4dec-7ff7-817b-6606f620b875
* Version Independent ID: c7517e7d-f011-a24c-53da-913771913998
* Content: [Saving Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/related-data)
* Content Source: [entity-framework/core/saving/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/related-data.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by MojtabaMontazery** [comment]
I guess the rational behaviour is to not deleting the previous blog (because e.g., it may have other posts), though I'm not sure.
