### ISSUE TITLE
Update owner aliases

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/EntityFramework.Docs#1262]

**Comment by ajcvickers** [comment]
@mairaw Are there guidelines on who the owner alias should be set to?

**Comment by bricelam** [comment]
Generally speaking...

**author**--the person who can answer questions about the content
**ms.author**--the person responsible for making decisions regarding the content. Can be a group alias

Contributors are populated based on commit authors. Individuals can be excluded if needed.

**Comment by bricelam** [comment]
Source: https://review.docs.microsoft.com/en-us/help/contribute/metadata-attributes

**Comment by ajcvickers** [comment]
Also update other ms-metadata as appropriate. See: https://github.com/dotnet/docs/blob/master/styleguide/template.md#metadata

**Comment by AndriySvyryd** [comment]
Fixed in https://github.com/dotnet/EntityFramework.Docs/pull/2736/commits/2ee9b5789f65cf92ad0d4bd1a2c6857308a29647
