### ISSUE TITLE
.Net Core Sample with Connectiong String source control warning

### ISSUE THREAD

**Issue by brubakerjeff** [dotnet/EntityFramework.Docs#1269]
Hi the .net core sample makes the following statement with a reference to this document.

"    #warning To protect potentially sensitive information in your connection string, you should move it out of source code. 
    See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
    optionsBuilder.UseSqlServer("Server=servername");"

The document above makes the following statement

"ASP.NET Core
In ASP.NET Core the configuration system is very flexible, and the connection string could be stored in appsettings.json, an environment variable, the user secret store, or another configuration source. See the Configuration section of the ASP.NET Core documentation for more details. The following example shows the connection string stored in appsettings.json."

Are the issues relating to source code control referenced in this document? Should appsettings.json be ignored, or include a file that is ignored?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by vor0nwe** [comment]
I’m assuming they’re referencing this bit:

> See the [Configuration section of the ASP.NET Core documentation](https://docs.microsoft.com/nl-nl/aspnet/core/fundamentals/configuration/index?view=aspnetcore-2.2) for more details.

That page then references [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/nl-nl/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows), which I think explains what you’re looking for.
