### ISSUE TITLE
Document in-memory database is rooted in internal service provider

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#1308]
See https://github.com/aspnet/EntityFrameworkCore/issues/9613#issuecomment-464664863

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c95e5c7e-882f-76f7-5301-2a5d1ede39d3
* Version Independent ID: 8754aa99-67a7-98ac-a51e-0ba995f96414
* Content: [Testing with InMemory - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory)
* Content Source: [entity-framework/core/miscellaneous/testing/in-memory.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/in-memory.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by xsoheilalizadeh** [comment]
The wrong document just wasted my 3 days.
Thanks EF.Docs Team :)))))
