### ISSUE TITLE
Fix documentation for query filters with navigation properties

### ISSUE THREAD

**Issue by tharidu** [dotnet/EntityFramework.Docs#1311]
According to this GitHub issue (https://github.com/aspnet/EntityFrameworkCore/issues/8881), "Filters cannot contain references to navigation properties" limitation is not there anymore. This conflicts with the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c9bd3e-4b99-9acf-48d8-e47bc53eb54e
* Version Independent ID: 220e0a6c-d227-956a-d27a-7c88804f770c
* Content: [Global Query Filters - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/filters)
* Content Source: [entity-framework/core/querying/filters.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/filters.md)
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **divega**

**Comment by Alirezanet** [comment]
yes. global filters works on navigation properties too

**Comment by ajcvickers** [comment]
Line removed that says they do not work. Still need some examples.
