### ISSUE TITLE
How to manage .NET Core 2.1 Console Application Environment Specifically

### ISSUE THREAD

**Issue by ParthiKarnan** [dotnet/EntityFramework.Docs#1338]
I'm creating a **Console Application** using  **.NET Core 2.1** with **EF Core** for receiving messages from service bus subscriptions. I want to maintain this application environment specifically. For example, I have three environments i.e **Qual, Stage, and Production** etc., Each environment has a separate connection string. How can I maintain the connection strings environment specifically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by divega** [comment]
Triage: add this to the connection string page.

**Comment by Rick-Anderson** [comment]
@ParthiKarnan see dotnet/docs#20598 which will be live soon.

**Comment by ParthiKarnan** [comment]
@Rick-Anderson - Thanks for the response. It works. Sorry for the delayed response.
