### ISSUE TITLE
Update guidance on using default values

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#1398]
See discussion here: https://github.com/aspnet/EntityFrameworkCore/issues/15070#issuecomment-477220843

* For hand-written code document:
  * Use client side default values. This ensures the defaults are consistent in the domain model.
  * Show how store-generated values work in the "normal" case--e.g. with integers
  * Show how to use option B for when both the normal way and client-side defaults are not appropriate, also mentioning C
  * Show how to get the default value into the migration if it needs to be there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f32ff95-761b-279a-f5a9-7fe859121356
* Version Independent ID: 63cc902d-8261-8185-d0a0-c48c627234b1
* Content: [Default Values - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/default-values)
* Content Source: [entity-framework/core/modeling/relational/default-values.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/default-values.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by Sergey-Nosov-GH** [comment]
Should setting default values in the parameter-less constructor of the underlying class also be an option?

For example:
```cs
class MyContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
}

public class Blog
{
    public Blog()
    {
        Rating = 3;
    }
    public int BlogId { get; set; }
    public string Url { get; set; }
    public int Rating { get; set; }
}
```

**Comment by ajcvickers** [comment]
@Sergey-Nosov-GH Can you give some details on why this is preferable to:
```C#
public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
    public int Rating { get; set; } = 3;
}
```

**Comment by Sergey-Nosov-GH** [comment]
@ajcvickers those are functionally equivalent, so your example would be fine. Nether is currently in the docs, and that is confusing. I came to this discussion from the following url:

[https://docs.microsoft.com/en-us/ef/core/modeling/relational/default-values](url)

As of right now, it has no mentions of defaults set on the underlying classes; and it makes the programmer wonder, if EF overrides such defaults, goes along with them, or what happens. Thus, more guidance would be helpful.

Thank you.

**Comment by ajcvickers** [comment]
@Sergey-Nosov-GH Yes, this issue is for adding more guidance here. See the link in the issue content above for a link to a discussion on this. I thought you were commenting on this discussion, where this pattern is covered.

**Comment by Sergey-Nosov-GH** [comment]
Oh, yes. These discussions have at least two interfaces for adding comments: one on GitHub and one as the Feedback feature on the live documentation site. As such visitor comments on the docs site end up on GitHub as well.

So, basically, just adding another vote for more examples of different ways to set defaults; the docs site is currently limited to HasDefaultValue and HasDefaultValueSql methods only.

Documentation feedback, in action. LOL
