### ISSUE TITLE
Add more examples for CRUD scenarios

### ISSUE THREAD

**Issue by rdegrove** [dotnet/EntityFramework.Docs#1453]
This is great for getting data out but simply changing the referenced object and saving existing parent changes through the EF context fails with errors about "AssociationSet is in an 'Added' state, correspnding [Parent Class] must also. Please provide examples of correctly updating such properties through EF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by jrzabott** [comment]
Came here for the same thing

**Comment by ImmutableVector** [comment]
Same. I am struggling to learn how to properly save and update many-to-many data.
