### ISSUE TITLE
Be explicit about when transactions are rolled back

### ISSUE THREAD

**Issue by hoksource** [dotnet/EntityFramework.Docs#1497]
will this automatically rollback everything after the transaction is disposed? (out of using clause)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by NickeManarin** [comment]
It says:
    // Commit transaction if all commands succeed, transaction will auto-rollback
    // when disposed if either commands fails"

I'm not sure but it looks like an "or" is missing in there.

**Comment by hoksource** [comment]
depending on the implementation it says if the transaction is disposed. it will be rollbacked

https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbtransaction.dispose?view=netframework-4.8#System_Data_Common_DbTransaction_Dispose

so i'll assume it will automatically rollback after the transaction disposed or exiting using scope.
assuming you are using sql server or azure sql server

**Comment by deivyd321** [comment]
Is there any info how rollback actually works? Situation: inside a transaction there are made some changes to the entity but the transaction is disposed. In the same service I am using the entity again from same db context, will the entity have the changes made during transaction? Is there a way to completely reset db context?

**Comment by AndriySvyryd** [comment]
@deivyd321 When a transaction is rolled back the context will be in the same state as it was before the call to `SaveChanges`.
You can call `context.Entry(entity).Reload()` to get the entity from the database. To reset the whole context it's recommended to create a new instance.

**Comment by ThatMouse** [comment]
So can we absolutely say Rollback() is NOT necessary in the catch? I see lots of examples with Rollback() in the catch, but these docs seem to say this is not necessary at least in EF Core.

`catch (Exception)
{
    transaction.Rollback();
} `

**Comment by hoksource** [comment]
> So can we absolutely say Rollback() is NOT necessary in the catch? I see lots of examples with Rollback() in the catch, but these docs seem to say this is not necessary at least in EF Core.
> 
> `catch (Exception) { transaction.Rollback(); } `

Looks like you don't need to call rollback. When the transaction dispose the roll back is automatically called. Although in some cases you might need to call them manually.

**Comment by HamzehJankhout-W** [comment]
> depending on the implementation it says if the transaction is disposed. it will be rollbacked
> 
> https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbtransaction.dispose?view=netframework-4.8#System_Data_Common_DbTransaction_Dispose
> 
> so i'll assume it will automatically rollback after the transaction disposed or exiting using scope. assuming you are using sql server or azure sql server

I think you should use rollback because in link you provided  for 4.8 and its the same for core 9 it is saying below:

>Remarks
>Dispose should rollback the transaction. However, the behavior of Dispose is provider specific, **and should not replace calling Rollback.**
