### ISSUE TITLE
Recommend using negative PK values for seed data in tables with auto-increment PKs

### ISSUE THREAD

**Issue by rynkevich** [dotnet/EntityFramework.Docs#1528]
After facing an error message like this:
``` 
The seed entity for entity type 'Entity' cannot be added because a non-zero value is required for property 'Id'. Consider providing a negative value to avoid collisions with non-seed data.
```
And reading the following issues:
https://github.com/aspnet/EntityFrameworkCore/issues/11776
https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/536

I would suggest adding a tip or a warning to [Data Seeding](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding) section with a recommendation of using negative PK values in seed data for tables with auto-increment PKs to avoid possible collisions with non-seed data.

**Comment by roji** [comment]
With https://github.com/npgsql/efcore.pg/issues/367 done on the Npgsql side in version 5.0, there shouldn't be a need to seed negative ID values any more.

**Comment by roji** [comment]
(AFAIK PostgreSQL was the only provider with this issue)
