### ISSUE TITLE
Document filtered Include

### ISSUE THREAD

**Issue by gargkapil90** [dotnet/EntityFramework.Docs#1534]
e.g: I want to include on that collection of "Post" entity in the "Blog" entity where "Title" of the "Post" entity is matching a certain condition. something as below:
context.Blogs
        .Include(blog =&gt; blog.Posts.Where(p=&gt; p.title == "someText"));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data#feedback)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by CalumJEadie** [comment]
We ran into the same issue and found we could generate the SQL required using the "LINQ" syntax. Something like

```
from b in context.Set<Blog>()
from p in context.Set<Post>().Where(p => b.BlogId == p.BlogId && p.Title == "someText").DefaultIfEmpty()
select new { b, p };
```

Feedback we would like to give on the documentation is we haven't found it so easy to understand the differences between the "LINQ" API and the "Context" API, when to use one or the other, and in particular, whether condition filtering on an include is something that is/will be supported.

**Comment by maumar** [comment]
https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include
