### ISSUE TITLE
Expand change tracking topic

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#1541]
We should cover things like automatic change detection, snapshot vs. notification entities, blobs, guidance on how to implement Equals() and GetHashCode(), etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3527ab8-2b07-a059-bd23-5f0700cfa0fc
* Version Independent ID: 1e317ee0-fe29-b37f-43ec-a0ac64e17db9
* Content: [Saving Data - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/)
* Content Source: [entity-framework/core/saving/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment]
Also that referential equality should be used for collection navigations of entities that override Equals().
And that custom types used in keys should implement IEquatable<> and IComparable<>

**Comment by paolofulgoni** [comment]
Also, how to get tracked changes (see https://github.com/aspnet/EntityFrameworkCore/issues/9237#issuecomment-317115094)
