### ISSUE TITLE
Example for 'migrations script' from and to options

### ISSUE THREAD

**Issue by ccjx** [dotnet/EntityFramework.Docs#1551]
It will be helpful to include a 'from' and 'to' example for the migration script generation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by sachinch1216** [comment]
Script-Database -From 2397823293-migration-to-add-tables -To 298239823-migration-to-add-more-tables

**Comment by sachinch1216** [comment]
Script-Migration -From 2397823293-migration-to-add-tables -To 298239823-migration-to-add-more-tables

**Comment by douglasg14b** [comment]
@sachinch1216 

>Unrecognized option '-from'

`dotnet ef migrations script -from 20191107232753_InitialCreate --context ApplicationDbContext`

**Comment by bricelam** [comment]
Omit `-from`, they're positional arguments in `dotnet ef` (they are in Script-Migration too, it just lets you specify the parameter names too because PowerShell)

**Comment by douglasg14b** [comment]
ah!

**Comment by roji** [comment]
This was already done.
