### ISSUE TITLE
Conflicting return types in sample code

### ISSUE THREAD

**Issue by zturchan** [dotnet/EntityFramework.Docs#1574]
This example code:

static MigrationBuilder CreateUser(
    this MigrationBuilder migrationBuilder,
    string name,
    string password)
    =&gt; migrationBuilder.Sql($"CREATE USER {name} WITH PASSWORD '{password}';");

Does not appear to work, as migrationBuilder.Sql returns an OperationBuilder, which appears to be incompatible with the MigrationBuilder return type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13eb107-79c2-7824-12c1-e637d2a92add
* Version Independent ID: aafc9673-c635-3cf2-6235-8577ff15d19c
* Content: [Custom Migrations Operations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/operations.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/operations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@bricelam Did we miss triaging this issue this morning? Is 3.1 correct?

**Comment by bricelam** [comment]
3.1 is fine. It's a very small change
