### ISSUE TITLE
Update CLI tools acquisition instructions for 3.0

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#1588]
This is currently covered in this page, also [3.0 breaking changes](https://docs.microsoft.com/ef/core/what-is-new/ef-core-3.0/breaking-changes) and more recently in the [CLI tool reference](https://docs.microsoft.com/ef/core/miscellaneous/cli/dotnet#ef-core-3x). 

There are several things to address:

1. This page needs to be updated with instructions on how to acquire the tools since in 3.0 they moved out-of-band.
2. The instructions added to the other two pages will always install 3.0.0-preview versions, even when we RTM, so we need separate instructions to install the RTM and preview tools.
3.  We should probably reduce duplication. The CLI reference should point to the install page for instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5747ad3-edd5-1977-883c-2cf77112306c
* Version Independent ID: d66d0616-2aa2-8be4-5ab6-24201ef00b59
* Content: [Installing Entity Framework Core](https://docs.microsoft.com/en-us/ef/core/get-started/install/)
* Content Source: [entity-framework/core/get-started/install/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/install/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
"The dotnet ef commands are included in current versions of the .NET Core SDK..." should be updated.
