### ISSUE TITLE
Create topic for relational vs. in-memory null equality/semantics

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#1612]
I couldn't find anything about this in the docs today, and it is one of the most referenced ideas from our uservoice site: http://data.uservoice.com/forums/72025-ado-net-entity-framework-ef-feature-suggestions/suggestions/1015361-incorrect-handling-of-null-variables-in-where-cl?ref=title#suggestion-1015361

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91606b46-d8a2-8824-a1ae-522f35362ec4
* Version Independent ID: 22a92f99-5e43-96d7-82d1-cd02ccdc5af8
* Content: [Querying Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/)
* Content Source: [entity-framework/core/querying/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
See https://github.com/dotnet/efcore/issues/12729
https://github.com/dotnet/efcore/issues/15722
https://github.com/dotnet/efcore/issues/18555
https://github.com/dotnet/efcore/issues/18597
https://github.com/dotnet/efcore/issues/18689
https://github.com/dotnet/efcore/issues/18725
https://github.com/dotnet/efcore/issues/19295
