### ISSUE TITLE
Unify the two async doc pages (querying/saving) into one

### ISSUE THREAD

**Issue by roji** [dotnet/EntityFramework.Docs#1722]
We have [this page for async saving](https://docs.microsoft.com/en-us/ef/core/saving/async) and [this one for async querying](https://docs.microsoft.com/en-us/ef/core/querying/async). We can unify those into a single cross-cutting async page, and place it under misc/fundamentals.

When doing this, also do #1332.

**Comment by ajcvickers** [comment]
Consider putting it under Fundamentals.
