### ISSUE TITLE
Reorganize table of contents

### ISSUE THREAD

**Issue by roji** [dotnet/EntityFramework.Docs#1726]
This is the new top-level TOC based on recent discussions:

- name: Entity Framework Core
  - **name: Welcome!** << Renamed
  - **name: Getting started** << Renamed
  - name: "Releases and planning (roadmap)"
  - name: Create a model
  - name: Manage database schemas
  - name: Query data
  - name: Save data
  - **name: Change tracking** << New
  - **name: Logging, events, and diagnostics** << New
  - **name: Testing** << New
  - **name: Miscellaneous** << New
  - name: Database providers
  - name: Tools & extensions
  - name: Command-line reference
  - name: EF Core API reference >>

The full TOC is below

- name: Entity Framework Core
  - name: Welcome!
  - name: Getting started
    - name: EF Core Overview
      - name: What is EF Core?
      - name: Getting EF Core
      - name: Your first EF Core app
    - name: ASP.NET Core tutorial >>
    - name: Blazor Server with EF Core guidance >>
    - name: WPF .NET Core tutorial
    - name: Windows Forms tutorial
    - name: Xamarin tutorial
  - name: "Releases and planning (roadmap)"
    - name: Current and planned releases
    - name: Release planning process
    - name: EF Core 5.0
      - name: High-level plan
      - name: "What's new?"
      - name: Breaking changes
    - name: EF Core 3.1
      - name: New features
      - name: Breaking changes
    - name: EF Core 2.1
    - name: Out of support
      - name: EF Core 2.2
      - name: EF Core 3.0 (Redirect to 3.1 for new features, breaking changes)
      - name: EF Core 2.0
          - name: New features
          - name: Upgrade from 1.x
      - name: EF Core 1.1
      - name: EF Core 1.0
  - name: Create a model
    - name: Overview
    - name: Entity types
    - name: Entity properties
    - name: Keys
    - name: Generated values
    - name: Concurrency tokens
    - name: Shadow and indexer properties
    - name: Property bags
    - name: Relationships
    - name: Indexes
    - name: Inheritance
    - name: Sequences
    - name: Backing fields
    - name: Value conversions
    - name: Value comparers
    - name: Data seeding
    - name: Entity type constructors
    - name: Table splitting
    - name: Owned entity types
    - name: Keyless entity types
    - name: Alternating models with same DbContext
    - name: Spatial data
    - name: Conventions
  - name: Manage database schemas
    - name: Overview
    - name: Migrations
      - name: Overview
      - name: Managing migrations
      - name: Applying migrations
      - name: Team environments
      - name: Custom operations
      - name: Use a separate project
      - name: Multiple providers
      - name: Custom history table
    - name: Create and drop APIs
    - name: Reverse engineering (scaffolding)
  - name: Query data
    - name: Overview
    - name: Load related data
        - name: Overview
        - name: Eager loading
        - name: Explicit loading
        - name: Lazy loading
        - name: Related data and serialization
    - name: Client vs. server evaluation
    - name: Tracking vs. no-tracking
    - name: Complex query operators
    - name: Raw SQL queries
    - name: Global query filters
    - name: Query tags
    - name: How queries work
  - name: Save data
    - name: Overview
    - name: Basic save
    - name: Related data
    - name: Cascade delete
    - name: Concurrency conflicts
    - name: Transactions
    - name: Disconnected entities
    - name: Explicit values for generated properties
  - name: Change tracking
    - name: Overview
    - name: Property changes
    - name: Relationship changes
    - name: Find and local queries
    - name: Accessing entity state
    - name: Notification entities
    - name: Change tracking proxies
  - name: Logging, events, and diagnostics
    - name: Overview
    - name: Simple logging
    - name: Microsoft.Extensions.Logging
    - name: ToQueryString
    - name: Events
    - name: Interceptors
    - name: Diagnostic listeners
    - name: Debug views
    - name: Event counters
  - name: Testing
    - name: Testing code that uses EF Core
    - name: EF Core testing sample
    - name: Sharing databases between tests
    - name: Test with SQLite
    - name: Test with InMemory
  - name: Miscellaneous
    - name: Supported .NET implementations
    - name: Asynchronous programming
    - name: Nullable reference types
    - name: Using dependeny injection
    - name: Collations and case sensitivity
    - name: Connection resiliency
    - name: Configuration and initialization
    - name: Connection strings
    - name: Context pooling
  - name: Database providers
    - name: Overview
    - name: Microsoft SQL Server
      - name: Overview
      - name: Function mappings
      - name: Indexes
      - name: Memory-optimized tables
      - name: Spatial data
      - name: Specify Azure SQL Database options
    - name: SQLite
      - name: Overview
      - name: SQLite limitations
      - name: Function mappings
      - name: Spatial data
      - name: Microsoft.Data.Sqlite >>
    - name: Cosmos
      - name: Overview
      - name: Work with unstructured data
      - name: Cosmos limitations
      - name: Function mappings
    - name: InMemory (for testing)
    - name: Write a database provider
    - name: Provider-impacting changes
  - name: Tools & extensions
  - name: Command-line reference
    - name: Overview
    - name: Package Manager Console (Visual Studio)
    - name: .NET Core CLI
    - name: Design-time DbContext creation
    - name: Design-time services
  - name: EF Core API reference >>

----

Original issue text:

We currently have a Fundamentals section (connection strings, logging, testing...), whose URL path is actually `miscellaneous`.

I think it's worth rethinking this a little. Some (most?) of the pages there seem like they are generally cross-cutting subjects that simply don't fit into the other categories, and in this sense they're more "miscellaneous"; does it really make sense for logging, connection resiliency, and testing to appear before "creating a model" and "querying" in the TOC? Another two examples of possibly good candidates for a miscellaneous section are an async page (#1722) and probably also the nullable reference types page (#1655), which is quite cross-cutting.

The remaining pages (connection strings, possibly also "Configuring a DbContext") could be moved/merged with "Getting started" or similar.

**Comment by smitpatel** [comment]
We should discuss a design in 3.1 timeframe.

**Comment by ajcvickers** [comment]
Assigning to @smitpatel to do the initial updates and re-directs. See also diff in https://github.com/dotnet/EntityFramework.Docs/pull/2797

**Comment by smitpatel** [comment]
Fixed in #2843
