### ISSUE TITLE
EF6: Document using App.config on .NET Core

### ISSUE THREAD

**Issue by bricelam** [dotnet/EntityFramework.Docs#1784]
There are a lot of gotcha's, and we should probably have a "here be dragons" page.

Some issues:
- You can't register ADO.NET providers here anymore https://github.com/dotnet/corefx/issues/37998
- App.config doesn't work with test runners and other tools that execute code https://github.com/dotnet/corefx/issues/32095

**Comment by ajcvickers** [comment]
See also https://github.com/aspnet/EntityFramework6/issues/1342
