### ISSUE TITLE
Make cross reference maps file available for 3rd-party providers

### ISSUE THREAD

**Issue by roji** [dotnet/EntityFramework.Docs#1811]
docfx has a feature where it publishes a [cross reference map file](http://qinezh.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-map-file), which other projects can reference, allowing their API (and conceptual) documentation to automatically link back to the project. For example, every project can reference string since docfx comes with a built-in cross reference map to the BCL types.

Can we have this file accessible somewhere (xrefmap.yml) so that 3rd-party EF Core providers can link to it? @mairaw do you want me to open this issue in a more general place?

**Comment by ajcvickers** [comment]
@mairaw And thoughts on this?

**Comment by roji** [comment]
@mairaw I've looked at this again. An xrefmap.yml for .NET itself is available at https://docs.microsoft.com/dotnet/xrefmap.yml (warning: pretty big) - this can be used by external projects generating their docs with docfx to link back to the .NET docs.

Interestingly, that references some EF-related types such as Microsoft.Extensions.DependencyInjection.EntityFrameworkCoreHealthChecksBuilderExtensions, so extensions seem to be included there - but no actual EF Core types.

On a hunch, I tried https://docs.microsoft.com/ef/xrefmap.yml, but that just gives a YAML table of contents for the conceptual docs - nothing for the API docs.

Any way you can help us route this to the right people?

**Comment by roji** [comment]
Scratch that, at least for now - it seems I've managed to get things at least partially working with [xrefService](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-services), and I can see EF Core types appearing on the Microsoft server (e.g. https://xref.docs.microsoft.com/query?uid=Microsoft.EntityFrameworkCore.DbContext), so I'm not sure anything needs to be done on the Microsoft side.

**Comment by ajcvickers** [comment]
@roji I think EntityFrameworkCoreHealthChecksBuilderExtensions comes from an extensions package, not an EF package.

**Comment by roji** [comment]
@ajcvickers yeah, I figured. In any case, the xrefmap.yml seems to be less important since all EF types seem to be covered by the xrefservice - hopefully I'm right.

**Comment by mairaw** [comment]
If you have any issues, reach out to the Docs support Teams internally or @TianqiZhang would be a good place to start
