### ISSUE TITLE
Concurrency Token vs Shadow Properties

### ISSUE THREAD

**Issue by FlippieCoetser** [dotnet/EntityFramework.Docs#1844]
Under the Shadow Properties section the .Property() method is used to configure a Shadow Property. In this section: Concurrency Tokens, The last example also uses the .Property() method but is followed by .IsRowVersion() method for to configure the property as a Timestamp. What is unclear in the documenation is appart from the fact that the property is a TimeStamp, is the property also a shadow property? The documentation should make explicit mention of this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041e7a47-a632-132a-3c9e-db46e3782a63
* Version Independent ID: a5de9c4c-56fe-416e-0801-f6acd061f25e
* Content: [Concurrency Tokens - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/concurrency#feedback)
* Content Source: [entity-framework/core/modeling/concurrency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@FlippieCoetser No. `Property` is sued to configure any property. It is only a shadow property if there isn't a matching CLR property.

Actionable: make it clear that using `Property` doesn't force a shadow property.
