### ISSUE TITLE
Documentation - What setup does and doesn't work when using EF 6.3 with .Net core?

### ISSUE THREAD

**Issue by penfold** [dotnet/EntityFramework.Docs#1883]
I'm struggling to find any documentation of how I migrate from .net framework to .net core using EF 6.3.

The project is ASP.net core with DI and using the 'connection string name' syntax on the base DbContext constructor.

e.g.

```
public class ApplicationDbContext : DbContext
{
        public ApplicationDbContext() : base("database")
        {
        }
}
```
where "database" was a connection string name in the web.config (in the .net framework) version.

This is provided via DI:

`services.AddScoped<ApplicationDbContext >();`

Please can you explain:

1. If it is possible to use the above syntax to pull a connection string from appsettings.json. (I can't seem to get it to work). Otherwise, what is the best way to do this? (Do I create and register a factory method with DI that pulls the connection string myself? 

2. Do I need to use DbProviderFactory to set up my provider if I'm using Sql Server (or Azure Sql)?

3. How do you add new migrations and how do migrations pick up their connection string? (In .net framework it would pick up the config file from the 'startup project'.) 

If I've missed the docs somewhere, please just point me at them.

Many thanks,
Paul

**Comment by bricelam** [comment]
Related to #1784
