### ISSUE TITLE
Document SQLite primitive type mapping

### ISSUE THREAD

**Issue by AdamJachocki** [dotnet/EntityFramework.Docs#1894]
Column which should be of type DateTime is of type TEXT

### Steps to reproduce

Just create simple model like:
```
class Model
{
    public Guid Id {get; set;}
    public DateTimeOffset Start {get;set;}
}

```
And create a migration.
Next, change DateTimeOffset to DateTime in migration file.
And call ctx.Database.Migrate().

In Sqlite this column is created as TEXT and not DATETIME.
This is real blocker for me. Is there anything fast that I can do to workaround this?

I am using EfCore 3 with Microsoft.Data.Sqlite

When I used nHibernate and System.Data.Sqlite, everything worked fine. 
Unfortunalety, my app has to work in MSSQL and in Sqlite at the same time. Things like converting DateTimeOffset to DateTime in Sqlite has been done in nHibernate (now in Dapper, that I use for querying). But EfCore created wrong table type. It doesn't take migration under consideration, but model.

**Comment by ErikEJ** [comment]
>> Column names are irrelevant to SQLite, Microsoft.Data.Sqlite, and EF Core. If you need it to be DATETIME, make it so:

Assume you mean "column types" ?

**Comment by bricelam** [comment]
lol, yeah. The names are pretty important...

**Comment by bricelam** [comment]
I believe this is all covered in [Data Types - Microsoft.Data.Sqlite](https://docs.microsoft.com/dotnet/standard/data/sqlite/types#column-types)
