### ISSUE TITLE
Multiple DbContexts with Configured Connection Strings

### ISSUE THREAD

**Issue by jfoshee** [dotnet/EntityFramework.Docs#1923]
It is not clear from this documentation, or the connection string documentation, how to handle configuration of the connection string with multiple DbContexts. 

That is, if my custom DbContext overrides `OnConfiguring` and sets a provider and a connection string, what happens in an ASP .NET Core app? When the practice there is to set the provider and connection string _outside_ of the DbContext.

Which DbContextOptions wins, in that case?

Must we set the provider and the connection string at the same time? Can we set the provider in the custom context and provide the connection string externally when services are configured?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b011c7a-3534-78e3-b491-addd96fb5ba1
* Version Independent ID: 371826c5-3ef2-4eef-32e9-d55c777cd9d3
* Content: [Migrations with Multiple Providers - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/providers.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/providers.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@jfoshee 

> That is, if my custom DbContext overrides OnConfiguring and sets a provider and a connection string, what happens in an ASP .NET Core app? When the practice there is to set the provider and connection string outside of the DbContext.

If two different providers are registered, then an exception will be thrown. If the same provider is registered twice, then the registration in `OnModelCreating` will be used. `OnModelCreating` is called last and non-conflicting options set there will override those passed as options to the constructor.

> Must we set the provider and the connection string at the same time? 

Yes.

> Can we set the provider in the custom context and provide the connection string externally when services are configured?

You can always inject whatever information you want into the constructor and then use it in OnConfiguring.

**Comment by jfoshee** [comment]
Thanks @ajcvickers for the additional explanation. It does sound like I can achieve what I need with some experimentation.
