### ISSUE TITLE
Add information about using foreign key properties to control relationships

### ISSUE THREAD

**Issue by freeboarder42** [dotnet/EntityFramework.Docs#1926]
The Relationship section is missing information about controlling a relationship by a foreign key property when using convention based model configuration:
If a non-nullable foreign key property exists, the relation requires a principal entity, and the deletion behaviour is set to `Cascade`.
If no or a nullable foreign key property exists, the relation requires no principal entity, and the deletion behaviour is set to `Restrict`.

**Comment by ajcvickers** [comment]
Backlog to check.
