### ISSUE TITLE
"Setup" and "set up"

### ISSUE THREAD

**Issue by xenophilios** [dotnet/EntityFramework.Docs#1930]
Just a point of English: "setup" is a noun. The verb is "set up".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649fbab8-b960-6873-14bf-188d14757fee
* Version Independent ID: f5ee3135-54c8-689c-e28b-b203b376bd6f
* Content: [Handling Concurrency Conflicts - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/concurrency)
* Content Source: [entity-framework/core/saving/concurrency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@xenophilios Please consider sending a PR to fix this.

**Comment by roji** [comment]
Fixed by #2157, but maybe we should keep this open to do a general pass for setup and set up?

**Comment by dennisseders** [comment]
> 
> 
> Fixed by #2157, but maybe we should keep this open to do a general pass for setup and set up?

@roji I can take this one away.
