### ISSUE TITLE
Document conventions API

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/EntityFramework.Docs#1937]
For users and provider writers.

- ConventionSource
- ConventionContext
- ConventionDispatcher
- ConventionBatch
- ConventionSet
- ConventionsBuilder
- ModelCustomizer
- The dangers of `IConvention*` API

Move the paragraph about conventions from "Model Bulk Configuration" to the new page and replace it with a link.
Always check whether the entity type is still in the model in OnRemoved conventions

**Comment by ajcvickers** [comment]
Update https://aka.ms/efcore-docs-conventions when done.

**Comment by ajcvickers** [comment]
Update AKA link
