### ISSUE TITLE
Docs for relational inheritance mapping

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/EntityFramework.Docs#1979]
Also mention the Metadata overloads that take a StoreObjectIdentifier

**Comment by ajcvickers** [comment]
Keywords: TPT, TPC, TPH

**Comment by NickStrupat** [comment]
> Also mention the Metadata overloads that take a StoreObjectIdentifier

Is this how EF Core knows what type to instantiate if you load the entities from a base type table? I'm currently playing with TPT in EF Core 5.0 RC2 and I'm curious how it does that.

**Comment by AndriySvyryd** [comment]
@NickStrupat More or less. We store the mapped table on each entity type and then use that to query the entities. The `StoreObjectIdentifier` overloads are used to store other table-specific information, such as different column names for each table a property is mapped to (the key properties in TPT).

**Comment by NickStrupat** [comment]
Ah ok, thanks.

So when I store a `Derived` entity and then load it from the `Set<Base>()`, EF seems to instantiate a `Derived` correctly. I'm curious how it achieves that since I don't see a discriminator column on the base table. Specifically, I'm curious of the Big-O of the performance of that mechanism. Thanks in advance if you can help me out!

**Comment by AndriySvyryd** [comment]
We generate an additional column for each type that has a bool indicating whether the row contains said type, see https://github.com/dotnet/efcore/issues/2266#issuecomment-653661902

The processing of the query results is `O(n*m)` where `n` is the number of rows and `m` is the number of types in the queried hierarchy. I can't speak to the performance of the query itself. Perhaps @smitpatel or @roji can help out if you have additional questions.
