### ISSUE TITLE
Need discussion of Value Comparers

### ISSUE THREAD

**Issue by sbsw** [dotnet/EntityFramework.Docs#1986]
So, I got this surprisingly helpful warning message, telling me that my POCO property has a value converter but no value comparer. I had followed the guidance on this page and declared a value converter, but it took a lot of digging to come up with [this SO answer](https://stackoverflow.com/a/53051419/1637105) that showed how to declare and wire up a value comparer.

The SO answer includes a bunch of undocumented magic, in particular `propertyBuilder.Metadata.SetValueConverter` and `propertyBuilder.Metadata.SetValueComparer`.

Since creation of a value converter apparently implies the necessity of creating a value comparer, please discuss this subject in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Part of #614

**Comment by ajcvickers** [comment]
Oops. That was for converters. Agree we need docs here.

**Comment by SidShetye** [comment]
Also shouldn't there be a default comparer for each primitive type? We have a custom string -> string converter but we still want a string comparer at the end of the day.

**Comment by ajcvickers** [comment]
@SidShetye There is.

**Comment by dansoper** [comment]
Is this the same as #1680?  That doesn't seem to be linked to this page, though.

**Comment by ajcvickers** [comment]
See also #1680. Make sure this relates to collection conversions.

**Comment by SidShetye** [comment]
@ajcvickers till the documentation comes up, is this the correct approach for ValueComparers to avoid warnings with custom converters?

```
property.SetValueConverter(new MyConverter<string>());
property.SetValueComparer(new ValueComparer<string>(
	(l, r) => string.Equals(l, r, StringComparison.Ordinal),
	v => StringComparer.Ordinal.GetHashCode(v),
	v => v)
);
```
and 
```
property.SetValueConverter(new MyConverter<byte[]>());
property.SetValueComparer(new ValueComparer<byte[]>(
	(l, r) => (l == null || r == null) ? (l == r) : l.SequenceEqual(r),
	v => v.GetHashCode())
);
```

where `property` comes from `modelBuilder.Model.GetEntityTypes()` -> `entityType.GetProperties()` i.e. `property` is `Microsoft.EntityFrameworkCore.Metadata.IMutableProperty` and the `.SetValueConverter()`, `.SetValueComparer()` methods come from `Microsoft.EntityFrameworkCore.MutablePropertyExtensions`

**Comment by ajcvickers** [comment]
@SidShetye Looks like you are trying to configure compares for the database type. It's the type in your model (the type that is being converted to byte[] or string) that needs  the be compared.

**Comment by SidShetye** [comment]
@ajcvickers We're transforming the values/contents, not the type itself. So `byte[]` remains `byte[]` and `string` remains `string` after the converters. The comparers seem silly/redundant but seems like it's the only way to avoid the EF Core warning. 

Thoughts?

**Comment by ajcvickers** [comment]
@SidShetye That sounds like it could be a bug. Please post a small, runnable project that reproduces this so we can investigate.

**Comment by ajcvickers** [comment]
Still need to update the fwlink.

**Comment by JimInNC** [comment]
I am hunting the internet for a good explanation of using the ValueConverter in my EF Core Db Context.  Following is a snippet from my context.  Is this snippet supposed to convert UTC from the database in to Local, and convert Local to UTC when SaveChanges() to the database?

`            ValueConverter<DateTime, DateTime> dateTimeConverter = new ValueConverter<DateTime, DateTime>(
               v => v.ToLocalTime(),
               v => DateTime.SpecifyKind(v, DateTimeKind.Utc));

            ValueConverter<DateTime?, DateTime?> nullableDateTimeConverter = new ValueConverter<DateTime?, DateTime?>(
                v => v.HasValue ? v.Value.ToLocalTime() : v,
                v => v.HasValue ? DateTime.SpecifyKind(v.Value, DateTimeKind.Utc) : v);

            foreach (var entityType in modelBuilder.Model.GetEntityTypes())
            {
                if (entityType.IsKeyless)
                {
                    continue;
                }

                foreach (var property in entityType.GetProperties())
                {
                    if (property.ClrType == typeof(DateTime))
                    {
                        property.SetValueConverter(dateTimeConverter);

                        property.SetValueComparer(new ValueComparer<DateTime>(
                            (l, r) => l == r,
                            v => StringComparer.Ordinal.GetHashCode(v),
                            v => v)
                        );
                    }
                    else if (property.ClrType == typeof(DateTime?))
                    {
                        property.SetValueConverter(nullableDateTimeConverter);

                        property.SetValueComparer(new ValueComparer<DateTime?>(
                           (l, r) => l == r,
                           v => StringComparer.Ordinal.GetHashCode(v),
                           v => v)
                       );
                    }
                }
            }
`

**Comment by ajcvickers** [comment]
@JimInNC We have [docs with many examples](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations) and sample code that can be downloaded from GitHub.

**Comment by JimInNC** [comment]
Yeah, I figured it out.  The following code allows me to manually set and
store a date as UTC.  When I read the date via the model, it comes back to
me as local time.
I wish there was a way for me NOT to have to manually set the time as UTC.
I wish the model would automatically convert it back to UTC when I save.

Anyway, that is what I wanted.  The article you referenced, I'm sure it
explains this fully.  But, I could not piece it together via that article.


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
ValueConverter<DateTime, DateTime> dateTimeConverter = new
ValueConverter<DateTime, DateTime>(
  v => v.ToUniversalTime(),
  v => DateTime.SpecifyKind(v, DateTimeKind.Local));

ValueConverter<DateTime?, DateTime?> nullableDateTimeConverter = new
ValueConverter<DateTime?, DateTime?>(
v => v.HasValue ? v.Value.ToUniversalTime() : v,
v => v.HasValue ? DateTime.SpecifyKind(v.Value, DateTimeKind.Local) : v);

foreach (var entityType in modelBuilder.Model.GetEntityTypes())
{
if (entityType.IsKeyless)
{
continue;
}

foreach (var property in entityType.GetProperties())
{
if (property.ClrType == typeof(DateTime))
{
property.SetValueConverter(dateTimeConverter);

property.SetValueComparer(new ValueComparer<DateTime>(
(l, r) => l == r,
v => StringComparer.Ordinal.GetHashCode(v),
v => v)
);
}
else if (property.ClrType == typeof(DateTime?))
{
property.SetValueConverter(nullableDateTimeConverter);

property.SetValueComparer(new ValueComparer<DateTime?>(
  (l, r) => l == r,
  v => StringComparer.Ordinal.GetHashCode(v),
  v => v)
  );
}
}
}
