### ISSUE TITLE
Document how to configure EF6 in an ASP.NET Core application

### ISSUE THREAD

**Issue by anirugu** [dotnet/EntityFramework.Docs#2017]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f431e6c-6c5f-9056-1486-99ba6b02c954
* Version Independent ID: 37943f43-c279-f190-b134-48f54ead1e38
* Content: [Connection strings and models - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/configuring/connection-strings#feedback)
* Content Source: [entity-framework/ef6/fundamentals/configuring/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/configuring/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by anirugu** [comment]
@ajcvickers  Thanks for reply Arthur, Just a little change,  I was taking about setup ef core in asp.net core.

**Comment by ajcvickers** [comment]
@anirugu https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio
