### ISSUE TITLE
Document best practices for EF Core in Blazor applications

### ISSUE THREAD

**Issue by VR-Architect** [dotnet/EntityFramework.Docs#2025]
Can MS provide guidance and code to Avoiding DbContext threading issues when using Blazor server-side? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a47bf610-692d-9d40-d85f-aec1e2a87a07
* Version Independent ID: 3c94634a-4b17-bc13-7436-0c61aea03ab6
* Content: [Configuring a DbContext - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#avoiding-dbcontext-threading-issues)
* Content Source: [entity-framework/core/miscellaneous/configuring-dbcontext.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/configuring-dbcontext.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by MisinformedDNA** [comment]
I'm having problems here too. The documented guidance is not enough. The error happens anyway.

**Comment by vincentw56** [comment]
Not sure if this will help, but adding the code below fixed this issue for me.

'services.AddDbContext<MirwDbContext>(); //MirwDbContext is the name of by DB Context'

**Comment by rkone** [comment]
The struggle for me at least, was sharing a dbcontext with more than 1 blazor component per page. A component and its subcomponent (and I assume other subcomponents) will run OnInitializedAsync() in parallel, leading to a concurrency error if they share the same dbcontext.  Best practice then, is to design your components so they can use a separate dbcontext. 
This is definitely an issue.  With this still fresh in my mind, the only solutions I have come up with so far was to join everything into 1 supercomponent, or to use different dbcontexts but then orchestrate a save among them all.  
I will be looking further into how to minimize the "editing" dbcontext, and using components that work with self-contained dbcontexts (and don't need to save).  Definitely a big change in process, coming from Silverlight where it was fine to load everything into one great big dbcontext...

**Comment by ajcvickers** [comment]
@JeremyLikness I think we can close this now, right?

**Comment by JeremyLikness** [comment]
@ajcvickers In my opinion, yes.
