### ISSUE TITLE
Document simple logging (DbContextOptionsBuilder.LogTo)

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#2085]
See https://github.com/dotnet/efcore/issues/15403#issuecomment-562332863

**Comment by jwooley** [comment]
By setting this as "Undocumented feature" does that mean that LogTo is not planned to be a supported solution going forward?

**Comment by ajcvickers** [comment]
@jwooley No. It means it needs to be documented.
