### ISSUE TITLE
Update the no-tracking query behavior for EF Core 3.0 and later

### ISSUE THREAD

**Issue by YaroslavKormushyn** [dotnet/EntityFramework.Docs#2097]
EF Core 3.0 and later doesn't use identity resolution for no-tracking queries as per https://docs.microsoft.com/en-us/ef/core/querying/tracking#identity-resolution.
The weak map should be moved to a 'Previous versions' segment.

Let me know if I'm missing something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c972607d-c880-2892-5542-df34bcb45634
* Version Independent ID: 29913f5e-5297-d13f-3d4a-961271959934
* Content: [How Queries Work - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/how-query-works#feedback)
* Content Source: [entity-framework/core/querying/how-query-works.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/how-query-works.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
The section is already up-to-date for EF Core 3.1
Tracking query still do identity resolution through changetracker.

**Comment by YaroslavKormushyn** [comment]
@smitpatel you're right, tracking queries do that. What I found is that the no-tracking queries don't.
This is not the case in this doc, which states: 
> If this is a no-tracking query, EF checks if the data represents an entity already in the result set for this query
> If so, the existing entity is returned (1)
which is not true due to [this doc](https://docs.microsoft.com/en-us/ef/core/querying/tracking#identity-resolution).

I didn't have the time to set up an example and try it, I'm only working with the docs.

**Comment by smitpatel** [comment]
Yes, this page is outdated. I missed which page you reported the issue on.
