### ISSUE TITLE
Provide alternatives for converting all decimals to double

### ISSUE THREAD

**Issue by ghost** [dotnet/EntityFramework.Docs#2098]
The most common scenario is when someone wants to perform
 modelBuilder.Entity&lt;MyEntity&gt;().Property(e =&gt; e.DecimalProperty).HasConversion&lt;double&gt;();
for all decimal properties in their models. Maybe you should add a link to walkarounds to do this, like the detailed here https://github.com/dotnet/efcore/issues/10784

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbc4d900-28a8-9c04-2443-7407f15a684f
* Version Independent ID: 545bb0b5-f15b-584e-cef7-7283a0e0729f
* Content: [SQLite Database Provider - Limitations - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations)
* Content Source: [entity-framework/core/providers/sqlite/limitations.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/sqlite/limitations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
We will document this for 6.0 as part of https://github.com/dotnet/efcore/issues/10784
