### ISSUE TITLE
Be clear and upfront about the involved considerations when using EF Core in production

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/EntityFramework.Docs#2106]
While EF Core is good at abstracting many things away, there are some general aspects that need to be handled before going to production to avoid common pitfalls:

- **Functional and integration testing**. It's important to replicate the production environment as close as possible (same provider, same type of database as well as other services the app depends on) to both to find issues in the app code as to catch breaking changes when upgrading EF Core or other dependencies. (e.g. adding or upgrading frameworks like ASP.NET Core, Application Insights, Serilog or Automapper can affect EF Core in unexpected ways)
- **Performance and stress testing** with representative loads. The naive usage of some features doesn't scale well (e.g. multiple collection Includes, heavy use of lazy loading, conditional queries on non-indexed columns, massive updates/inserts with store-generated values, lack of concurrency handling, large models, inadequate cache policy)
- **Security**. (e.g. handling of connection strings, database permissions for non-deployment operation, input validation for raw SQL, encryption for sensitive data)
- Make sure **logging and diagnostics** are sufficient and usable (e.g. appropriate logging configuration, query tags, Application Insights)
- **Error recovery**. Prepare contingencies for common failure scenarios (e.g. version rollback, fallback servers, scale-out and load balancing, DoS mitigation, data backups)
- Application **deployment and migration**. See #1879 and #814
- Detailed **examination and testing of generated migrations**. The shape of the schema as well as the column types cannot be easily changed once the tables contain production data. (e.g. on SqlServer nvarchar(max) and decimal(18, 2) are rarely the best types for columns mapped to string and decimal properties). See #2188
- As a consequence of the above at least **intermediate-level knowledge of the underlying database server** is essential for success.

**Comment by AndriySvyryd** [comment]
@JonPSmith FYI

**Comment by roji** [comment]
@Rick-Anderson submitted the excellent #2668, do we think we need more on this?
