### ISSUE TITLE
LINQ vs "Context Based API"

### ISSUE THREAD

**Issue by CalumJEadie** [dotnet/EntityFramework.Docs#2118]
We've used the "Collection selector references outer in a where clause" to help us generate a query like the following

```sql
SELECT *
FROM Blogs
LEFT JOIN (
  SELECT p.PostId, p.Title
  FROM Posts as p
  WHERE p.OrganisationId = <some org id>
) AS x ON b.BlogId = x.BlogId
```

using LINQ like the following

```
from b in context.Set<Blog>()
from p in context.Set<Post>().Where(p => b.BlogId == p.BlogId && p.OrganisationId = <some org id>).DefaultIfEmpty()
select new { b, p };
```

I wasn't sure from the documentation on this page, whether the complex query operators require the use of the "LINQ" API or whether it's possible to use the "Context API" as generally we've been using code like the following so far

```
context.Blogs
  .Include(blog => blog.Posts)
```

Perhaps you could provide clarification on this page as to the relationship between the "LINQ" and "Context" APIs and confirm whether the "LINQ" API allows you to express things that can't be expressed with the "Context" API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1acf84-126c-f01d-b39a-ab077819351f
* Version Independent ID: 5d3bdd6d-ad0e-e306-5aef-0d5adea892b6
* Content: [Complex Query Operators - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#feedback)
* Content Source: [entity-framework/core/querying/complex-query-operators.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/complex-query-operators.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@CalumJEadie I think you are referring to [query syntax verse method-call syntax](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/query-syntax-and-method-syntax-in-linq) Query syntax is also known as query comprehension syntax.

Both APIs support the same set of features. The compiler builds an expression tree that looks the same in either case.
