### ISSUE TITLE
Performance Guidance

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/EntityFramework.Docs#212]
Some things already mentioned in various docs. Would be nice to have one doc dedicated to all the perf tips.

Some ideas:
- [ ] Streaming vs buffering (IEnumerable/IAsyncEnumerable vs. ToList/ToListAsync). Possibly refer from https://docs.microsoft.com/en-us/ef/core/querying/how-query-works#when-queries-are-executed.
- [ ] Split/single queries
- [ ] Perf counters
- [ ] Tracking vs no-tracking (per query, per type, etc.)
- [ ] DbContext pooling
- [ ] Compiled queries
- [ ] FromSql for complex queries
- [ ] INotifyPropertyChanged
- [ ] Key generation: sequence vs identity
- [ ] Batching (configuring sizes, networking conditions, etc)

**Comment by bartlannoeye** [comment]
Any progress on this? In particular looking for SQLite+UWP perf tips.

**Comment by rowanmiller** [comment]
@bartlannoeye the perf issues in UWP/SQLite are bugs that we're working with the .NET Native team to address. Unfortunately there isn't really any way to work around them.

**Comment by rowanmiller** [comment]
Putting this on the backlog. A lot of the perf guidance from EF6 doesn't really apply to EF Core and I'm not sure how much we need to document here. I think it probably makes sense to wait a bit longer and see what kind of things aren't obvious to most folks, and then document these.

**Comment by Rick-Anderson** [comment]
@divega a Short perf doc would be beneficial and would surely grow as customers contributed their perf findings. https://github.com/aspnet/Docs/pull/964 has a short EF perf section. It would be better to move that section to this repo and the ASP.NET Core perf doc could point to it.

**Comment by divega** [comment]
@Rick-Anderson The short EF section I read in the PR seems like a good start of a page on the EF Core side. I posted some comment that hopefully can make it better. 

There a few things remaining here that of course also have value, although at this point I think I would leave the "Key generation: sequence vs identity" part out.

**Comment by roji** [comment]
Consult https://docs.microsoft.com/en-us/ef/ef6/fundamentals/performance/perf-whitepaper

**Comment by Rick-Anderson** [comment]
> Consult https://docs.microsoft.com/en-us/ef/ef6/fundamentals/performance/perf-whitepaper

But isn't Rowan correct

> A lot of the perf guidance from EF6 doesn't really apply to EF Core

**Comment by roji** [comment]
@Rick-Anderson yeah, this should be reviewed case-by-case, lots of things are relevant, some probably aren't... This is one of the major docs tasks on my plate.
