### ISSUE TITLE
EF Core

### ISSUE THREAD

**Issue by juszkiem** [dotnet/EntityFramework.Docs#2122]
Excellent article. Can someone do the same for the Entity Core? I did the example in EF Core 3.1 code first and my data object does not showup in the object tree.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73b2e5a-9526-e664-a2da-556717d344e1
* Version Independent ID: 93442b78-6869-139c-bdbc-9a1efa21b7a6
* Content: [Databinding with WPF - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/wpf#feedback)
* Content Source: [entity-framework/ef6/fundamentals/databinding/wpf.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/databinding/wpf.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
See https://github.com/dotnet/efcore/issues/20044 and https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/plan#ef-core-platforms-experience
