### ISSUE TITLE
Returns

### ISSUE THREAD

**Issue by yellowpanda** [dotnet/EntityFramework.Docs#2128]
AddAsync returns ValueTask&lt;EntityEntry&lt;TEntity&gt;&gt; not  Task&lt;EntityEntry&lt;TEntity&gt;&gt; as written on this page... at least in version 3.1.2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be049303-fa58-10f2-1213-29047dfb8626
* Version Independent ID: f85bffe8-6c80-e6f2-e061-69fb66b5f501
* Content: [DbSet&lt;TEntity&gt;.AddAsync(TEntity, CancellationToken) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.addasync?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbSet`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbSet`1.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
Filed https://github.com/dotnet/EntityFramework.ApiDocs/issues/73

It is likely issue in doc generation tool. We can close this one for now and re-activate if we need to react in source code.
