### ISSUE TITLE
Registering value converters for a type

### ISSUE THREAD

**Issue by Leon99** [dotnet/EntityFramework.Docs#2129]
> There is currently no way to specify in one place that every property of a given type must use the same value converter. This feature will be considered for a future release.

What about replacing IValueConverterSelector (e.g. as shown here - https://andrewlock.net/strongly-typed-ids-in-ef-core-using-strongly-typed-entity-ids-to-avoid-primitive-obsession-part-4/#replacing-the-default-ivalueconverterselector-with-a-custom-implementation)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#built-in-converters)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
@Leon99 The service is also replaced by the currently configured provider and the implementation can change in the future, so while this is a decent workaround it's too fragile to be generally recommended. A better solution is tracked by https://github.com/dotnet/efcore/issues/10784

**Comment by Leon99** [comment]
That was quick, thanks! What about workarounds suggested in https://github.com/dotnet/efcore/issues/10784, is any of them better than the one I referenced?
Oh and I really hope you won't kill workarounds until an officially recommended solution appears.

**Comment by AndriySvyryd** [comment]
@Leon99 The other workarounds don't dependent on the current provider, but do depend on the order in which they are called relative to the other configuration.

**Comment by Leon99** [comment]
IMHO, there is a huge difference between

> There is currently no way to 

and 

> it's too fragile to be generally recommended

This difference may cost too much, both to customer and to MS - I was just about to jump the ship to Postgres, in part due to this issue.

@AndriySvyryd thanks/дякую anyway
