### ISSUE TITLE
Updating owned collection only adds, never removes.

### ISSUE THREAD

**Issue by lp-ly** [dotnet/EntityFramework.Docs#2130]
Is this intended behavior or am I not following the example properly? How can we delete entries from the collection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#feedback)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
@lp-ly Could you show the code you are using ti delete the entries?

**Comment by lp-ly** [comment]
I figured out what the problem was. In my situation, we queried with AsNoTracking. So without tracking you can only add entries then, correct?
