### ISSUE TITLE
Breadcrumb path are not links

### ISSUE THREAD

**Issue by JasonCard** [dotnet/EntityFramework.Docs#2131]
Breadcrumbs after "Entity Framework" such as "Entity Framework Core" and "Overview" are no links, but is this by-design?
e.g. Entity Framework / Entity Framework Core / Overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b15cd4c-9cba-c0e2-7618-7d621a3c5936
* Version Independent ID: f4681bc6-57be-6e69-cad9-776ce64d93bd
* Content: [Overview of Entity Framework Core - EF Core](https://docs.microsoft.com/en-us/ef/core/#feedback)
* Content Source: [entity-framework/core/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@JasonCard It's a consequence of how the docs platform has evolved. Welcome to hear ideas on how to make it better.

**Comment by JasonCard** [comment]
@ajcvickers I see, I compared the breadcrumbs of EF with ASP.NET and others products. Their breadcrumbs usually start with "Docs" and only the last breadcrumb is not a link. So I suggest the following for consistent look and feel:
![breadcrumb](https://user-images.githubusercontent.com/18313964/75175728-bdcd3d80-56e7-11ea-84e1-a66ecd28e142.png)

**Comment by ajcvickers** [comment]
@JasonCard And this can be done without breaking any existing links?

**Comment by JasonCard** [comment]
@ajcvickers I'm not familiar with editing the breadcrumbs, so I'd recommend to reach out to an expert on how to make this change.

**Comment by smitpatel** [comment]
cc: @scottaddie

**Comment by ajcvickers** [comment]
Team notes: we're happy for the docs team to suggest/make changes here, but relatively speaking this seems low priority compared to many other things, so closing.

**Comment by scottaddie** [comment]
@ajcvickers I have this item on my to-do list.
