### ISSUE TITLE
Document connection management when using SQLite in-memory mode

### ISSUE THREAD

**Issue by EmadBustati** [dotnet/EntityFramework.Docs#2135]
I spend some time to understand how to change my `InMemory` provider to `SQLite(Data Source=:memory:)` in my Integration tests.

My problem was related to how to persistent the SQLite memory DB while running my integration tests, and finally found the solution [here](https://github.com/dotnet/efcore/issues/5086#issuecomment-210783773).

Please mention how to [open the connection](https://github.com/dotnet/efcore/issues/5086#issuecomment-210783773) in the [SystemTest](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#customize-webapplicationfactory) ConfigureServices in the [docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite)

**Comment by ajcvickers** [comment]
@bricelam I found these two issues, but neither seem to really be a dupe:
* https://github.com/dotnet/EntityFramework.Docs/issues/1304
* https://github.com/dotnet/EntityFramework.Docs/issues/430

**Comment by bricelam** [comment]
https://github.com/dotnet/efcore/issues/16103

**Comment by bricelam** [comment]
It's briefly mentioned here, but with no real guidance on *how*: [In-memory databases - Microsoft.Data.Sqlite](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/in-memory-databases)
