### ISSUE TITLE
What replaces RelationalQueryModelVisitor in .net Core 3?

### ISSUE THREAD

**Issue by norcino** [dotnet/EntityFramework.Docs#2140]
What replaced **RelationalQueryModelVisitor** in the latest version of .net Core?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d91292-59de-23dc-a696-6a2e02941174
* Version Independent ID: d724555c-2100-be32-63dc-aebf3e2ae47a
* Content: [RelationalQueryModelVisitor Class (Microsoft.EntityFrameworkCore.Query)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.query.relationalquerymodelvisitor?view=efcore-2.2&viewFallbackFrom=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Query/RelationalQueryModelVisitor.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Query/RelationalQueryModelVisitor.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
EF Core 3.0 does not use QueryModel coming from Remotion.Linq hence it is altogether removed without any replacement.

State exact scenario you are trying to achieve by using this class. 

P.S. https://en.wikipedia.org/wiki/XY_problem

**Comment by norcino** [comment]
Thank you for the information, I suggest to update the documentation pointing the reader to the new documentation for newer versions of the framework.

**Comment by smitpatel** [comment]
I believe https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.query.relationalquerymodelvisitor?view=efcore-2.2#applies-to section should cover that it does not apply to latest version.

Let us know if we can improve further in any way.
