### ISSUE TITLE
Why is EF core so damn complicated

### ISSUE THREAD

**Issue by himanshukodwani** [dotnet/EntityFramework.Docs#2149]
```c#
public class Location
{
   [Key]
   [MaxLength(50)]
   public string LocationName{get; set;}
   [MaxLength(100)]
   public string Description {get; set;}
   public ICollection<Warehouses> WarehousesWithThisAsParentLocation {get; set;} 
}

public class Warehouses
{
    [Key]
    [MaxLength(50)]
    public string WarehouseName{get; set;}
    [MaxLength(100)]
    public string Description {get; set;}
    [Required]
    public Location ParentLocation{get; set;}
    public ICollection<Bins> BinsWithThisAsWarehouse {get; set;} 
}

public class Bins
{
    [Key]
    [MaxLength(50)]
    public string Bin{get; set;}
    [MaxLength(100)]
    public string Description {get; set;}
    [Required]
    public Warehouses Warehouse{get; set;}
}
```

My problem is :
1) The above class will produce migration errors regarding certain ForeignKey declaration etc. which EF should do by itself. 
2) While seeding data it will produce another exception which it shouldn't.

Seeding code :

```c#
var loc = new Locations() { LocationCode = "LOC-DEFAULT", City = "Home", Country = "Home" };
modelBuilder.Entity<Locations>().HasData(loc);
var wh = new Warehouses() { WarehouseName = "WH-DEFAULT", Location = loc };
modelBuilder.Entity<Warehouses>().HasData(wh);
modelBuilder.Entity<Bins>().HasData(new Bins() { BinName = "BIN-DEFAULT", Warehouse = wh });
```

Exception message -
The seed entity for entity type 'Bins' cannot be added because it has the navigation 'Warehouse' set. To seed relationships you need to add the related entity seed to 'Warehouses' and specify the foreign key values {'WarehouseForeignKey'}. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the involved property values.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffdc279-736f-92e4-6de3-cce42342cd6b
* Version Independent ID: d3d4904a-f60d-a0a2-b634-cb12671fa7a2
* Content: [Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/entity-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/entity-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
> The above class will produce migration errors regarding certain ForeignKey declaration etc. which EF should do by itself.

Can you please post the migration errors you're seeing?

>  The seed entity for entity type 'Bins' cannot be added because it has the navigation 'Warehouse' set. To seed relationships you need to add the related entity seed to 'Warehouses' and specify the foreign key values {'WarehouseForeignKey'}. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the involved property values.

This is explained [in the docs](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#limitations-of-model-seed-data) - key values (primary, foreign) must be explicitly specified in the migrations even if they're database-generated in normal usage.

**Comment by himanshukodwani** [comment]
After reading the linked document, I got the point, why seeding relations in my case aren’t working. This document also explains a manual way which I think will suit me.
Thanks for your prompt reply.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by roji** [comment]
Happy it's working out for you.
