### ISSUE TITLE
Add a link to EFCore.NamingConventions

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/EntityFramework.Docs#2156]
https://github.com/efcore/EFCore.NamingConventions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8875eb79-99ff-662b-c189-86eb8cdb5488
* Version Independent ID: fa03a7fa-1922-7aa1-acda-b0d216ef37cb
* Content: [Tools & Extensions - EF Core](https://docs.microsoft.com/en-us/ef/core/extensions/?source=docs#feedback)
* Content Source: [entity-framework/core/extensions/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/extensions/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ErikEJ
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment]
Resolved by #2272
