### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AnthonyMonterrosa** [dotnet/EntityFramework.Docs#2162]
In the sentence fragment "Here your learn about two different approaches to use EF6: ...", I think "your" is a misspelling of "you".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d06865-183f-140e-a1f1-099cd36b93fe
* Version Independent ID: 401fd98e-66bf-acbc-50f8-16af48c90adf
* Content: [Get started with Entity Framework 6 - EF6](https://docs.microsoft.com/en-us/ef/ef6/get-started#feedback)
* Content Source: [entity-framework/ef6/get-started.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/get-started.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
