### ISSUE TITLE
Collation

### ISSUE THREAD

**Issue by git-hub-user** [dotnet/EntityFramework.Docs#2172]
I think this article should address collation, as I experienced that linq queries to an in memory database with Contains() and StartsWith() calls match case-sensitively, whereas the same queries will match on the actual database depending on its collation.
So far, I have not found a way to set the collation of my in memory database and don't expect it will be possible.
Also, I do not want to work around it, by changing my production code to work properly with in memory databases injected from unit tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c95e5c7e-882f-76f7-5301-2a5d1ede39d3
* Version Independent ID: 8754aa99-67a7-98ac-a51e-0ba995f96414
* Content: [Testing with InMemory - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory#feedback)
* Content Source: [entity-framework/core/miscellaneous/testing/in-memory.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/in-memory.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Covered by #1304.
