### ISSUE TITLE
How many total open connections are supported?

### ISSUE THREAD

**Issue by veljkoz** [dotnet/EntityFramework.Docs#2173]
I landed on this page investigating how many connections can be opened - it would be helpful if there's some further links or similar to find this answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ffd31b0-e8fc-bbee-a6d8-93b095db487f
* Version Independent ID: da24dfb6-c202-5e29-40d0-3b9ed5362595
* Content: [Connection management - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-management)
* Content Source: [entity-framework/ef6/fundamentals/connection-management.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/connection-management.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@veljkoz EF doesn't put any limit on the number of open connections.
