### ISSUE TITLE
Upgrade to 3.1 broke the IPluralizer interface

### ISSUE THREAD

**Issue by aquacat123** [dotnet/EntityFramework.Docs#2178]
Hi, i just upgraded to 3.1 and now my code will not build.  The error indicates that the IPluralizer interface could not be found even though the class is using the Microsoft.EntityFrameworkCore.Design namespace?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71858966-7500-916c-00fd-a4f80969c42b
* Version Independent ID: 35ad739b-40e2-a2c7-f1f7-25f598b4e8ff
* Content: [IPluralizer Interface (Microsoft.EntityFrameworkCore.Design)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.design.ipluralizer?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Design/IPluralizer.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Design/IPluralizer.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@aquacat123 This is because the design package, which contains the IPluzalizer, was made a development dependency. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dip for how to update your package references.

**Comment by xr280xr** [comment]
@ajcvickers Making it a development dependency makes sense, but the mitigations example does not seem to make a difference. I updated my csproj from 

`<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.3" />`
to
```
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.3">
      <PrivateAssets>all</PrivateAssets>
      <!-- Remove IncludeAssets to allow compiling against the assembly -->
      <!--<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
</PackageReference>
```
and still get "The type or namespace name 'IPluralizer' does not exist in the namespace 'Microsoft.EntityFrameworkCore.Design' could not be found"
