### ISSUE TITLE
Identity gets dropped from owner entity key

### ISSUE THREAD

**Issue by aramikm** [dotnet/EntityFramework.Docs#2179]
You can check the detail in the following link:
https://stackoverflow.com/questions/60645980/ownsone-drops-identity-from-tables-key
---

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by ajcvickers** [comment]
@roji This could be an Npgsql migrations issue.

**Comment by ajcvickers** [comment]
@roji Ping.

**Comment by roji** [comment]
This turned out to be a bug in the Npgsql provider, see https://github.com/npgsql/efcore.pg/issues/1324. [A fix is out](https://github.com/npgsql/efcore.pg/pull/1325) and should get merged for 3.1.4.
