### ISSUE TITLE
Default Value

### ISSUE THREAD

**Issue by rogerzanelato** [dotnet/EntityFramework.Docs#2181]
What's the default value for MaxBatchSize, or how does EF Core decide the number of entitites to send in the same query, against a database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c728ef5-fb24-a14c-2fa9-b3b1e9490dc6
* Version Independent ID: 551e287f-25ad-194e-2eac-988b2d7e5b3c
* Content: [RelationalOptionsExtension.MaxBatchSize Property (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.relationaloptionsextension.maxbatchsize?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/RelationalOptionsExtension.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/RelationalOptionsExtension.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment]
Currently there's no default max size, so it's only limited by the database (e.g. 1000 rows, 65536 characters or 2100 parameters (whichever is reached first) for SQL Server)

But we do plan to change this: https://github.com/dotnet/efcore/issues/9270
