### ISSUE TITLE
LINQ query execution

### ISSUE THREAD

**Issue by balukantu** [dotnet/EntityFramework.Docs#2183]
Hi Team,

I am trying to use Azure Cosmos Provider in the project. I have a question regarding the LINQ execution in CosmosDB.

Below is the LINQ:

class Student
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
    }

var student = dbContext.Students.Where( p => p. StudentId >3 )

In SQL, the LINQ query will be executed at the server-side and the filtered records will be sent to the end-user.

Now, my question is, where the execution of LINQ will happen in Cosmos provider?  Will it get all records to in-memory and filtering happens at the client-side or is it like SQL provider execution?

**Comment by AndriySvyryd** [comment]
Simple queries like this will be translated to the server. If for any reason the query can't be translated an exception will be thrown instead of evaluating in memory.
