### ISSUE TITLE
2 demo code errors

### ISSUE THREAD

**Issue by CeciAc** [dotnet/EntityFramework.Docs#2189]
@heroxxCN commented on [Mon Mar 16 2020](https://github.com/dotnet/EntityFramework.Docs.zh-cn/issues/65)

```C#
    using (var context = new EntitySplittingEntities())
    {
        var person = new Person
        {
            FirstName = "John",
            LastName = "Doe",
            Email = "john@example.com",
            Phone = "555-555-5555"
        };

        context.People.Add(person);
        context.SaveChanges();

        foreach (var item in context.People)
        {
            Console.WriteLine(item.FirstName);
        }
    }
```
The two context.People in the above code should be changed to context.Person

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6484e79b-a6d1-4b2a-eb4a-8c3db41b07bb
* Version Independent ID: 4f869927-97ed-8a4b-572a-faa6708016f7
* Content: [设计器实体拆分-EF6](https://docs.microsoft.com/zh-cn/ef/ef6/modeling/designer/entity-splitting)
* Content Source: [entity-framework/ef6/modeling/designer/entity-splitting.md](https://github.com/dotnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/ef6/modeling/designer/entity-splitting.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

---

@srvbpigh commented on [Mon Mar 16 2020](https://github.com/dotnet/EntityFramework.Docs.zh-cn/issues/65#issuecomment-599328457)

Hello, @heroxxCN
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ajcvickers** [comment]
> The two context.People in the above code should be changed to context.Person

Why so?

**Comment by heroxxCN** [comment]
> > The two context.People in the above code should be changed to context.Person
> 
> Why so?

Cause the entity name is Person,not People.
SQL codes in the "Create Database" section are like this:
CREATE TABLE [dbo].[Person] (
.......

The Table name in database is "Person",when it come to entity,It's name is "Person"  too.

**Comment by ajcvickers** [comment]
@heroxxCN Yes, but pluralization of DbSet names is on by default, and I don't see any indications in the walk through that it should be switched off.
