### ISSUE TITLE
Please discuss how `HasConversion` interacts with the change tracker

### ISSUE THREAD

**Issue by togakangaroo** [dotnet/EntityFramework.Docs#2196]
Does the change tracker consider the value before or after conversion? In other words, if I have a `JObject` property and a conversion serializing it to a string, can I change its contents and have it save because the serialized value would be different than the loaded value?

**Comment by AndriySvyryd** [comment]
Change tracker uses value comparers for this, see https://github.com/dotnet/EntityFramework.Docs/issues/1986 and https://github.com/dotnet/EntityFramework.Docs/pull/2192

**Comment by ajcvickers** [comment]
@togakangaroo To add to what Andriy said, we compare without converting mostly because the other way would require many conversions just to detect changes, which would be very slow.

#2192 is documenting exactly your case.
