### ISSUE TITLE
Generating migration scripts without `GO` statements?

### ISSUE THREAD

**Issue by jessebarocio** [dotnet/EntityFramework.Docs#2197]
Is it possible to generate a script without `GO`s following each statement? `GO` is not a T-SQL statement and only works in sqlcmd or SQL Management Studio. 

We use a custom script runner/migration utility that can't handle `GO` statements. Right now I have to manually remove them to get the utility to execute EF migration scripts. I'm sure I'm not the only one who doesn't use sqlcmd to automate database migrations, so if it's possible to remove them then having this documented would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@bricelam Can you clarify when we generate GO and when we don't?

**Comment by bricelam** [comment]
You can override the internal service to avoid generating GO:
```c#
class NoGoSqlGenerationHelper : SqlServerSqlGenerationHelper
{
   public NoGoSqlGenerationHelper(RelationalSqlGenerationHelperDependencies dependencies)
        : base(dependencies)
    {
    }

    public override string BatchTerminator => Environment.NewLine;
}
```
```c#
options
    .UseSqlServer(...)
    .ReplaceService<ISqlGenerationHelper, NoGoSqlGenerationHelper>();
```

**Comment by bricelam** [comment]
Beware, however, that some statements need to be separated by batches so you may run into issues.
