### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by vladimirsakic** [dotnet/EntityFramework.Docs#2206]
This doesn't work. I created simple database with one table with Id column (not identity) and sequence, and did everything as in this article, and it's not working. I get error "Cannot insert the value NULL into column 'Id', table 'Test.dbo.Table'; column does not allow nulls. UPDATE fails."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf3bd16-1954-0974-500a-8f04d0a5ed5f
* Version Independent ID: 2818db16-6495-65ca-fe64-7792d6a2d1b5
* Content: [Sequences - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/sequences#feedback)
* Content Source: [entity-framework/core/modeling/sequences.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/sequences.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@vladimirsakic I have not been able to reproduce any issues here--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public static class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Order());
            context.Add(new Order());
            
            context.SaveChanges();
        }

        using (var context = new SomeDbContext())
        {
            var orders = context.Set<Order>().ToList();
        }
    }
}

public class SomeDbContext : DbContext
{
    private static readonly ILoggerFactory
        Logger = LoggerFactory.Create(x => x.AddConsole()); //.SetMinimumLevel(LogLevel.Debug));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasSequence<int>("OrderNumbers");

        modelBuilder.Entity<Order>()
            .Property(o => o.OrderNo)
            .HasDefaultValueSql("NEXT VALUE FOR OrderNumbers");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .EnableSensitiveDataLogging()
            .UseSqlServer(Your.SqlServerConnectionString);
}

public class Order
{
    public int Id { get; set; }
    public int OrderNo { get; set; }
}
```

**Comment by vladimirsakic** [comment]
@ajcvickers your example works fine. Difference is that I used database first and scaffolding. I also made things very simple and it's definitely not working

**Comment by ajcvickers** [comment]
@vladimirsakic The code above configures the model so that when a database is created using Migrations (or EnsureCreated) it will have the appropriate sequence created in the schema and column configuration in the table to use the sequence. If you're using database first, then you'll need to set this up in the database using whatever mechanism you are using to evolve the database schema.

**Comment by vladimirsakic** [comment]
Thanks but I'm aware of all this, I have sequence in database, scaffold created this line:
modelBuilder.HasSequence<int>("DefinicijaPoljaSequence")
                .StartsAt(0)
                .HasMin(0);
and this one:
modelBuilder.Entity<DefinicijaPolja>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
......

I changed last one to:
entity.Property(e => e.Id).HasDefaultValueSql("NEXT VALUE FOR DefinicijaPoljaSequence");

But it's not working, it's trying to add record to database with Id = null
I'm pretty sure that it's ef bug

**Comment by vladimirsakic** [comment]
@ajcvickers Thanks but I'm aware of all this, I have sequence in database, scaffold created this line:
modelBuilder.HasSequence("DefinicijaPoljaSequence")
.StartsAt(0)
.HasMin(0);
and this one:
modelBuilder.Entity(entity =>
{
entity.Property(e => e.Id).ValueGeneratedNever();
......

I changed last one to:
entity.Property(e => e.Id).HasDefaultValueSql("NEXT VALUE FOR DefinicijaPoljaSequence");

But it's not working, it's trying to add record to database with Id = null
I'm pretty sure that it's ef bug

**Comment by ajcvickers** [comment]
@vladimirsakic Please post the database schema for that table so that I can attempt to reproduce.

**Comment by ilcos91** [comment]
I have the same error. To reproduce this error it may be useful to have the column "Id" of the Order table as primary key or simply not null.
Any help would be appreciated.

**Comment by ajcvickers** [comment]
@ilcos91 Can you post the database schema for the table?

**Comment by ilcos91** [comment]
That's my table

CREATE TABLE [dbo].[CHATGROUPS](
	[CHATGROUPS_CONTEXT_CODE] [int] NOT NULL,
	[CHATGROUPS_COMPANY_CODE] [int] NOT NULL,
	[CHATGROUPS_ID] [int] NOT NULL,
	[CHATGROUPS_DESCRIPTION] [varchar](50) NULL,
	[CHATGROUPS_ISPUBLIC] [bit] NOT NULL,
	[CHATGROUPS_ISCONTEXTVISIBLE] [bit] NOT NULL,
	[CHATGROUPS_ISDEPARTMENT] [bit] NOT NULL,
	[CHATGROUPS_MEMBER_VISIBLE] [bit] NOT NULL,
 CONSTRAINT [PK_CHATGROUPS] PRIMARY KEY CLUSTERED 
(
	[CHATGROUPS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

**Comment by ilcos91** [comment]
@ajcvickers could you post your database schema for the table? In this way the example could be more clear.

**Comment by vladimirsakic** [comment]
I made test database, you can reproduce bug:

USE [master]
GO
/****** Object:  Database [Testt]    Script Date: 3.4.2020. 10:14:36 ******/
CREATE DATABASE [Testt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Testt', FILENAME = N'C:\Users\vsakic\Testt.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Testt_log', FILENAME = N'C:\Users\vsakic\Testt_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Testt] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Testt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Testt] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Testt] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Testt] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Testt] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Testt] SET ARITHABORT OFF 
GO
ALTER DATABASE [Testt] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Testt] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Testt] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Testt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Testt] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Testt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Testt] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Testt] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Testt] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Testt] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Testt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Testt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Testt] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Testt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Testt] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Testt] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Testt] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Testt] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Testt] SET  MULTI_USER 
GO
ALTER DATABASE [Testt] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Testt] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Testt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Testt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Testt] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Testt] SET QUERY_STORE = OFF
GO
USE [Testt]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Testt]
GO
USE [Testt]
GO
/****** Object:  Sequence [dbo].[DefinicijaPoljaSequence]    Script Date: 3.4.2020. 10:14:36 ******/
CREATE SEQUENCE [dbo].[DefinicijaPoljaSequence] 
 AS [int]
 START WITH 0
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 2147483647
 CACHE 
GO
/****** Object:  Table [dbo].[DefinicijaPolja_Istorija]    Script Date: 3.4.2020. 10:14:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DefinicijaPolja_Istorija](
	[Id] [int] NOT NULL,
	[ContainerId] [int] NOT NULL,
	[VrstaPoljaId] [int] NOT NULL,
	[VrstaPoljaDetaljId] [int] NULL,
	[SistemskiNaziv] [nvarchar](50) NOT NULL,
	[Labela] [nvarchar](500) NOT NULL,
	[TipPodatkaPoljaId] [int] NOT NULL,
	[RoditeljPoljeId] [int] NULL,
	[Obavezno] [bit] NOT NULL,
	[ValidacioniIzraz] [nvarchar](max) NULL,
	[Lista] [bit] NOT NULL,
	[RedniBroj] [int] NULL,
	[MaksimalnaDuzina] [int] NULL,
	[ReadOnly] [bit] NOT NULL,
	[DatumKreiranja] [datetime] NOT NULL,
	[IdSesijeKreiranja] [bigint] NOT NULL,
	[DatumIzmene] [datetime] NULL,
	[IdSesijeIzmene] [bigint] NULL,
	[JeObrisano] [bit] NOT NULL,
	[VremenskiZig] [timestamp] NOT NULL,
	[SysStartTime] [datetime2](7) NOT NULL,
	[SysEndTime] [datetime2](7) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [ix_DefinicijaPolja_Istorija]    Script Date: 3.4.2020. 10:14:36 ******/
CREATE CLUSTERED INDEX [ix_DefinicijaPolja_Istorija] ON [dbo].[DefinicijaPolja_Istorija]
(
	[SysEndTime] ASC,
	[SysStartTime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DefinicijaPolja]    Script Date: 3.4.2020. 10:14:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DefinicijaPolja](
	[Id] [int] NOT NULL,
	[ContainerId] [int] NOT NULL,
	[VrstaPoljaId] [int] NOT NULL,
	[VrstaPoljaDetaljId] [int] NULL,
	[SistemskiNaziv] [nvarchar](50) NOT NULL,
	[Labela] [nvarchar](500) NOT NULL,
	[TipPodatkaPoljaId] [int] NOT NULL,
	[RoditeljPoljeId] [int] NULL,
	[Obavezno] [bit] NOT NULL,
	[ValidacioniIzraz] [nvarchar](max) NULL,
	[Lista] [bit] NOT NULL,
	[RedniBroj] [int] NULL,
	[MaksimalnaDuzina] [int] NULL,
	[ReadOnly] [bit] NOT NULL,
	[DatumKreiranja] [datetime] NOT NULL,
	[IdSesijeKreiranja] [bigint] NOT NULL,
	[DatumIzmene] [datetime] NULL,
	[IdSesijeIzmene] [bigint] NULL,
	[JeObrisano] [bit] NOT NULL,
	[VremenskiZig] [timestamp] NOT NULL,
	[SysStartTime] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEndTime] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL,
 CONSTRAINT [PK_FieldDefinition] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [dbo].[DefinicijaPolja_Istorija] )
)
GO
ALTER TABLE [dbo].[DefinicijaPolja] ADD  DEFAULT (getdate()) FOR [DatumKreiranja]
GO
ALTER TABLE [dbo].[DefinicijaPolja] ADD  DEFAULT ((0)) FOR [IdSesijeKreiranja]
GO
ALTER TABLE [dbo].[DefinicijaPolja] ADD  DEFAULT ((0)) FOR [JeObrisano]
GO
ALTER TABLE [dbo].[DefinicijaPolja] ADD  DEFAULT (getutcdate()) FOR [SysStartTime]
GO
ALTER TABLE [dbo].[DefinicijaPolja] ADD  DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999')) FOR [SysEndTime]
GO
ALTER TABLE [dbo].[DefinicijaPolja]  WITH NOCHECK ADD  CONSTRAINT [FK_FieldDefinition_FieldDefinition_Roditelj] FOREIGN KEY([RoditeljPoljeId])
REFERENCES [dbo].[DefinicijaPolja] ([Id])
GO
ALTER TABLE [dbo].[DefinicijaPolja] CHECK CONSTRAINT [FK_FieldDefinition_FieldDefinition_Roditelj]
GO
USE [master]
GO
ALTER DATABASE [Testt] SET  READ_WRITE 
GO

**Comment by ajcvickers** [comment]
@vladimirsakic @ilcos91 It doesn't seem like either of those databases are setup to use a sequence for generating default values. Here's the database that EF creates from the code I posted above:

```sql
CREATE SEQUENCE [dbo].[OrderNumbers] 
 AS [int]
 START WITH 1
 INCREMENT BY 1
 MINVALUE -2147483648
 MAXVALUE 2147483647
 CACHE 
GO
/****** Object:  Table [dbo].[Order]    Script Date: 4/3/2020 2:18:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderNo] [int] NOT NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Order] ADD  DEFAULT (NEXT VALUE FOR [OrderNumbers]) FOR [OrderNo]
GO
USE [master]
GO
ALTER DATABASE [ConTest] SET  READ_WRITE 
GO
```

Notice that:
* A sequence has been defined and configured
* The column is configured to take default values from the sequence

Your database will need to have a similar configuration to this.

**Comment by vladimirsakic** [comment]
Why do I need to setup database, can I setup ef to take default values from the sequence, without modifying database?

**Comment by ajcvickers** [comment]
@vladimirsakic No--this is configured in the database schema.

**Comment by vladimirsakic** [comment]
ok, then it's not a bug, but it would be useful if I could. I'm not owner of the database, and they're using sequence for id. I'm using ef, and now I'm taking sequence numbers with sql command, and then set id before doing insert with ef. It would be helpful if I can setup ef to use sequence for id like: entity.Property(e => e.Id).HasDefaultValueSql("NEXT VALUE FOR DefinicijaPoljaSequence"); even if database is not setup like this.
