### ISSUE TITLE
Stuck? - c# Data Source Configuration Wizard

### ISSUE THREAD

**Issue by martinandersen3d** [dotnet/EntityFramework.Docs#2207]
I'm following this tutorial, but I'm stuck here, since "Category" does not show up. What should I do?

https://stackoverflow.com/questions/60790953/tutorial-stuck-c-sharp-data-source-configuration-wizard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73b2e5a-9526-e664-a2da-556717d344e1
* Version Independent ID: 93442b78-6869-139c-bdbc-9a1efa21b7a6
* Content: [Databinding with WPF - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/wpf#feedback)
* Content Source: [entity-framework/ef6/fundamentals/databinding/wpf.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/databinding/wpf.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@martinandersen3d See https://github.com/dotnet/efcore/issues/19993. Data binding in WPF is broken for both EF6 and EF Core. @diverdan92 indicates that these issues should be filed directly through Visual Studio to reach the WPF team.

/cc @JeremyLikness
