### ISSUE TITLE
Previous Docs

### ISSUE THREAD

**Issue by sadiqkhoja** [dotnet/EntityFramework.Docs#2211]
I would like to see the docs of previous version, where are those?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b15cd4c-9cba-c0e2-7618-7d621a3c5936
* Version Independent ID: f4681bc6-57be-6e69-cad9-776ce64d93bd
* Content: [Overview of Entity Framework Core - EF Core](https://docs.microsoft.com/en-us/ef/core/)
* Content Source: [entity-framework/core/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@sadiqkhoja The docs are not separated by version--we already had a considerable amount of docs written across multiple versions before this became available, and we don't have the resources to go back and re-write them. Instead, we call out in the docs when a certain feature requires a certain version.
