### ISSUE TITLE
Warnings and Errors when I follow the tutorial

### ISSUE THREAD

**Issue by Gorboram** [dotnet/EntityFramework.Docs#2218]
I am trying to follow this tutorial, but I am encountering big problems.

First, the command "Install-Package EntityFramework" gives the warning "Missing function body in function declaration...".

Then, when I get to the step where I run "Enable-Migrations", I get the error "The term 'Enable-Migrations' is not recognized as the name of a cmdlet, function, script file, or operable program...".

Is this tutorial defunct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002d162b-8595-ad48-7ef8-2cd10194a3b4
* Version Independent ID: a29d6e0c-f9eb-86d9-f82e-0e9fc41b5a0d
* Content: [Code First Migrations - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Gorboram If the package does not install, then nothing else is going to work. I suggest you follow up by filing an issue against NuGet and including full details of the error you are seeing.
