### ISSUE TITLE
table name rules?

### ISSUE THREAD

**Issue by BDTomasz** [dotnet/EntityFramework.Docs#2220]
Anywhere I can find rules around what characters the table name can contain???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffdc279-736f-92e4-6de3-cce42342cd6b
* Version Independent ID: d3d4904a-f60d-a0a2-b634-cb12671fa7a2
* Content: [Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#table-name)
* Content Source: [entity-framework/core/modeling/entity-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/entity-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
You can find that in the documentation for the database server you are using.
