### ISSUE TITLE
supid answer for a stupid question...? table name rule

### ISSUE THREAD

**Issue by BDTomasz** [dotnet/EntityFramework.Docs#2221]
So if I'm reading about data annotations for the framework on this page of documentation and I ask a question because I can't see relevant information here, it doesn't link from this documentation to other info I need to be aware of, then I get an answer that is a dead end? As long as you get paid I guess...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffdc279-736f-92e4-6de3-cce42342cd6b
* Version Independent ID: d3d4904a-f60d-a0a2-b634-cb12671fa7a2
* Content: [Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#table-name)
* Content Source: [entity-framework/core/modeling/entity-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/entity-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Since there are so many different database providers and every database's documentation lives in different place, your best bet would be to use a search engine to find the docs you need. Since you want links to those documentations, here you go
- SqlServer - https://docs.microsoft.com/en-us/sql/?view=sql-server-ver15
- Sqlite - https://sqlite.org/docs.html
- Npgsql - http://www.npgsql.org/doc/
- MySql - https://dev.mysql.com/doc/

You can navigate to the documentation of the database you are using and find the naming rules it has for table names.

**Comment by BDTomasz** [comment]
Thanks for that. I do know how to use a search engine, funnily enough, landed on this article from a search, however my point is (and in my own opinion of course), this page is a dead end. It's not obvious to me after reading this article what I should be referring to next when trying to figure out what characters or patterns I can use to decorate the table names with and there's no reference that it is dependant on the DB used, who knows what EF Core does under the hood, maybe if I give it a name like Funny{}$#Chars, EF will strip items that are not allowed or replace. Rather unclear article in general. That's my point.

**Comment by BDTomasz** [comment]
Forgive the sarcasm, it will pass as with the disappearance of the corona virus...

**Comment by smitpatel** [comment]
>who knows what EF Core does under the hood, maybe if I give it a name like Funny{}$#Chars, EF will strip items that are not allowed or replace.

As the case with corona virus, prepare for the worst. Don't trust EF Core to do any additional processing and pass only name which is allowed by database. You don't want your application to die.

**Comment by ajcvickers** [comment]
Discussed with the team and we feel it is reasonable to assume that EF Core will use whatever you specify for table names.
