### ISSUE TITLE
Scaffold Overwrites Custom Filters

### ISSUE THREAD

**Issue by cgountanis** [dotnet/EntityFramework.Docs#2228]
How can I have scaffold not overwrite my custom protected override void OnModelCreating code? Is there a simple way to have these entries in a separate file?

**Comment by ErikEJ** [comment]
Use the OnModelCreatingPartial partial method in a partial class. (If you use EF Core 3 or EF Core Power Tools)

**Comment by cgountanis** [comment]
> Use the OnModelCreatingPartial partial method in a partial class. (If you use EF Core 3 or EF Core Power Tools)

Oh I found a nice example on stack. Is there any official documentation or maybe I recommended file placement suggestion? There are times where I clear out the models folder for rescaffold so it might be nice to have it out of that folder?

**Comment by cgountanis** [comment]
Thanks
