### ISSUE TITLE
One migration set - detect active database provider

### ISSUE THREAD

**Issue by Sebazzz** [dotnet/EntityFramework.Docs#2234]
&gt; If operations can only be applied on one provider (or they're differently between providers), use the ActiveProvider property to tell which provider is active.

There are extension methods available now: 

```
if (migrationBuilder.IsSqlite()) {
     // SQlite!
}
```

Example: https://github.com/Sebazzz/PokerTime/blob/master/src/PokerTime.Persistence/Migrations/20200323211733_AddSymbolSets.cs#L17

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b011c7a-3534-78e3-b491-addd96fb5ba1
* Version Independent ID: 371826c5-3ef2-4eef-32e9-d55c777cd9d3
* Content: [Migrations with Multiple Providers - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/providers.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/providers.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
Superseded by #1554
