### ISSUE TITLE
An example on using identity as FK

### ISSUE THREAD

**Issue by akshaybabloo** [dotnet/EntityFramework.Docs#2238]
It would be good to have an example of using Identities `IdentityUser` as a foreign key

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#single-navigation-property-1)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@akshaybabloo Can you provide some more details on exactly what you mean?

**Comment by akshaybabloo** [comment]
@ajcvickers Maybe this - https://stackoverflow.com/q/60942405/3782963 - can help

**Comment by ajcvickers** [comment]
@akshaybabloo Customization of the Identity model is documented here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1 (However, be aware that because of the generics in the model, any customization is quite difficult.)

**Comment by akshaybabloo** [comment]
@ajcvickers I am not trying to customise the identity model, I am just trying to add a foreign key, example a posts model that points to its user (IdentityUser), but when I do that, it creates a new table called `IdentityUser` similar to `AspNetUsers`, which is not what I intended.

**Comment by ajcvickers** [comment]
@akshaybabloo Something like this:

```C#
public class ApplicationDbContext : IdentityDbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        
        modelBuilder.Entity<Post>();
    }
}

public class Post
{
    public int Id { get; set; }
    
    public string UserId { get; set; }
    public IdentityUser User { get; set; }
}
```

**Comment by akshaybabloo** [comment]
This works, but when trying to add a cross-context then it doesn't work.

https://stackoverflow.com/questions/61042691/cross-context-foreign-key-in-entityframework-core

**Comment by ajcvickers** [comment]
@akshaybabloo You'll need to map `IdentityUser` in your model in the normal way, then edit generated migrations so that your migrations don't try to create/modify the table that already exists for Identity. See #2725.

**Comment by akshaybabloo** [comment]
OK, thanks @ajcvickers
