### ISSUE TITLE
Please fix the link for the referenced blog post

### ISSUE THREAD

**Issue by krptodr** [dotnet/EntityFramework.Docs#2239]
Can you please update the link for the Blog Post?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af0b8bf0-8cdb-e5ae-0344-e2e281f41969
* Version Independent ID: 90d5f106-4bee-1075-3e43-054556a301df
* Content: [Handling transaction commit failures - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-resiliency/commit-failures?source=docs#feedback)
* Content Source: [entity-framework/ef6/fundamentals/connection-resiliency/commit-failures.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/connection-resiliency/commit-failures.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@krptodr Unfortunately, almost all old .NET blog links were broken a few years ago. We'll look at finding the new links an updating them in our docs.
