### ISSUE TITLE
Update on EFCore limitations

### ISSUE THREAD

**Issue by balukantu** [dotnet/EntityFramework.Docs#2246]
As per the documentation, below are the temporary limitations on EFCore.

1. Even if there is only one entity type without inheritance mapped to a container it still has a discriminator property.
2. Entity types with partition keys don't work correctly in some scenarios
3. Include calls are not supported
4. Join calls are not supported

I would like to know the update/ fix on those temporary limitations.

Apart from the above limitations, Does EFCore is supporting transactions that the client has initiated like EntityFramework?

Also, Is there any list of scenarios that don't work properly if Entities has partition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a102d2e4-41d0-4619-a463-3e3862311a01
* Version Independent ID: a80b35f2-09dc-da67-df83-253ca5fd78cb
* Content: [Azure Cosmos DB Provider - Limitations - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/limitations)
* Content Source: [entity-framework/core/providers/cosmos/limitations.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/cosmos/limitations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
> Even if there is only one entity type without inheritance mapped to a container it still has a discriminator property.

You can remove the discriminator property by calling `Entity().HasNoDiscriminator()`

> Entity types with partition keys don't work correctly in some scenarios

See https://github.com/dotnet/efcore/issues/17318

> Include calls are not supported

See https://github.com/dotnet/efcore/issues/16920

> Join calls are not supported

See https://github.com/dotnet/efcore/issues/17314

> Apart from the above limitations, Does EFCore is supporting transactions that the client has initiated like EntityFramework?

Yes, but Cosmos DB doesn't

> Also, Is there any list of scenarios that don't work properly if Entities has partition?

No. This is referring to the queries that would work in-partition, but wouldn't work cross-partition and EF Core doesn't properly recognize that they are in-partition
