### ISSUE TITLE
Information on what to do with ancient migrations

### ISSUE THREAD

**Issue by MRVDH** [dotnet/EntityFramework.Docs#2247]
We have a project with several hundreds of code first migrations, which are taking up a lot of space in our git code repository. I haven't been able to find any documentation on how to safely remove those old migrations from the code base and clean the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by roji** [comment]
Regardless of what you'd do with EF Core, even if you deleted these migrations they'd still be in your git history and take up space. In any case, if you're looking to squash many migrations, the relevant issue is https://github.com/dotnet/efcore/issues/2174.

**Comment by MRVDH** [comment]
Alright, I'll try one of those solutions. Thanks for the link :)
