### ISSUE TITLE
Need details about how cancellationToken is handled

### ISSUE THREAD

**Issue by bgillet** [dotnet/EntityFramework.Docs#2248]
When using SaveChangesAsync with a CancellationToken, documentation doesn't explain how token is used by the method. Does it throw an OperationCancelledException ? When is it checked ? Only at the beginning of the method ? If no exception has been thrown because IsCancellationRequested is used instead of the ThrowIfCancellationRequested method then how to know if data have been saved or not ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: aece550f-d934-0dae-c3ac-0d9b3660bd1a
* Version Independent ID: aebedd48-a65c-c92e-ab4f-f7b4fe467e03
* Content: [DbContext.SaveChangesAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/fr-fr/dotnet/api/microsoft.entityframeworkcore.dbcontext.savechangesasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DFR-FR%26k%3Dk(Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@bgillet Generally, EF passes the cancellation token to the underlying ADO.NET provider (e.g. SqlClient) and any behavior is defined by that ADO.NET provider.

Putting this on the backlog to figure out if we can document cancellation tokens in a more effective way.

**Comment by roji** [comment]
Removing to consider improving docs on this in the 5.0 timeframe.
