### ISSUE TITLE
No HasNoKey in EF Core?

### ISSUE THREAD

**Issue by MCcoder52** [dotnet/EntityFramework.Docs#2251]
HasNoKey() is not present in EF Core 2.2. Please include updated information on reading data from tables/Views with No Keys!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc10f39-8fe5-e856-5839-9aa5e9d435c6
* Version Independent ID: 10ddba97-42d2-0cda-3e7f-eaeb4fda74b0
* Content: [Keyless Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types#feedback)
* Content Source: [entity-framework/core/modeling/keyless-entity-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/keyless-entity-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
EF Core 2.2 used query types for this:
```C#
modelBuilder.Query<BlogPostsCount>().ToView("View_BlogPostCounts")
```

**Comment by gregdasney** [comment]
Here is the old documentation https://github.com/dotnet/efcore/issues/8127

**Comment by 1937forza** [comment]
### ### ### ### 

> 

> 

- > 

- [ ] 

- [ ] kknkk****
