### ISSUE TITLE
All examples don't work for me: all give errors like 'column u.Discriminator' is not found

### ISSUE THREAD

**Issue by CeciAc** [dotnet/EntityFramework.Docs#2254]
Hi team, 
I moved this from here: https://github.com/dotnet/EntityFramework.Docs.it-it/issues/6

@strawberryfield commented yesterday
All examples don't work for me: all give errors like 'column u.Discriminator' is not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10898c5-abee-1843-cfff-b2707f8a079a
* Version Independent ID: d9399618-488e-20b1-f707-35a191b95cc1
* Content: [Inheritance - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#feedback)
* Content Source: [entity-framework/core/modeling/inheritance.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/inheritance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by ajcvickers** [comment]
@strawberryfield Likely you need to update your database schema to reflect the changes in your model. See [managing database schemas](https://docs.microsoft.com/en-us/ef/core/managing-schemas/)

**Comment by strawberryfield** [comment]
I don't have a Column 'u.Discriminator' in my database, I don't want such column in the database and that column is not in the model. 
If a remove derived class (in which there is only a new method) all works fine.
