### ISSUE TITLE
Concurrency handling with Cosmos DB Provider

### ISSUE THREAD

**Issue by M0ns1gn0r** [dotnet/EntityFramework.Docs#2257]
Is this behavior specific to SQL provider only or it also applies to Cosmos DB? Should I do any additional configuration or `_etag` is used as concurrency token automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649fbab8-b960-6873-14bf-188d14757fee
* Version Independent ID: f5ee3135-54c8-689c-e28b-b203b376bd6f
* Content: [Handling Concurrency Conflicts - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/concurrency)
* Content Source: [entity-framework/core/saving/concurrency.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@M0ns1gn0r Its essentially the same in terms of the patterns used, but limited to _ETags. We will update the documentation accordingly.
