### ISSUE TITLE
Looking for reference applications on Entity Framework

### ISSUE THREAD

**Issue by sdg002** [dotnet/EntityFramework.Docs#2269]
Hi All,
I am looking for a moderately complex sample application(s) built on EF which could be used as an example for an upcoming project.

Any suggestions?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=netcore-cli#feedback)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro
