### ISSUE TITLE
object-database mapper vs object-relational mapper

### ISSUE THREAD

**Issue by isaeed** [dotnet/EntityFramework.Docs#2271]
the docs says, "Entity Framework Core (EF Core) is a modern object-database mapper" but "Entity Framework 6 (EF6) is an object-relational mapper " . so the confusion is , "object-database mapper" and "object-relational mapper" are different concepts? or same? please explain. thanks

**Comment by ErikEJ** [comment]
EF Core also supports non-relational data sources, like Cosmos DB and MongoDb

**Comment by brownbonnie** [comment]
Was about to ask this same question - thanks for explaining!
