### ISSUE TITLE
Update document regarding the accumulation of Transient services

### ISSUE THREAD

**Issue by akovac35** [dotnet/EntityFramework.Docs#2278]
Using transient services my cause memory leaks: https://github.com/dotnet/extensions/issues/1785

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a47bf610-692d-9d40-d85f-aec1e2a87a07
* Version Independent ID: 3c94634a-4b17-bc13-7436-0c61aea03ab6
* Content: [Configuring a DbContext - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#feedback)
* Content Source: [entity-framework/core/miscellaneous/configuring-dbcontext.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/configuring-dbcontext.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by akovac35** [comment]
Hi Team - regarding my remark, I would like to point out that users really don't expect the described behavior from the DI framework. It might be better to just introduce a braking change and make it perform as expected instead of documenting it - this is something EF Core team is doing regularly and it shows because the framework is getting better and better. Otherwise, how exactly are you planning to document this? Don't use transients in case of ... ? It just doesn't seem right :)

**Comment by ajcvickers** [comment]
@akovac35 The behavior of transients with D.I. is out of the scope of EF to change, as is the way these work with ASP.NET Core requests. For other D.I. scenarios, such as Blazor, we are looking into better guidance as well as providing appropriate hooks, etc. in EF Core to make this more of a pit of success.

**Comment by akovac35** [comment]
Hi, this request was more an attempt to surface the issue with DI as it impacts the whole of ASP.NET Core. If I waren’t so prudent with tracing to put one in dispose method, we would have discovered the problem only in production while obviously not knowing what is happening. There is another request with the same title with DI team and I hope EF Core team will put some weight on it in the sense of offering some guidance on declaring braking changes ;) or just to increase the priority. I don’t think there are many users who are aware that transients are released only when scope ends. Regards, Aleksander
