### ISSUE TITLE
Migration: naming issue 

### ISSUE THREAD

**Issue by Urgen-Dorjee** [dotnet/EntityFramework.Docs#2284]
I have a dbcontext name: MyContext.

I ran Add-Migration command to create a migration schema with the same name (MyContext).

>**PM>Add-Migration "MyContext" -context MyContext -p xyzProject** 

Migration schema created without any error, however when you try to seed the data it won't create a table based on migration schema rather its ignore if there was no migration schema present in the project directory. 

I am not sure why? Add-Migration command won't complain about the naming convention. Why did it creates migration schema at the first place?

Thanks
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
Duplicate of https://github.com/dotnet/efcore/issues/17509. Fixed in 5.0.0-preview2

**Comment by Urgen-Dorjee** [comment]
I was using VS2019 version 16.5.3 when the migration schema was generated and now it is updated to version: 16.5.4. Your [reference](https://github.com/dotnet/efcore/issues/17509#issuecomment-594163379) thread has stated that it should now throw an exception with having same name. However I don't see this happens; as it has generated migration schema happily. Should not cli throws an exception! as I spent quite amount of time on debugging.

**Comment by bricelam** [comment]
It will throw an exception if you update to EF Core 5.0.0-preview.2

**Comment by Urgen-Dorjee** [comment]
Alright, will try this in future. Thanks 
I don't need any help as of now hence closing this ticket.
