### ISSUE TITLE
Update for EF Core 3.x

### ISSUE THREAD

**Issue by jayarka** [dotnet/EntityFramework.Docs#2285]
The tools are no longer included with Core 3.0 and must be installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [EF Core tools reference (Package Manager Console) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by jacobestell** [comment]
I just upgraded a project from 2.2 to 3.1 and I'm running into an issue with the tools not being installed also. It would be great for this article to be updated with the new information from 3.0 and 3.1

**Comment by mattfrear** [comment]
I'm starting a new .NET Core 3.1 project and agree that this page is incorrect. It says the tools are included but they're not.
