### ISSUE TITLE
Describe what this method does?

### ISSUE THREAD

**Issue by bzaar** [dotnet/EntityFramework.Docs#2288]
And why does the generated method duplicate the whole database schema on every migration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3900da3-e08d-b079-090a-e3553ac923da
* Version Independent ID: 66207f14-c252-d1c0-29ac-72c5f5b3f1b1
* Content: [Migration.BuildTargetModel(ModelBuilder) Method (Microsoft.EntityFrameworkCore.Migrations)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.migrations.migration.buildtargetmodel?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Migrations/Migration.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Migrations/Migration.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@bzaar Please provide some more details on what you are trying to use this method for. It is typically used internally to build the target model for the model-diffing part of Migrations.

**Comment by bzaar** [comment]
I am not using it directly. The method was generated using ```dotnet ef migrations add```. 

My main question is why does the generated method duplicate the whole database schema on every migration? I would only expect to see the diff there. My database schema is quite large so I was surprised to see it duplicated in every migration. Or am I doing something wrong here?

**Comment by ajcvickers** [comment]
> why does the generated method duplicate the whole database schema on every migration

I don't understand what you mean by this. This method creates an EF model. It doesn't directly do anything to the database schema.

**Comment by bzaar** [comment]
Sorry for not making myself clear. Maybe I should step back a bit. 

I'm setting up EF Core 3.1.3 migrations against an existing SQL Server database.

This is what I've done so far:

 1. Scaffold my model from the existing database.
 2. Add the InitialCreate migration.
 3. Remove the contents of the Up() method in InitialCreate.
 4. Update database to create the __EFMigrationsHistory table.
 5. Add back the contents of the Up() method.

Then I added a property to an entity class and ran ```dotnet ef add migration```.

Now looking at the BuildTargetModel method of the second migration I see that it contains pretty much the same code as MyDbContextModelSnapshot.BuildModel. I.e. it lists all entities and all their properties and relationships. This seems strange to me as I would only expect to see the differences in migration code.

Is it by design that the whole schema, including tables that have not changed, is duplicated in every migration's BuildTargetModel()?

**Comment by smitpatel** [comment]
Migration.BuildTargetModel stores the model which will be created as a result of that particular migration. ModelSnapshot will have same content as last migration's target model. It helps dotnet ef in the case snapshot file is removed.

**Comment by ajcvickers** [comment]
@bzaar Yes.

**Comment by bzaar** [comment]
OK thanks for taking the time to clear up my doubts.

**Comment by bzaar** [comment]
Just out of curiosity, under what scenario might BuildTargetModel() for a non-final and non-initial migration be called?

**Comment by AndriySvyryd** [comment]
@bzaar It is used to provide supplemental information for some operations, like the column types for InsertDataOperation

**Comment by levanlongktmt** [comment]
@AndriySvyryd @ajcvickers from my view I see it's too much code, could I empty this method after migrations has been applied ?

**Comment by AndriySvyryd** [comment]
@levanlongktmt If you are not planning to reapply the migrations the recommended approach is to squash them. Currently you'd need to do this manually, but we are [working on making this easier](https://github.com/dotnet/efcore/issues/2174).

**Comment by ravindUwU** [comment]
Hi @smitpatel 🙂,

> It helps dotnet ef in the case snapshot file is removed.
> (from https://github.com/dotnet/EntityFramework.Docs/issues/2288#issuecomment-614758680)

By "snapshot file", were you referring to the file that contains the class that extends `Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot`?

In which case, is it safe to delete the designer files if the corresponding snapshot file is retained? 🤔
