### ISSUE TITLE
Breadcrumb link is broken 

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#2291]
If you click on the Entity Framework link in the breadcrumb at the very top of the page, you’ll get directed to 404 page. It points to https://docs.microsoft.com/en-us/ef/index.yml instead of the landing page https://docs.microsoft.com/en-us/ef/. 

I suspect the fix is a just a tweak in the files used to generate the breadcrumb or the index.

PS: Good job EF folks on the new landing page. Much improved signal to noise ratio! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=netcore-cli#feedback)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Submitted a fix in #2292

**Comment by wadepickett** [comment]
Thanks @smitpatel, I was on it but you got it in before I did.  :)

**Comment by ajcvickers** [comment]
Thanks @divega. Good to hear from you. :-)
