### ISSUE TITLE
Keyless attribute should not be on general documentation

### ISSUE THREAD

**Issue by Domyouji** [dotnet/EntityFramework.Docs#2294]
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

According to https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#use-a-c-attribute-to-indicate-that-an-entity-has-no-key the Keyless attribute is not going to be until ef core 5.0 but it is listed in the general documentation for the keyless entities.

https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types?tabs=data-annotations

**Comment by lajones** [comment]
I could add something to the note at the top of the page saying that the Data Annotation is not available til 5.0 if you like?
