### ISSUE TITLE
Why are model generator "fixes" in the documentation and not in the code?

### ISSUE THREAD

**Issue by jameslear** [dotnet/EntityFramework.Docs#2298]
This workaround was very helpful.  Thank you!

However, why does the model generator use HashSet and ICollection and not an ObservableListSource by default?  If there's no penalty for ObservableListSource, can the generator be changed to work out of the box for newbies like me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93ad154e-e7a6-0ce7-4bb3-8ea56532624b
* Version Independent ID: 19a924ea-6e54-0df8-ace6-702a5bdbb2bc
* Content: [Databinding with WinForms - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/winforms?redirectedfrom=MSDN)
* Content Source: [entity-framework/ef6/fundamentals/databinding/winforms.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/databinding/winforms.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
ObservableListSource has more overhead. You should only use it when needed for data binding or similar.
