### ISSUE TITLE
Please add an example for Unit Testing 

### ISSUE THREAD

**Issue by subhroneeldey** [dotnet/EntityFramework.Docs#2301]
For EFCore Cosmos implementation. Please provide information regarding Unit tests. How do we mock the EFContext.

I tried using InMemory Database. This leads to problem as the OnConfiguring method is overridden for Cosmos implementation.
It threw an exception: 
>>>
System.InvalidOperationException: 'Services for database providers 'Microsoft.EntityFrameworkCore.InMemory', 'Microsoft.EntityFrameworkCore.Cosmos' have been registered in the service provider. Only a single database provider can be registered in a service provider. If possible, ensure that Entity Framework is managing its service provider by removing the call to UseInternalServiceProvider. Otherwise, consider conditionally registering the database provider, or maintaining one service provider per database provider.'
>>>

![contextMocking](https://user-images.githubusercontent.com/28774788/79765194-ee2a0480-8343-11ea-8cd1-ae14bd2f07eb.PNG)

![overrideOnConfiguring](https://user-images.githubusercontent.com/28774788/79765434-3ea16200-8344-11ea-8b35-e4fa4189da8d.PNG)

I tried mocking the Context, but the DbSet inside the Context could not be overridden and throws an exception

**Comment by ajcvickers** [comment]
@subhroneeldey We are currently working on updated guidance-see https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/. I will hopefully get back to this soon and add samples.

**Comment by subhroneeldey** [comment]
Hi Arthur,

Please provide any code samples if available

Thanks, Subhroneel
