### ISSUE TITLE
Note on collection navigations is wrong

### ISSUE THREAD

**Issue by ugumba** [dotnet/EntityFramework.Docs#2308]
A collection navigation property may be null if the property has not been Include()'d, so it should be recommended to make it nullable, no? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#feedback)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@ugumba It's always a valid option to accept that it will have nulls and therefore make it nullable. However, sometimes the nulls are an implementation detail and in the domain model it will always be non-null when used.
