### ISSUE TITLE
dotnet CLI Command failed

### ISSUE THREAD

**Issue by emamcoder** [dotnet/EntityFramework.Docs#2310]
I am trying to add migration file in the solution, I am referring this [document](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#create-a-migration) but I received an error.

I have reported this issue in [dotnet/core](https://github.com/dotnet/core/issues/4589)

**Comment by ajcvickers** [comment]
@emamcoder Please provide _detailed_ information about the steps you are taking and the issue you are seeing. (We can't help you unless we know what is you're doing and where it's not working.)

**Comment by emamcoder** [comment]
@ajcvickers  I have dotNet Core 3.0.1 solution (Visual Studio For Mac-Community 8.5.3 built 16 ) in that I have added the dotNet Stander Library project version 2.1. I have added a package for EF 3.1.3. When I am trying to add the migration, getting error as mentioned below.

![image](https://user-images.githubusercontent.com/22444566/79899824-f315b380-842a-11ea-8f43-a08426aa22a0.png)

If you need any specific information please let me know.

**Comment by ajcvickers** [comment]
@emamcoder First, .NET Core 3.0 is out-of-support. You should update to the latest 3.1 release.
Second, you're trying to run the CLI commands from within Visual Studio. This can be done, but it's better to use the PowerShell commands as shown in that doc page under the "Visual Studio" tabs.

It seems like going through a tutorial like https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio would likely be helpful for you to learn the concepts involved with .NET in general and EF Core in particular.

**Comment by emamcoder** [comment]
@ajcvickers  Sorry for the typo, I am using dotNer Core ***3.1***.
As suggested I used PowerShell command, but after executing the command getting below error.
![image](https://user-images.githubusercontent.com/22444566/79904267-109a4b80-8432-11ea-95a1-ae3cf7b946a1.png)

I referred to this [document](https://docs.microsoft.com/en-us/visualstudio/mac/set-startup-projects?view=vsmac-2019) for the solution, but since this project (Samurai.App.Data/Samurai.App.Data.csproj) is a class library I don't see in list to select as startup project.

**Comment by emamcoder** [comment]
I have resolved this issue.
