### ISSUE TITLE
Required dependents is incorrect

### ISSUE THREAD

**Issue by smitpatel** [dotnet/EntityFramework.Docs#2320]
This line 
&gt; Reference navigations to owned entity types cannot be null unless they are explicitly mapped to a separate table from the owner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#feedback)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by Davilink** [comment]
Also, you should put an example with the nullable constraints activated (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types). A good example/caveat is when you have an entity that all his property are null, the value return by EFCore is a null value, not an empty object so the type of the property (that use an owned entity type) should be nullable, but when all or one of the property are required then the type of the property should not be nullable.
