### ISSUE TITLE
self-referencing

### ISSUE THREAD

**Issue by CeciAc** [dotnet/EntityFramework.Docs#2321]
@fjod commented on [Fri Apr 24 2020](https://github.com/dotnet/EntityFramework.Docs.ru-ru/issues/26)

please add examples for self-referencing relationship!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Связи — EF Core](https://docs.microsoft.com/ru-ru/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#feedback)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

---

@srvbpigh commented on [Fri Apr 24 2020](https://github.com/dotnet/EntityFramework.Docs.ru-ru/issues/26#issuecomment-618947853)

Hello, @fjod
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by wsimf** [comment]
Here is a good example, if someone is looking: https://stackoverflow.com/questions/9955491/self-referencing-parent-child-relationship-in-entity-framework

**Comment by anticrisis** [comment]
Another example: https://medium.com/@dmitry.pavlov/tree-structure-in-ef-core-how-to-configure-a-self-referencing-table-and-use-it-53effad60bf
