### ISSUE TITLE
issue: Lambda expression used inside Include is not valid.

### ISSUE THREAD

**Issue by SafvanPP** [dotnet/EntityFramework.Docs#2329]
```c#
var query = _context.CustomerDls
    .Include(p => p.customerDlsMaster)
    .Include(p => p.customerAddressBook.Where(cab => cab.IsMainAddress == true ))
    .AsQueryable();
query = query.IgnoreQueryFilters();
var item = await query.FirstOrDefaultAsync(i => i.CustomerCode == _customerCode);

return item;
```

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing
the request.
System.InvalidOperationException: Lambda expression used inside Include is not valid.

my api.csproj:

```xml
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0-preview.2.20159.4"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-preview.2.20159.4"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-preview.2.20159.4"/>
```

any help please

**Comment by roji** [comment]
@SafvanPP you are using a Where inside an Include, which is the new [filtered includes](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-5-0-preview-3/) feature introduced only in 5.0.0 preview3, not preview2. Change your csproj to reference 5.0.0-preview.3.20181.2 instead.
