### ISSUE TITLE
Document Find

### ISSUE THREAD

**Issue by TyneBridges** [dotnet/EntityFramework.Docs#2331]
For a beginner this is impossible to follow without examples. In some cases, isn't the entity also the object we want to search?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ff656e-4936-b37c-e1cc-1824aa148ccd
* Version Independent ID: b18f904f-d60c-955b-5aee-b739ffd8fe9f
* Content: [DbContext.FindAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.findasync?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
>  In some cases, isn't the entity also the object we want to search?

Can you elaborate on this?

**Comment by TyneBridges** [comment]
The detail: as a beginner I can't grasp this type of description without examples of usage and I've had a raft of different errors trying to use FindAsync. I'm trying to pass the table's primary key (an int value) from one page to another. If I pass the function the whole entity/table name I'm told it can't convert it into an integer. If I pass it the field (primary key) name I get "Cannot implicitly convert type 'MyAppName.Models.MyTableEntity' to 'System.Collections.Generic.List<MyAppName.Models.MyTableEntity>', and this same error is also thrown if I just use MyTableEntity = await db.MyTableEntity.FindAsync(); The data from the entity can be listed as text on a page or in a dropdown but I've spent literally days trying to read the value selected in the dropdown.

**Comment by ajcvickers** [comment]
@TyneBridges Find accepts the actual PK value. So, if your PK is an int, then `Find(33)` will find the entity with PK value of 33.

@smitpatel Do we have any conceptual docs on Find? (I looked but couldn't find anything.)

**Comment by smitpatel** [comment]
No Find docs for EF Core.

**Comment by TyneBridges** [comment]
Thanks. That makes sense. The problem may be that no value was passed, for reasons I still don't understand. Guess I need to keep repeating some of the tutorials.
