### ISSUE TITLE
Behavior in EF6 and future versions

### ISSUE THREAD

**Issue by cyungmann** [dotnet/EntityFramework.Docs#2332]
I don't understand this:
> For EF6 and future versions we have taken the approach that if the calling code chooses to open the connection by calling context.Database.Connection.Open() then it has a good reason for doing so and the framework will assume that it wants control over opening and closing of the connection and will no longer close the connection automatically.

> Note
> This can potentially lead to connections which are open for a long time so use with care.

To me, this suggests that calling `context.Database.Connection.Open()` makes `context` no longer cleanup the connection when it is disposed. However, that is not consistent with my reading of the EF6 source code or with this test code:

```csharp
#define TRACE
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Threading.Tasks;

namespace DbConnectionOpenTest
{
	public static class Program
	{
		public static async Task Main()
		{
			var db = new TestContext();
			await db.Database.Connection.OpenAsync();
			var conn = (SqlConnection)db.Database.Connection;
			var objectContext = ( (IObjectContextAdapter)db ).ObjectContext;
			var entityConnection = objectContext.Connection;
			var privateEntityConnection = new PrivateObject( entityConnection );
			var storeConnection = (SqlConnection)privateEntityConnection.GetField( "_storeConnection" );
			Trace.Assert( ReferenceEquals( storeConnection, conn) );
			var privateObjectContext = new PrivateObject( objectContext );
			var contextOwnsConnection = (bool)privateObjectContext.GetField( "_contextOwnsConnection" );
			Trace.Assert( contextOwnsConnection );
			db.Dispose();
			Trace.Assert( conn.State == ConnectionState.Closed );
			Trace.Assert( entityConnection.State == ConnectionState.Closed );
		}

		private sealed class TestContext : DbContext { }
	}
}
```

In the test code, given the documentation I would have expected `db.Dispose()` to not close the connection but in fact `db.Dispose()` _does_ close the connection, and additionally calling `db.Database.Connection.OpenAsync()` seems to have no effect on `_contextOwnsConnection`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ffd31b0-e8fc-bbee-a6d8-93b095db487f
* Version Independent ID: da24dfb6-c202-5e29-40d0-3b9ed5362595
* Content: [Connection management - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-management#feedback)
* Content Source: [entity-framework/ef6/fundamentals/connection-management.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/connection-management.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by cyungmann** [comment]
Also, those warnings in the documentation seem to contradict the example that follows, which includes the comment `// The context is disposed – so now the underlying store connection is closed`.


Perhaps I just do not understand what 

> close the connection automatically

means.

**Comment by cyungmann** [comment]
I see now that other EF6 operations seem to by default "open" the connection before the operation and "close" the connection after the operation by incrementing or decrementing a reference counter, and when the counter gets to zero the connection is "closed" (though may remain open behind the scenes due to connection pooling).

Maybe it would be clearer if "close the connection automatically" instead read "close the connection after query operations are completed" or something similar?

**Comment by ajcvickers** [comment]
@cyungmann I think you may be confusing closing with disposing. EF disposes the connection if it owns it. This is orthogonal to how the connection is opened and closed.

**Comment by cyungmann** [comment]
@ajcvickers I understand the behavior at this point but think the documentation could be clearer. In particular, under "Behavior for EF5 and earlier versions" it reads:

> Separately, if you open the database connection by calling Database.Connection.Open() it will be open until the next time you execute a query or call anything which requires a database connection (for example, SaveChanges()) but after that the underlying store connection will be closed. The context will then re-open and re-close the connection any time another database operation is required:

I would therefore suggest updating this paragraph under "Behavior in EF6 and future versions":

> For EF6 and future versions we have taken the approach that if the calling code chooses to open the connection by calling context.Database.Connection.Open() then it has a good reason for doing so and the framework will assume that it wants control over opening and closing of the connection and will no longer close the connection automatically.

to read

> For EF6 and future versions we have taken the approach that if the calling code chooses to open the connection by calling context.Database.Connection.Open() then it has a good reason for doing so and the framework will assume that it wants control over opening and closing of the connection and will no longer close the connection automatically **when you execute a query, perform a database operation, or call anything that requires a database connection (for example, SaveChanges())**.

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
