### ISSUE TITLE
Consider spelling out PMC and CLI in the documentation

### ISSUE THREAD

**Issue by lajones** [dotnet/EntityFramework.Docs#2335]
See [this comment](https://github.com/dotnet/EntityFramework.Docs/pull/2333#discussion_r416872086). @AndriySvyryd is suggesting spelling out PMC as "Package Manager Console" and CLI as ".NET Core CLI" throughout the docs so as to help with localization. However these abbreviations are widely used - and in some cases specifically called out as abbreviations - see e.g. https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding. So raising for discussion with the whole team.

**Comment by ajcvickers** [comment]
Team notes: spell out PMC the first time it is used, then use PMC afterwards. There doesn't seem to be a way that we can control the localization of PMC, so we will leave it as is.
