### ISSUE TITLE
Remove Layer - 2 (L2) .NET navigation header

### ISSUE THREAD

**Issue by wadepickett** [dotnet/EntityFramework.Docs#2343]
A new navigation header has been already published for all docs.microsoft.com It duplicates items already in the .NET layer 2 navigation header.   We are removing the .NET layer 2 navigation header across all published dotnet content repos.  

- Remove the L2 .NET Header from docfx.json

Also reviewed:
- Do we add a  "Download .NET" and/or Community link to the EF Hub page or elsewhere?
Conclusion:  Do not include them.

**Comment by wadepickett** [comment]
@JeremyLikness, does this proposal sound good to you?  The L2 Navigation that I am referring to is the ".NET  About Learn Docs Downloads Community" navigation layer at the top.

**Comment by JeremyLikness** [comment]
I don't see a lot of community clicks and "download .NET" feels out of place on the Entity Framework Core hub. I recommend we just remove L2 navigation.

**Comment by JeremyLikness** [comment]
Pinging @ajcvickers for his thoughts.

**Comment by ajcvickers** [comment]
Agree with @JeremyLikness
