### ISSUE TITLE
Discriminator Configuration

### ISSUE THREAD

**Issue by justSimpleDeveloper** [dotnet/EntityFramework.Docs#2354]
How can I provide type and value of discriminator per class? String takes more data space and time to check match by SQL query than int.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10898c5-abee-1843-cfff-b2707f8a079a
* Version Independent ID: d9399618-488e-20b1-f707-35a191b95cc1
* Content: [Inheritance - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#feedback)
* Content Source: [entity-framework/core/modeling/inheritance.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/inheritance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by roji** [comment]
@justSimpleDeveloper have you seen [the docs on discriminator configuration](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#discriminator-configuration), which specifically show how to configure the type and values of discriminators? Is there anything lacking there?

**Comment by justSimpleDeveloper** [comment]
I read this but it seems I focused on the string example too much, somehow I missed it guess... Let me play with this a bit :) Thanks
