### ISSUE TITLE
What makes the ConnectionString special over other configs in the same file?

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/EntityFramework.Docs#2359]
As the title says.  Why bother separating out connection strings into their own flattened namespace in the config?  Are there any benefits to doing this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@bricelam Does either the EF `name=` syntax or the ASP.NET Core tooling expect the connection string to have a well-known location in the config?

**Comment by bricelam** [comment]
Yes. The `ConnectionStrings` section has first-class API:

https://github.com/dotnet/runtime/blob/2019cd60fbaaf8f5004b9b90bd38b10efff0b5cb/src/libraries/Microsoft.Extensions.Configuration.Abstractions/src/ConfigurationExtensions.cs#L35-L38

**Comment by atrauzzi** [comment]
Is there anything beyond that?

**Comment by bricelam** [comment]
I think Web Publish also uses this section to allow replacing connection strings during deployment
