### ISSUE TITLE
CancellationTokens ignored when using EF Core

### ISSUE THREAD

**Issue by rkone** [dotnet/EntityFramework.Docs#2363]
Minimal repro: https://github.com/pranavkm/ef-cancel/blob/master/ConsoleApp1/Program.cs

------------------------------------

Original issue:

### Describe the bug
When using a Blazor component that has a dbContext through OwningComponentBase, there seems no way to cancel a long running database operation.

[This sample blazor app](https://github.com/rkone/BlazorApp1) has a modified FetchData component that has a button that calls CancelAndFetch:

    private CancellationTokenSource _tokenSource = new CancellationTokenSource();
    private async void CancelAndFetch()
    {
        _tokenSource.Cancel();
        _tokenSource = new CancellationTokenSource();
        forecasts = null;
        await Service.LongTask(_tokenSource.Token);
        if (_tokenSource.IsCancellationRequested) return;
        forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
        await InvokeAsync(StateHasChanged);
    }

The dbcontext LongTask is simply:

      public async Task LongTask(CancellationToken cancellationToken = default)
      {
          await Database.ExecuteSqlRawAsync("WAITFOR DELAY '0:0:2'", cancellationToken);
      }

Running CancelAndFetch() twice will crash with an InvalidOperationException on the 2nd run through.

### To Reproduce
Download and run the repo. In the Fetch Data page, click the "Cancel & Fetch" twice, the second time while the component is still on "Loading..."

### Further technical details
- ASP.NET Core version 3.1.1
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200-preview-014883
 Commit:    4e2a0ee959

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-014883\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-014883 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS 2019 16.4.4

**Comment by ajcvickers** [comment]
Moving to docs repo to clarify this in the docs.

**Comment by rkone** [comment]
First, thanks for the effort of looking into this everyone!
I think something is a little odd still - my async console app seems to be able to cancel the task rapidly, but the TaskCompletionSource version seems to need the operation to finish.

**Comment by roji** [comment]
@rkone in your console program, you're not catching any exceptions that occur inside the Task.Run lambda - so the exceptions are being silently discarded. I've modified your sample code and can see the EF Core exception coming out when inputting 's' twice in a row.

<details>
    <summary>Full sample code</summary>

```c#
class Program
{
    private static SampleContext _ctx;
    private static CancellationTokenSource _tokenSource = new CancellationTokenSource();
    
    static void Main(string[] args)
    {
        using var ctx = new SampleContext();
        ctx.Database.EnsureDeleted();
        ctx.Database.EnsureCreated();
        
        var i = 0;
        _ctx = new SampleContext();
        string input = null;
        while (input != "x")
        {
            input = Console.ReadLine();
            if (input == "s")
            {
                i++;
                Task.Run(async () =>
                {
                    Console.WriteLine($"Starting {i}");
                    _tokenSource.Cancel();
                    _tokenSource = new CancellationTokenSource();
                    var tokenSource = _tokenSource;
                    try
                    {
                        await _ctx.LongTask(tokenSource.Token);
                        Console.WriteLine($"Completed {i}");
                    }
                    catch (OperationCanceledException)
                    {
                        Console.WriteLine($"Cancelled {i}");
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine($"Failed {i}: " + e);
                    }
                });
            }
        }
    }
}

public class SampleContext : DbContext
{
    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    public Task LongTask(CancellationToken cancellationToken)
        => Database.ExecuteSqlRawAsync("WAITFOR DELAY '0:0:1'", cancellationToken);
}
```
</details>

**Comment by rkone** [comment]
Got it roji.  Thanks again for your help!

**Comment by roji** [comment]
Is this basically already covered by the new Blazor demo/guidance? /cc @JeremyLikness

**Comment by ajcvickers** [comment]
We believe [the new Blazor doc](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1#use-of-entity-framework-dbcontext-from-di) covers the important points.
