### ISSUE TITLE
Display data from each entity.

### ISSUE THREAD

**Issue by MarkInLasVegas** [dotnet/EntityFramework.Docs#2364]
Please include examples of iterating through a List.  Output would include columns from each related table.

I tried using foreach and was unable to get Post data.  Thank you!  These docs have been very helpful. 

using (var context = new BloggingContext())
{
    var blogs = context.Blogs
        .Include(blog =&gt; blog.Posts)
        .ToList();
}

foreach (var item in blogs)
 {
        Console.WriteLine(  );
  }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data#feedback)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@MarkInLasVegas we already have several examples on that page with ToList, which part exactly do you think is missing - a `foreach` on that list? If so, that seems like a basic C# concept that doesn't need to be explicit in the EF Core docs...

**Comment by MarkInLasVegas** [comment]
Thank you for your response. When I use a foreach loop, I am only able to access Blog columns. I was just looking for the means to access the related Post columns.  "item." only lists Blog columns.  Is there a way to access Post columns in "item"?  If so, how?  I was hoping there would be a simple answer.  I've searched for examples and have tried IntelliSense suggestions with no luck.  Can Post columns be accessed with the many ".ToList()" examples?  If a different query is required, can such examples be added?  Thank you.

**Comment by roji** [comment]
@MarkInLasVegas the Posts for each blog are accessible via that blog's Posts property:

```c#
using (var context = new BloggingContext())
{
    var blogs = context.Blogs
        .Include(blog => blog.Posts)
        .ToList();

    foreach (var blog in blogs) {
        foreach (var post in blog.Posts) {
            // Acces post in some way:
            Console.WriteLine(post.Id);
        }
    }
}
```

Note this sentence in the doc page:

> In the following example, the blogs that are returned in the results will have their Posts property populated with the related posts.

**Comment by MarkInLasVegas** [comment]
Perfect!  Thank you.
