### ISSUE TITLE
RelationalQueryableExtensions.FromSqlInterpolated

### ISSUE THREAD

**Issue by rbrooks33** [dotnet/EntityFramework.Docs#2366]
Regarding this article: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalqueryableextensions.fromsqlinterpolated?view=efcore-3.1

I was wondering if there could be provided detailed or background information that would reassure ones concerned with sql injection attack that this method will indeed "automatically convert into dbparameter"? Also, I stumbled upon the intellisense using EF6 and so would like confirmation the aforementioned question can be applied to EF6?

I appreciate your taking time to answer on what might seem a trivial issue. 

Regards, Rodney

**Comment by roji** [comment]
@rbhanda when you use FromSqlInterpolated, any interpolated parameter values you supply will automatically be converted to a DbParameter (as written in the docs). That means that the value gets sent as a parameter outside of the SQL, and is safe with regards to any SQL injection. More detailed information about this is available in [our documentation page on raw SQL operations](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql).

Re EF6, I'm no expert but [the API documentation for [ExecuteSqlCommand](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.database.executesqlcommand?redirectedfrom=MSDN&view=entity-framework-6.2.0#overloads) says the same thing.

**Comment by rbrooks33** [comment]
Thanks a million for the additional link and confirmation. I'm a solo developer working for a client who is hesitant to use EF in general and "FromSql" (without dbparameter objects) specifically for security reasons. Also, there seems to be a perception of EF (in general) as an unneeded "wrapper" or "layer". I am no expert but my take, especially using minimally a dbcontext and "FromSql", is that layers have been scraped away. Thanks again.

**Comment by roji** [comment]
@rbrooks33 FWIW you (and your client) are very right to hesitate, as this is one of the highest security risks in database programming. Note that we also have FromSqlRaw, which behaves differently. In cases of doubt (especially when it comes to security), I'd suggest doing a tiny test project and checking the SQL coming out.
