### ISSUE TITLE
Document where to place code for applying migrations at runtime

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/EntityFramework.Docs#2369]
The "Apply migrations at runtime" section contains code but doesn't say where in your app to put it. I found the answer at https://stackoverflow.com/a/38263675, but it would be nice if the article mentioned where this code should be placed within your app :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#apply-migrations-at-runtime)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
If you understand the security risks of using a connection string with permissions to alter the database schema and you understand problems that can occur when multiple instances of your app try to migrate the database at the same time...

You can do it in Program.Main. If you're using Microsoft.Extensions.Hosting, it would look like this:

```cs
public static void Main(string[] args)
{
    var host = CreateHostBuilder(args).Build();

    using (var scope = host.Services.CreateScope())
    {
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
        db.Database.Migrate();
    }

    host.Run();
}
```

You could also consider adding an admin page that requires the user to be authenticated before clicking a button to migrate the database.
