### ISSUE TITLE
One migration set

### ISSUE THREAD

**Issue by Kurira** [dotnet/EntityFramework.Docs#2373]
&gt; If you don't like having two sets of migrations, you can manually combine them into a single set that can be applied to both providers.

How to actually do this? I have two contexts `MyContext` and a derived `MyTestingContext : MyContext` with different connection string for testing, but there is no way to reuse already existing migrations for my test database. I tried using `options.MigrationsAssembly("MyAssembly")` but it seems that migrations are marked with `DbContextAttribute` which prevents reusing them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b011c7a-3534-78e3-b491-addd96fb5ba1
* Version Independent ID: 371826c5-3ef2-4eef-32e9-d55c777cd9d3
* Content: [Migrations with Multiple Providers - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/providers.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/providers.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
Yes, if the model is the same between both, I believe it's possible. You'd just need two `[DbContext]` attributes on each migration and the snapshot.

**Comment by bricelam** [comment]
But that hasn't been tested, so you might run into issues.

**Comment by bricelam** [comment]
@Kurira Do you need two two DbContext types? Can you reuse the same type with different connections strings instead?

**Comment by bricelam** [comment]
``` cs
class MyDbContext : DbContext
{
    readonly string _connectionString;

    public MyDbContext(string connectionString)
        => _connectionString = connectionString;

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlServer(_connectionString);
}
```
``` cs
using var testContext = new MyDbContext(testConnectionString);
testContext.Database.Migrate();
```

**Comment by Kurira** [comment]
Two attributes doesn't compile now and I think it would clear itself on generation or would have to be added by hand on each migration. Also can't really add them as testing assembly is in different project.

Reusing the same context works as expected. But feels weird to use as it would have to be wrapped pretty hard to include all the testing functionality without polluting production context API, like
- automatic db migration (was done on static constructor once)
- passing connection string
- dropping data before testing (don't really want to introduce public api on context to be accidentally used in production)
- and even with wrapper it would probably be unusable as you still need to pass the dbcontext type to the controller, etc.

We were using in memory provider before, so we didn't have problems up until now 😃
Not sure if this testing scenario is used widely enough to accommodate for though 😦

**Comment by ajcvickers** [comment]
@Kurira All your bullet points are typically things that are not directly coupled to the context. Is there any reason you want to couple them?

**Comment by bricelam** [comment]
Note, you don't have to use the string constructor. This pattern plays better with ASP.NET:
```cs
class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options)
        : base(options)
    {
    }
}
```
```cs
var testOptions = new DbContextOptionsBuilder<MyDbContext>()
    .UseSqlServer(testConnectionString)
    .Options;
using var testContext = new MyDbContext(testOptions);
testContext.Database.Migrate();
```

**Comment by Kurira** [comment]
> All your bullet points are typically things that are not directly coupled to the context. Is there any reason you want to couple them?

> Note, you don't have to use the string constructor. This pattern plays better with ASP.NET Core:

Our normal context is indeed using recommended context options and migrating on startup, but there is no DI and startup class in a testing project, so we prefer ease of use instead. By coupling migrate/drop data/create testing context which is easy to achieve with inheritance.

For now we went with a static helper
```C#
public static class TestContext
{
    private static DbContextOptions<MyContext> Options { get; }

    static TestContext()
    {
        Options = new DbContextOptionsBuilder<MyContext>()
            .UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=TestDb;Trusted_Connection=True;MultipleActiveResultSets=True")
            .Options;

        using MyContext context = new MyContext(Options);

        context.Database.Migrate();
    }

    public static DbContext Create()
    {
        return new MyContext(Options);
    }

    public static DbContext Drop(this DbContext context)
    {
        context.RemoveRange(context.Set<AppUser>());
        ...

        context.SaveChanges();

        return context;
    }
}
```
