### ISSUE TITLE
Algorithm used

### ISSUE THREAD

**Issue by miegir** [dotnet/EntityFramework.Docs#2374]
This documentation said thet the algorighm used is the same as NEWSEQUENTIALID() in Microsoft SQL Server. But comment in the source at https://github.com/dotnet/efcore/blob/master/src/EFCore/ValueGeneration/SequentialGuidValueGenerator.cs said the opposite.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 257112ad-5920-6a75-3b5a-3bba1f24faf7
* Version Independent ID: 8fa859e2-0617-9abf-61b6-d0f51024e3dc
* Content: [SequentialGuidValueGenerator Class (Microsoft.EntityFrameworkCore.ValueGeneration)](https://docs.microsoft.com/ru-ru/dotnet/api/microsoft.entityframeworkcore.valuegeneration.sequentialguidvaluegenerator?view=efcore-3.1&source=docs#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.ValueGeneration/SequentialGuidValueGenerator.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.ValueGeneration/SequentialGuidValueGenerator.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@miegir The docs need to be updated. See https://github.com/dotnet/efcore/issues/19124

**Comment by roji** [comment]
Closing as the text has already been updated - we'll see about when it goes live.
