### ISSUE TITLE
Properties should not return arrays?

### ISSUE THREAD

**Issue by sbsw** [dotnet/EntityFramework.Docs#2375]
fxcop emits a warning for the `public byte[] Timestamp { get; set; }` statement:

> CA1819: Properties should not return arrays

Is there an alternative construct that achieves the same result? Or, perhaps you just want to mention the fxcop warning and state that it is unavoidable and can be ignored or suppressed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041e7a47-a632-132a-3c9e-db46e3782a63
* Version Independent ID: a5de9c4c-56fe-416e-0801-f6acd061f25e
* Content: [Concurrency Tokens - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/concurrency?tabs=data-annotations#feedback)
* Content Source: [entity-framework/core/modeling/concurrency.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@sbsw many FxCop warnings aren't necessarily appropriate for all use cases - it's pretty common to pick and choose the warnings which make sense and suppress the others. For using SQL Server timestamp, the above is correct and the warning should be suppressed.

**Comment by sbsw** [comment]
Yes, I understand that. That's why I wrote the issue. The folks writing this documentation need to view the documentation through the eyes of everyday users. The docs provide (or at least SHOULD provide) more than just the nuts and bolts of how to do it. They also serve as templates that are copied by literally thousands of users who probably don't understand the ramifications of the code they are copying. In this particular case, copying the example code leads to a scary warning that EVERY developer who copies the code needs to decode and decide how to handle. You owe it to the developers who read these docs to mention things such as this warning, and to provide guidance. A simple note to the effect that this code will produce a particular warning in .Net 3 and above, and that the warning can be ignored or suppressed, is all it takes.

**Comment by ajcvickers** [comment]
@sbsw The problem is that there are so many FxCop warnings like this. I recommend developers turn off most FxCop rules this because FxCop generates too many errors that are either plain wrong, don't apply to the code in question, and are very hard to understand.
