### ISSUE TITLE
dotnet : Could not execute because the specified command or file was not found.

### ISSUE THREAD

**Issue by gcogco10** [dotnet/EntityFramework.Docs#2376]
Hi Team

I want to create dbcontext on my models folder, i have installed the packages and they do exist .csproj file.
Install-Package Microsoft.EntityFrameworkCore.Tools Install-Package Microsoft.EntityFrameworkCore.SqlServer

I am now trying to run this command,  dotnet ef dbcontext scaffold "Server=GcobaniM-L\SQLEXPRESS;Database=eNtsaRegistration;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models

I  need some help please mates to this issue,
dotnet : Could not execute because the specified command or file was not found.
At line:1 char:1
+ dotnet ef dbcontext scaffold "Server=GcobaniM-L\SQLEXPRESS;Database=e ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Could not execu... was not found.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to r
un a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by roji** [comment]
@gcogco10 have you installed the EF Core global tools [as shown in the docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)? You need to execute `dotnet tool install --global dotnet-ef` once before being able to use it.

Note that this is for the command-line, if you prefer to use Powershell commands inside the Visual Studio Package Manager Console, [see this page instead](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell).

**Comment by P7162** [comment]
This helps for me that you @roji
