### ISSUE TITLE
Owned entities + lazy loading

### ISSUE THREAD

**Issue by justSimpleDeveloper** [dotnet/EntityFramework.Docs#2382]
Why after using loading for context i'm forced to use it for each and every entity/navigation property?
By turning on lazy loading for context, all my navigation properties needs to be lazy ones. When I combine it with entity having owned type it causes having additional join in SQL read (from the same table to the same one). Finally having one row with 4 owned types (4 of the same type, each having two columns), instead of having single "select columns from table",
I have such overheaded SQL: 

```sql
SELECT TOP(2) [m].[Id], [t].[Id], [t].[DayPeriodConfiguration_ErrorIndicator], [t].[DayPeriodConfiguration_WarningIndicator], [t0].[Id], [t0].[HourPeriodConfiguration_ErrorIndicator], [t0].[HourPeriodConfiguration_WarningIndicator], [t1].[Id], [t1].[MonthPeriodConfiguration_ErrorIndicator], [t1].[MonthPeriodConfiguration_WarningIndicator], [t2].[Id], [t2].[WeekPeriodConfiguration_ErrorIndicator], [t2].[WeekPeriodConfiguration_WarningIndicator]
FROM [Integration].[MessagesStatusReportConfiguration] AS [m]
LEFT JOIN (
    SELECT [m0].[Id], [m0].[DayPeriodConfiguration_ErrorIndicator], [m0].[DayPeriodConfiguration_WarningIndicator]
    FROM [Integration].[MessagesStatusReportConfiguration] AS [m0]
    WHERE [m0].[DayPeriodConfiguration_WarningIndicator] IS NOT NULL AND [m0].[DayPeriodConfiguration_ErrorIndicator] IS NOT NULL
) AS [t] ON [m].[Id] = [t].[Id]
LEFT JOIN (
    SELECT [m1].[Id], [m1].[HourPeriodConfiguration_ErrorIndicator], [m1].[HourPeriodConfiguration_WarningIndicator]
    FROM [Integration].[MessagesStatusReportConfiguration] AS [m1]
    WHERE [m1].[HourPeriodConfiguration_WarningIndicator] IS NOT NULL AND [m1].[HourPeriodConfiguration_ErrorIndicator] IS NOT NULL
) AS [t0] ON [m].[Id] = [t0].[Id]
LEFT JOIN (
    SELECT [m2].[Id], [m2].[MonthPeriodConfiguration_ErrorIndicator], [m2].[MonthPeriodConfiguration_WarningIndicator]
    FROM [Integration].[MessagesStatusReportConfiguration] AS [m2]
    WHERE [m2].[MonthPeriodConfiguration_WarningIndicator] IS NOT NULL AND [m2].[MonthPeriodConfiguration_ErrorIndicator] IS NOT NULL
) AS [t1] ON [m].[Id] = [t1].[Id]
LEFT JOIN (
    SELECT [m3].[Id], [m3].[WeekPeriodConfiguration_ErrorIndicator], [m3].[WeekPeriodConfiguration_WarningIndicator]
    FROM [Integration].[MessagesStatusReportConfiguration] AS [m3]
    WHERE [m3].[WeekPeriodConfiguration_WarningIndicator] IS NOT NULL AND [m3].[WeekPeriodConfiguration_ErrorIndicator] IS NOT NULL
) AS [t2] ON [m].[Id] = [t2].[Id]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
See https://github.com/dotnet/efcore/issues/10787 and https://github.com/dotnet/efcore/issues/12462 In particular, https://github.com/dotnet/efcore/issues/12462 is fixed in the EF Core 5 previews which are available now on NuGet and should stop owned properties from being lazy-loaded.

**Comment by MEnzio** [comment]
is there any way to disable lazy  loading for a specific entity i didnt find any thing in this link

im using ef core  3.1.7
