### ISSUE TITLE
Check updated date on all docs

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/EntityFramework.Docs#2383]
The date of this page is 10/27/2016, but it is clearly including information for EF Core 5 (yet to be released). As these pages are not versioned for a specific EF version it is kinda confusing to find out if this page actually contains new information for 3.x+, as the page looks to be 3.5 years old. May I recommend updating the date to the most recent edit date, whenever something is edited?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data#feedback)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Tornhoof Thanks. It's easy to forget when making small edits to the pages. We'll try to do better.

**Comment by ajcvickers** [comment]
Discussed and decided not to do a global push, but to make sure we update the date on future PRs.
