### ISSUE TITLE
Synchronization of navigation property vs. foreign key

### ISSUE THREAD

**Issue by pepiku** [dotnet/EntityFramework.Docs#2389]
Hello,

In EF (not core) it is explicitly mentioned in the documentation that proxies will synchronize the values of navigation properties (object) against the foreign key. For this to work the entity objects must not be created using 'new', but instead using DbSet.Create().

It is unclear to me based on the documentation whether and how exactly this is supposed to work in EFCore.

If I use the 'new' keyword to create entity objects, there is no synchronization happening, only when calling DetectChanges. (And I guess this happens implicitly during save.)

I see there is a CreateProxy method on DbSet. If the new entity is created using this method, I see that a proxy type is created instead (as expected), nevertheless setting the navigation property to a valid object retrieved from the proper exntityset will only update the navigation property itself, but it will not update the foreign key property.

Is such a synchronization feature foreseen (and shall proxies be used - if yes how?) or will it only deal with inconsistent 'object vs. foreign key' situations during DetectChanges and Save? In this case it would probably be advisable not to use explicit foreign keys in the models.

Tanks,
Oliver

**Comment by ajcvickers** [comment]
@pepiku You're looking for [change tracking proxies](https://github.com/dotnet/efcore/issues/10949) which is implemented for EF Core 5.0 and included in the [previews currently available on NuGet](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/5.0.0-preview.3.20181.2).

Documentation is tracked by #2076.
