### ISSUE TITLE
DbUpdateConcurrencyException due to code for adding blog posts

### ISSUE THREAD

**Issue by wldevries** [dotnet/EntityFramework.Docs#2398]
It seems there is a problem in the code that adds blog posts to an existing blog.
```
            if (existingPost == null)
            {
                existingBlog.Posts.Add(post);
            }
```
After saving the changes we get the following exception:

> Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

It seems that changing the original code to the following fixes the problem:
```
            if (existingPost == null)
            {
                context.Add(post);
            }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9826f28-46b2-e845-f1bf-5cbc2d940208
* Version Independent ID: 9c4a46cf-daa2-0e14-7ff1-c195db237cd0
* Content: [Disconnected Entities - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities)
* Content Source: [entity-framework/core/saving/disconnected-entities.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/disconnected-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@wldevries I just cloned and ran the sample from which this code is taken and it is working correctly. I suspect you are using a different key type or have changed key configuration to not use generated key values. If not, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by wldevries** [comment]
We generate our primary ids in code, but did not set them to not value generated. That is probably the problem.

**Comment by wldevries** [comment]
I checked with my colleague and that is indeed what the problem was. All of our primary keys are set to generated values, but our domain always generates these prior to inserting them. The combination is not logical, but we would not expect such an exception to occur or at least to get a more informative error. Is there a reason EF does not protest when you insert an entity with a filled in primary key when the key is configured to generate values?

By setting our primary keys to never generate values we fixed the crash.

**Comment by ajcvickers** [comment]
It's not an error to explicitly set the primary key value even if it is configured to be generated. There are scenarios where allowing both is useful. However, when doing so the state of the entity must also be explicitly set in many cases.
