### ISSUE TITLE
Explicitly mention that raw SQL isn't supported with InMemory

### ISSUE THREAD

**Issue by CriggerMarg** [dotnet/EntityFramework.Docs#2400]
It seems that EF Core 3.1 does not contain raw sql methods anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1289d5-8364-18a4-3445-6bba05c6854b
* Version Independent ID: 2680e647-f64a-7991-f821-3b5e2a845960
* Content: [Raw SQL Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#feedback)
* Content Source: [entity-framework/core/querying/raw-sql.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/raw-sql.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@CriggerMarg As it says at the end of the page, the 2.2 methods were renamed. See also https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#fromsql

**Comment by CriggerMarg** [comment]
@ajcvickers so page I mentioned probably should mention it too in order to stop confusing people like me

**Comment by ajcvickers** [comment]
@CriggerMarg It does. From the page:

> EF Core version 2.2 and earlier had two overloads of method named FromSql, which behaved in the same way as the newer FromSqlRaw and FromSqlInterpolated. It was easy to accidentally call the raw string method when the intent was to call the interpolated string method, and the other way around. Calling wrong overload accidentally could result in queries not being parameterized when they should have been.

**Comment by CriggerMarg** [comment]
@ajcvickers there is no any method in DbSet class that starting with "From...".

**Comment by ajcvickers** [comment]
https://github.com/dotnet/efcore/blob/release/3.1/src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs

**Comment by JasonLiebgott** [comment]
public static RelationalDataReader ExecuteSqlQuery(this DatabaseFacade databaseFacade, string sql, params object[] parameters)
        {
            var concurrencyDetector = databaseFacade.GetService<IConcurrencyDetector>();

            using (concurrencyDetector.EnterCriticalSection())
            {
                var rawSqlCommand = databaseFacade
                    .GetService<IRawSqlCommandBuilder>()
                    .Build(sql, parameters);

                return rawSqlCommand
                    .RelationalCommand
                    .ExecuteReader(
                        databaseFacade.GetService<IRelationalConnection>(),
                        parameterValues: rawSqlCommand.ParameterValues);
            }
        }

This method is no longer working (after update to Core 3.1.4) -- any ideas on where to start with getting it working?

**Comment by CriggerMarg** [comment]
@ajcvickers  thing is I installed ef core 3.1.4 and I don't have these methods at all.

**Comment by ErikEJ** [comment]
Do you have the required using statement?

**Comment by ErikEJ** [comment]
Do you have the required using statement?

**Comment by CriggerMarg** [comment]
Ok I fugured that out. 

To get RelationalQueryableExtensions methods family working in my app I had to install 
Microsoft.EntityFrameworkCore.Relational package. 

It's not listed anywhere in documentation. Please update it, or let me create PR. Let me know which option would work for you.

**Comment by ErikEJ** [comment]
@CriggerMarg What packages did you have installed?

**Comment by CriggerMarg** [comment]
@ErikEJ here is my sample project csproj file, whole. 

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.4" />
  </ItemGroup>

</Project>

**Comment by ErikEJ** [comment]
You need to mark all the xml as code in markup

**Comment by CriggerMarg** [comment]
I tried, but gave up. So removed all opened tags

**Comment by ErikEJ** [comment]
So originally you only had Microsoft.EntityFrameworkCore installed?? That is very unusual.

**Comment by CriggerMarg** [comment]
How should I know to install other packages? They didn't installed automatically nor from package manager and from popup when I typed DbContext in my code.

**Comment by ErikEJ** [comment]
From the docs perhaps? https://docs.microsoft.com/da-dk/ef/core/get-started/?tabs=netcore-cli#install-entity-framework-core

**Comment by CriggerMarg** [comment]
Could you point me where Microsoft.EntityFrameworkCore.Relational is listed in this article please?

**Comment by ErikEJ** [comment]
Installing a relational provider will due to NuGet magic automatically install Microsoft.EntityFrameworkCore.Relational. https://docs.microsoft.com/en-us/nuget/concepts/package-installation-process

**Comment by CriggerMarg** [comment]
Does not happenning when you install InMemory adapter though.

I think it's not constructive to mention different part of documentation when I clearly pointed what's wrong with this particular one and suggested how to fix it to avoid confusion.

**Comment by roji** [comment]
@CriggerMarg InMemory brings in Microsoft.EntityFrameworkCore, but not Microsoft.EntityFrameworkCore.Relational, because InMemory isn't a relational provider. That's why the raw SQL methods aren't available there - InMemory cannot run SQL...

**Comment by CriggerMarg** [comment]
@roji  that makes sense, thank you! Could it still be mentioned in documentation?

**Comment by roji** [comment]
We already do in [various](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory) [places](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/#approach-3-the-ef-core-in-memory-database).

**Comment by CriggerMarg** [comment]
Still there is a man who got confused so there is room for improvement

**Comment by roji** [comment]
Submitted #2402 to specifically call out the lack of raw SQL support in InMemory.

**Comment by CriggerMarg** [comment]
Great, I'll closing this one

**Comment by roji** [comment]
Reopening, to be closed when the PR is merged.
