### ISSUE TITLE
EnsureCreated() is throwing "The process has no package identity" exception

### ISSUE THREAD

**Issue by jsantosh14** [dotnet/EntityFramework.Docs#2401]
Application: WPF App on .Net 4.8. A simple plain WPF application that will not be submitted to Windows Store. 

Package: Microsoft.EntityFrameworkCore.Sqlite
Version: 3.1.4

Issue: EnsureCreated() is throwing the exception saying "The process has no package identity". 

V3.1.3 is working well.

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
