### ISSUE TITLE
How to update embedded entities

### ISSUE THREAD

**Issue by Marusyk** [dotnet/EntityFramework.Docs#2408]
My models
```
public class State : Entity
 {
        public string Id { get; set; }
        public int Position { get; set; }
        public GenericStateEnum GenericState { get; set; }
        public ICollection<Floor> Floors { get; set; }
  }

public class Floor
{
     public int Number { get; set; }
     public string Label { get; set; }
 }
```
Configuration

```
builder.ToContainer("States");
            builder.HasKey(o => o.Id);
            builder.HasPartitionKey(o => o.Id);
            builder.OwnsMany(o => o.Floors, sa =>
            {
                sa.ToJsonProperty("Floors");
                sa.Property(p => p.Number).ToJsonProperty("Number");
                sa.Property(p => p.Label).ToJsonProperty("Label");
            });
```
And code where I try to update `Label` in floors collection:
```
State existState = await _dbContext.States.SingleOrDefaultAsync(s => s.Id== entity.Id);
EntityEntry<State> entry = _dbContext.Entry(existState);
entry.CurrentValues.SetValues(entity);
_dbContext.SaveChanges();
```
but embedded entity not changed. It works when I edit main model (Id, Position ). How to edit embedded entities?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738deb7b-d752-f628-3860-fe53891cadb0
* Version Independent ID: e0a18db9-d605-2a78-b77a-d22375dcfd4e
* Content: [Azure Cosmos DB Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/cosmos/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/cosmos/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
You'd need to get the entity entry for the embedded entity, e.g.
```C#
foreach (var floor in entity.Floors)
{
    var floorEntry = entry.Collection("Floors").FindEntry(floor);
    // Act on floorEntry
}
```

**Comment by Marusyk** [comment]
Thank you very much.
I used
```
entry.CurrentValues.SetValues(entity);
entry.Collection(nameof(entity.Floors)).CurrentValue = entity.Floors;
```
