### ISSUE TITLE
Add linq2db.EntityFrameworkCore to extensions page.

### ISSUE THREAD

**Issue by sdanyliv** [dotnet/EntityFramework.Docs#2411]
linq2db.EntityFrameworkCore is an alternative translator of LINQ Queries using EF Core model mappings and LINQ extensions.

In addition to EF Core implementation it gives ability to:
- Fast Eager Loading (incomparable faster on massive Include query)
- Better SQL optimization
- Use CTE in LINQ queries 
- Table hints
- Full Window functions support
- Fast BulkCopy of millions records
- Native SQL operations for updating, deleting, inserting records via LINQ query
- Temporary Tables support
- Cross Database/Linked Server queries.

[GitHub repository](https://github.com/linq2db/linq2db.EntityFrameworkCore)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8875eb79-99ff-662b-c189-86eb8cdb5488
* Version Independent ID: fa03a7fa-1922-7aa1-acda-b0d216ef37cb
* Content: [Tools & Extensions - EF Core](https://docs.microsoft.com/en-us/ef/core/extensions/)
* Content Source: [entity-framework/core/extensions/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/extensions/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ErikEJ
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@sdanyliv Please submit a PR if you want to add this to the list of extensions.
