### ISSUE TITLE
Point out that the default project is set with the dropdown in PMC

### ISSUE THREAD

**Issue by jameslear** [dotnet/EntityFramework.Docs#2414]
The document defines target, default, and startup projects.  This may seem so obvious that it's unnecessary, but the [Target and Startup Project ](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#target-and-startup-project) section should mention that the package manager console has a dropdown to select the default project .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [EF Core tools reference (Package Manager Console) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
The docs mention that:

> By default, the **Default project** selected in **Package Manager Console** is the target project.
