### ISSUE TITLE
What are the values of Task<Int32> that can be returned?

### ISSUE THREAD

**Issue by DrReedo** [dotnet/EntityFramework.Docs#2417]
Can you please document what values are returned in the Task Result?

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aece550f-d934-0dae-c3ac-0d9b3660bd1a
* Version Independent ID: aebedd48-a65c-c92e-ab4f-f7b4fe467e03
* Content: [DbContext.SaveChangesAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.savechangesasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync);k(DevLang-csharp)%26rd%3Dtrue&view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by roji** [comment]
@DrReedo the API docs say the following about the result type:

> A task that represents the asynchronous save operation. The task result contains the number of state entries written to the database.

Is that insufficient?

**Comment by DrReedo** [comment]
Ok, that's fine.  Thanks Roji.
