### ISSUE TITLE
Change Documentation

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/EntityFramework.Docs#2418]
With the recent release style it becoming really hard to actually know what was fix/changed in each release.

Could someone en-lighten me as to how to understand the new format, as it will mostly take you to links about dotnet core in general apposed to what was actually done to the specific repo.

example go to: https://github.com/aspnet/EntityFramework6/releases

for release .NET Core 3.1.0-preview3 baring in mind i am under EntityFramework6 and not core, it
shows a link for "Release Notes" great..  but his take you to a link about 
".NET Core 3.1.0 Preview 3 - November 14, 2019"

also for release v6.4.0, no links, you can click on and it will show 
"167 commits to master since this tag"
from this i can not even find what the actual changes were in a readable way... mostly automated commits.

I preferred the much older way of doing this where there was actually just a summary of the commits made in a readable format.

thoughts?...

**Comment by smitpatel** [comment]
Fixed broken link on release page.
