### ISSUE TITLE
Add an example of how to pass command line args to IDesignTimeDbContextFactory

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#2419]
See https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation#from-a-design-time-factory

For example:

Arguments are now flowed from the command line into the `CreateDbContext` method of [IDesignTimeDbContextFactory](). 
For example, to indicate this is a dev build, a custom argument (e.g. `dev`) can passed on the command line:

```
dotnet ef migrations add two --verbose --dev
``` 

This argument will then flow into the factory, where it can be used to control how the context is created and initialized.
For example:

```CSharp
public class MyDbContextFactory : IDesignTimeDbContextFactory<SomeDbContext>
{
    public SomeDbContext CreateDbContext(string[] args) 
        => new SomeDbContext(args.Contains("--dev"));
}
```

**Comment by ConnerPhillis** [comment]
Just a heads up, I think their may be a mistake with this bit of documentation.
The [what's new in EF Core 5.0 page](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#flow-arguments-into-idesigntimedbcontextfactory) gives this command for adding custom arguments: 
```
dotnet ef migrations add two --verbose --dev
```
The prior command does not seem to work correctly. It errors out with the message `Unrecognized option '--dev'`. In the [documentation for Design-time DbContext Factory](https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#args) the command is listed as this: 
```
dotnet ef database update -- --environment Production
```
Which does work, note the extra `--` listed in the command from the design time one.

The "what's new" page was the first to pop up in a google search when I went looking for this feature, I have no problem editing this myself, just wanted to make sure

**Comment by YoungLiao** [comment]
Update-Database -Args '--environment Production' 
still not know how to use the environment, no example
