### ISSUE TITLE
Scaffold-DbContext Namespace and ContextNamespace options not working.

### ISSUE THREAD

**Issue by m-otis** [dotnet/EntityFramework.Docs#2422]
Contrary to online documentation, the -Namespace and -ContextNamespace parameters do not work with the Scaffold-DbContext command. I get a "NamedParameterNotFound" error.

Here is the documentation link I'm referencing: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#scaffold-dbcontext

I'm using latest Microsoft.EntityFrameworkCore.Tools package v3.1.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [EF Core tools reference (Package Manager Console) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#scaffold-dbcontext)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@m-otis These were added for the 5.0 release. We will update the documentation to indicate such.
