### ISSUE TITLE
Not creating a new ILoggerFactory

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/EntityFramework.Docs#2423]
Seems odd to emphasize that it's "very important that applications do not create a new ILoggerFactory" without even mentioning how the code prevents that, or how I should prevent that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83069f-39a8-e992-95f7-a8b41154b6f4
* Version Independent ID: 144fe168-080f-6557-e4b2-a18adb4b89ed
* Content: [Logging - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging?tabs=v3)
* Content Source: [entity-framework/core/miscellaneous/logging.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/logging.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@SoftCircuits The code already demonstrates this by using a static property for the ILogger.
