### ISSUE TITLE
Creating entities with null "owned entity" references

### ISSUE THREAD

**Issue by sbsw** [dotnet/EntityFramework.Docs#2427]
Suppose an entity contains an "owned entity" reference, like this:

```C#
    public class Person
    {
        public int Id { get; set; }
        public Name Name { get; set; }
    }

    [Owned]
    public class Name
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
```

Previously, if code created an instance of the `Person` entity **without populating the `Name` property**, then adding it to the database resulted in a misleading error message.

```C#
var person = new Person();
_db.People.Add(person);
await _db.SaveChangesAsync();
```

> InvalidOperationException: The entity of type 'Person' is sharing the table 'People' with entities of type 'Person.Name#Name', but there is no entity of this type with the same key value that has been marked as 'Added'.

The workaround that I employed was to explicitly initialize ALL owned entity references in my data models, like this:

```C#
    public class Person
    {
        public int Id { get; set; }
        public Name Name { get; set; } = new Name(); // Initialize it
    }

    [Owned]
    public class Name
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
```

This allowed the above code to work without error, since all owned entity references are now non-null.

This also allowed code to set values into the owned entity through the owned entity instance provided by the initialization code shown above. For example, this works as expected:

```C#
var person = await _db.People.FirstOrDefaultAsync();
person.Name.FirstName = "Fred";
await _db.SaveChangesAsync();
```

Now, both of these scenarios are changed. One of these changes should be considered a **breaking change**.

EF now allows entities containing null references to owned entities to be added to the database, so the first scenario (above) works and no longer causes the `InvalidOperationException`. This may not be a "breaking change", but it should be documented somewhere.

The breaking change has to do with the way EF tracks changes to owned entities. If an owned entity did not yet contain non-null data, the old behavior was to return a non-null reference to the owned entity (all of whose properties were null). I could then update an owned entity property through that non-null reference, as shown in the above example.

With the new behavior, EF returns a null reference to the owned entity. But since I've initialized it in the owning entity's constructor, the above code executes without error. **But the changed data is not saved to the database.**

In order to update the previously null owned entity, I must replace the non-null reference that I created in the initializer with a new Name object:

```C#
var person = await _db.People.FirstOrDefaultAsync();
person.Name = new Name { FirstName = "Fred" };
await _db.SaveChangesAsync();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d0e044-b0cb-21e2-19c1-2f137da671ac
* Version Independent ID: 1cbedd95-8640-1649-9967-d0ef71633534
* Content: [Breaking changes in EF Core 3.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@sbsw 

> explicitly initialize ALL owned entity references

This is likely not going to work because effectively every time you create a new instance of the parent entity type, you will also create a new instance of the child, even if there is an existing instance in the database that should be used. See #18007.

> EF now allows entities containing null references to owned entities to be added to the database

This is documented here: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dependent-entities-sharing-the-table-with-the-principal-are-now-optional
