### ISSUE TITLE
Document the new savepoint API

### ISSUE THREAD

**Issue by roji** [dotnet/EntityFramework.Docs#2429]
Following #20176

In [the transactions page](https://docs.microsoft.com/en-us/ef/core/saving/transactions).

**Comment by AliCharper** [comment]
Hi,

I create a sample console app to see how the CreateSavepoint works, but it seems nothing is happening.

private static void ShouldbeRolledBackatSomeStages()
        {
            TaxDbContext _Context = new TaxDbContext();

            using (var transaction = _Context.Database.BeginTransaction())
            {

                var NewAssetComponent = new Asset_Component
                {
                    AcquisitionDate = DateTime.Now,
                    AssetId = Guid.NewGuid(),
                    Cost = 110,
                    Description = new Random().Next().ToString() + " New Component",
                    QualifyingAmount = 10000,
                };

                //
                _Context.Asset_Components.Add(NewAssetComponent);

                _Context.Database.CreateSavepoint("First_SavePoint");


                var NewAsset_Details = new Asset_Details
                {
                    AssetId = Guid.NewGuid(),
                    Description = new Random().Next().ToString() + " New Desc",
                };

                _Context.Asset_Details.Add(NewAsset_Details);



                var NewAsset_Version = new Asset_Version
                {
                    Notes= new Random().Next().ToString() + " New Note",
                    PurchaseDate=DateTime.Now
                };


                _Context.Asset_Version.Add(NewAsset_Version);

                _Context.Database.CreateSavepoint("Second_SavePoint");


                

                _Context.Database.RollbackToSavepoint("First_SavePoint");

                _Context.SaveChanges();

                transaction.Commit();
            }

        }

**Comment by Tommigun1980** [comment]
Please add the documentation as it's hard to test new features in the preview builds without any documentation whatsoever. Thanks!

**Comment by AliCharper** [comment]
@Tommigun1980

I did provide an example

  private static void ShouldbeRolledBackatSomeStages()
        {
            TaxDbContext _Context = new TaxDbContext();

            using (var transaction = _Context.Database.BeginTransaction())
            {
                var NewAssetComponent = new Asset_Component
                {
                    AcquisitionDate = DateTime.Now,
                    AssetId = Guid.NewGuid(),
                    Cost = 110,
                    Description = new Random().Next().ToString() + " New Component",
                    QualifyingAmount = 10000,
                };

                //
                _Context.Asset_Components.Add(NewAssetComponent);

                _Context.SaveChanges();

                _Context.Database.CreateSavepoint("First_SavePoint");

                var NewAsset_Details = new Asset_Details
                {
                    AssetId = Guid.NewGuid(),
                    Description = new Random().Next().ToString() + " New Desc",
                };

                _Context.Asset_Details.Add(NewAsset_Details);

                _Context.SaveChanges();

                _Context.Database.CreateSavepoint("Second_SavePoint");

                var NewAsset_Version = new Asset_Version
                {
                    Notes= new Random().Next().ToString() + " New Note",
                    PurchaseDate=DateTime.Now
                };

                
                _Context.Asset_Version.Add(NewAsset_Version);

                _Context.SaveChanges();

                _Context.Database.CreateSavepoint("Third_SavePoint");
                
                _Context.Database.RollbackToSavepoint("First_SavePoint");

                //Commeting the Transaction
                transaction.Commit();
            }

        }

**Comment by AliCharper** [comment]
@Tommigun1980

I can send you the working/full solution if you need it.

**Comment by Tommigun1980** [comment]
Thanks a lot @AliCharper, I appreciate it!
