### ISSUE TITLE
typo quality-> equality

### ISSUE THREAD

**Issue by cantSleepNow** [dotnet/EntityFramework.Docs#2437]
[Enter feedback here]
typo: "An expression for checking quality" should be "An expression for checking equality"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 024a57e2-f662-9c87-87cc-9ad0d6685f5a
* Version Independent ID: dc1373cb-3aa8-ff73-1bb6-1c5404757db3
* Content: [Value Comparers - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-comparers#background)
* Content Source: [entity-framework/core/modeling/value-comparers.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-comparers.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks!
