### ISSUE TITLE
Incorrect variable passed to Context.Entry()

### ISSUE THREAD

**Issue by krptodr** [dotnet/EntityFramework.Docs#2439]
Shouldn't ```context.Entry(course).Reference``` instead be ```context.Entry(course2).Reference```?

```csharp
// Get the course where currently DepartmentID = 2.
    Course course2 = context.Courses.First(c => c.DepartmentID == 2);

    // Use DepartmentID foreign key property
    // to change the association.
    course2.DepartmentID = 3;

    // Load the related Department where DepartmentID = 3
    context.Entry(course).Reference(c => c.Department).Load();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1156c548-5ab9-eb9f-f5cd-61a2a6312911
* Version Independent ID: 6b2d009a-d8db-b065-f46e-d307e25e278a
* Content: [Relationships, navigation properties, and foreign keys - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/relationships#loading-related-objects)
* Content Source: [entity-framework/ef6/fundamentals/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks @krptodr, changed to use course as the variable name.
