### ISSUE TITLE
Clarity on the default method that EF Core Tools looks for in a project's Program.cs

### ISSUE THREAD

**Issue by liamwhan** [dotnet/EntityFramework.Docs#2441]
Reading through [Design-time DbContext Creation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation) and there is this line regarding how the tools resolve the `DbContext` object:
> The tools first try to obtain the service provider by invoking Program.CreateHostBuilder(), calling Build(), then accessing the Services property.

This conflicts with the [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host) docs which indicate that the tools look for a method names `CreateWebHostBuilder` on the `Program` class:

> The code that calls CreateDefaultBuilder is in a method named CreateWebHostBuilder, which separates it from the code in Main that calls Run on the builder object. This separation is required if you use Entity Framework Core tools. The tools expect to find a CreateWebHostBuilder method that they can call at design time to configure the host without running the app. An alternative is to implement IDesignTimeDbContextFactory. For more information, see Design-time DbContext Creation.

Just seeking some clarification on whether the disparity between `CreateHostBuilder` and `CreateWebHostBuilder` is consequential? Do the tools look for a method with either name on the Program class? 

Thanks in advance, 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa64390-1232-8dd3-f170-7d5c68e29ad9
* Version Independent ID: 245bbba8-3102-4a66-15eb-650e05eb9e62
* Content: [Design-time DbContext Creation - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation)
* Content Source: [entity-framework/core/miscellaneous/cli/dbcontext-creation.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dbcontext-creation.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
It looks for (in this order):

1. CreateHostBuilder().Build().Services
2. CreateWebHostBuilder().Build().Services
3. BuildWebHost().Services

**Comment by liamwhan** [comment]
Thanks @bricelam !
