### ISSUE TITLE
Out of date docs

### ISSUE THREAD

**Issue by Ju66ernaut** [dotnet/EntityFramework.Docs#2449]
I believe this documentation is out of date. 
In the example for ASP.NET Core, C# code example. The method signature for `Configuration.GetConnectionString()` has changed it no longer has a single (string) argument but now takes in an IConfiguration parameter and a string name parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings#feedback)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Ju66ernaut GetConnectionString is an [extension method](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods).
