### ISSUE TITLE
IncludeProperties does not exist on ModelBuilder

### ISSUE THREAD

**Issue by proforce2k** [dotnet/EntityFramework.Docs#2457]
The example given uses a method that isnt available:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Post>()
        .HasIndex(p => p.Url)
        .IncludeProperties(p => new
        {
            p.Title,
            p.PublishedOn
        });
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f85ea32c-8d23-d61d-6036-cd772e3e95d9
* Version Independent ID: 25dd8ac4-2521-5200-0ddf-63ac8c83787a
* Content: [Indexes - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/indexes)
* Content Source: [entity-framework/core/modeling/indexes.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/indexes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Which provider are you using?

**Comment by proforce2k** [comment]
Ah I see - i was using Microsoft.EntityFrameworkCore.Relational, not Microsoft.EntityFrameworkCore.SqlServer. 

Thanks

J
