### ISSUE TITLE
public virtual TEntity Find (params object[] keyValues);

### ISSUE THREAD

**Issue by 1257960069** [dotnet/EntityFramework.Docs#2461]
[在此处输入反馈]
public virtual TEntity Find (params object[] keyValues);
这个方法可以输入多个参数,但最终返回一个实体对象.
如果我 执行  Find(1,2,3),会报错.
这是为什么,是方法设计错误了吗?
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 681bc5c0-cca6-1811-ec3b-93742747e838
* Version Independent ID: c439f4b8-4edd-6faa-56a7-0779d46c3d99
* Content: [DbContext.Find Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/zh-cn/dotnet/api/microsoft.entityframeworkcore.dbcontext.find?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Machine translation:

> (Enter feedback here)
> public virtual TEntity Find (params object s. keyValues);
> This method can enter multiple parameters but eventually return an entity object.
> If I execute Find (1,2,3), I will report an error.
> Why is this the wrong method design?

**Comment by ajcvickers** [comment]
@1257960069 See https://github.com/dotnet/EntityFramework.Docs/issues/2403#issuecomment-634126253
