### ISSUE TITLE
How to ensure transactionality of two sqlserver databases

### ISSUE THREAD

**Issue by CeciAc** [dotnet/EntityFramework.Docs#2462]
The comments below were machine translated

@bxjg1987 commented on [Mon Jun 15 2020](https://github.com/dotnet/EntityFramework.Docs.zh-cn/issues/74)

In the previous .net framework version, TransactionScope can be used. Is there any solution in .net core 3.x version?

---

@srvbpigh commented on [Tue Jun 16 2020](https://github.com/dotnet/EntityFramework.Docs.zh-cn/issues/74#issuecomment-644585621)

Hello, @bxjg1987
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ajcvickers** [comment]
@bxjg1987 .NET Core does not support distributed transactions. See https://github.com/dotnet/runtime/issues/715
