### ISSUE TITLE
--connection <CONNECTION> option of database update is not supported

### ISSUE THREAD

**Issue by Peter-B-** [dotnet/EntityFramework.Docs#2470]
It seems like the `--connection` option of `dotnet ef database update` is not supported any more in version `3.1.5`.

Is there an alternative?

```
> dotnet ef database update --help
                                                                                                                        
Usage: dotnet ef database update [arguments] [options]

Arguments:
  <MIGRATION>  The target migration. If '0', all migrations will be reverted. Defaults to the last migration.

Options:
  -c|--context <DBCONTEXT>               The DbContext to use.
  -p|--project <PROJECT>                 The project to use.
  -s|--startup-project <PROJECT>         The startup project to use.
  --framework <FRAMEWORK>                The target framework.
  --configuration <CONFIGURATION>        The configuration to use.
  --runtime <RUNTIME_IDENTIFIER>         The runtime to use.
  --msbuildprojectextensionspath <PATH>  The MSBuild project extensions path. Defaults to "obj".
  --no-build                             Don't build the project. Only use this when the build is up-to-date.
  -h|--help                              Show help information
  -v|--verbose                           Show verbose output.
  --no-color                             Don't colorize output.
  --prefix-output                        Prefix output with level.

```

```
> dotnet ef database update --version
Entity Framework Core .NET Command-line Tools
3.1.5
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by smitpatel** [comment]
It is available in 5.0 release https://github.com/dotnet/efcore/issues/10750

**Comment by Peter-B-** [comment]
Ah. Thanks. I didn't realize that.
Another reason to upgrade.

**Comment by mark-patton** [comment]
Hi everyone, I came across this issue with 3.1.5 where i too got the `--connection <CONNECTION> option of database update is not supported`

If you go to the section **Known issue with --connection...** in this article i pulled together to explain my experience of this,   you'll see how I updated my appsettings.json connection string on the fly, in the pipeline, and then running `dotnet ef database update`.  Here's the link: [https://markpatton.cloud/2020/07/03/entity-framework-core-migrations-in-azure-devops/](url)

Hope you find it useful.
