### ISSUE TITLE
Seeding different data for development

### ISSUE THREAD

**Issue by divinebovine** [dotnet/EntityFramework.Docs#2488]
What about seeding data that differs between environments. E.g. while working with healthcare data, you may want to seed anonymized data for development to limit the exposure to protected health information (PHI).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/data-seeding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
[Custom initialization logic](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#custom-initialization-logic) would be the best way to do that, Generally model seed data shouldn't contain PHI, PII or other sensitive data.
