### ISSUE TITLE
`Task.WhenAll()` is disabled but not documented as breaking change

### ISSUE THREAD

**Issue by Tri125** [dotnet/EntityFramework.Docs#2489]
I was upgrading to EF Core 3.0 and the app started throwing ``InvalidOperationException`` when calling Task.WhenAll with queries on the same dbContext.
I found this issue https://github.com/dotnet/efcore/issues/10914 but I didn't see it being documented in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d0e044-b0cb-21e2-19c1-2f137da671ac
* Version Independent ID: 1cbedd95-8640-1649-9967-d0ef71633534
* Content: [Breaking changes in EF Core 3.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#query-types-are-consolidated-with-entity-types)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Tri125 It was never safe or supported, but we improved the detection of negative cases in 3.0.
