### ISSUE TITLE
Undocumented breaking change : FromSqlRaw returning null entity if all column values are null on keyless entity

### ISSUE THREAD

**Issue by Tri125** [dotnet/EntityFramework.Docs#2491]
If you read the mitigation section for the breaking change [Query types are consolidated with entity types](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#query-types-are-consolidated-with-entity-types) you are lead to believe that you only need to change the type ``DbQuery`` to ``DbSet<>`` and to configure the entity with ``HasNoKey()``.

However, a DbQuery with an empty result was returning an object instance where all properties where null.

On EF Core 3.0 the keyless entity will simply be null. As part of the mitigation we need to make sure that those null values are properly handled.

https://github.com/dotnet/efcore/issues/19537

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d0e044-b0cb-21e2-19c1-2f137da671ac
* Version Independent ID: 1cbedd95-8640-1649-9967-d0ef71633534
* Content: [Breaking changes in EF Core 3.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Tri125 The breaking change is actually this one: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#de. That being said, I agree that this consequence of the change  is not clear from the docs.

**Comment by Tri125** [comment]
Thank you for the clarification!
