### ISSUE TITLE
No mention of how to turn of the auto creation of the shadow property for missing foreign keys or alternate keys

### ISSUE THREAD

**Issue by Thrillseeker419** [dotnet/EntityFramework.Docs#2494]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 550a3c36-7f1d-efa7-3ed8-769720168da4
* Version Independent ID: 627c4301-e00d-826e-d545-3a244305dec9
* Content: [Shadow Properties - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties)
* Content Source: [entity-framework/core/modeling/shadow-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/shadow-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
Would you prefer that an exception is thrown? Then call
```C#
.ConfigureWarnings(b => b.Error(CoreEventId.ShadowPropertyCreated))
```
