### ISSUE TITLE
Copy paste error in documentaion

### ISSUE THREAD

**Issue by Kurt17P** [dotnet/EntityFramework.Docs#2496]
I guess the code snippet following "A property that would be optional by convention can be configured to be required as follows:" is incorrect. Instead of [Required] it should be [Optional] (or whatever the keyword is for marking an entry as optional).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4381838-81bb-52c6-d921-f8b9ae8163d2
* Version Independent ID: 892a8dd8-7a63-ce0b-de20-27e92b88f971
* Content: [Entity Properties - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cfluent-api%2Cwithout-nrt)
* Content Source: [entity-framework/core/modeling/entity-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/entity-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @lajones
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Entity type string which is nullable type so conventionally property will be optional and RequiredAttribute marks it as required rather than optional. Hence the text and the code snippet as correct.

**Comment by Kurt17P** [comment]
my fault, you are correct. Sorry.
