### ISSUE TITLE
Tools: Include backreference to the common parameters under each command

### ISSUE THREAD

**Issue by ShahryarSaljoughi** [dotnet/EntityFramework.Docs#2498]
I expect to see a complete list of parameters for each command or a link to some page which covers more details.  
As an example, `Update-Database` can get a `-Context` parameter which is not listed in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [EF Core tools reference (Package Manager Console) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ShahryarSaljoughi** [comment]
I can see now that I was wrong. You've separated common parameters to some other section.  
I'm sorry for the my rush to create an issue.
I'll close this issue.

**Comment by bricelam** [comment]
I think your feedback is valid. Maybe we should link back to the common parameters under each command.
