### ISSUE TITLE
Why to have the ID for navigation property

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/EntityFramework.Docs#2502]
This part of code:

```csharp
public int DepartmentID { get; set; }
public virtual Department Department { get; set; }
```

Is a bit confusing, why `Department` navigation property isn't sufficient alone? Is there any benefits adding `DepartmentID`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1156c548-5ab9-eb9f-f5cd-61a2a6312911
* Version Independent ID: 6b2d009a-d8db-b065-f46e-d307e25e278a
* Content: [Relationships, navigation properties, and foreign keys - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/relationships)
* Content Source: [entity-framework/ef6/fundamentals/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
That's the foreign key value from the database. It doesn't have to be stored in the entity, but it's often pragmatic to do so.
