### ISSUE TITLE
What package the UseSqlite is hiding in?

### ISSUE THREAD

**Issue by HerraHak** [dotnet/EntityFramework.Docs#2507]
Hi,

I always love the microsoft docs, but it would be much much more efficient if you would put the nuget packages we need to use to actually call the UseSqlite method.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7b56f-7f91-2f15-1fb6-4f481e97534f
* Version Independent ID: 6d9c65c6-f159-b234-48fd-f25da05f0f32
* Content: [Testing with SQLite - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite)
* Content Source: [entity-framework/core/miscellaneous/testing/sqlite.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/sqlite.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Microsoft.EntityFrameworkCore.Sqlite ?

**Comment by ErikEJ** [comment]
It is listed in the sample .csproj file: https://github.com/dotnet/EntityFramework.Docs/blob/master/samples/core/Miscellaneous/Testing/ItemsWebApi/Tests/Tests.csproj
