### ISSUE TITLE
please mention dotnet tool install

### ISSUE THREAD

**Issue by Josbourne2** [dotnet/EntityFramework.Docs#2513]
Please mention dotnet tool install command needed for installing the ef toolset..
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5747ad3-edd5-1977-883c-2cf77112306c
* Version Independent ID: d66d0616-2aa2-8be4-5ab6-24201ef00b59
* Content: [Installing Entity Framework Core - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/install/)
* Content Source: [entity-framework/core/get-started/install/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/install/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment]
Duplicate of #1588
