### ISSUE TITLE
Self-referencing relationship

### ISSUE THREAD

**Issue by ip75** [dotnet/EntityFramework.Docs#2515]
Self-referencing relationship: A relationship in which the dependent and the principal entity types are the same.

there is no samples and any descriptions Self-referencing relationship. my sprint will fail because of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#one-to-one)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
Here's an example:
```C#
public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }

    public Person Parent { get; set; }
    public ICollection<Person> Children { get; set; }
}
```

**Comment by ip75** [comment]
one-to-one self reference

```
public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }


    public int NextId  { get; set; }
    public int PreviousId  { get; set; }
    public virtual Person Previous { get; set; }
    public virtual Next { get; set; }
}
```

definition of class is a trivial part of it.
what about entity type configuration with Fluent API?

            builder.HasOne(ci => ci.Next)
                .WithOne(x => x.Previous)
                .HasForeignKey<Person>(e => e.NextId)
                .IsRequired(false);

            builder.HasOne(ci => ci.Previous)
                .WithOne(x => x.Next)
                .HasForeignKey<Person>(e => e.PreviousId)
                .IsRequired(false);

this one gives errors: 

  Error Message:
   System.AggregateException : One or more errors occurred. (The child/dependent side could not be determined for the one-to-one relationship between 'Person.Next' and 'Person.Previous'. To identify the child/dependent side of the relationship, configure the foreign key property. If these navigations should not be part of the same relationship configure them without specifying the inverse. See http://go.microsoft.com/fwlink/?LinkId=724062 for more details.) (The following constructor parameters did not have matching fixture data: DbFixtureDictionaries fixture)
---- System.InvalidOperationException : The child/dependent side could not be determined for the one-to-one relationship between 'ManagerReply.NextReply' and 'ManagerReply.PreviousReply'. To identify the child/dependent side of the relationship, configure the foreign key property. If these navigations should not be part of the same relationship configure them without specifying the inverse. See http://go.microsoft.com/fwlink/?LinkId=724062 for more details.
---- The following constructor parameters did not have matching fixture data: DbFixtureDictionaries fixture
  Stack Trace:

**Comment by AndriySvyryd** [comment]
@ip75 You only need one FK property and configure the relationship once. If it's optional the FK property should be of `int?` type.

**Comment by ip75** [comment]
FK is an `int?` type in my project and i got the same error.
I have a record with links to previous and next record.
I do not understand how to configure the relationship once? I have 2 IDs.

**Comment by AndriySvyryd** [comment]
@ip75 You have two navigations for the same relationship, you only need one FK property to represent it.

`Next` points to a `Person` with same `Id` value as `NextId` on the current instance, `Previous` points to a `Person` with same `NextId` value as `Id` on the current instance

**Comment by ip75** [comment]
@AndriySvyryd you suggest me to remove `PreviousId` but i need `Id` of previous instance when i have current instance values.

**Comment by AndriySvyryd** [comment]
@ip75 Yes. You can get it from `Previous.Id`

**Comment by ip75** [comment]
@AndriySvyryd 
1. I have 3 records. `inst1` -> `inst2` -> `inst3`
2. I remove `inst2`
3. where `inst3.Previous.Id` will point to?

**Comment by AndriySvyryd** [comment]
If you remove `inst2` you need to update `inst1.Next` to point to `inst3` and `inst1.NextId` will be updated accordingly.

At this point your original question has been answered. Any non-EF-specific follow ups on data structures and relational databases will be considered off-topic.

**Comment by ip75** [comment]
Please, correct me if i misunderstand.
```
public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }

    public int? NextId  { get; set; }
    public virtual Person Previous { get; set; }
    public virtual Person  Next { get; set; }
}
```
`Person` have only `NextId` in database. we describe `NextId` as a FK in FluentAPI. When we use EF 
`Previous` and `Next` are the only virtual objects that keep only in memory while raising context. And forward and backward objects (`Previous` and `Next`) are temporary in memory and they are destroyed when context is closed. So `PreviousId` field in database is redundant. Is it correct?

**Comment by AndriySvyryd** [comment]
> And forward and backward objects (Previous and Next) are temporary in memory and they are destroyed when context is closed.

No. When you dispose the context all objects remain as long as you have a reference to them.

> I can change Previous and Next records and then call SaveChanges to keep data in previous and next record in database accordingly. All logic for two directions linked list performs EF. So PreviousId field in database scheme is redundant. Is it correct?

Yes.
