### ISSUE TITLE
Referenced NRT example is missing

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/EntityFramework.Docs#2529]
In the section "Non-nullable properties and initialization", the second sentence says "In our example above, we avoided these warnings by using constructor binding ..."

Did the example that's mentioned get moved to a different page? I don't see any examples on this page that use constructor binding, although I could be missing something :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#dbcontext-and-dbset)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
You're right, this was probably a result of some change at some point. I'll amend the docs with an example of using constructor bindings.

**Comment by Bosch-Eli-Black** [comment]
Cool; thanks :)
