### ISSUE TITLE
The SQL type for a property marked with a [Timestamp] attibute is TIMESTAMP, not ROWVERSION

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/EntityFramework.Docs#2533]
A check on the SQL created by the [Timestamp] attribute on a SQL Server (version 13.0.4001.0) is TIMESTAMP, not ROWVERSION.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041e7a47-a632-132a-3c9e-db46e3782a63
* Version Independent ID: a5de9c4c-56fe-416e-0801-f6acd061f25e
* Content: [Concurrency Tokens - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/concurrency?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/concurrency.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@JonPSmith `rowversion` is a synonym for `timestamp` in SQL Server.

**Comment by ajcvickers** [comment]
We discussed in triage, SQL Server `timestamp` conflicts with the `timestamp` defined in the SQL standard. Therefore we always refer to it as `rowversion` which avoids ambiguity.
