### ISSUE TITLE
Is the -Connection flag still supported?

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/EntityFramework.Docs#2543]
When I run the command

```
Update-Database -Connection="..."
````

I get this error message:

```
Update-Database : A parameter cannot be found that matches parameter name 'Connection'.
```

Running the command `get-help Update-Database`, it gives this for the syntax:

```
SYNTAX
    Update-Database [[-Migration] <String>] [-Context <String>] [-Project <String>] [-StartupProject <String>] [<CommonParameters>]
```

From the description of the syntax, it looks like `-Connection` isn't supported. Am I looking at the wrong documentation, or is the `-Connection` flag no longer supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [EF Core tools reference (Package Manager Console) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
It's coming in EF Core 5.0.0. Looks like we forgot to update the PMC page when we fixed #2470.

**Comment by Bosch-Eli-Black** [comment]
Ah, got it; thanks.

Should I close this bug or leave it open for the documentation to be fixed?

**Comment by bricelam** [comment]
Leave open to fix docs. 👌
