### ISSUE TITLE
DbFunctions documentation missing methods

### ISSUE THREAD

**Issue by NetMage** [dotnet/EntityFramework.Docs#2548]
The documentation for methods in DbFunctions seems to be missing a few methods, such as `DateFromParts`, `TimeFromParts`, `SmallDateTimeFromParts`, `DataLength`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c516f9eb-928c-2f34-63e1-2285f2c524e5
* Version Independent ID: 27061b6e-0ab1-de5a-d03d-d7cbd2a2618e
* Content: [DbFunctions Class (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbfunctions?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbFunctions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbFunctions.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@NetMage API docs are typically not updated until the RTM release, at which point they are generated from the doc comments in the code.

**Comment by NetMage** [comment]
Thank you, I didn't realize it was a future feature.
