### ISSUE TITLE
EF Transaction timeouts

### ISSUE THREAD

**Issue by Monkeyfish7000** [dotnet/EntityFramework.Docs#2558]
[Enter feedback here]
When using the transaction API, the page makes no mention of total timeout available to the transaction as a whole. Is there a default timeout to the transaction? Is the timeout of the whole transaction limited to the same as CommandTimeout? Or can the transaction last indefinitely as long as each SaveChanges call remains under CommandTimeout?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
In general, I'm not aware of a transaction timeout in database - you can keep a transaction open indefinitely (but that's probably not a good idea). The CommandTimeout of the commands executed within that transaction is what matters (e.g. SaveChanges).

Note that [System.Transactions.TransactionScope](https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transactionscope?view=netcore-3.1) has a timeout, but that's not related to the EF Core transaction APIs described on this page.
