### ISSUE TITLE
Clarification needed about using SaveChanges transactions, BeginTransaction transactions and nested SQL transactions

### ISSUE THREAD

**Issue by dialedin2014** [dotnet/EntityFramework.Docs#2567]
If within a transaction created by BeginTransaction, does SaveChanges rollback the transaction if there is an error?  Or is its default behavior overridden when BeginTransaction is used?

SaveChanges may call SQL functions or result in SQL triggers firing.  The TSql code may call Rollback Transaction, which rolls back the outermost transaction in the batch (see [When nesting transactions, this same statement rolls back all inner transactions to the outermost BEGIN TRANSACTION statement.](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/rollback-transaction-transact-sql?view=sql-server-ver15).

How does this work if BeginTransaction was called, and subsequent operations involve multiple calls to SaveChanges?  Will SQL Server consider the transaction created by BeginTransaction outermost?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e17e30-4349-3193-01f1-5eb33cb88546
* Version Independent ID: dcb6d719-ffc2-2796-c82c-b9873b74cb76
* Content: [Working with Transactions - EF6](https://docs.microsoft.com/en-us/ef/ef6/saving/transactions)
* Content Source: [entity-framework/ef6/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@dialedin2014 SaveChanges will not roll back an explicitly created transaction. It will only rollback the transaction it creates if no explicit transaction has been specified.
