### ISSUE TITLE
EF Core version chart confusion

### ISSUE THREAD

**Issue by joelhall** [dotnet/EntityFramework.Docs#2570]
According yo the version compatibility chart on this page, EF Core 3.1.x appears to only be compatible with the 2.0 versions of both .net standard and core, but I have projects that are using it with the 2.1 version of .net standard and the 3.1 version .net core. What gives?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7cee01-ae77-571c-5517-8037428a2277
* Version Independent ID: 832b8636-b005-c397-dbb4-0ad7f9c0b43d
* Content: [Supported .NET implementations - EF Core](https://docs.microsoft.com/en-us/ef/core/platforms/)
* Content Source: [entity-framework/core/platforms/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/platforms/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment]
.NET strives to be backwards compatible. The versions listed in the table are *minimum* compatible versions. If a library runs on .NET Core 2.0, it is also expected to work on .NET Core 2.1, .2.2, 3.0, 3.1, and 5.0.
