### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by carlbm** [dotnet/EntityFramework.Docs#2572]
[Enter feedback here] Nothing more here than over the IDE. It's not just this page, it's the MS documentation in general 😞 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c0cb48c-ea16-6478-2cf1-c0c71a6b3fb2
* Version Independent ID: ff4c965b-24b0-26d8-3656-f426218293cd
* Content: [SqlExpressionFactory.Function Method (Microsoft.EntityFrameworkCore.Query)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.query.sqlexpressionfactory.function?view=efcore-3.1#Microsoft_EntityFrameworkCore_Query_SqlExpressionFactory_Function_System_String_System_Collections_Generic_IEnumerable_Microsoft_EntityFrameworkCore_Query_SqlExpressions_SqlExpression__System_Type_Microsoft_EntityFrameworkCore_Storage_RelationalTypeMapping_)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Query/SqlExpressionFactory.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Query/SqlExpressionFactory.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by roji** [comment]
This API has already been documented more thoroughly for 5.0, which hasn't been released yet. [Consult the source code](https://github.com/dotnet/efcore/blob/8c4bc0e91b22d865212062412741d81ac3a7ca5e/src/EFCore.Relational/Query/ISqlExpressionFactory.cs#L398) for the new documentation, once 5.0 is out that will appear on the website too.
