### ISSUE TITLE
Please elaborate more on unit-testing with DbContext and DbSet

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/EntityFramework.Docs#2581]
Hi,

In my case, I have a service layer that depends on `DbContext`.
I wish I could simply mock `IDbSet<T>` to throw exceptions or return data for simple unit testing scenarios.

Please elaborate more on setting up unit test where the SUT depends on a `DbContext`, maybe a little example to narrow down the options.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc404118-9d76-7dac-9813-e286b63bab7d
* Version Independent ID: 5af33a34-b1fc-9b02-f26d-f30be393409b
* Content: [Testing code that uses EF Core - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/)
* Content Source: [entity-framework/core/miscellaneous/testing/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@weitzhandler Can you post an example of something you want to test? I'm interested to dig into this, but things get very ambiguous when dealing with IQueryables, like DbSet. I would like to see an example of business logic that you want to test by creating a context test double.

**Comment by weitzhandler** [comment]
I don't like to handle my logic in the controller. I like to have a black-boxed business layer that takes care of everything, validation etc.
When the service provided to the business layer is `DbContext` exposing `DbSet<T>`s, it's really harder to mock them. I wish there was an abstraction of `DbSet<T>`, such as `IDbSet<T>` so that I can create service contracts like the following:

```c#
public interface IStudentStorageService
{
  IDbSet<Student> Students { get; }
  Task<int> SaveChangesAsync();
}

public SchoolDbContext : IStudentStorageService
{
  public IDbSet<Student> Students { get; set; }
}

public interface IStudentBusinessService
{
   Task AddStudent(Student student);
}

public class StudentBusinessService : IStudentBusinessService
{
   public StudentBusinessService(
    IStudentStorageService storage,
    IValidator<Student> validator,
    ILogger<StudentBusinessService> logger)
  {
    //set fields
  }

  public async Task AddStudent(Student student)
  {
    Validate(student);
    PerformFiddlestickChecks(student);
    StorageService.Students.Add(student);
    await StorageService.SaveChangesAsync();
  }   
}

/ *** /
services.Register<IStudentStorageService, StudentDbContext>();
services.Register<ITeacherStorageService, StudentDbContext>();
services.Register<IStorageService<>, StorageService<>>(); //via DbContext.Set<T>

services.Register<IStudentBusinessService, StudentBusinessService>();
/ *** /

public class StudentBusinessServiceUnitTests
{
  readonly Mock<IDbSet<Student>> = new ...
  readonly Mock<IStudentStorageService> = new ...
  readonly Mock<IValidator<Student>> = new ...
  readonly IStudentBusinessService studentBusinessService;

  public StudentBusinessServiceUnitTests()
  {
    this.studentBusinessService =
      new StudentBusinessService(
        this.studentStorageService.Object, 
        this.validatorMock.Object,
        this.loggerMock.Object);
  }

  [Fact]
  public async Task Should_throw_if_validation_failed()
  {
    // arrange
    this.validationMock.Setup(validation should fail);
    ...
    var task = this.studentBusinessService.AddStudentAsync(invalidStudent);
    ...

    // act
    var exception = await Record.ExceptionAsync(() => task);
    
    // assert    
    exception
      .Should().BeOfType<SomeServiceValidationException>()
      .Which
      .Message.Should().Be("Nope!");

    this.loggerMock.Verify(logger => something was logged);
  }


  [Fact]
  public async Task Should_success_if_valid()
  {
    // arrange
    this.studentStorageService.SetupGet(storageService.Students, this.studentsSet.Object);
    this.validationMock.Setup(validation should succeed);
    ...
    ...

    // act
    await this.studentBusinessService.AddStudentAsync(validStudent);
    
    // assert    
    this.studentSetMock.Verify(studentSet => studentSet.Add was called with student)
    this.studentStorageServiceMock.Verify(storageService => storageService.SaveChangesAsync was called);
  }
}
```

**Comment by weitzhandler** [comment]
Actually I see `DbSet`'s methods are all virtual, so it might just work out the box. Would still be useful if there is guidance in the docs.

**Comment by ajcvickers** [comment]
@weitzhandler In your example, is your mock DbSet an IQueryable? If so, what code runs when the application tries to use it to run a LINQ query?

**Comment by weitzhandler** [comment]
I think I understand what you're asking, you mean that we expose the actual LINQ query to the service consumer, but really it doesn't matter because let's say we expose an `IEnumerable<T>` or even a `ReadOnlyList<T>` or whatever materialized result, the question still stands, how can I easily mock the underlying services (i.e. the `DbContext`), while keeping my focus on what the system under test (in my sample business-service) is meant to do, e.g. validation etc?

**Comment by JeremyLikness** [comment]
Will take to design and discuss improvements.

**Comment by JeremyLikness** [comment]
@roji to consolidate issues that may already exist.

**Comment by ajcvickers** [comment]
@weitzhandler How do you expose only `IEnumerable<T>` or even a `ReadOnlyList<T>` given that DbSets are `IQueryable`?

**Comment by weitzhandler** [comment]
It doesn't really matter, so long I setup the mocking service's method I'll be going to use, and verify no other methods have been called.
This way, the setup and verification doesn't require a bunch of coding for the mocks setup, and the rest methods are easily readable and straight forward.

**Comment by ajcvickers** [comment]
@weitzhandler Yes, but mocking IQueryable is very hard and error-prone, and in my opinion should be avoided. I can't see how mocking a context without mocking IQueryable is useful, so I'm trying to understand what you are intending to do instead. Can you give an example of the kind of test you want to write against the mocked context? Specifically, assume you have a fully mocked context, can you post the code of a representative test that uses it?

**Comment by ajcvickers** [comment]
@weitzhandler I'm really interested in figuring this out. I would love to write guidance for mocking DbSets that would be useful to people. I just don't see a way of doing that yet.

**Comment by weitzhandler** [comment]
@ajcvickers thanks for your reply.
If there is anything I can do to help, I'd be happy to.
We can also chat on Twitter or on Gmail (same as my GH handle), so that you or someone can give me some instructions.

**Comment by ajcvickers** [comment]
@weitzhandler I think it would be great if you could show some tests that you would like to write and then we can figure out what needs to be done for the mocking.

**Comment by roji** [comment]
@weitzhandler I'm also curious what exact usage you want to make of IDbSet that wouldn't work with the InMemory provider.

**Comment by weitzhandler** [comment]
Actually I made [an example project](https://bit.ly/2FRsg6O) using Moq, and apparently, mocking classes seems to be fairly easy, including mocking of `DbSet<T>`.

I'm gonna close this issue, but it's still recomended documentation should be added for business-layer scenarios, where the repository or storage layer is irrelevant for the business scenario (e.g. entity validation), and no in-memory is required for that.

Here's my test class:

```c#
public class ContactsBusinessLayerTests
{
    readonly Mock<IRepository<Contact>> contactRepositoryMock = new Mock<IRepository<Contact>>();
    readonly Mock<DbSet<Contact>> contactDbSetMock = new Mock<DbSet<Contact>>();
    readonly Mock<IValidator<Contact>> contactValidatorMock = new Mock<IValidator<Contact>>(MockBehavior.Strict);
    readonly Mock<ILogger> loggerMock = new Mock<ILogger>();
    readonly ContactsBusinessLayer contactsBusinessLayer;

    public ContactsBusinessLayerTests()
    {
        contactsBusinessLayer = new ContactsBusinessLayer(
            contactRepositoryMock.Object,
            contactValidatorMock.Object,
            loggerMock.Object);
    }

    [Fact]
    public async Task Should_add_if_valid()
    {
        // arrange
        var contact = new Contact { Name = "Arthur" };

        contactRepositoryMock
            .Setup(repository => repository.Set())
            .Returns(contactDbSetMock.Object);

        contactValidatorMock
            .Setup(validator => validator.Validate(contact))
            .Returns(true);

        // act
        await contactsBusinessLayer.AddAsync(contact);

        // assert
        contactValidatorMock
            .Verify(contactValidator => contactValidator.Validate(contact),
                Times.Once);

        contactDbSetMock
            .Verify(dbSet => dbSet.Add(contact),
                Times.Once);

        contactRepositoryMock
            .Verify(repository => repository.SaveChangesAsync(new CancellationToken()),
                Times.Once);

        VerifyNoOtherCalls();
    }

    [Fact]
    public async Task Should_log_error_and_not_add_if_invalid()
    {
        // arrange
        var contact = new Contact();
        var expectedErrorMessage = $"Validation failed for contact {contact}.";

        contactValidatorMock
            .Setup(validator => validator.Validate(contact))
            .Returns(false);

        // act
        await contactsBusinessLayer.AddAsync(contact);

        // assert
        contactValidatorMock
            .Verify(contactValidator => contactValidator.Validate(contact),
                Times.Once);

        loggerMock
            .Verify(logger => logger.LogError(expectedErrorMessage),
                Times.Once);

        VerifyNoOtherCalls();
    }

    void VerifyNoOtherCalls()
    {
        contactValidatorMock.VerifyNoOtherCalls();
        contactRepositoryMock.VerifyNoOtherCalls();
        contactDbSetMock.VerifyNoOtherCalls();
        loggerMock.VerifyNoOtherCalls();
    }
}
```
