### ISSUE TITLE
System.Transactions implementation in .NET Core for distributed transactions

### ISSUE THREAD

**Issue by pfdsilva** [dotnet/EntityFramework.Docs#2588]
The following has been mentioned in this webpage. (https://docs.microsoft.com/en-us/ef/core/saving/transactions)

_"As of version 2.1, the System.Transactions implementation in .NET Core does not include support for distributed transactions, therefore you cannot use TransactionScope or CommittableTransaction to coordinate transactions across multiple resource managers."_

Is there any update on this based on the latest version of .Net Core?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This is tracked in the dotnet/runtime repo: https://github.com/dotnet/runtime/issues/715
