### ISSUE TITLE
Other advantages of moving the migrations to a library?

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/EntityFramework.Docs#2596]
Hello, what are the other advantages of moving the migrations to a separate project/library? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Using a Separate Migrations Project - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@gojanpaolo Advantages other than what?

**Comment by gojanpaolo** [comment]
@ajcvickers The docs say one advantage is the ability to have multiple sets of migrations for multiple environmets (dev, prod, etc)

> You may want to store your migrations in a different assembly than the one containing your DbContext. You can also use this strategy to **maintain multiple sets of migrations, for example, one for development and another for release-to-release upgrades**.

**Comment by AndriySvyryd** [comment]
- You can also maintain different migration sets for different providers
- The main assembly size would be smaller

**Comment by gojanpaolo** [comment]
Thanks @AndriySvyryd! If the migration project is separate, does it still need to be deployed to the server for the app to work?

**Comment by bricelam** [comment]
> does it still need to be deployed

Not if you apply migrations as part of publishing. Yes if you call dbContext.Database.Migrate()

**Comment by gojanpaolo** [comment]
Thanks @bricelam!
