### ISSUE TITLE
What replaces the ApplyConfiguration<TQuery>(IQueryTypeConfiguration<TQuery>) API?

### ISSUE THREAD

**Issue by wmmaintz** [dotnet/EntityFramework.Docs#2598]
ApplyConfiguration<TQuery>(IQueryTypeConfiguration<TQuery>)

Warning

This API is now obsolete.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5236739c-346b-c5b9-1621-4e99ea66f17c
* Version Independent ID: ff432dff-3a44-1c2d-2260-a8c0f27d4ae9
* Content: [ModelBuilder.ApplyConfiguration Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.modelbuilder.applyconfiguration?view=efcore-3.1#Microsoft_EntityFrameworkCore_ModelBuilder_ApplyConfiguration__1_Microsoft_EntityFrameworkCore_IEntityTypeConfiguration___0__)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/ModelBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/ModelBuilder.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#query-types-are-consolidated-with-entity-types

IEntityTypeConfiguration should be used in place of IQueryTypeConfiguration.

**Comment by JeremyLikness** [comment]
Will update link to add small note.
