### ISSUE TITLE
Note potential performance implications

### ISSUE THREAD

**Issue by kevbry** [dotnet/EntityFramework.Docs#2608]
It should be noted in documentation that using async operations in EF Core backed by sqlclient may result in very severe performance degradation over a synchronous option.

https://github.com/dotnet/efcore/issues/22331

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 763dd10a-6619-d9b0-28fb-d9a0be0048b5
* Version Independent ID: 81b05619-22c4-cd7c-7d27-fcb08b888a77
* Content: [Asynchronous Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/async)
* Content Source: [entity-framework/core/querying/async.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/async.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
We don't usually note bugs and issues in external providers which are outside of our control - https://github.com/dotnet/sqlclient contains many other issues which may be blocking for other users etc.

But at this is quite severe, a limitations page under the SQL Server provider docs may be relevant, we'll discuss this in triage.
