### ISSUE TITLE
Is your example doing what it comments not to do?

### ISSUE THREAD

**Issue by syendev** [dotnet/EntityFramework.Docs#2618]
You state in your comment 
`.UseLoggerFactory(MyLoggerFactory) // Warning: Do not create a new ILoggerFactory instance each time`

Are you giving an example of what not to do? or is your example usable as is?

`LoggerFactory.Create` should return a singleton, no?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83069f-39a8-e992-95f7-a8b41154b6f4
* Version Independent ID: 144fe168-080f-6557-e4b2-a18adb4b89ed
* Content: [Logging - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging?tabs=v3)
* Content Source: [entity-framework/core/miscellaneous/logging.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/logging.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Example usable as is. If you see definition of MyLoggerFactory then it is a static field which is initialized only once per class so everytime you initialize the context, it would be same logger factory. The comment specifically says that do not create new instance and pass here every time which using a static field solves.

> LoggerFactory.Create should return a singleton, no?

Singleton/scoped is inside DI. This is outside of DI. Create method creates a logger factory and gives it back to user. There is no scoping. User needs to manage object themselves.
