### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by irsharp23** [dotnet/EntityFramework.Docs#2629]
I added the following to my code, as shown in this article:

[Key]

The compiler does not accept it.

What else needs to be added in order for the [Key] keyword to be accepted?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a084df-15c4-ab25-26ca-83c8bdf6f026
* Version Independent ID: f1fba5b2-eb2e-da0a-fce0-d492855c1777
* Content: [Keys - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/keys?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/keys.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/keys.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
Add `using System.ComponentModel.DataAnnotations;` at the beginning of the file.

Most modern IDEs should show a suggestion to do this.
