### ISSUE TITLE
Error in sample code

### ISSUE THREAD

**Issue by novanettor** [dotnet/EntityFramework.Docs#2633]
In the C# example on how to specify a split query for loading collections, the code uses the method _.AsSingleQuery()_ rather than _.AsSplitQuery()_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Fixed by https://github.com/dotnet/EntityFramework.Docs/pull/2659
