### ISSUE TITLE
Update fwlinks

### ISSUE THREAD

**Issue by smitpatel** [dotnet/EntityFramework.Docs#2634]
https://go.microsoft.com/fwlink/?linkid=2131316 -> https://docs.microsoft.com/en-us/ef/core/querying/filters#accessing-entity-with-query-filter-using-required-navigation

https://go.microsoft.com/fwlink/?linkid=2134277 once the split pages go to live

**Comment by smitpatel** [comment]
https://go.microsoft.com/fwlink/?linkid=2129535 points to base docs and used in exception message that string.Equals cannot be used with string comparison.

**Comment by JeremyLikness** [comment]
2131316 is updated. What's the status on 2134277 ... what should it point to? Where should I redirect 2129535? /cc @smitpatel @ajcvickers

**Comment by smitpatel** [comment]
2134277, you already updated the other day from PR.
2129535 should probably file a new issue and point to it till we have some docs for it? @dotnet/efteam

**Comment by JeremyLikness** [comment]
Pinging on this ... any action here @smitpatel @ajcvickers ? Not clear on what specific doc we are waiting to go live for this.

**Comment by smitpatel** [comment]
https://github.com/dotnet/EntityFramework.Docs/issues/2634#issuecomment-691341532 is still pending.

**Comment by ajcvickers** [comment]
@JeremyLikness I'm not aware of anything else.

**Comment by ajcvickers** [comment]
Closing as dupe of #409
