### ISSUE TITLE
Issue with recommendation (or the very existence of this product)

### ISSUE THREAD

**Issue by xavier-90** [dotnet/EntityFramework.Docs#2641]
I quote: _"Carefully consider before using this approach in production. Experience has shown that the simplicity of this deployment strategy is outweighed by the issues it creates. Consider using SQL scripts instead."_

So what is the _raison d'etre_ of this product? What is the point in spending any time at all developing migration scripts if ultimately we also have to spend time developing SQL scripts to migrate production servers?

I understand the caution and the recommendation not to include the scripts in the primary application but surely the migration mechanism can form part of a separate application/process to upgrade production servers under controlled conditions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06b35eff-79e4-2068-6d1c-f9079d43f903
* Version Independent ID: 6c575b10-048c-349c-397e-0d9c11d47235
* Content: [Applying Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/applying.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/applying.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ErikEJ** [comment]
@xavier-90 the tooling creates the SQL script for you.
