### ISSUE TITLE
Docs and many-to-many relationship example for reverse engineering

### ISSUE THREAD

**Issue by bmoteria** [dotnet/EntityFramework.Docs#2646]
I believe an example of many-to-many relationship example like [this one (RC1)](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#many-to-many) but using reverse engineering is missing? Please correct me if I am wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32360b50-1129-b3d2-2d71-c6b89cd9f2c6
* Version Independent ID: 4f18f8dc-5cd5-cb37-0f59-fb1767609b2b
* Content: [What's New in EF Core 5.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#feedback)
* Content Source: [entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
That is actually not implemented yet...

**Comment by ajcvickers** [comment]
@bmoteria See https://github.com/dotnet/efcore/issues/22475

**Comment by bmoteria** [comment]
@ajcvickers Thanks for redirecting.

**Comment by ajcvickers** [comment]
Note from triage: add a note that this isn't implemented in 5.0 and point to @ErikEJ's Power Tools if it works there.

The document fully when implemented.

**Comment by smitpatel** [comment]
@dotnet/efteam - Which page note about M2M reveng is not supported goes?

**Comment by smitpatel** [comment]
Fixed in #2852
