### ISSUE TITLE
Encourage a level of familiarity with the chosen RDBMS before using EF Core

### ISSUE THREAD

**Issue by lukesdm** [dotnet/EntityFramework.Docs#2657]
The way this documentation is presented makes using an ORM seem much simpler than it is in reality. It can lead to unexpected behaviour and performance problems that become apparent at a later stage in the application's life-cycle, once realistic data loads start to be encountered.  

To avoid and troubleshoot these issues requires a substantial level of knowledge of the chosen RDBMS. 
Such concepts include: Primary keys, foreign keys, constraints, indexes, normalization, DML statements, DDL statements, data types, using a profiler, admin tools, and probably more.  

Perhaps consider adding an aside about this, with links to learning materials for the for the popularly supported RDBMSs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion.

**Comment by ajcvickers** [comment]
@Rick-Anderson Can you please not close issues in this repo. We have a regular triage twice per week for new issues.

**Comment by ajcvickers** [comment]
@lukesdm While I don't necessarily agree with your characterization of the issue, we do believe that having some more documentation in this area would be useful. This is tracked by #2106.

**Comment by lukesdm** [comment]
> @lukesdm While I don't necessarily agree with your characterization of the issue, we do believe that having some more documentation in this area would be useful. This is tracked by #2106.

It would be useful to hear what you disagree with, if it's not too much trouble. Regardless, thank you very much for your response.

**Comment by Rick-Anderson** [comment]
@lukesdm  sorry I accidently closed this issue. As the team responds, review #2668. I don't see much different that what you asserted.

**Comment by ajcvickers** [comment]
@lukesdm I believe it is reasonable for a developer to use EF Core even with little experience using relational databases. As the developer learns they may/should find places where they can improve what they are doing, but that doesn't mean they should feel afraid to even give things a try.
