### ISSUE TITLE
How to specify version of Sql Server when generating SQL Scripts with Script-Migration?

### ISSUE THREAD

**Issue by herrbehn** [dotnet/EntityFramework.Docs#2664]
Hi. When using the Script-Migration command, we get sql scripts that do not work on the production server as this one is not the newest.
Is there a way to specify which version of Sql Server the produced SQL migrations script should work on?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [EF Core tools reference (Package Manager Console) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#common-parameters)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ErikEJ** [comment]
What SQL Server version is your production, and what part of the script fails?

**Comment by herrbehn** [comment]
Production is an Sql Server Enterprise version 14.0.3335.7 and the error we receive is when creating new tables, then

OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF

is part of it and it is not recognized in that version of Sql Server (but works fine on our local development databases).

Of course, we can manually remove that one line, but I guess other unsupported keywords could be used as well?

Den 18. september 2020 kl. 14.16.46 +02.00, skrev Erik Ejlskov Jensen <notifications@github.com>:

**Comment by ErikEJ** [comment]
And that is included in the output from "Script-Migration" - I doubt that.

**Comment by ajcvickers** [comment]
@herrbehn Can you please attach/post the code that results in this script generation so that we can investigate?

**Comment by herrbehn** [comment]
Hi

It turns out that a developer abused the migrations to add sql scripts directly. So I’m sorry for asking this - it’s all good after all :-)

Sendt fra min iPhone
