### ISSUE TITLE
When are they going to bring back a UWP, Entity Framework, SQLite, CodeFirst example.

### ISSUE THREAD

**Issue by maxmin88** [dotnet/EntityFramework.Docs#2672]
There used to be an example of this on docs.Microsoft.  This is the old link that used to show a UWP EF SQLite example
[https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started](url)

It now resolve to the Console app on this page.

Why doesn't MS have a good example of a UWP app using SQLite and EF????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@maxmin88 We're holding off on UWP work while we see where things evolve with [Project Reunion](https://github.com/microsoft/ProjectReunion). The guide we had previously had issues and in general the experience with UWP is not very good. We hope that in the future we'll be able to create and document a great experience as the U.I. platform evolves.
