### ISSUE TITLE
Pomelo has added spatial support

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/EntityFramework.Docs#2674]
Last week [we joined](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/3.2.0) the global movement of spatial awareness.
I get back to you later with the list of officially supported methods and properties, in case you want to add Pomelo to the table in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dcf82b-f177-e91b-96a5-67f2f57bd6c4
* Version Independent ID: 89c0803f-570f-07a6-6dc2-285678712c86
* Content: [Spatial Data - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/spatial)
* Content Source: [entity-framework/core/modeling/spatial.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/spatial.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ErikEJ** [comment]
I have added support for MySql spatial mappings in the latest daily build of EF Core Power Tools

**Comment by roji** [comment]
Great news, congrats @lauxjpn!

Note that we're thinking of splitting spatial information to provider-specific pages rather than trying to consolidate everything into one page (#2611) - this the MySQL spatial info would probably be a better fit in your docs (we'd link to it though).

**Comment by ajcvickers** [comment]
@lauxjpn Very nice. :-) It's great to see the plan to support spatial in a common way across multiple providers coming to fruition. And also embracing the ecosystem with NTS rather than re-inventing spatial types. Again.

Are you on Twitter? I would like to mention you when tweeting about this.

**Comment by roji** [comment]
I very much agree! I remember that early EF Core spatial discussions, and the pain around DbGeometry/DbGeography. I'm really happy spatial ended up working with a good open-source community package instead.

**Comment by lauxjpn** [comment]
> Are you on Twitter? I would like to mention you when tweeting about this.

Unfortunately neither Pomelo (as far as I know) nor I am on twitter. Is this something we should look into?

**Comment by ajcvickers** [comment]
@lauxjpn You don't need to be on there, but I find it useful for getting the word out about new things.

**Comment by lauxjpn** [comment]
> You don't need to be on there, but I find it useful for getting the word out about new things.

@ajcvickers I added my twitter handle (same as the one I use on GitHub) to my GitHub profile. Of course there isn't much going on there yet :)
