### ISSUE TITLE
Update many-to-many table config code example for consistency

### ISSUE THREAD

**Issue by dan-meier** [dotnet/EntityFramework.Docs#2691]
In the RC1 code example (below) describing table configuration of many-to-many relationships, the tables and relationships are different than what was used earlier in the document.  For consistency, I recommend sticking with the Posts/Tags example used up to this point in the document.  For many-to-many relationships, it seems like this table configuration code example is the only code example that does NOT use the Posts/Tags relationship.

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder
        .Entity<Community>()
        .HasMany(e => e.Members)
        .WithMany(e => e.Memberships)
        .UsingEntity<PersonCommunity>(
            b => b.HasOne(e => e.Member).WithMany().HasForeignKey(e => e.MembersId),
            b => b.HasOne(e => e.Membership).WithMany().HasForeignKey(e => e.MembershipsId))
        .Property(e => e.MemberSince).HasDefaultValueSql("CURRENT_TIMESTAMP");
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32360b50-1129-b3d2-2d71-c6b89cd9f2c6
* Version Independent ID: 4f18f8dc-5cd5-cb37-0f59-fb1767609b2b
* Content: [What's New in EF Core 5.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#many-to-many)
* Content Source: [entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Added a note to #1978.
