### ISSUE TITLE
Sharing Databases example : Seed is out of order with SQL Lite - should this be mentioned?

### ISSUE THREAD

**Issue by jimleonardo** [dotnet/EntityFramework.Docs#2699]
When using SQL Lite for my test DB provider, I had to use `Connection.Open()` **before** calling seed. This is most likely because SQLLite will destroy the DB once a connection is closed and so this order is different than SQL Server which, when I tested it, does need the order mentioned in the sample/article.

``` csharp
        public MyDbContextFixture()
        {
            Connection = new SqliteConnection("Filename=:memory:");
            Connection.Open();
            Seed();
            
        }
```

The sample uses SQL Server for an example and likely is most important with non-memory dbs, but some test suites w/in memory DBs may still benefit from using a fixture so I believe that may be worth mentioning in the sample or article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc24a97-4ba7-89d4-eb07-61695a9304cf
* Version Independent ID: b93a52b2-071b-f6f2-6f19-705ccd6464d8
* Content: [Sharing databases between tests - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sharing-databases)
* Content Source: [entity-framework/core/miscellaneous/testing/sharing-databases.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/sharing-databases.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@jimleonardo Can you provide some more details as to why you ant to share an in-memory database in this manner?

**Comment by jimleonardo** [comment]
@ajcvickers I'm new to XUnit so may just be missing something in how it stands classes up, or maybe something with SQLLite. However, using the class fixture approach seems to take about 200ms for the first test in a given class vs ~950ms for the first test in that class. Subsequent tests for same class seem to be same. Here are a couple of typical runs for the project I'm working on:

Without class fixture
Update_Updates Passed 99 ms
Add_Adds Passed 13 ms
Delete_Deletes Passed 13 ms
GetList_Gets Passed 16 ms
Get_Gets Passed **947 ms**

With class fixture
Update_Updates Passed 82 ms
Add_Adds Passed 4 ms
Delete_Deletes Passed 5 ms
GetList_Gets Passed 8 ms
Get_Gets Passed **207 ms**

Even without that odd difference, take this same pattern to a `ICollectionFixture` instead and it's potentially saving a big chunk of time if you've got a bunch of test classes using the same DbContext, e.g. multiple repository classes.

I'm not asking to rework samples or anything, just wondering if it's worth a note in the docs that the position of the `Connection.Open` may need to change with SQLLite.
