### ISSUE TITLE
Why only apply IS NOT NULL to sql server and not postgres/other dbs?

### ISSUE THREAD

**Issue by meyerovb** [dotnet/EntityFramework.Docs#2708]
Why only sql server, not postgres too?

When using the SQL Server provider EF adds an 'IS NOT NULL' filter for all nullable columns that are part of a unique index. To override this convention you can supply a null value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f85ea32c-8d23-d61d-6036-cd772e3e95d9
* Version Independent ID: 25dd8ac4-2521-5200-0ddf-63ac8c83787a
* Content: [Indexes - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/indexes)
* Content Source: [entity-framework/core/modeling/indexes.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/indexes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
PostgreSQL and most other databases don't enforce uniqueness on null values by default.
