### ISSUE TITLE
Where is 'using' class libraries for other annotations?

### ISSUE THREAD

**Issue by JavaJoe127** [dotnet/EntityFramework.Docs#2726]
Cannot use data annotations like [NotMapped] or [ComplexType] because I have no idea what class library to include?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3437af67-630b-d28f-7fbd-3eedf647f22a
* Version Independent ID: 6c44f987-19a7-c256-e8fa-10378e61cf6e
* Content: [Creating and configuring a model - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/)
* Content Source: [entity-framework/core/modeling/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@JavaJoe127 Some attributes are in the `Schema` sub-namespace of `System.ComponentModel.DataAnnotations`. Typically these are easy to find with modern IDEs that will prompt you to import the namespace. The example here doesn't use those annotations, and the sample does not explicitly use that namespace.
