### ISSUE TITLE
Is this what I need?

### ISSUE THREAD

**Issue by JavaJoe127** [dotnet/EntityFramework.Docs#2727]
A simple example would be great. Without it, I'm not sure it's worth my time to figure out what's going on here.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5372d6bf-c52e-2dcb-7a40-97a1f95fa982
* Version Independent ID: 6e1514c4-25cc-f485-c869-8f7ec6891315
* Content: [CastingConverter&lt;TModel,TProvider&gt; Class (Microsoft.EntityFrameworkCore.Storage.ValueConversion)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.valueconversion.castingconverter-2?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Storage.ValueConversion/CastingConverter`2.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Storage.ValueConversion/CastingConverter`2.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@JavaJoe127 It is expected that the API docs be used in conjuction with the conceptual docs--for example, the [value conversions docs](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions) in this case.

Issue https://github.com/dotnet/efcore/issues/17508 is tracking adding links from the API docs to the conceptual docs to make this more discoverable.
