### ISSUE TITLE
Breaking change in EFCore 5.0

### ISSUE THREAD

**Issue by tsproesser** [dotnet/EntityFramework.Docs#2731]
After switching from EF3 to EF5 I get an System.InvalidOperationException on a method that previously worked:

System.InvalidOperationException: "Not enough information to uniquely identify outer element in correlated collection scenario. This can happen when trying to correlate on keyless entity or when using 'Distinct' or 'GroupBy' operations without projecting all of the key columns."

I'm afraid it is a bit complicated to reproduce since it is part of a very huge project, but I'll do my very best and can try to create a sample project, if the misbehavior is unknown and not reproducable:

I'm having a Queryable of **Offers** that gets authorized by a generic method:

```
public IQueryable<Guid> GetAuthorization(Guid paramUserId, IEnumerable<string> paramHierarchys = null, IEnumerable<string> paramPrivileges = null)
            => UserHierarchys
                .Where(h => h.Id == paramUserId && (paramHierarchys == null || paramHierarchys.Contains(h.Hierarchy)) && (paramPrivileges == null || paramPrivileges.Contains(h.Privilege)))
                .Select(h => h.CanAccessId)
                .Distinct()
            ;
```

where UserHierarchy is a simple table:

```
public class UserHierarchy : IUserHierarchy
    {
        public string Hierarchy { get; set; }
        public Guid Id { get; set; }
        public Guid CanAccessId { get; set; }
        public string Privilege { get; set; }
    }
```

Offer inherits from CreateableBase and its UserIdCreated is joined:

```
public abstract class CreateableBase : ModelBase, ICreateable
    {
        [KeepValue]
        [IgnoreHasChanged]
        public Guid? UserIdCreated { get; set; }

        [KeepValue]
        [IgnoreHasChanged]
        [ForeignKey("UserIdCreated")]
        public virtual User UserCreated { get; set; }

        [KeepValue]
        [IgnoreHasChanged]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime DateCreated { get; set; } = DateTime.UtcNow;
    }

public IQueryable<T> Authorize<T>(IQueryable<T> paramQueryable, Guid paramUserId, string paramHierarchy = null, string paramPrivilege = null) where T : ICreateable
            => Authorize(paramQueryable, paramUserId, p => p.UserIdCreated.Value, paramHierarchy == null ? null : new string[] { paramHierarchy }, paramPrivilege == null ? null : new string[] { paramPrivilege });
```

If an authorized Queryable now gets some includes, e.g.

```
offers = offers
                .Include(p => p.Etikettes)
                .ToArray();
```

the exception is thrown.

The query works without the Authorize / Include, but not if **both** are present. Not all includes break the program, but I couldn't figure out what includes do and what don't. Maybe some developer here has some suggestions what to check?

And there's another, maybe correlating issue I hoped to get rid of with EFCore 5.0 but don't:

I have a base class ChangeableBase inheriting from CreateableBase:

  ```
  public abstract class ChangeableBase : CreateableBase, IChangeable
    {
        [KeepValue]
        [IgnoreHasChanged]
        public Guid? UserIdChanged { get; set; }

        [KeepValue]
        [IgnoreHasChanged]
        [ForeignKey("UserIdChanged")]
        [NotMapped]
        public virtual User UserChanged { get; set; }

        [KeepValue]
        [IgnoreHasChanged]
        public DateTime? DateChanged { get; set; }
    }
```

I **need** to set UserChanged to not mapped, since the AutoMapper seams to get confused with relations of the same type pointing to different fields (UserCreated from BaseClass and UserChanged).

Thank you very much for your support!

EF Core version: 5.0.0 rc.1.20451.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1

**Comment by ajcvickers** [comment]
Note from triage: we will document as a breaking change the differences in 5.0 here, since some queries generated by 3.1 did return correct results. We should try to add examples (like shown above) for ways to re-write the queries for 5.0.

**Comment by smitpatel** [comment]
@maumar - Can you "implement" this?

**Comment by tsproesser** [comment]
> @tsproesser Your second issue throws the same error and has the same model validation warning on both 3.1 and 5.0:
> 
> ```
> warn: Microsoft.EntityFrameworkCore.Model[10612]
>       Navigations 'User.UserChanged' and 'User.UserCreated' were separated into two relationships as ForeignKeyAttribute was specified on navigations on both sides.
> Unhandled exception. System.InvalidOperationException: Unable to determine the relationship represented by navigation property 'UserProperty.UserChanged' of type 'User'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidatePropertyMapping(IModel model, IDiagnosticsLogger`1 logger)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
>    at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
>    at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IConventionModelBuilder modelBuilder)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IConventionModelBuilder modelBuilder)
>    at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
>    at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
>    at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
>    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
>    at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
>    at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies()
>    at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()
>    at Program.Main(String[] args) in /home/ajcvickers/AllTogetherNow/ThreeOne/ThreeOneApp.cs:line 19
> ```

Yeah, sorry! This probably was a bit unclear. It is absolutely off-topic and is worth a new issue I'll create one. Is this a bug? Should this work? Or did I just use it wrong?

**Comment by ajcvickers** [comment]
@tsproesser Please file a new issue and we'll look there. This issue is already way overloaded!

**Comment by tsproesser** [comment]
> You can rewrite your query to do filtering via Where rather than Join.
> 
> ```
>         query = query.Where(q => context.UserHierarchys.Select(h => h.CanAccessId).Distinct().Any(k => q.UserIdCreated = k));
> ```

This sure is a suitable workaround, but generates a less performant execution plan! Even though it's still quite fast this is not a real solution for my issue but more a workaround.

**Comment by ilmax** [comment]
Hey @smitpatel do you know what's the issue that tracks fixing the breaking change I reported above? Thanks

**Comment by smitpatel** [comment]
@ilmax - #22892 should track that. Though the earlier release it was actually incorrect result since we ignored it altogether.

**Comment by ilmax** [comment]
Thank you!
