### ISSUE TITLE
It would be nice to describe the return value of SaveChanges()

### ISSUE THREAD

**Issue by stefandebuhr** [dotnet/EntityFramework.Docs#2735]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 635ce96a-7f29-7fcb-b007-4685cef0499b
* Version Independent ID: 6999fa37-7550-6bc6-678f-1a4fb33d2101
* Content: [DbContext.SaveChanges Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.savechanges?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ErikEJ** [comment]
It is already there:

```
<returns>
                The number of state entries written to the database.
            </returns>

```

**Comment by smitpatel** [comment]
The issue turns out to be in docs rendering/generation tool (there are probably 2-3 different bugs. They are being tracked internally.
Work-around is to remove indentation in the EcmaXML. This issue happens for every `returns` in XML doc which uses multiple lines. I will do it alongwith #2748 after 5.0 API docs are also added to the repo.

**Comment by AndriySvyryd** [comment]
See https://github.com/dotnet/EntityFramework.ApiDocs/pull/82

**Comment by smitpatel** [comment]
Turns out issue with returns was a legacy issue which was already fixed. We never live site using fixed code. Docs team did force rebuild on live branch. Now all returns are correctly rendered.
