### ISSUE TITLE
Links to examples don't work

### ISSUE THREAD

**Issue by urza** [dotnet/EntityFramework.Docs#2753]
Links in this sentence do not work:

> You can view a multi-tenancy sample and samples using navigations on GitHub.

https://github.com/dotnet/EntityFramework.Docs/tree/master/samples/core/QueryFilters
https://github.com/dotnet/EntityFramework.Docs/tree/master/samples/core/QueryFiltersNavigations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c9bd3e-4b99-9acf-48d8-e47bc53eb54e
* Version Independent ID: 220e0a6c-d227-956a-d27a-7c88804f770c
* Content: [Global Query Filters - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/filters)
* Content Source: [entity-framework/core/querying/filters.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/filters.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @anpete
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
It will be fixed once we update the live site. We changed the samples structure.
