### ISSUE TITLE
Samples: async or sync?

### ISSUE THREAD

**Issue by roji** [dotnet/EntityFramework.Docs#2754]
#2698 changed the "saving" samples to be async, but we should make a decision as a team, and change all samples accordingly.

**Comment by roji** [comment]
Decision from triage:
* Entry-level docs should be sync-only: we don't want to overload beginners and force them to understand async/await. It also adds clutter
* For other, advanced docs, we can do sync or async - although some people we should be consistent rather than random, so it may be better to just to sync unless there's a good reason to do async.
* For contexts where async is relevant/significant we obviously use async.

Keeping open to revert the changes in #2698.

**Comment by virzak** [comment]
@roji, for async context it is recommended to to use .ConfigureAwait on IAsyncDisposable as shown [here](https://devblogs.microsoft.com/dotnet/configureawait-faq/#can-i-use-configureawait-when-await-using-an-iasyncdisposable)?

**Comment by roji** [comment]
@virzak whether you need to use ConfigureAwait or not depends on your program - libraries should absolutely do it, user code manipulating GUI components should not. In any case, for this specific code the decision has been made to revert to sync code.
