### ISSUE TITLE
The migrations don't work even with simple model changes.

### ISSUE THREAD

**Issue by maxmin88** [dotnet/EntityFramework.Docs#2759]
Simple model updates not working with EF Migrations.

Even a simple property (column) rename doesn't work.  First I get the following warning when I rename one Property in the model and run add-migration.
An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy.

Then when I run my project I get.
SQLite does not support this migration operation ('DropColumnOperation'). For more information, see http://go.microsoft.com/fwlink/?LinkId=723262

Why is there a DropColumn when I am just Renaming my Property/Column???  And besides that, DropColumn is supported by SQLite

And this document clearly says Rename column is supported.

RenameColumn | ✔ | 2.2.2
-- | -- | --

I am using:
Microsoft.EntityFrameworkCore.Sqlite     Ver 3.1.8
Microsoft.EntityFrameworkCore.Tools      Ver 3.1.8

I would really like to continue using EF and CodeFirst data modeling with SQLite but these issues make it VERY hard to work with.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbc4d900-28a8-9c04-2443-7407f15a684f
* Version Independent ID: 545bb0b5-f15b-584e-cef7-7283a0e0729f
* Content: [SQLite Database Provider - Limitations - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations)
* Content Source: [entity-framework/core/providers/sqlite/limitations.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/sqlite/limitations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment]
DropColumn support was added in EF Core 5.0

**Comment by maxmin88** [comment]
Hi Brice,

Thanks for the reply.

I am using
Microsoft.NETCore.UniversalWindowsPlatform      V6.2.10
It was automatically installed when I created my new UWP project.
Note: I am using the 3 project approach needed for UWP: UWP project; Console project and Model project.  (BTW is MS ever going to fix it so Code First/Migrations/SQLite will work properly with a UWP project???)

My real issue is not being able to change Property/Column names.  Why isn’t this working for me.  Am I missing something?

Thanks in advance.

Robert Twickler

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by roji** [comment]
@maxmin88 you may need to look at [these docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#column-renames) on managing column renames in migrations.

**Comment by maxmin88** [comment]
OK. I guess I see that tracking a name change through the Property definition could be a challenge.  I will follow your advice.  Thanks for that.

Though perhaps something like a [RenameFrom XXX] attribute could be used to track and make the a name change automatically.?  Then the attribute could be cleared after a migration….  Just a thought.

Robert Twickler

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AndriySvyryd** [comment]
We can't add new features in patch releases. We'll consider rename column improvements in 6.0
