### ISSUE TITLE
EF Core 5.0 RC1 example is incorrect/incomplete

### ISSUE THREAD

**Issue by kotpal** [dotnet/EntityFramework.Docs#2762]
In the last paragraph of https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew, it is stated that:

> EF Core allows full customization of the join table. For example, the code below configures a many-to-many relationship that also has navigations to the join entity, and in which the join entity contains a payload property

However, the example code doesn't show how this is done. There is no payload property at all in the example provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32360b50-1129-b3d2-2d71-c6b89cd9f2c6
* Version Independent ID: 4f18f8dc-5cd5-cb37-0f59-fb1767609b2b
* Content: [What's New in EF Core 5.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew)
* Content Source: [entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
The example does show how to add a property:
```C#
j.Property(pt => pt.PublicationDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
```

By *payload* it refers to any property that's not part of the primary key.
