### ISSUE TITLE
Unsupported parameters 'Namespace' and 'ContextNamespace' in EF core v3.1.9 are in documentation.

### ISSUE THREAD

**Issue by git-hub-user** [dotnet/EntityFramework.Docs#2772]
With Microsoft.EntityFrameworkCore v3.1.9 I get:

> Scaffold-DbContext : A parameter cannot be found that matches parameter name 'Namespace'.

and

> Scaffold-DbContext : A parameter cannot be found that matches parameter name 'ContextNamespace'.

The documentation describes these parameters and as far as I can see, it applies to this version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1601c3e-3f29-5d84-6350-2b38eeaf6adc
* Version Independent ID: 92a856d6-c5da-e215-46ac-d67c411f3ff9
* Content: [Reverse Engineering - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/scaffolding.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/scaffolding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
> By default, the namespace will be the root namespace plus the names of any subdirectories under the project's root directory. However, from EFCore 5.0 onwards, you can override the namespace for all output classes by using --namespace. You can also override the namespace for just the DbContext class using --context-namespace:

It works from EF Core 5.0 onwards only.
