### ISSUE TITLE
examples and documentation for DbConnectionInterceptor

### ISSUE THREAD

**Issue by 3GDXC** [dotnet/EntityFramework.Docs#2785]
Please provide examples and documentation of how to use DbConnectionInterceptor to redirect a connection to a different underlying implementation of the DbConnection type

**Comment by roji** [comment]
@3GDXC is this about https://github.com/dotnet/efcore/issues/23025, can it be closed? If not, what exactly are you looking for?

**Comment by 3GDXC** [comment]
@roji it relates, but is still needed as I've not see any documentation/examples on how to write interceptor for DbConnection/DbCommand etc.  and example of how to replace the connection and/or command implementation would be good

**Comment by roji** [comment]
Duplicate of #1543

**Comment by roji** [comment]
Docs for interceptors are tracked by #1543 - note #2787 which adds this.
