### ISSUE TITLE
Examples have formatting errors.

### ISSUE THREAD

**Issue by jimt4593** [dotnet/EntityFramework.Docs#2788]
All the examples, on this page, have formatting errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2f6d50-fd4a-4829-d6f3-371f34a36167
* Version Independent ID: d0b13466-1522-6157-2035-c47c123eb3bf
* Content: [EntityFrameworkQueryableExtensions.Include Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.include?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
Fixed by https://github.com/dotnet/EntityFramework.ApiDocs/pull/84

**Comment by ajcvickers** [comment]
See also: https://github.com/dotnet/efcore/issues/19987

**Comment by smitpatel** [comment]
Updated to live site manually. For automation and issue rendering => filed internal issue.
