### ISSUE TITLE
Very helpful

### ISSUE THREAD

**Issue by InteXX** [dotnet/EntityFramework.Docs#2792]
Excellent. This is perfect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a04a5e4-3060-2331-f78d-8b45064b8983
* Version Independent ID: 673d9406-3fa1-a9eb-f5cc-a431155e0260
* Content: [Testing with a mocking framework - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/testing/mocking?redirectedfrom=MSDN)
* Content Source: [entity-framework/ef6/fundamentals/testing/mocking.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/testing/mocking.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks for the kind words!
