### ISSUE TITLE
--connection option does not work for dotnet ef update

### ISSUE THREAD

**Issue by navidmatin** [dotnet/EntityFramework.Docs#2793]
When passing in `--connection` option as mentioned in [dotnet ef database update](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#dotnet-ef-database-update) section, I'm getting 
```
Unrecognized option '--connection'
```

Here is what I'm running:
```
dotnet ef update -p <ProjectWithDbContext> -s <StartingProject> --connection <connectionString>
```

I'm using [Postgresql ](https://www.npgsql.org/efcore/index.html) as the underlying database so I'm not sure if that is something that would affect this CLI command or not. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment]
Can you confirm that you’re using version 5.0 of both the NuGet packages *and* `dotnet ef`?

**Comment by navidmatin** [comment]
I'm not, I'm using `3.1.9`. I'll check against version `5.0.0-rc.2.20475.6`

**Comment by navidmatin** [comment]
Upgrading the EF core tool to v5 fixed this issue. Thanks.
