### ISSUE TITLE
RC2 update?

### ISSUE THREAD

**Issue by rupe120** [dotnet/EntityFramework.Docs#2794]
Please update with changes that are found in RC2. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32360b50-1129-b3d2-2d71-c6b89cd9f2c6
* Version Independent ID: 4f18f8dc-5cd5-cb37-0f59-fb1767609b2b
* Content: [What's New in EF Core 5.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew)
* Content Source: [entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@rupe120 There are no new features in RC2. You can query GitHub to see individual issues fixed: https://github.com/dotnet/efcore/issues?q=is%3Aissue+milestone%3A5.0.0-rc2+is%3Aclosed

I also updated the release: https://github.com/dotnet/efcore/releases/tag/v5.0.0-rc.2.20475.6
