### ISSUE TITLE
DbSet not updated

### ISSUE THREAD

**Issue by InteXX** [dotnet/EntityFramework.Docs#2795]
Unfortunately, this example doesn't fully work as-is.

Often we need to add an entity to an underlying store (likely a `List(Of T)` during testing), and then verify that it was added correctly. The example doesn't show how to do so. `BlogService.AddBlog()` returns `Nothing` and no `Blog` is added to `Context.Blogs`.

This can be accomplished by mocking the `DbSet.Add()` method:

```c#
[Fact]
public void CreateBlog_saves_a_blog_via_context()
{
  var data = new List<Blog>
  {
    new Blog { Name = "BBB" },
    new Blog { Name = "ZZZ" },
    new Blog { Name = "AAA" },
  };
  
  var mockSet = new Mock<DbSet<Blog>>();
  mockSet.Setup(blogs => blogs.Add(It.IsAny<Blog>)).Returns<Blog>(blog =>
  {
    data.Add(blog);
    return blog;
  });
  
  var mockContext = new Mock<BloggingContext>();
  mockContext.Setup(m => m.Blogs).Returns(mockSet.Object);
  
  var service = new BlogService(mockContext.Object);
  var blog = service.AddBlog("_ADO.NET Blog", "http://blogs.msdn.com/adonet");
  var blogs = service.GetAllBlogs();
  
  mockSet.Verify(m => m.Add(It.IsAny<Blog>()), Times.Once());
  mockContext.Verify(m => m.SaveChanges(), Times.Once());
  
  Assert.NotNull(blog)
  Assert.Equal(4, blogs.Count);
  Assert.Equal("AAA", blogs(1).Name);
  Assert.Equal("BBB", blogs(2).Name);
  Assert.Equal("ZZZ", blogs(3).Name);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a04a5e4-3060-2331-f78d-8b45064b8983
* Version Independent ID: 673d9406-3fa1-a9eb-f5cc-a431155e0260
* Content: [Testing with a mocking framework - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/testing/mocking?redirectedfrom=MSDN)
* Content Source: [entity-framework/ef6/fundamentals/testing/mocking.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/testing/mocking.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
