### ISSUE TITLE
Breaking change lists net standard 2.1, but 2.0 in implementation table

### ISSUE THREAD

**Issue by RobMalvern** [dotnet/EntityFramework.Docs#2811]
The breaking changes for release 3.x lists moving to net standard 2.1 as a breaking change. But the implementations page for EF Core (https://docs.microsoft.com/en-us/ef/core/platforms/) states that 3.1 is compatible with net standard 2.0. Which is correct? Can I use EF Core 3.1 in a net standard 2.0 library?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6de92d83-815b-f81c-4039-ae107571a576
* Version Independent ID: 2479a75e-571b-40ba-fdd6-de3b88970553
* Content: [Breaking changes in EF Core 3.x - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.x/breaking-changes.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.x/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@RobMalvern EF Core 3.0 indeed targeted netstandard2.1, but EF Core 3.1 was changed to target netstandard2.0 again, so you can use EF Core 3.1 from a netstandard2.0 library. This is explained in the full [breaking change](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#netstandard21).

We should consider removing or striking-through this breaking change.

**Comment by RobMalvern** [comment]
Thanks for the super quick reply @roji!!
