### ISSUE TITLE
Code examples has wrong enconding

### ISSUE THREAD

**Issue by Roog** [dotnet/EntityFramework.Docs#2814]
Hi!
There is some wrong encoding on the code examples, `=&gt;` instead of `=>`

Would make a nicer documentation with the correct encoding.

Best regards
Roger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2f6d50-fd4a-4829-d6f3-371f34a36167
* Version Independent ID: d0b13466-1522-6157-2035-c47c123eb3bf
* Content: [EntityFrameworkQueryableExtensions.Include Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.include?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
https://github.com/dotnet/EntityFramework.Docs/issues/2788

**Comment by ajcvickers** [comment]
Closing as external, as indicated in #2788
