### ISSUE TITLE
Does this work with oracle?

### ISSUE THREAD

**Issue by Martin-Andersen** [dotnet/EntityFramework.Docs#2815]
[Enter feedback here]
                
I have tried using "select samson.REPORT_ID_SEQUENCE.nextval from dual" insted of the sql syntax.
But the next value are not selected 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf3bd16-1954-0974-500a-8f04d0a5ed5f
* Version Independent ID: 2818db16-6495-65ca-fe64-7792d6a2d1b5
* Content: [Sequences - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/sequences)
* Content Source: [entity-framework/core/modeling/sequences.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/sequences.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@Martin-Andersen that sounds like a question that's better addressed to the Oracle provider project - can you please post it there?
