### ISSUE TITLE
Database creation?

### ISSUE THREAD

**Issue by plettb** [dotnet/EntityFramework.Docs#2830]
This page (and the async equivalent) clearly says "Will create the database if it does not already exist."  I need to know how the database gets created, and how I can step into that process.  Specifically, I need some control over how the database is created in Azure.  My database is being created, but in the wrong pricing tier and in the wrong pool.  How do I control that?

I have code (that works) to create the database "manually from code", but that is not being used in the migration pipeline.  How do I introduce that kind of thing?

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e7d6b84-a096-c0d3-e42c-f0036669d03c
* Version Independent ID: b14b4e27-a3cc-e7b4-8d6e-a5f8ab4588bb
* Content: [RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.migrate?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
You can see how to specify Azure specific options at https://docs.microsoft.com/en-us/ef/core/providers/sql-server/azure-sql-database

You can see how to output the schema creation script at https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli

You can see how to add custom migration operations at https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations

**Comment by plettb** [comment]
> You can see how to specify Azure specific options at https://docs.microsoft.com/en-us/ef/core/providers/sql-server/azure-sql-database

This _appears_ to be exactly what I need, but sadly it doesn't seem to work for me.  Here's my code:
```
protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);
    builder.HasPerformanceLevel($"ELASTIC_POOL ( name = {_azureSettings.ElasticPoolName} )");
...

```
Any ideas?

**Comment by AndriySvyryd** [comment]
@plettb Looks correct. Try generating a script from the migration to see whether something is incorrect.
