### ISSUE TITLE
The IConventionRelationshipBuilder interface has been changed to IConventionForeignKeyBuilder 

### ISSUE THREAD

**Issue by hakenr** [dotnet/EntityFramework.Docs#2831]
Related commit:

https://github.com/dotnet/efcore/commit/858dfe7eb1b37c2e680282d34d64dac92fcd8365#diff-a86939e7ed3eba023473c9fce45284d08736a82b415dc6304b6fde4be1d25602

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf4e07c-25f8-ad59-fde6-3629e2c4e8d7
* Version Independent ID: df8c8aea-9f7d-db72-18b3-bac134acfd9a
* Content: [Breaking changes in EF Core 5.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes)
* Content Source: [entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
@hakenr There's currently no supported way of using this in user code. And we don't track provider/plug-in breaking changes on this page.
