### ISSUE TITLE
DeleteBehavior.NoAction and DeleteBehavior.Restrict identical descriptions

### ISSUE THREAD

**Issue by pwarner** [dotnet/EntityFramework.Docs#2836]
In the documentation for DeleteBehavior enum, NoAction and Restrict show identical descriptions but in this [post ](https://stackoverflow.com/questions/64259612/what-is-different-between-deletebehavior-noaction-and-deletebehavior-restrict-in) the behaviour described for each is different. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2df9f508-7992-183c-a909-5b27316e3efd
* Version Independent ID: 8e25c165-0abc-9990-ef58-f0ac29c130e3
* Content: [DeleteBehavior Enum (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@pwarner This documentation needs updating--tracked by #473 and related issues. The API docs are correct, there is effectively no difference between the behavior of these two choices, other than what is used by Migrations when creating the database. Some databases may then behave slightly differently in when the constraint checking happens, but this is rarely important at the application level.
