### ISSUE TITLE
Looking for inmemory database code example

### ISSUE THREAD

**Issue by darren-j-mcleod** [dotnet/EntityFramework.Docs#2838]
Was looking for an imemory database code example and this page only has links to other pages that don't have an inmemory database code example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5589fb47-8773-6ed5-e152-136bfee49da3
* Version Independent ID: c9f5b694-d1a0-479e-43f2-5dc1fe74590b
* Content: [EF Core testing sample - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/testing-sample)
* Content Source: [entity-framework/core/miscellaneous/testing/testing-sample.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/testing-sample.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@darren-j-mcleod The sample linked from that document uses the in-memory database, and the docs page talks about this.
