### ISSUE TITLE
Links to the EF Core GitHub repository use the URL of the former location

### ISSUE THREAD

**Issue by dennisseders** [dotnet/EntityFramework.Docs#2844]
Usage of links to go the EF Core repository of the project are used extensively in the EntityFramework.Docs repository. Current hyperlink occurrences use the URL which refer to the former location of the repository which was: [https://github.com/aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) When the user goes to the page the GitHub server responds with status code `301 Moved Permanently` and URL [https://github.com/dotnet/efcore.](https://github.com/dotnet/efcore.) as value of the `Location` response header which ensures that the user is redirected to the given location.

As the redirect ensures that the user lands on the repository this actually can be classified a a non-issue but I believe that at least the official documentation should use the actual location as URL in links. Also: it just prevents unnecessary redirects.

If this proposed change only involves replacing occurrences of the actual value with the expected value I am willing to create a pull request for this.

**Comment by ajcvickers** [comment]
@dennisseders A PR for this would be great.

**Comment by dennisseders** [comment]
@ajcvickers I created the following PR: https://github.com/dotnet/EntityFramework.Docs/pull/2845. Could you link the PR to this issue?

**Comment by dennisseders** [comment]
> 
> 
> @ajcvickers I created the following PR: #2845. Could you link the PR to this issue?

@ajcvickers nevermind. I linked this issue to the pull request myself.
