### ISSUE TITLE
Update page to reflect that EF Core 5.0 is stable

### ISSUE THREAD

**Issue by dennisseders** [dotnet/EntityFramework.Docs#2861]
The table [Stable releases](https://docs.microsoft.com/en-us/ef/core/what-is-new/#stable-releases) should be extended with a row containing information about EF Core 5.0. I believe the EF Core team should decide what to do with the headings [EF Core 5.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/#ef-core-50), [Get it now](https://docs.microsoft.com/en-us/ef/core/what-is-new/#get-it-now) and the accompanying content as it seems that they become out-of-date since [today](https://devblogs.microsoft.com/dotnet/announcing-the-release-of-ef-core-5-0/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05ec70a8-5402-78da-2a4d-c3d2c1e59f97
* Version Independent ID: da449417-8152-ce2d-4aec-fbd9b692e432
* Content: [EF Core releases and planning](https://docs.microsoft.com/en-us/ef/core/what-is-new/)
* Content Source: [entity-framework/core/what-is-new/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@dennisseders See https://github.com/dotnet/EntityFramework.Docs/pull/2857

We just haven't pushed this to the live site yet.
