### ISSUE TITLE
Missing 'await' for async call in 'Handling Deletes' example

### ISSUE THREAD

**Issue by dsurrao** [dotnet/EntityFramework.Docs#2867]
[Enter feedback here]
var existingPost = **await** existingBlog.Posts
                .AsQueryable()
                .FirstOrDefaultAsync(p => p.PostId == post.PostId);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9826f28-46b2-e845-f1bf-5cbc2d940208
* Version Independent ID: 9c4a46cf-daa2-0e14-7ff1-c195db237cd0
* Content: [Disconnected Entities - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities)
* Content Source: [entity-framework/core/saving/disconnected-entities.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/disconnected-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Note for triage: it looks like this code is just wrong. (I can't imagine why I would have written `.AsQueryable().FirstOrDefaultAsync` on a nav property, but there it is.)

**Comment by ajcvickers** [comment]
Looks like this was a consequence of making the samples async, but then this was fixed when #2698 was reverted.

/cc @roji
