### ISSUE TITLE
The doc doesn't provide sufficient information on how to consume existing stored procedures and map the results to a model

### ISSUE THREAD

**Issue by anilvalavala** [dotnet/EntityFramework.Docs#2868]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2c8d490-ce49-c4e6-8acb-13794d3f4c42
* Version Independent ID: 70120e6f-10b5-8154-f998-bf047e4b96a0
* Content: [Code First Insert, Update, and Delete Stored Procedures - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/fluent/cud-stored-procedures?redirectedfrom=MSDN)
* Content Source: [entity-framework/ef6/modeling/code-first/fluent/cud-stored-procedures.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/fluent/cud-stored-procedures.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
