### ISSUE TITLE
Extension methods section layout needs to be fixed

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/EntityFramework.Docs#2871]
The method names are hard to read because the left column is too small.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c8fa9e8-a072-ff78-8f3e-80a6a426e5b9
* Version Independent ID: 2d04ad4f-1820-5a0a-f6b7-4c3b87771f94
* Content: [DatabaseFacade Class (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade?view=efcore-5.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/DatabaseFacade.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/DatabaseFacade.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@smitpatel to follow up with docs team.

**Comment by ajcvickers** [comment]
Could be due to `code` sections in the descriptions.

**Comment by smitpatel** [comment]
Fixing in https://github.com/dotnet/EntityFramework.ApiDocs/pull/90
