### ISSUE TITLE
ThenInclude required?

### ISSUE THREAD

**Issue by ygoe** [dotnet/EntityFramework.Docs#2873]
Is the use of `ThenInclude` required? I can also just call `.Include(e => e.Related1.SubRelated2)` to do it all in one step. What's the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a3ce6e-43ab-e0af-01b3-a82fdaf3cb31
* Version Independent ID: 320e7305-e0a3-a1c6-77f2-1d3029b660b1
* Content: [Eager Loading of Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager)
* Content Source: [entity-framework/core/querying/related-data/eager.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data/eager.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Note for triage: we should show examples of dotting through for reference Includes.

@ygoe In general, ThenInclude is needed for collections. However, it helps consistency to show the same pattern for both references and collections.
