### ISSUE TITLE
Add HasData seeding example for many-to-many relationship

### ISSUE THREAD

**Issue by maumar** [dotnet/EntityFramework.Docs#2879]
When using many-to-many with generated join entity, the exception we throw is not great, e.g.:

```
The seed entity for entity type 'Tag' cannot be added because it has the navigation 'Posts' set. To seed relationships,  add the entity seed to 
'PostTag (Dictionary<string, object>)' and specify the foreign key values {'TagsTagId'}.
```

all these are generated by EF so it might be nice to show people how to do this (or maybe throw better exception for m2m with generated join entity?)

**Comment by maumar** [comment]
```cs
            modelBuilder.Entity<Post>()
                .HasMany(p => p.Tags)
                .WithMany(t => t.Posts)
                .UsingEntity<Dictionary<string, object>>(
                    "PostTag",
                    r => r.HasOne<Tag>().WithMany().HasForeignKey("TagId"),
                    l => l.HasOne<Post>().WithMany().HasForeignKey("PostId"),
                    je =>
                    {
                        je.HasKey("PostId", "TagId");
                        je.HasData(
                            new { PostId = 1, TagId = "general" },
                            new { PostId = 1, TagId = "informative" },
                            new { PostId = 2, TagId = "classic" },
                            new { PostId = 3, TagId = "opinion" },
                            new { PostId = 4, TagId = "opinion" },
                            new { PostId = 4, TagId = "informative" });
                    });
```

**Comment by TAGC** [comment]
Is it possible to specify the seed data for a generated join entity separately without needing to define a CLR type for it?

I seed all my data separately from where I define my entity configurations. I've got an entity configuration class like this, defining a many-to-many relationship between `ProductConsistencyRule` and `ProductMinMixRange` via a generated join table called `ProductMinMixRangeAssociation`:

```cs
public class ProductConsistencyRuleConfiguration : DomainEntityConfiguration<ProductConsistencyRule>
{
    public const string ProductMinMixRangeJoinTable = "ProductMinMixRangeAssociation";

    protected override void ConfigureCore(EntityTypeBuilder<ProductConsistencyRule> builder)
    {
        builder.ToTable(nameof(ProductConsistencyRule));

        builder.Ignore(x => x.ProductMinMixRanges);
        builder.Property(x => x.CommissionBonus).HasColumnType("decimal(18,2)");

        builder
            .HasMany(pcr => pcr.ProductMinMixRanges)
            .WithMany("ProductConsistencyRules") // Workaround until https://github.com/dotnet/efcore/issues/3864 resolved
            .UsingEntity(j => j.ToTable(ProductMinMixRangeJoinTable));
    }
}
```

Then elsewhere I try to seed this join table using its name:

```
modelBuilder.Entity(ProductConsistencyRuleConfiguration.ProductMinMixRangeJoinTable)
    .HasData(productMinMixRangeAssociations);
```

Then the first time my DbContext is instantiated, I get this exception:

> System.InvalidOperationException: 'The entity type 'ProductMinMixRangeAssociation' is in shadow state. A valid model requires all entity types to have corresponding CLR type.'

**Comment by Redplcs** [comment]
I would like to mention that if you're declaring poco class instead of mapping dictionary to many-to-many relationship entity, you're class must have ids instead of reference.

I was trying to map them to objects for like 4 hours, but ef core keeps blame me for not assigning value to PostId when I had already assigned value to Post object.

I hope I knew this earlier
