### ISSUE TITLE
linq lambda expression

### ISSUE THREAD

**Issue by yulObraz** [dotnet/EntityFramework.Docs#2884]
I'm sure this page must have linq lambda variant too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1acf84-126c-f01d-b39a-ab077819351f
* Version Independent ID: 5d3bdd6d-ad0e-e306-5aef-0d5adea892b6
* Content: [Complex Query Operators - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators)
* Content Source: [entity-framework/core/querying/complex-query-operators.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/complex-query-operators.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@yulObraz We discussed this again, but we don't believe the method-call syntax are very understandable for these types of queries. For example, the first two would look like this:

```C#
var query = context.Set<PersonPhoto>()
    .Join(
        context.Set<Person>(),
        photo => photo.PersonPhotoId,
        person => person.PhotoId,
        (photo, person) => new { person, photo });

var query = context.Set<PersonPhoto>()
    .Join(
        context.Set<Person>(),
        photo => new
        {
            Id = (int?)photo.PersonPhotoId,
            Caption = photo.Caption
        },
        person => new
        {
            Id = person.PhotoId,
            Caption = "SN"
        },
        (photo, person) => new { person, photo });
```

Since this page is about explaining concepts, we believe this is communicated better with the current syntax. A good IDE will be able to automatically refactor between the two syntax forms, if you need that.

**Comment by yulObraz** [comment]
I prefer lambda syntax. (Really I hate basic in serious development.)
I had experience with EF 6 before. But I have big difficulties in EF Core joins because it was unexpected that I must use result parameter. So I received different issues with not working includes and so on. Query without result parameter sometimes goes without problems. But sometimes with failures. So the syntax must be mentioned somewhere.
