### ISSUE TITLE
What is this ?

### ISSUE THREAD

**Issue by dogutumerdem** [dotnet/EntityFramework.Docs#2888]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d59bd36b-c8e0-afa4-64da-dc9e93d1e6b8
* Version Independent ID: 46ed436e-b883-3323-f118-67b86727b254
* Content: [RelationalStrings.SetOperationsNotAllowedAfterClientEvaluation Property (Microsoft.EntityFrameworkCore.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.relationalstrings.setoperationsnotallowedafterclientevaluation?view=efcore-5.0#Microsoft_EntityFrameworkCore_Diagnostics_RelationalStrings_SetOperationsNotAllowedAfterClientEvaluation)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Diagnostics/RelationalStrings.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Diagnostics/RelationalStrings.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@dogutumerdem It provides access to one of the resource strings EF Core uses for the message when generating an exception. It would be very unusual for an application to need to access this directly.
