### ISSUE TITLE
Document `ToView(null)` breaking change in 5.0

### ISSUE THREAD

**Issue by lcrumbling** [dotnet/EntityFramework.Docs#2890]
We've just converted our EF Core projects from 3.1 to 5.0. After creating our first migration since the conversion, we're seeing the migration contain statements to drop tables for for entities that were previously configured with `.ToView(null)`. This is happening for both of the providers that we are using, SqlServer and PostgreSQL.

```
void IEntityTypeConfiguration<GroupHierarchyItem>.Configure(EntityTypeBuilder<GroupHierarchyItem> builder)
{
     builder.HasNoKey().ToView(null);
}
```

This generates both the SQL Server migration and the Postgres migration with:
```
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.DropTable(
        name: "GroupHierarchyItem");
}
```

EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer, Shared.DataContext.DatabaseTypes.PostgreSQL
Target framework: .NET 5.0
Operating system: Windows 10 19041.630
IDE:  Visual Studio 2019 Professional 16.8.1

**Comment by lcrumbling** [comment]
@ajcvickers BTW, you may want to update the docs as well. [This page](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types?tabs=data-annotations#mapping-to-database-objects) goes out of its way to say:

> Note
> 
> ToView assumes that the object already exists in the database and it won't be created by migrations.
> 

Going to try `.ToTable(null, t => t.ExcludeFromMigrations());` now, and make sure it behaves in the same manner as .ToView(null) did.

**Comment by CaringDev** [comment]
@lcrumbling `.ToTable` does not work with neither `null` nor `""`. We use `ToView("SomeName")` now 🤷‍♂️

**Comment by lcrumbling** [comment]
> @lcrumbling `.ToTable` does not work with neither `null` nor `""`. We use `ToView("SomeName")` now 🤷‍♂️

Yes, I ended up doing 
`builder.HasNoKey().ToTable("viewname", t => t.ExcludeFromMigrations());`
And that seems to be working as expected.
