### ISSUE TITLE
Add clarity to Entity Framework Core tools reference

### ISSUE THREAD

**Issue by dan-giddins** [dotnet/EntityFramework.Docs#2901]
[Enter feedback here]

The following text could be added to clearly show that there are two different tools, and either can be used:

> ...reverse engineering the schema of a database.

"Either of the following tools can be used:"

> The EF Core Package Manager Console tools run...
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a29ee0-8047-292a-f758-f46f2edce8df
* Version Independent ID: 8e17fd37-46a1-1d4d-865f-e3a202832d84
* Content: [Entity Framework Core tools reference - EF Core](https://docs.microsoft.com/en-us/ef/core/cli/)
* Content Source: [entity-framework/core/cli/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/cli/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@dan-giddins Doesn't "Both tools expose the same functionality" cover this?

**Comment by dan-giddins** [comment]
@ajcvickers Yes, but only after you have read the whole page. The only reason I raise this is that there was confusion from a colleague when we were going through the docs trying to set up the tools. He was working through the docs linearly, and as a result, after reading the first paragraph and clicking through to both, he thought that they were both required!

**Comment by ajcvickers** [comment]
@dan-giddins It's a short page (2 mins to read) but if you think it would make a difference, then please feel free to submit a PR ro make the change.
