### ISSUE TITLE
Document the increased memory requirements associated with connection resiliency

### ISSUE THREAD

**Issue by dstj** [dotnet/EntityFramework.Docs#2902]
I've just hunted down a tenfold memory increase after moving to EF Core 3.1.10 (from 2.2.6) and the cause was that the query was no longer automatically split into 5 simpler queries by EF Core, _i.e._ the [single query / no automatic splitting](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#eager-loading-of-related-entities-now-happens-in-a-single-query) feature of EF Core 3. 

EF Core 2 - ~120 MB used
![big asset import - efcore2](https://user-images.githubusercontent.com/467692/100120828-6579c680-2e46-11eb-997e-6167128c3d47.png)

EF Core 3 - ~1.3 GB used
![big asset import - efcore3](https://user-images.githubusercontent.com/467692/100120977-9659fb80-2e46-11eb-8abf-11a3b5796a4c.png)

This has a **huge** impact.

FYI, the EF Core 2 query looked like:

```sql
var company = await _dbContext.Companies
				.Include(c => c.Sites)
				.Include(c => c.Categories)
				.Include(c => c.Assets).ThenInclude(a => a.Site)
				.Include(c => c.Assets).ThenInclude(a => a.Tasks)
				.AsTracking()
				.SingleOrDefaultAsync(c => c.Id == companyId);
```

_Note_: I'll try to create a small project to reproduce the issue a bit later.

--
_Originally posted by @dstj in https://github.com/dotnet/efcore/issues/18022#issuecomment-733086888_

**Comment by roji** [comment]
Yep, we warn on potentially bad cartesian explosion in 5.0, and give you the option to throw as well.

I've transferred this to our docs repo to add proper documentation that resiliency causes buffering.
