### ISSUE TITLE
Make "What's New" for the current release more visible

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#2903]
Keeping what's new up-to-date through the previews was a nice change we made for 5.0, and the result was a lot of useful info for people coming to EF Core 5.0 after the release. However, the current location is not very discoverable, since it requires expanding three levels of nesting. I propose that following a release we:

* Clean up the document to refer to the entire release, rather than being preview-focused. (Shay is already doing this for 5.0.)
* Add a new, very discoverable link. My suggestion is:

![image](https://user-images.githubusercontent.com/1430078/100289897-d5fc1280-2f2e-11eb-90f8-a31f71138ea6.png)

The link text would be. "What's new in EF Core 5.0". Once we ship 6.0, it would be updated to point to the page for 6.0. All the what's new pages will still be kept under each release for posterity. Also, we'll still have a what's new for the release we are currently working on.

**Comment by roji** [comment]
@ajcvickers I'll just do this as part of #2904
