### ISSUE TITLE
To use EntityTypeBuilder or not to use?

### ISSUE THREAD

**Issue by gukoff** [dotnet/EntityFramework.Docs#2905]
[One doc](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder?view=efcore-5.0) advises against using EntityTypeBuilder unless "with extreme caution and knowing that doing so can result in application failures".

[This doc](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1?view=efcore-5.0) advises to use it.

Which one is right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec42a21d-cd10-1ef9-3507-e020ec18a28e
* Version Independent ID: b56d229a-a8b1-11f2-e3b1-03ad082af00e
* Content: [EntityTypeBuilder Class (Microsoft.EntityFrameworkCore.Metadata.Builders)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@gukoff the comment about the API being internal (and therefore dangerous to rely on) is on the constructor of EntityTypeBuilder; the type itself is fully public and can be used without issues.

**Comment by gukoff** [comment]
Ah, gotcha. The specific constructor isn't recommended for use. Thanks!
