### ISSUE TITLE
Documentation on cascading effects is confusing - if not conflicting

### ISSUE THREAD

**Issue by iinatti** [dotnet/EntityFramework.Docs#2906]
In chapter [Required relationships](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete#required-relationships) on page Cascade Delete, there is a note saying:
"In EF Core, unlike EF6, cascading effects do not happen immediately, but instead only when SaveChanges is called."

Is this in conflict with documentation of the breaking change of EF Core 3.1: [Cascade deletions now happen immediately by default
](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#cascade-deletions-now-happen-immediately-by-default)

If there is no conflict, the wording could be changed somehow, as it is now a bit confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Cascade Delete - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@iinatti Thanks; the docs need updating since this changed in 3.0.
