### ISSUE TITLE
Public view not updating from repo

### ISSUE THREAD

**Issue by msawczyn** [dotnet/EntityFramework.Docs#2918]
Hey all,

[This page](https://docs.microsoft.com/en-us/ef/core/extensions/) hasn't refreshed publicly since April, 2020. I know there have been changes - the repo shows this page was last updated a few hours ago - but nothing visible. Wasn't sure if you were aware of it, or if it were a larger problem on this or other pages in EntityFramework.Docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8875eb79-99ff-662b-c189-86eb8cdb5488
* Version Independent ID: fa03a7fa-1922-7aa1-acda-b0d216ef37cb
* Content: [Tools & Extensions - EF Core](https://docs.microsoft.com/en-us/ef/core/extensions/)
* Content Source: [entity-framework/core/extensions/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/extensions/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ErikEJ
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
That is just inaccurate date written in the page. The page itself has been updated in live on Nov 18.
All the changes made through PR in the repo are pushed to master branch. The public view builds from live branch. Master is merged into live branch every other week (or based on demand if there is high priority content which needs to be released to public). It will update with latest master when we push it to live in upcoming days.

Closing the issue as there is nothing actionable here which is not planned.

**Comment by msawczyn** [comment]
@smitpatel - Request that this issue be reopened. I'll be more detailed here but, for reference, please read through the page at https://docs.microsoft.com/en-us/ef/core/extensions/

As an example, I'll use a piece that I had edited and was merged with [PR 2917](https://github.com/dotnet/EntityFramework.Docs/pull/2917). When looking at the page from the public view (https://docs.microsoft.com/en-us/ef/core/extensions/), after clearing my browser cache, I see

> **Entity Framework Visual Editor**
> Entity Framework Visual Editor is a Visual Studio extension that adds an O/RM designer for visual design of EF 6, and EF Core classes. Code is generated using T4 templates so can be customized to suit any needs. It supports inheritance, unidirectional and bidirectional associations, enumerations, and the ability to color-code your classes and add text blocks to explain potentially arcane parts of your design. For EF Core: 2.

When I look at it in the repo (https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/extensions/index.md), I see 

> **Entity Framework Visual Editor**
> Entity Framework Visual Editor is a Visual Studio extension that adds an O/RM designer for visual design of EF 6, and EF Core classes. Code is generated using T4 templates so can be customized to suit any needs. It supports inheritance, unidirectional and bidirectional associations, enumerations, and the ability to color-code your classes and add text blocks to explain potentially arcane parts of your design. For EF Core: 2, 3, 5.

Note that the last sentence is different (and, indeed, quite important to the reader). I also noted that [the last PR](https://github.com/dotnet/EntityFramework.Docs/pull/2917), add quite recently, wasn't on the public site either.

Either I'm not understanding how the workflow for the documentation project is set up or something is not working properly. In the end, though, it appears that the contents in the repo is not being propagated to the site where the public is reading the docs.

Thanks.
