### ISSUE TITLE
Built for version updates

### ISSUE THREAD

**Issue by mguinness** [dotnet/EntityFramework.Docs#2919]
Since [EF Core 5.0](https://devblogs.microsoft.com/dotnet/announcing-the-release-of-ef-core-5-0/) is released, it would be good to update providers that support it (see below).  BTW links for Db2, Informix are dead.

Microsoft.EntityFrameworkCore.SqlServer
Microsoft.EntityFrameworkCore.Sqlite
Microsoft.EntityFrameworkCore.InMemory
Microsoft.EntityFrameworkCore.Cosmos
Npgsql.EntityFrameworkCore.PostgreSQL
Pomelo.EntityFrameworkCore.MySql (prerelease)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9338b2a-93b1-595a-2e8e-86119e6eecbd
* Version Independent ID: 9890ab79-bc72-6075-4294-5450e6693668
* Content: [Database Providers - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by mguinness** [comment]
Will anyone be updating for providers that support version 6.0, i.e. Pomelo?

**Comment by roji** [comment]
@mguinness submitted #3553
