### ISSUE TITLE
Page seems to imply that EF Core 5 has not been released

### ISSUE THREAD

**Issue by kinetiq** [dotnet/EntityFramework.Docs#2929]
Confusing - this whole section (High Level Plan and What's New) seems to imply that EF Core 5 has not been released yet, but it was released on Nov 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32360b50-1129-b3d2-2d71-c6b89cd9f2c6
* Version Independent ID: 4f18f8dc-5cd5-cb37-0f59-fb1767609b2b
* Content: [What's New in EF Core 5.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew)
* Content Source: [entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by kinetiq** [comment]
...Or maybe the problem is that this is a roadmap page, but I'm trying to figure out how to upgrade to EF Core 5. It wasn't clear that this is part of a roadmap.

**Comment by roji** [comment]
#2904 should help here, we should also decide at some point what to do with the high-level plan page.

/cc @ajcvickers
