### ISSUE TITLE
Create a page that covers domain-driven design with EF Core

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/EntityFramework.Docs#2932]
Create a page that covers domain-driven design with EF Core that explains what features EF Core have that can be used to implement DDD and how they can be used to accomplish that.

So it lists each feature and links to the page of each feature.
- Backing fields
- Value conversions
- Value comparers
- Entity types with constructors
- Owned entity types

Link to the ASP.NET Core documentation on [how to implement a custom model binder](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-5.0#implementing-a-modelbinderprovider) using `ModelBinderProvider` to model strongly-typed properties on your model which you use together with EF Core value converters.

Give an example on how to use a [`TypeConverter`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter) to JSON serialize/deserialize strongly-typed properties used together with EF Core value converters.

**Comment by ajcvickers** [comment]
@vanillajonathan There is a lot of external documentation suggesting how to do DDD with EF Core. However, there is a lot of variation in how these people interpret DDD and therefore the patterns that are implemented. I don't think there is one "right way" to do DDD, and hence this is not something we plan to provide first-party guidance on.

**Comment by vanillajonathan** [comment]
I had more in mind a page which simple focused on the functionality offered by EF and how to use them to implement things without advocating any particular pattern or way.

The page could even explicitly state that:
- It will not explain DDD and assumes that the reader has prior knowledge about the topic.
- It does not recommend or advocate any particular pattern or strategy.

The page would be provide information on:
- What functionality that EF Core offers (which is applicable to DDD)
- How to implement said functionality

**Comment by ajcvickers** [comment]
@vanillajonathan

> how to use them to implement things without advocating any particular pattern or way

This is the problem. Take for example, a value object. I would implement it like this:

```C#
public class Point
{
    public Point(int x, int y)
    {
        X = x;
        Y = y;
    }

    public int X { get; }
    public int Y { get; }
}
```

The top search result instead points to this: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects#value-object-implementation-in-c Notice how much code there is there? This shows how the implementation of the concepts makes a huge different to how they might be mapped in EF Core.

**Comment by vanillajonathan** [comment]
@ajcvickers Then the example code snippet in the article would contain just the code in your post above without the implementation of any equality operators, interfaces or base classes. Just a note stating that in a real world value object you would probably want to implement means to determine object equality, but how to do so is out of scope for the article.

**Comment by ajcvickers** [comment]
@vanillajonathan I think at that point we come very close to advocating patterns for DDD. But I'll re-open and discuss again with the team.

**Comment by ajcvickers** [comment]
@vanillajonathan We discussed again, but agreed that this is not a path we want to take the EF Core official docs.
