### ISSUE TITLE
Validate that all samples run

### ISSUE THREAD

**Issue by virzak** [dotnet/EntityFramework.Docs#2935]
There are multiple runtime exceptions I'm experiencing.

An example is the Saving example [here](https://github.com/dotnet/EntityFramework.Docs/blob/2667d7425ab1043f5599c182c75b9112389b46c3/samples/core/Saving/Basics/Sample.cs#L62):

`Queries performing 'Last' operation must have a deterministic sort order. Rewrite the query to apply an 'OrderBy' clause on the sequence before calling 'Last'.'`

I noticed that the the github actions [yml](https://github.com/dotnet/EntityFramework.Docs/blob/2667d7425ab1043f5599c182c75b9112389b46c3/.github/workflows/build-samples.yml#L35) doesn't run the samples, so which makes it difficult to determine if the problem is in my environment or not.

Are there plans to add `dotnet run` to CI/CD and if not would you take a PR for that?

**Comment by ajcvickers** [comment]
@virzak We have discussed this in the past, but currently we don't have any plans to do it. We want to keep the samples relatively simply, and adding validation can obscure what the samples are trying to show.

That being said, we should check all the samples are still working. We will take a look at the one you mention.

**Comment by ajcvickers** [comment]
Note for triage: verified that the sample is broken.

**Comment by ajcvickers** [comment]
We should do this now, and again before each release.

**Comment by MostHated** [comment]
That would be great. I kept trying to follow along with an example from https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli. I spent an hour trying to figure out what in the world I was doing wrong, thought Rider was goofed up, etc. I finally download the same repo and try it... it doesn't work.
