### ISSUE TITLE
wrong example for aplying a BlogEntityTypeConfiguration

### ISSUE THREAD

**Issue by nunofilipecosta** [dotnet/EntityFramework.Docs#2941]
The example for applying a `IEntityTypeConfiguration<Blog>` should be 

`modelBuilder.ApplyConfiguration(new BlogEntityTypeConfiguration());` 

right ??

Using net5.0
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3437af67-630b-d28f-7fbd-3eedf647f22a
* Version Independent ID: 6c44f987-19a7-c256-e8fa-10378e61cf6e
* Content: [Creating and configuring a model - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/)
* Content Source: [entity-framework/core/modeling/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@nunofilipecosta Either way is fine.

**Comment by nunofilipecosta** [comment]
Understood , thank for your patience! 🤦
