### ISSUE TITLE
Finding how to return an int from EF6 stored proc

### ISSUE THREAD

**Issue by gewarren** [dotnet/EntityFramework.Docs#2951]
---
**Issue moved from MicrosoftDocs/feedback#3316**
- Please respond to @LJ9999.

---

_From @LJ9999 on Wednesday, December 9, 2020 7:18:24 AM_

This is amazing!!!! I spent the better part of an evening trying to figure out how to return an integer from a stored proc using EF 6.

And I couldn't find jackschitt!!!! I found a million assholes with their hairbrained ideas for how to do it. They threw their half-assed untested crap guesses at the wall but none of it works!!!

This is amazing. Something so simple but there are one million answers. AND THEY"RE ALL EFFING WRONG!

Of course Microsoft docs are worthless. You people couldn't teach addition to a Math Major.

This is typical Microsoft bullshit. After 30 years in IT I'm used to it. You people just C A N N O T simply anything. Everything has to have 20 convoluted ways to accomplish something.

The result is millions of confused developers luckily getting your crap to work and then falsely believing they are experts on it so that they can confuse millions more developers with their solutions unique to them.

Anyway, I just got a kick out of it. 'Frustrating as absolute fuck but what's one developer gonna do except spend the next evening looking for information he should already have.

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3316**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Wednesday, December 9, 2020 7:18:26 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
