### ISSUE TITLE
Clarification on "4. Configure the migrations assembly".

### ISSUE THREAD

**Issue by fisherthewol** [dotnet/EntityFramework.Docs#2960]
Hi All,

I'm writing a WPF App, using EF Core as the ORM.
I'm attempting to follow [Using a Separate Migrations Project](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects) as I believe it to be the correct process for my solution.
I've done steps 1 through 3, so far so good. My target project is called `PSSytem`, and my migrations project is called `DevMigrations`. I would share the git repo but unfortunately it has to stay private.
However, when attempting step 4, I am unclear as to where I am meant to write the provided code. In `PSSytem`, there is an automatically generated `AssemblyInfo.cs`; however there is no such item in `DevMigrations`. So I'm failing to see where I could "configure an assembly".
Any clarification would be wonderful.

Many Thanks,
Fisher.
(PS: This ambiguity may fully be due to my lack of experience with C#, .NET, and EF; It's also 4am here and I might just be blind).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Using a Separate Migrations Project - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by fisherthewol** [comment]
I ended up just moving migrations back in to the main project.

**Comment by bricelam** [comment]
Duplicate of #933

This page definitely needs some work.

**Comment by fisherthewol** [comment]
> Duplicate of #933
> 
> This page definitely needs some work.

Ah, sorry for not finding the duplicate first!!
Probably already mentioned there, but from my limited knowledge this page is messy because it assumes knowledge of ASP.NET, then describes actions based on an ASP solution structure.
If you know ASP.NET then that's fine, you can "translate" it for other projects. But if you don't then it leaves you in the dark.
Or I could be completely off the mark with this.
Anyway, thanks for getting back to me!

**Comment by bricelam** [comment]
Well, it's not exactly a dupe, but I wanted to link it so we didn't miss your specific feedback when updating that page.
