### ISSUE TITLE
Add usage example for EfLocalDb

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/EntityFramework.Docs#2961]
I would like to propose [EfLocalDb](https://github.com/SimonCropp/LocalDb#entityframework-core) as an replacement for the document [Sharing databases between tests](https://docs.microsoft.com/en-us/ef/core/testing/sharing-databases#sharing-the-fixture). Or at least add a document that shows it as an alternative.

I created EfLocalDb to address the exact problems "Sharing databases between tests" attempts to work around:

> For that sample, each test created a new database. This is a good pattern when using SQLite or the EF in-memory database, but it can involve significant overhead when using other database systems.
https://docs.microsoft.com/en-us/ef/core/testing/sharing-databases

EFLocalDb mitigates this by initially spinning up a template db, then that db is taken offline and a copy the mdf and ldf files are mounted for each test method.

> it is important to have appropriate locking to ensure only one thread does the database creation and seeding.
https://docs.microsoft.com/en-us/ef/core/testing/sharing-databases#sharing-the-fixture

No locking is required with EFLocalDb since every test method gets its own sql database based on the current test file and test method. seeding can be done once in the static context https://github.com/SimonCropp/LocalDb/blob/master/pages/ef-usage.md#seeding-data-in-the-template

> This requires understanding:
> How to safely share objects between tests
> When the test framework runs tests in parallel
> How to keep the database in a clean state for every test

EFLocalDb handle all this

> It can be faster to "clean" the existing database using something like respawn rather than re-create it each time. However, care must be taken to ensure that the database schema is up-to-date with the EF model when doing this.

EFLocalDb handle this efficiently by copying and mounting the template mdf and ldf files. The template db is automatically re-generated when the DB context assembly has changed.

> The database connection is disposed when the fixture is disposed. You may also consider deleting the test database at this point. However, this will require additional locking and reference counting if the fixture is being shared by multiple test classes. Also, it is often useful to have the test database still available for debugging failed tests.

EFLocalDb leaves the dbs in place for each method. so any failure for any test can be debugged.

> Note that tests within a single class will not be run in parallel. This means it is safe for each test to use the same database connection, even though the DbConnection object is not thread-safe.

EFLocalDb supports running tests in parallel

## Full Test

The code to use EFLocalDb is also significantly simpler

```
public class SharedDatabaseTest
{
    static SqlInstance<ItemsContext> sqlInstance;

    static SharedDatabaseTest()
    {
        sqlInstance = new SqlInstance<ItemsContext>(
            constructInstance: builder => new(builder.Options),
            buildTemplate: async context =>
                {
                    await context.Database.EnsureCreatedAsync();
                    AddItems(context);
                    await context.SaveChangesAsync();
                });
    }

    static void AddItems(ItemsContext context)
    {
        var one = new Item("ItemOne");
        one.AddTag("Tag11");
        one.AddTag("Tag12");
        one.AddTag("Tag13");

        var two = new Item("ItemTwo");

        var three = new Item("ItemThree");
        three.AddTag("Tag31");
        three.AddTag("Tag31");
        three.AddTag("Tag31");
        three.AddTag("Tag32");
        three.AddTag("Tag32");

        context.AddRange(one, two, three);
    }

    [Fact]
    public async Task Can_get_items()
    {
        await using var database = await sqlInstance.Build();
        var controller = new ItemsController(database);

        var items = controller.Get().ToList();

        Assert.Equal(3, items.Count);
        Assert.Equal("ItemOne", items[0].Name);
        Assert.Equal("ItemThree", items[1].Name);
        Assert.Equal("ItemTwo", items[2].Name);
    }
}
```

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd515f67-3587-6e8e-0a81-6a76cb30a808
* Version Independent ID: f9f5275d-1b90-b34d-d39c-228b7f310125
* Content: [Sharing databases between tests - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/sharing-databases#sharing-the-fixture)
* Content Source: [entity-framework/core/testing/sharing-databases.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/testing/sharing-databases.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@SimonCropp While we appreciate this extension can be useful for people, we don't believe that the docs should not use any specific external package that is not needed, except in cases where that package is something we are recommending everyone use. This wouldn't be the case here, so we believe this is best referenced as an extension for those who want to give it a try.
