### ISSUE TITLE
The Entity "PostTag" is never defined, how can the example code ref it???

### ISSUE THREAD

**Issue by mingtong** [dotnet/EntityFramework.Docs#2963]
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

**Comment by ajcvickers** [comment]
What code or documentation are you referencing?

**Comment by mingtong** [comment]
> What code or documentation are you referencing?

https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#many-to-many


The many to many example.

**Comment by ajcvickers** [comment]
@mingtong These are intended as incomplete snippets that give a peak into new features. For full code, see the full docs here: https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key and consider downloading the samples from GitHub.
