### ISSUE TITLE
Calculate Rating as Double, optimise=true and other tweaks

### ISSUE THREAD

**Issue by DickBaker** [dotnet/EntityFramework.Docs#2964]
arising from roji's 2934 and
https://docs.microsoft.com/en-us/ef/core/performance/performance-diagnosis?tabs=simple-logging%2Cload-entities

The calculations sum / count as-is yield int when should yield double
Need optimise=true in the .csproj to satisfy Benchmark.net
needs a Console.Read() at end so results can be viewed/kept
updated EF packages to latest
various analyzer-suggested enhancements and needs .editorconfig file for consistency

I am raising a PR for this

BTW my results are
// * Summary *

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1256 (1909/November2018Update/19H2)
Intel Core i7-4500U CPU 1.80GHz (Haswell), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=5.0.101
  [Host]     : .NET Core 5.0.1 (CoreCLR 5.0.120.57516, CoreFX 5.0.120.57516), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Core 5.0.1 (CoreCLR 5.0.120.57516, CoreFX 5.0.120.57516), X64 RyuJIT

|                 Method |      Mean |     Error |    StdDev | Ratio | RatioSD | Gen 0 | Gen 1 | Gen 2 |  Allocated |
|----------------------- |----------:|----------:|----------:|------:|--------:|------:|------:|------:|-----------:|
|           LoadEntities | 41.559 ms | 11.102 ms | 32.032 ms |  5.96 |    6.30 |     - |     - |     - | 1312.48 KB |
| LoadEntitiesNoTracking | 31.226 ms |  6.760 ms | 18.845 ms |  4.26 |    3.17 |     - |     - |     - |  542.91 KB |
|     ProjectOnlyRanking | 12.785 ms |  1.413 ms |  3.891 ms |  1.57 |    0.73 |     - |     - |     - |  255.06 KB |
|    CalculateInDatabase |  9.215 ms |  1.529 ms |  4.313 ms |  1.00 |    0.00 |     - |     - |     - |   36.38 KB |

**Comment by roji** [comment]
Closing as #2990 has been merged.
