### ISSUE TITLE
Cosmos options

### ISSUE THREAD

**Issue by bobbyangers** [dotnet/EntityFramework.Docs#2968]
The Tip section links to **CosmosClientOptions** but was expecting to end up at **CosmosDbContextOptionsBuilder** 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738deb7b-d752-f628-3860-fe53891cadb0
* Version Independent ID: e0a18db9-d605-2a78-b77a-d22375dcfd4e
* Content: [Azure Cosmos DB Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli#cosmos-options)
* Content Source: [entity-framework/core/providers/cosmos/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/cosmos/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@bobbyangers This is intentional. The linked document contains more details than the option builder docs.
