### ISSUE TITLE
Rollback db?

### ISSUE THREAD

**Issue by kwaazaar** [dotnet/EntityFramework.Docs#2969]
And how to rollback the database to a previous migration?

Where is the documentation? This looks more like examples only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d4bb699-8a1f-b908-65f8-3c3dbbea25e7
* Version Independent ID: 9d82c393-ac60-0526-1779-f51c8ce16102
* Content: [Managing Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/managing.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/managing.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@kwaazaar See https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli. Rolling back to a previous migration is the same operation as updating to a new migration; specify the target migration that you want to get to and EF Core will go up or down as needed.

Keeping the issue open to make this clearer in the docs.
