### ISSUE TITLE
Document how to use a value comparer to compensate for different behavior of string comparisons in client and store

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#2979]
Typically string comparisons performed on the store can have different behaviors to comparisons in memory, e.g. trailing blanks and casing may be ignored in the store. 

In previous versions of EF this made things like fixup of string keys hard to predict: related data would be pulled from the database because the FK and PK values matched according to the server semantics but once in memory the strings didn't match and therefore fixup didn't happen. This is described in more detail in [CodePlex dotnet/efcore#284](https://entityframework.codeplex.com/workitem/284).

This kind of difference appears more often when working with existing data, so how important this is depends on how much we prioritize those scenarios. If the data was stored by EF then string keys have a better chance to be an exact match.

The idea to address this is that on the client, EF Core could always use a custom string comparison algorithm that would mimic the behavior in the database. That is, one that ignores trailing blanks and casing.

**Comment by ajcvickers** [comment]
@RichardD2 It's very likely this doesn't work on 3.1. Value comparers have seen significant improvements since then.

**Comment by RichardD2** [comment]
@ajcvickers Thanks. Looks like using a value converter works in 3.1 as an alternative:

```csharp
public sealed class StringToUpperValueConverter : ValueConverter<string, string>
{
    private static readonly Expression<Func<string, string>> ToProvider = s => s;
    private static readonly Expression<Func<string, string>> FromProvider = s => s.ToUpperInvariant();
    public static readonly StringToUpperValueConverter Instance = new();

    private StringToUpperValueConverter() : base(ToProvider, FromProvider)
    {
    }
}
```
