### ISSUE TITLE
Merge repeated sections

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/EntityFramework.Docs#2980]
Related: https://github.com/dotnet/EntityFramework.Docs.pl-pl/issues/11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [Generated Values - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=fluent-api)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
This doesn't seem like a mangled merge conflict - the page seems intentionally structured to first have a "conceptual" section explaining the 3 value generation patterns, and then a "concrete" section for each type (e.g. detailing computed columns specifically for on-add-or-update).

I'll submit a PR to simplify and merge.
