### ISSUE TITLE
InMemory testing with views and HasNoKey

### ISSUE THREAD

**Issue by YauGoh** [dotnet/EntityFramework.Docs#2983]
Hi 

I'm interested in running inmemory tests against a dbset mapped to a view with HasNoKey.  The article said there was a runnable sample using ToInMemoryQuery.  I've followed the link but was unable to find such sample.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc10f39-8fe5-e856-5839-9aa5e9d435c6
* Version Independent ID: 10ddba97-42d2-0cda-3e7f-eaeb4fda74b0
* Content: [Keyless Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/keyless-entity-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/keyless-entity-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@YauGoh the testing docs, along with a full code sample for the different testing techniques, can be found [here](https://docs.microsoft.com/en-us/ef/core/testing/testing-sample) (the actual source code is [here](https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core/Miscellaneous/Testing/ItemsWebApi/Tests), you can start with InMemoryItemsControllerTest.cs and its base class).

Note that I'm re-working the test docs to make it easier to find code samples for each testing method (Sqlite, InMemory, repository...). Will close this issue as part of that.
