### ISSUE TITLE
using EF good/bad/ugly client-side

### ISSUE THREAD

**Issue by DickBaker** [dotnet/EntityFramework.Docs#2991]
EF starting well with perf initiative for v5-v6 at https://docs.microsoft.com/en-us/ef/core/performance/performance-diagnosis?tabs=simple-logging%2Cload-entities and I am hoping this will develop to contrast the different styles of using EF in anger [not just trivial courseware/demoware]. Building on Roji's work [minimising roundtrip/traffic] I will shortly contribute a [more involved] PR highlighting client-side alternatives to show some gotchas / goodness that I hope you will publish [after inevitable wrangling!] to enlighten & encourage efficient methodologies.
Besides the C# code I will submit an .XLSX to portray my results, but I am conscious that probably will still need a good wordsmith to explain the angles in best light. HTH anyway even if few sacred cows get scapegoated [sorry pun].

**Comment by ajcvickers** [comment]
Ping @roji

**Comment by roji** [comment]
Let's wait a few more days for a response on https://github.com/dotnet/EntityFramework.Docs/pull/2992#issuecomment-766878278

**Comment by roji** [comment]
Closing this for now as per https://github.com/dotnet/EntityFramework.Docs/pull/2992#issuecomment-774492540
