### ISSUE TITLE
Update limitation description about EF Core's public API not being annoted for nullability

### ISSUE THREAD

**Issue by dennisseders** [dotnet/EntityFramework.Docs#3001]
The description tells that it is planned to address this in the Entity Framework Core 5.0 release. It seems that this was scoped out of EF Core 5.0. Also the issue which tracks this is not mentioned.

Please update the release in which it is planned to address this and include the issue which tracks this. 

Consider to leave out mentioning the release here as the GitHub repository can be considered as the source-of-truth. This just avoids that this part of the  document gets out-of-date again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks, submitted #3002 to fix this. Work is already underway to annotate EF for nullability.
