### ISSUE TITLE
Localization broke display

### ISSUE THREAD

**Issue by vernou** [dotnet/EntityFramework.Docs#3003]
In the french documentation, it has this ugly display :
https://docs.microsoft.com/fr-fr/ef/core/managing-schemas/scaffolding?tabs=vs#specifying-tables
![image](https://user-images.githubusercontent.com/1659796/104181383-f9abe700-540e-11eb-9899-873b2ecf85dd.png)
> I enable **Read in English**, but this don't affect the problem

I notice this problem in all languages that I tested (it/de/es/fr), I think the problem is present for all languages.

The problem come from this commit for FR :
See `scaffolding.md` line 83
https://github.com/dotnet/EntityFramework.Docs.fr-fr/commit/b5668a1426d180820aa1742058c917e5703f7fc4
![image](https://user-images.githubusercontent.com/1659796/104182110-3c21f380-5410-11eb-8d15-40d75dde0d83.png)

Idem for ES :
See `scaffolding.md` line 83
https://github.com/dotnet/EntityFramework.Docs.es-es/commit/7cf649f6150628d6645b2accaf06fec5845e7d72

In the original doc (us) the tab is correctly closed (with `***`) and the page is correctly displayed. I think the problem came from the localization tool.

**Comment by roji** [comment]
Duplicate of #2900

**Comment by roji** [comment]
Thanks for looking into the reason!

**Comment by JasonCard** [comment]
This issue is now fixed :)
