### ISSUE TITLE
Missing Documentation for Microsoft.EntityFrameworkCore.Analyzers

### ISSUE THREAD

**Issue by AndyWDev** [dotnet/EntityFramework.Docs#3011]
There is a link from the Nuget site for Microsoft.EntityFrameworkCore.Analyzers to the entity framework core documentation - however, there appears to be no information on what this package is and what it does.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b15cd4c-9cba-c0e2-7618-7d621a3c5936
* Version Independent ID: f4681bc6-57be-6e69-cad9-776ce64d93bd
* Content: [Overview of Entity Framework Core - EF Core](https://docs.microsoft.com/en-nz/ef/core/)
* Content Source: [entity-framework/core/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
At the moment, this package contains a single analyzer which detects any usage of internal EF Core APIs. EF Core exposes most of its internal APIs publicly, but within an Internal namespace (or annotated with an `[EntityFrameworkInternal]`); the analyzer detects usage of those. In the future we may add some more useful code analysis for code using EF Core.

We can add a note somewhere in our docs, though not sure this is important enough.

**Comment by AndyWDev** [comment]
Thanks for the explanation
