### ISSUE TITLE
  => options.UseSqlite("Data Source=blogging.db")    does not work. 

### ISSUE THREAD

**Issue by ywwyeu** [dotnet/EntityFramework.Docs#3013]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488629d4-9bd2-42b5-4644-34e3f2baee59
* Version Independent ID: b38b9d14-6bad-12e0-8d2d-24b50bc4977e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=visual-studio)
* Content Source: [entity-framework/core/get-started/overview/first-app.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/overview/first-app.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by ywwyeu** [comment]
Getting the error message that the Blog Table does not exist.    When I use ("Data Source = c:\\Yourfolder\\blogging.db")  the error does not occur.

**Comment by ajcvickers** [comment]
@ywwyeu I am not able to reproduce this. Did you download the sample or create it from scratch?

**Comment by ywwyeu** [comment]
Hello,

 

I did not download the sample, I copied the code on the https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli

Page.

 

I followed all the steps described in the document.

 

Microsoft Visual Studio Community 2019 Version 16.8.4

 

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <OutputType>Exe</OutputType>

    <TargetFramework>netcoreapp3.1</TargetFramework>

    <StartWorkingDirectory>$(MSBuildProjectDirectory)</StartWorkingDirectory>

  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.2">

      <PrivateAssets>all</PrivateAssets>

      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>

    </PackageReference>

    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.2" />

  </ItemGroup>

</Project>

 

 

Microsoft.EntityFrameworkCore.DbUpdateException

  HResult=0x80131500

  Message=An error occurred while updating the entries. See the inner exception for details.

  Source=Microsoft.EntityFrameworkCore.Relational

  StackTrace:

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)

   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)

   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)

   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()

   at EFGetStarted.Program.Main() in C:\AI\Storm bvba\Projecten Nieuw\ClassLibraryWS\ConsoleApp1\Program.cs:line 16

 

  This exception was originally thrown at this call stack:

    [External Code]

 

Inner Exception 1:

SqliteException: SQLite Error 1: 'no such table: Items'.

 

 

 

If I put the database in c:\temp\     and use      => options.UseSqlite("Data Source=C:\\temp\\dbase.sqlite");  

I don’t get the error.

 

Regards

Olivier

**Comment by ywwyeu** [comment]
I then even simplified the model (this explains the error message cannot find ‘item’ table)

 

public class Item

    {

      

        public string Id { get; set; }

        public string Text { get; set; }

        public string Description { get; set; }

    }

 

 

 

 

    using (var db = new BloggingContext())

            {

                // Create

                Console.WriteLine("Inserting a new item");

                db.Add(new Item {  Description = "test",  Text ="test", Id = "1" });

                db.SaveChanges();

          

            }

 

 

class Program

    {

        static void Main()

        {

            using (var db = new BloggingContext())

            {

               // Create

                Console.WriteLine("Inserting a new item");

                db.Add(new Item {  Description = "test",  Text ="test", Id = "1" });

                db.SaveChanges();

        

            }

        }

    }

 

 

 

public class BloggingContext : DbContext

    {

     

        public DbSet<Item> Items { get; set; }

             

        //protected override void OnConfiguring(DbContextOptionsBuilder options)

        //  => options.UseSqlite("Data Source=C:\\temp\\dbase.sqlite");

 

        protected override void OnConfiguring(DbContextOptionsBuilder options)

      => options.UseSqlite("Data Source=blogging.db");

    }

**Comment by ywwyeu** [comment]
Sorry for having used up your time.  

The cause of the error was because I forgot to add :

 

<StartWorkingDirectory>$(MSBuildProjectDirectory)</StartWorkingDirectory>

 

In the project file
