### ISSUE TITLE
Apply migrations at runtime no longer supported by .net core 5 it appears.

### ISSUE THREAD

**Issue by stermic2** [dotnet/EntityFramework.Docs#3015]
Apply migrations at runtime no longer supported by .net core 5 it appears.

The documentation should be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06b35eff-79e4-2068-6d1c-f9079d43f903
* Version Independent ID: 6c575b10-048c-349c-397e-0d9c11d47235
* Content: [Applying Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/applying.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/applying.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by stermic2** [comment]
Ok. It seems that I was wrong that it's no longer supported, but the manner the documentation currently outlines only seems to work for <=.NET 3

[This works](https://www.learnentityframeworkcore5.com/migrations-in-ef-core#apply-migration-at-runtime) for .NET 5

I'm not having issues though, I'm loving .NET 5
Keep up the good work.

**Comment by stermic2** [comment]
I'd make the pull request myself, but I don't know for certain where it should be called. 
This might be the correct context:

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // database provider is configured before runtime migration update is applied e.g:
            optionsBuilder.UseSqlServer(ConnectionString);
            Database.Migrate();
        }

**Comment by roji** [comment]
> but the manner the documentation currently outlines only seems to work for <=.NET 3

Can you point to which documentation you're referring to? [This is the official EF documentation on applying migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli), and the section on "apply migrations at runtime" certainly doesn't show the code you're using.

Regardless, it certainly isn't a good idea to put `Database.Migrate()` in your OnConfiguring - this means you're executing it every time you instantiate a context... If you wish to use `Datebase.Migrate()` (which we generally recommend against in production applications), run that at some point in your program startup instead.

**Comment by stermic2** [comment]
I'm afraid I was confusing this documentation (where we're applying the migration from the Host Builder), with hypothetical documentation (where we would apply the migration from the Application Builder).

Which you could also argue oughtn't be recommended...

I apologize for reporting an issue where there wasn't one.

Thank you, And again very impressed with your work.
