### ISSUE TITLE
What about EF Core

### ISSUE THREAD

**Issue by utillity** [dotnet/EntityFramework.Docs#3018]
thanks for the very detailed info on logging - there is NO HINT however, how to do this with EF Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97eca854-650c-5c9e-25f2-e5e92e91c310
* Version Independent ID: be1279e0-ce03-8b44-bdf7-d9d173aba9b7
* Content: [Logging and intercepting database operations - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/logging-and-interception?redirectedfrom=MSDN)
* Content Source: [entity-framework/ef6/fundamentals/logging-and-interception.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/logging-and-interception.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@utillity EF Core documentation is here: https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/
