### ISSUE TITLE
Sample code under 'SRID Ignored during client operations' seems out of date and will not compile

### ISSUE THREAD

**Issue by eddieyanez** [dotnet/EntityFramework.Docs#3019]
Examples:

1. new CoordinateSystemServices(...) now requires a minimum of two parameters.
2. code MathTransformFilter will not compile even if referencing GeoAPI.CoordinateSystems and using GeoAPI.CoordinateSystems.Transformations.IMathTransform instead of MathTransformation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dcf82b-f177-e91b-96a5-67f2f57bd6c4
* Version Independent ID: 89c0803f-570f-07a6-6dc2-285678712c86
* Content: [Spatial Data - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/spatial)
* Content Source: [entity-framework/core/modeling/spatial.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/spatial.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@eddieyanez I am not able to reproduce this. Did you download the sample, or create it from scratch?

**Comment by eddieyanez** [comment]
> @eddieyanez I am not able to reproduce this. Did you download the sample, or create it from scratch?

I've created it from scratch. Let me put together a sample project + steps to reproduce later this afternoon and share. I'll try the sample too. Thanks.

**Comment by eddieyanez** [comment]
@ajcvickers The page https://docs.microsoft.com/en-us/ef/core/modeling/spatial doesn't seem to have a link to a downloadable sample. I've looked everywhere and searched for Sample but couldn't find anything. Am I missing anything?

**Comment by ajcvickers** [comment]
https://github.com/dotnet/EntityFramework.Docs/tree/master/samples/core/Spatial

The link is missing from this page; we will add it.

**Comment by eddieyanez** [comment]
Meanwhile, here's the sample solution [DOCS-3019.zip](https://github.com/dotnet/EntityFramework.Docs/files/5832446/DOCS-3019.zip)

Steps to reproduce:

1. Create a new solution with a .Net 5.0 Console project.
2. Add latest (stable) NuGet packages for:
* Microsoft.EntityFrameworkCore (latest stable version is 5.0.2)
* Microsoft.EntityFrameworkCore.SqlServer (latest stable version is 5.0.2)
* Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite (latest stable version is 5.02)
* ProjNET4GeoAPI (referenced on page, latest stable version is 1.4.1)
3. Create new file called GeometryExtensions.cs
4. Paste the code from box that starts with **static class GeometryExtensions**
5. Compile

Once compiled, errors are:
* /projects/DOCS-3019/DOCS-3019/GeometryExtensions.cs(19,19): Error CS1729: 'CoordinateSystemServices' does not contain a constructor that takes 1 arguments (CS1729) (DOCS-3019)
* /projects/DOCS-3019/DOCS-3019/GeometryExtensions.cs(50,50): Error CS1503: Argument 1: cannot convert from 'GeoAPI.CoordinateSystems.Transformations.IMathTransform' to 'ProjNet.CoordinateSystems.Transformations.MathTransform' (CS1503) (DOCS-3019)
* /projects/DOCS-3019/DOCS-3019/GeometryExtensions.cs(28,28): Error CS1501: No overload for method 'Transform' takes 3 arguments (CS1501) (DOCS-3019)

**Comment by eddieyanez** [comment]
> https://github.com/dotnet/EntityFramework.Docs/tree/master/samples/core/Spatial
> 
> The link is missing from this page; we will add it.

@ajcvickers thanks. Just had a look at the code and the difference between the sample code and mine is that the sample code uses the NuGet Package **ProjNet**, whereas the mine uses the NuGet package mentioned on the page **ProjNET4GeoAPI**. ProjNet is not mentioned on the page.

**Comment by bricelam** [comment]
👍 We need to update the docs to **ProjNet**. The other package was left over from EF Core 2.2
