### ISSUE TITLE
Unapply migrations

### ISSUE THREAD

**Issue by nbon12** [dotnet/EntityFramework.Docs#3026]
Is there a way to unapply migrations or to name a specific migration to go back to?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e1bea0-9bff-3e9c-adfa-a1e373dfd0f1
* Version Independent ID: 9196177d-8a82-d054-9128-317e091b551e
* Content: [RelationalDatabaseFacadeExtensions.MigrateAsync(DatabaseFacade, CancellationToken) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.migrateasync?view=efcore-5.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@nbon12 yes, a migration and be rolled back - this is detailed in the [Applying Migrations doc page](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli). Simply specify a target migration that is earlier than the database's current one.

**Comment by nbon12** [comment]
@roji Ah, I was mistakenly not specific!
I meant to ask: using the C# .MigrateAsync() function, I don't see a parameter to supply the migration name. I'm not using the CLI tool, I'm using the following C# code to perform the migration:

```C#
var dbOptionsBuilder = new DbContextOptionsBuilder<DbContext>();
dbOptionsBuilder.UseMySql(connectionString);
await using var dbContextEf = new InnkeeperDbContext(dbOptionsBuilder.Options);
Console.WriteLine($"[{dbContextEf.Database.GetDbConnection().Database}] Begin Migrating Tenant {tenantSchema.Name} transactional business database... (may take awhile)");
await dbContextEf.Database.MigrateAsync();
```

**Comment by roji** [comment]
MigrateAsync has a `targetMigration` parameter where you can specify which migration to go to. If it's a previous migration, then it rolls back (calling the Down methods).

**Comment by nbon12** [comment]
I don't see `targetMigration` as a parameter; however, I see a  `databaseFacade` parameter.
```public static System.Threading.Tasks.Task MigrateAsync (this Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade databaseFacade, System.Threading.CancellationToken cancellationToken = default);
```
Is the `targetMigration` a member of `databaseFacade`?

**Comment by ajcvickers** [comment]
@nbon12 The database facade doesn't expose all the features of the migrator. Instead you can get the actual `IMigrator` service from your DbContext and use that. For example:

```C#
context.GetService<IMigrator>().Migrate("TargetMigration");
```
