### ISSUE TITLE
Missing link to Github repository

### ISSUE THREAD

**Issue by 420tech** [dotnet/EntityFramework.Docs#3036]
[Enter feedback here]
The page is missing the link to the github repository for the sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf41872-597e-d846-0e54-e6e84f00ac72
* Version Independent ID: 19da55b4-6887-cb39-a87e-bb71c433de8b
* Content: [Getting Started with EF Core and Xamarin - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/xamarin)
* Content Source: [entity-framework/core/get-started/xamarin.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/xamarin.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by JeremyLikness** [comment]
@420tech are you sure? I see a prominent link at the top. I checked and it works. Can you please confirm?

![A screenshot that shows the link](https://user-images.githubusercontent.com/5479675/105886616-76b68f00-5fbf-11eb-809f-c72a73cfd0b0.png)

**Comment by 420tech** [comment]
Thanks. I missed it
