### ISSUE TITLE
So, eh...what is an ItemsContext and where does it come from?

### ISSUE THREAD

**Issue by drathnow** [dotnet/EntityFramework.Docs#3039]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ef36e12-dfc2-ac09-76b7-4af887bc39c1
* Version Independent ID: 87e16518-5ade-2159-ba56-11fbf6b2bf69
* Content: [EF Core testing sample - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/testing-sample)
* Content Source: [entity-framework/core/testing/testing-sample.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/testing/testing-sample.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Simplifying the samples to use a standard BloggingContext and adding links to the sample code on github where appropriate.
