### ISSUE TITLE
Finding my way to the truly parameterless DbContext constructor

### ISSUE THREAD

**Issue by HalHaynes** [dotnet/EntityFramework.Docs#3040]
Many pages that follow this one include code samples that kick off with the likes of
```C#
using (var context = new BloggingContext())
```
But these are all, evidently, oblivious to the data source. I'm working on a .NET CORE 3.1 console project that kicks off async tasks requiring SQL Server access. I know I'm supposed to feed the constructor of my DbContext subclass a DbContextOptions object that has had a SQL connection attached to it via UseSqlServer(). 
```C#
using (var context = new BloggingContext(options))
```
The method in each task that handles database operations is a couple of levels down from where the task is invoked. It seems improper for the intervening levels to have passing through the `options` object through them, expecting each to pass it down to the next level in its parameter list, when none of them have any use for it or any reason to know what it is or even that the next level down needs it.

```C#
public class MyScheduledTask
{
  public void Run(DbContextOptions options)
  {
    // I have no use for this, but apparently I'm supposed to know to do this:
      OneLevelDown(options);
  }
  
  private void OneLevelDown(DbContextOptions options)
  {
    // I have no idea what this is either, but the developer made me carry it in my parameter list,
    // and somehow I'm supposed to know that the next method down needs it.
    TwoLevelsDown(options);
  }
  
  private void TwoLevelsDown(DbContextOptions options)
  {
    // I'm clueless too. Hey, do you want this?
    DbAccessor accessor = new DbAccessor(options);
  }
}

public class DbAccessor
{
  private readonly DbContextOptions options;
  public DbAccessor(DbContextOptions options)
  {
    // Hey, thanks all of you! Just what I needed! If I need anything else, I'll bug the developer
    // to change EVERY SINGLE ONE of you as well so that you can pass that to me.
    MyContext context = new MyContext(options);
    ...
  }
}
```

This page covers dependency injection in context where, clearly, the framework is going to be producing the contexts. It also has sections that acknowledge that DI isn't always available and that the code may need to instantiate a context object explicitly. Well, then, it needs access at that point to the DbContextOptions object. How can I get that from wherever it was defined in Startup.cs without having to burden the parameter lists of every method above the database access method in the call stack?

The pages tries to anticipate that by giving me this options:
```C#
public class ApplicationDbContext : DbContext
{
    private readonly string _connectionString;

    public ApplicationDbContext(string connectionString)
    {
        _connectionString = connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(_connectionString);
    }
}
```
That just pushes the question down the line. Now I'm creating the optionsBuilder in place, which is fine, but then where is `connectionString` coming from? I want to define *that* in one place, presumably in Startup.cs, again without having to push it through the parameter lists of all the intervening methods.

It would be helpful if this documentation, like *much* documentation about dependency injection, gave a clearer picture of how to get a hold of all these elements that, I presume, should be configured in Startup.cs for access wherever they're needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055bb8db-139d-beb5-61c1-47cf1ea6ea93
* Version Independent ID: b0a3d5ad-b62c-1ff4-386a-f11e350eea0c
* Content: [DbContext Lifetime, Configuration, and Initialization - EF Core](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/)
* Content Source: [entity-framework/core/dbcontext-configuration/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/dbcontext-configuration/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@HalHaynes DbContext doesn't do anything special here. The application is responsible for obtaining the configuration and getting it to the DbContext in some way. The ASP.NET Core way of doing this is with an application dependency injection container from which services, like DbContext, are resolved. `Startup.cs` in an ASP.NET Core doesn't setup any other mechanism to obtain the context configuration. Both EF Core and ASP.NET Core are, by-design, not coupled to any global/app-domain configuration. However, if you want to have startup store the configuration in some global state, and then have your DbContext code read that, then you can do so, but you must manage that in your application.
