### ISSUE TITLE
Missing code snippet on NRT doc

### ISSUE THREAD

**Issue by garyng** [dotnet/EntityFramework.Docs#3048]
https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#navigating-and-including-nullable-relationships
![image](https://user-images.githubusercontent.com/4453664/106182498-d7b9af00-61d9-11eb-9a67-ff499dc22e43.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@smitpatel looks like the doc system stopped handled code snippet links of the form:

```
[!code-csharp[Main](../../../samples/core/Miscellaneous/NullableReferenceTypes/Program.cs?range=46)]
```

Curiously, `?range=36-39&highlight=2` (just below) does work - maybe it's the fact that it's a single line (`?start=46&end=46` also didn't work). I've converted to named regions for the collations page (#3050) but maybe we should reach out to the docs team...
