### ISSUE TITLE
Tip about "If you have no existing migrations" seems inaccurate

### ISSUE THREAD

**Issue by sfmskywalker** [dotnet/EntityFramework.Docs#3054]
The following tip seems inaccurate:

> If you have no existing migrations, generate one in the project containing the DbContext then move it. This is important because if the migrations project does not contain an existing migration, the Add-Migration command will be unable to find the DbContext.

As it turns out, when I add just a single class that implements `IDesignTimeDbContextFactory<TContext>`, things will just work out when I run e.g. `dotnet ef migrations add Initial -- "{some connection string}"`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Using a Separate Migrations Project - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment]
@sfmskywalker That's another perfectly valid approach. I tried to describe the simplest approach in the documentation, since implementing IDesignTimeDbContextFactory isn't trivial when it depends heavily on application services.

**Comment by sfmskywalker** [comment]
I see. Then perhaps an improvement might be to say something like this so that at least the text is correct (since Add-Migration can still find the DbContext if you have a factory rather than an initial migration)?

> If you have no existing migrations, generate one in the project containing the DbContext then move it or add a class implementing `IDesignTimeDbContextFactory<TContext>`. This is important because if the migrations project does not contain an existing migration or a factory, the Add-Migration command will be unable to find the DbContext.

**Comment by ajcvickers** [comment]
@sfmskywalker I think we would consider a PR for this that indicates that generating a migration is the simplest way to do this, but there are also other options, including implementation of a context factory.
