### ISSUE TITLE
 Machine translation should ignore examples of code

### ISSUE THREAD

**Issue by AndrewKitu** [dotnet/EntityFramework.Docs#3064]
Page: https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli
Line: Both IDesignTimeDbContextFactory.CreateDbContext and Program.CreateHostBuilder accept command line arguments.

IDesignTimeDbContextFactory.CreateDbContext is example of code.
But it is not marked as example of code, so the translator tries to translate it.

Can I submit a pull request that will fix it?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 459d20e7-ba25-c162-5721-359ef3562999
* Version Independent ID: d988e806-cb86-19f5-7f76-6ce3bfcd94ed
* Content: [Создание DbContext во время разработки — EF Core](https://docs.microsoft.com/ru-ru/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/cli/dbcontext-creation.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/cli/dbcontext-creation.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Yes. These should be marked with `<xref:<fullname>?displayProperty=nameWithType>` so that a reference to our API documentation are created.

**Comment by ajcvickers** [comment]
Just to clarify, out of these "words", "IDesignTimeDbContextFactory", "CreateDbContext", "Program", and "CreateHostBuilder", the only one that it is possible to translate is "Program". The others are not English words and so it is literally impossible to translate them from English.

**Comment by Rick-Anderson** [comment]
> IDesignTimeDbContextFactory.CreateDbContext is example of code.>But it is not marked as example of code, so the translator tries to translate i

Here is what's on the english page

Both IDesignTimeDbContextFactory.CreateDbContext and Program.CreateHostBuilder accept command line arguments.

And the `/ru` page

![image](https://user-images.githubusercontent.com/3605364/106682893-34203280-660f-11eb-8777-e97142f8d3d5.png)

I know your team has decided not to follow the code fence all terms as you're used to reading it that way, but the rest of use are used to reading it with them `code fenced` and we much prefer it.

**Comment by Rick-Anderson** [comment]
@ajcvickers please assign this to me if you'd like me to fix it.

**Comment by AndrewKitu** [comment]
https://github.com/dotnet/EntityFramework.Docs/pull/3070

**Comment by AndrewKitu** [comment]
@Rick-Anderson  
https://github.com/dotnet/EntityFramework.Docs/pull/3070
