### ISSUE TITLE
For specific commands, they should not be translated into Chinese 

### ISSUE THREAD

**Issue by daoye** [dotnet/EntityFramework.Docs#3066]
English per google translate:

For specific commands, they should not be translated into Chinese

For example: dotnet ef database is deleted, obviously dotnet ef database drop should be kept

Original:
对于具体的命令，不应该翻译为中文

例如： dotnet ef 数据库删除 ，很明显应该保留 dotnet ef database drop

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4d1bdeea-0ebc-04ff-5b58-1020ad9cd72a
* Version Independent ID: 847fe92a-2940-afbf-b2ee-e68f8a8060be
* Content: [EF Core 工具参考 ( .NET CLI) -EF Core](https://docs.microsoft.com/zh-cn/ef/core/cli/dotnet)
* Content Source: [entity-framework/core/cli/dotnet.md](https://github.com/dotnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
@ajcvickers I'm going through the localized repro's and transferring here as appropriate. Let me know if that's OK.

**Comment by AndriySvyryd** [comment]
Related https://github.com/dotnet/EntityFramework.Docs/issues/3068
