### ISSUE TITLE
誤訳

### ISSUE THREAD

**Issue by iwamoto-takaaki** [dotnet/EntityFramework.Docs#3073]
[フィードバックをこちらに入力してください]
「DbConfiguration クラスを Dbconfiguration クラスと同じアセンブリに配置します。」
→
「DbConfiguration クラスを DbContext クラスと同じアセンブリに配置します。」
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fcb983de-7c86-dfeb-6548-dde4a9f17379
* Version Independent ID: 547e9c6a-75e6-da12-f60b-93b767eed3f7
* Content: [コードベースの構成-EF6](https://docs.microsoft.com/ja-jp/ef/ef6/fundamentals/configuring/code-based)
* Content Source: [entity-framework/ef6/fundamentals/configuring/code-based.md](https://github.com/dotnet/EntityFramework.Docs.ja-jp/blob/live/entity-framework/ef6/fundamentals/configuring/code-based.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
Related https://github.com/dotnet/EntityFramework.Docs/issues/3068
