### ISSUE TITLE
fixes

### ISSUE THREAD

**Issue by error911** [dotnet/EntityFramework.Docs#3075]
Свойство, которое было бы необязательным **->** Свойство, которое было бы **обязательным**
[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a4381838-81bb-52c6-d921-f8b9ae8163d2
* Version Independent ID: 892a8dd8-7a63-ce0b-de20-27e92b88f971
* Content: [Свойства сущности — EF Core](https://docs.microsoft.com/ru-ru/ef/core/modeling/entity-properties?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/entity-properties.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/modeling/entity-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@error911 @Rick-Anderson are you talking about the [Explicit configuration](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#explicit-configuration) section, where it says:

> A property that would be optional by convention can be configured to be required as follows:

If so, the current sentence seems correct to me.

**Comment by AndriySvyryd** [comment]
The translation is missing the "required" part

> Свойство, которое было бы необязательным по соглашению, может быть настроено следующим образом

 ->
> Свойство, которое было бы необязательным по соглашению, может быть настроено **обязательным** следующим образом:

Though this won't help that much since the translated sentence is still very hard to understand.

**Comment by Rick-Anderson** [comment]
@JasonCard  can you have the translation team look at this?

**Comment by JasonCard** [comment]
@error911 @AndriySvyryd @Rick-Anderson Thank you for your feedback. This article is machine translated, so please understand that some translation quality issues are expected. It's not scalable to fix all minor MT issues, so we only plan to fix major/blocking issues. It appears that this translation issue would be considered minor, so please go ahead to close this issue.

**Comment by Rick-Anderson** [comment]
@JasonCard should I  open a  MT suggestion issue that embedded suggestions should be used? `<!-- EmbeddedSuggestion::: suggestion here -->`

It would be great to leverage the combined skills of a programmer and `/ru-ru`

**Comment by JasonCard** [comment]
@Rick-Anderson In general, if there's a suggested translation, I'd recommend to open a PR instead of GitHub Issue. Also, for MT translation that's difficult to understand, we would encourage users to use the "Read in English" toggle to refer back to the original sentence in English.
