### ISSUE TITLE
Excess backslash in documentation

### ISSUE THREAD

**Issue by roma4004** [dotnet/EntityFramework.Docs#3076]
In examples many times I finded excess backslash "\"
like in this example:
"
...
`var newValues = new Dictionary\<string, object>`
...
"
---
Please fix it by removeing excess backslashes, thanks in advance ^_^

#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: fe4e1787-3d61-e5f3-ba22-f9de0adb6c9f
* Version Independent ID: 86f26f36-9727-244d-93c8-709f4ef72a08
* Content: [Работа со значениями свойств — EF6](https://docs.microsoft.com/ru-ru/ef/ef6/saving/change-tracking/property-values)
* Content Source: [entity-framework/ef6/saving/change-tracking/property-values.md](https://github.com/dotnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/ef6/saving/change-tracking/property-values.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks, have submitted a PR to fix these.
