### ISSUE TITLE
extension method has  private modifier "private static OperationBuilder<CreateUserOperation> CreateUser("

### ISSUE THREAD

**Issue by IgorGolovko** [dotnet/EntityFramework.Docs#3086]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13eb107-79c2-7824-12c1-e637d2a92add
* Version Independent ID: aafc9673-c635-3cf2-6235-8577ff15d19c
* Content: [Custom Migrations Operations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations)
* Content Source: [entity-framework/core/managing-schemas/migrations/operations.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/operations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@IgorGolovko Why are you calling this out?

**Comment by IgorGolovko** [comment]
@ajcvickers I just tried to create a custom migration operation and did it with code snippets from Microsoft Docs, but saw that the extension method in a code snippet has a private modifier instead of public.  I'm new in this flow so, maybe, I did something wrong. This issue can be closed if it's not necessary.

**Comment by bricelam** [comment]
I agree, they should be `internal` or `public` in the sample.
