### ISSUE TITLE
No actual example on how to update a record.

### ISSUE THREAD

**Issue by xshiiiidev** [dotnet/EntityFramework.Docs#3088]
The document example in the [update section](https://docs.microsoft.com/en-us/ef/core/get-started/xamarin#explore-the-code) contains this code

```
var newPost = new Post
{
    BlogId = BlogId,
    Content = postCell.Text,
    Title = titleCell.Text
};

using (var blogContext = new BloggingContext())
{
    var blog = await blogContext
        .Blogs
        .FirstAsync(b => b.BlogId == BlogId);

    blog.Posts.Add(newPost);

    await blogContext.SaveChangesAsync();
}
```

it is actually performing an INSERT/Add operation and not the actual example of updating a record.

I am looking for an example of how to update an actual record.

I hope someone can give an example or update the documentation thank you.

**Comment by roji** [comment]
@xshiiiidev since Posts is a different table and you're adding a new post, isn't an INSERT what you want here? Updating would mean loading an existing Post, making some change on it, and then saving that back.

Take a look at the [Saving Related Data docs](https://docs.microsoft.com/en-us/ef/core/saving/related-data), which contain more info.

**Comment by xshiiiidev** [comment]
@roji Thank you for the reply and reference link.

Yup that is correct it is updating the table of the list using the INSERT/Add operation of EF Core.

What I am looking for an example of updating a single Entity properties.

I can't find it in the documentation examples.

**Comment by roji** [comment]
Are you looking for [this](https://docs.microsoft.com/en-us/ef/core/saving/basic#updating-data)?

**Comment by xshiiiidev** [comment]
@roji exactly what I'm looking for thank you so much didn't saw that before. Will be closing this now :)
