### ISSUE TITLE
Update-database returns "Values can not be null"

### ISSUE THREAD

**Issue by maxwell60701** [dotnet/EntityFramework.Docs#3089]
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues
I use NET CORE,in my StartUp.cs,I write my code like this

`services.AddDbContext<MyDbContext>(options =>
               options.UseSqlServer(Configuration.GetConnectionString("myconnection")));`

This connection is get from appSetting.json,Then I execute Command "update-database",returns "Values can not be null",means my connectionString is null.I confirmed that 
"Configuration.GetConnectionString("myconnection")" returns a string.

However.if I write my code like this 
`services.AddDbContext<MyDbContext>(options =>
               options.UseSqlServer("Data Source =.; Initial Catalog = MyDb; User = sa; Password = 123"));`
it will be ok.

**Comment by ErikEJ** [comment]
Use "Name=xx"- see https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli#configuration-and-user-secrets

**Comment by maxwell60701** [comment]
Thanks,After I use EntityFrameworkCore\Update-Database,it will be ok
