### ISSUE TITLE
Recommended word change

### ISSUE THREAD

**Issue by baxternicholas** [dotnet/EntityFramework.Docs#3095]
Good day,

May I recommend exchanging the word "scaffolded" with "generated" in the early part of this page.

Kind regards,

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002d162b-8595-ad48-7ef8-2cd10194a3b4
* Version Independent ID: a29d6e0c-f9eb-86d9-f82e-0e9fc41b5a0d
* Content: [Code First Migrations - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@baxternicholas "scaffolded" has a more specific meaning than "generated". It means that the generated code is a starting point for further modification. Contrast this to auto-generated code that should not be modified.
