### ISSUE TITLE
Absolutely no help

### ISSUE THREAD

**Issue by dave0783** [dotnet/EntityFramework.Docs#3100]
No examples given on usage.  Currently attempting to use in a LINQ Query Expression and and getting "could not be translated. Additional information: Translation of method 'Microsoft.EntityFrameworkCore.SqlServerDbFunctionsExtensions.DateDiffYear' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information."

```
queryable = from f in queryable
                    join e in context.Set<Experience>() on f.ID equals e.FacultyID
                    where
                        EF.Functions.DateDiffYear(e.StartDate, e.EndDate) >= years
                        && sp.Experience.Contains(e.TypeID) 
                    select f;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b826d5e1-f401-90e1-5fc8-62fdf10e6d43
* Version Independent ID: 095d6b17-db1f-5b04-c487-71f24bde30fb
* Content: [SqlServerDbFunctionsExtensions.DateDiffYear Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.sqlserverdbfunctionsextensions.datediffyear?view=efcore-5.0#Microsoft_EntityFrameworkCore_SqlServerDbFunctionsExtensions_DateDiffYear_Microsoft_EntityFrameworkCore_DbFunctions_System_Nullable_System_DateTime__System_Nullable_System_DateTime__)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/SqlServerDbFunctionsExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/SqlServerDbFunctionsExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@dave0783 can you please post a runnable code sample so that we can investigate? Also, can you confirm that you're running against SQL Server?

**Comment by dave0783** [comment]
I passed the code snippet. After further review, we have determined that this is happening because our test environment is running SQLite; this error does not occur in the production environment using AzureSQL. That said, I still maintain the docs should still have example of usage; however, feel free to close this.

~Dave

**Comment by ajcvickers** [comment]
Covered by https://github.com/dotnet/efcore/issues/17508
