### ISSUE TITLE
Document DbSet not implementing IAsyncEnumerable

### ISSUE THREAD

**Issue by roji** [dotnet/EntityFramework.Docs#3101]
https://github.com/dotnet/efcore/issues/24041

**Comment by shravan2x** [comment]
Unsure if this is the documentation you're referring to already, but I'll include it here as another page to update - https://docs.microsoft.com/en-us/ef/core/miscellaneous/async .

**Comment by roji** [comment]
You're right - this was more about a breaking change note [here](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes), but the async page indeed should be updated as well.
