### ISSUE TITLE
I've got problems and questions about this tutorial on EF 6 Data Migrations

### ISSUE THREAD

**Issue by rfalanga** [dotnet/EntityFramework.Docs#3104]
Yeah, I've got a **LOT** of feedback/questions.

First, in your tutorial you show someone opening SQL Server Management Studio to look at the newly created database. I've got SSMS 18.8 installed. I opened it up. I don't see any more database, certainly not the new MigrationsCodeDemo.BlogContext database. How in heck do I see the new database in SSMS?

Second. I mistakenly added the Abstract column to the Blog table class. Yes, wrong class. Hey, I sometimes make mistakes. I'm human; it happens sometimes.  I've no idea how to undo it. And Package Manager Console demands that I finish applying AddPostAbstract before I do anything else. But I can't, because of the mistake I made. I tried doing a command `Delete-Migration`. That failed, telling me that there was no such command. Then I tried issuing `Remove-Migration`. That failed, too. Same error. I've no idea what to do. I've no guidance as to what to do. I'm stuck, not able to continue the tutorial because of the lack of help and direction, when making a mistake. So, how do I get out of this???????

You know, in your tutorials it would be **EXTREMELY HELPFUL** if you would consider putting in instructions as to how to fix errors a user might make when following along in the tutorial. I know that I am going to continue to make the odd mistake every now and then, following a tutorial. I would like to learn how to undo the boneheaded mistake I've made, so I may continue to learn.

Third. When working on Windows development, on a XAML based development, I will sometimes add the INotifyPropertyChanged interface to a model class, including that interface accordingly as well as including the code to raise a property changed event in the setter of a property. I've found this to be extremely helpful in such development. Anyway, I'd really like to know how implementing the INotifyPropertyChanged interface in a model class will affect EF data migrations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002d162b-8595-ad48-7ef8-2cd10194a3b4
* Version Independent ID: a29d6e0c-f9eb-86d9-f82e-0e9fc41b5a0d
* Content: [Code First Migrations - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@rfalanga Unfortunately, it's not really possible for us to general anticipate where and how people will make mistakes. However, we do try to add pointers and tips for common issues.
