### ISSUE TITLE
Oracle ef core 5 provider is available

### ISSUE THREAD

**Issue by VaclavK** [dotnet/EntityFramework.Docs#3115]
It seems there is now _full_ Oracle ef core 5 provider.. the page would seem to indicate support for 3.1 only

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9338b2a-93b1-595a-2e8e-86119e6eecbd
* Version Independent ID: 9890ab79-bc72-6075-4294-5450e6693668
* Content: [Database Providers - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks, submitted #3116 to update.
