### ISSUE TITLE
Potentially wrong information in article

### ISSUE THREAD

**Issue by Saborion** [dotnet/EntityFramework.Docs#3117]
The [Field-only properties](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=fluent-api#field-only-properties) section talks about how the field-only properties are different from shadow properties:
_"You can also create a conceptual property in your model that does not have a corresponding CLR property in the entity class, but instead uses a field to store the data in the entity. This is different from Shadow Properties, where the data is stored in the change tracker, rather than in the entity's CLR type."_

Near the end of the section it contains the following paragraph:
_"EF will attempt to find a CLR property with the given name, or a field if a property isn't found. If neither a property nor a field are found, a shadow property will be set up instead."_

This seems contradictory and I am curious if the text is wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e162696-b19f-d73f-8b1f-d1b4c3048b62
* Version Independent ID: a83e4fb5-e4ae-a46f-7248-487ea2679ac5
* Content: [Backing Fields - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/backing-field.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/backing-field.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@Saborion where do you see the contradiction? You can have (conceptual) properties which use a CLR property (the normal case), (conceptual) properties which use a CLR field (the first described above), and conceptual properties which use neither (shadow properties, the second described above).

**Comment by Saborion** [comment]
Apologies. I now read it "differently" and see what is meant. Thanks for taking the time to clarify for me. Closing the issue.
