### ISSUE TITLE
Are migration checks necessary? 

### ISSUE THREAD

**Issue by diberry** [dotnet/EntityFramework.Docs#3126]
Can we use Entity Framework to create the database and corresponding .NET objects but disconnect the migration checks after that? In an environment with only 1 database (for whatever reason), I want to create new tables and columns but not have EF throw errors that the EF model and the Db are out of sync. Can I turn that check off somehow? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations Overview - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
@diberry EF Core doesn't have any runtime checks for the migration state of the database.
To create or update the database you need to call `dotnet ef database update`

**Comment by diberry** [comment]
This is the text of the error which seems like it is doing active comparisons to the DB: "The model backing the 'TwitterBotContext' context has changed since the database was created. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=238269)."

**Comment by ErikEJ** [comment]
@diberry That is EF6, not EF Core

**Comment by diberry** [comment]
@ErikEJ Ok, where can I turn off this connection in EF6? Or ask the question?

**Comment by AndriySvyryd** [comment]
IN EF6 you can set the initializer to always update:
`Database.SetInitializer(new MigrateDatabaseToLatestVersion<MyDbContext, Configuration>());`
or to remove the checks:
`Database.SetInitializer(new NullDatabaseInitializer<MyDbContext>());`

Or implement your own.
