### ISSUE TITLE
Update Sample EF project from .NET 5 to .NET 6

### ISSUE THREAD

**Issue by ivanfarkas2** [dotnet/EntityFramework.Docs#3127]
# Update Sample EF project from .NET 5 to .NET 6

[EntityFramework.Docs/samples/core/Miscellaneous/NewInEFCore6/NewInEFCore6.csproj](https://github.com/dotnet/EntityFramework.Docs/blob/master/samples/core/Miscellaneous/NewInEFCore6/NewInEFCore6.csproj)

**Current:**
```xml
<PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFramework>net5.0</TargetFramework>
  <RootNamespace />
</PropertyGroup>
```

**Fixed:**
```xml
<PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFramework>net6.0</TargetFramework>
  <RootNamespace />
</PropertyGroup>
```

**Comment by ajcvickers** [comment]
It is currently by-design that you don't need the preview of .NET 6 to use the previews of EF Core 6. We should update this at the point that .NET 6 is required.

**Comment by ajcvickers** [comment]
Covered by #3023
