### ISSUE TITLE
Inheritance article adjustments

### ISSUE THREAD

**Issue by stdfst** [dotnet/EntityFramework.Docs#3130]
Hi! Please could you add something like "If you specify HasValue only for one derived entity then EF Core will not add a predicate over discriminator column in the query due to performance reasons and you should set IsComplete(false) until you add more derived entities". I have spent a lot of time figuring out why table is not filtered using configured discriminator and I have to set IsComplete(false) because my table currently contains only one kind of discriminator values. Thanks a lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10898c5-abee-1843-cfff-b2707f8a079a
* Version Independent ID: d9399618-488e-20b1-f707-35a191b95cc1
* Content: [Inheritance - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance)
* Content Source: [entity-framework/core/modeling/inheritance.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/inheritance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
The page currently states
> When querying for derived entities, which use the TPH pattern, EF Core adds a predicate over discriminator column in the query. This filter makes sure that we don't get any additional rows for base types or sibling types not in the result. This filter predicate is skipped for the base entity type since querying for the base entity will get results for all the entities in the hierarchy. When materializing results from a query, if we come across a discriminator value, which isn't mapped to any entity type in the model, we throw an exception since we don't know how to materialize the results. This error only occurs if your database contains rows with discriminator values, which aren't mapped in the EF model. If you have such data, then you can mark the discriminator mapping in EF Core model as incomplete to indicate that we should always add filter predicate for querying any type in the hierarchy. IsComplete(false) call on the discriminator configuration marks the mapping to be incomplete.

Do you think this is not enough?

**Comment by stdfst** [comment]
Yes, I have read this part of article twice. Let me show you short example:

```
public abstract class TelephoneDirectory {
	public int DirectoryId { get; set; } // Primary Key
	public int? Id { get; set; }         // IDs from different tables
	public int? Idtype { get; set; }     // Discriminator
}

public partial class ApplicantTelephoneDirectory: TelephoneDirectory {
	public Applicant Applicant;
}
```

```
protected override void OnModelCreating(ModelBuilder modelBuilder) {
	modelBuilder.Entity<TelephoneDirectory>(entity => {
		entity.HasDiscriminator<int?>(t => t.Idtype)
			.HasValue<ApplicantTelephoneDirectory>((int)TelephoneDirectoryIdTypeEnum.Applicant)
			.IsComplete(false);
	});

	modelBuilder.Entity<ApplicantTelephoneDirectory>(entity => {
		entity.HasOne(t => t.Applicant)
			.WithMany(a => a.ApplicantTelephoneDirectories)
			.HasForeignKey(t => t.Id);
	});
}
```
Querying without IsComplete(false):
```
this.Context.ApplicantTelephoneDirectories.Where(telephoneDirectory => telephoneDirectory.Id == applicant.ApplicantId);

SELECT [t].[DirectoryID], [t].[ID], [t].[IDType]
FROM [TelephoneDirectory] AS [t]
WHERE [t].[ID] = @__applicant_ApplicantId_0
```

With or without IsComplete (false), but if another entity is added and registered with HasValue:
```
SELECT [t].[DirectoryID], [t].[ID], [t].[IDType]
FROM [TelephoneDirectory] AS [t]
WHERE ([t].[IDType] = 7) AND ([t].[ID] = @__applicant_ApplicantId_0)
```

**Comment by ajcvickers** [comment]
@stdfst The text @AndriySvyryd posted above describes exactly the situation you show in your code.

**Comment by stdfst** [comment]
@ajcvickers But why do I need to specify .IsComplete(false) to get ([t].[IDType] = 7) condition inside the query when .HasValue<ApplicantTelephoneDirectory>((int)TelephoneDirectoryIdTypeEnum.Applicant) is configured for derived type? I am querying derived type, not a base.

**Comment by ajcvickers** [comment]
@stdfst I see; thanks.

@dotnet/efteam 

So here:

> This filter predicate is skipped for the base entity type since querying for the base entity will get results for all the entities in the hierarchy.

It's _technically_ not the base type if the base type is abstract and therefore doesn't have a discriminator value.

**Comment by stdfst** [comment]
Ohh... I didn't notice that, thanks a lot!
