### ISSUE TITLE
This documentation is old. I cannot find how to do this in VS2019!

### ISSUE THREAD

**Issue by akhyarkamili** [dotnet/EntityFramework.Docs#3135]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6327694-56ae-2d48-11c3-d6e1af422531
* Version Independent ID: c5280888-67b5-4c13-bdc6-3a0ec6bfbe20
* Content: [Code First to an Existing Database - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/existing-database)
* Content Source: [entity-framework/ef6/modeling/code-first/workflows/existing-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/workflows/existing-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
