### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dotnetnutty** [dotnet/EntityFramework.Docs#3148]
"will have no affect." should be "will have no effect."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f206b3c-87c1-ffca-4348-740c39ff3353
* Version Independent ID: 5c797f46-b6df-f052-eed4-911dd5f7e87e
* Content: [QueryableExtensions.AsNoTracking Method (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.queryableextensions.asnotracking?redirectedfrom=MSDN&view=entity-framework-6.2.0#overloads)
* Content Source: [EF/xml/System.Data.Entity/QueryableExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/QueryableExtensions.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)

**Comment by dotnetnutty** [comment]
Thanks, but I cannot find document https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.queryableextensions.asnotracking in github.com.
