### ISSUE TITLE
IndexBuilder.HasName is now obsolete

### ISSUE THREAD

**Issue by danmck5** [dotnet/EntityFramework.Docs#3150]
If your project includes migrations generated prior to EF Core version **2.0.0**, you can safely ignore the warning in those files and suppress it by adding #pragma warning disable 612, 618.

Should this not be prior to EF Core version **5.0.0**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf4e07c-25f8-ad59-fde6-3629e2c4e8d7
* Version Independent ID: df8c8aea-9f7d-db72-18b3-bac134acfd9a
* Content: [Breaking changes in EF Core 5.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes)
* Content Source: [entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@danmck5 2.0.0 is correct. In 2.1 we started scaffolding the pragmas automatically.
