### ISSUE TITLE
ADD references should be AAD

### ISSUE THREAD

**Issue by danmiser** [dotnet/EntityFramework.Docs#3153]
[Enter feedback here]
The link and content title refer to "ADD", when it should be "AAD"

Example: Connection interception for SQL Azure authentication using ADD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9a8e9e-a397-64b9-419d-fbcf525c3698
* Version Independent ID: f10c27f0-4b5b-c2b7-dd32-fac7b0d8060e
* Content: [Interceptors - EF Core](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors)
* Content Source: [entity-framework/core/logging-events-diagnostics/interceptors.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/logging-events-diagnostics/interceptors.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks, fixed.
