### ISSUE TITLE
Add link to complete sample to Handling Concurrency Conflicts

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/EntityFramework.Docs#3160]
Once @JeremyLikness  PR https://github.com/dotnet/AspNetCore.Docs/pull/21576 merges, add link to a complete example of handling conflicts.

@JeremyLikness   please review https://docs.microsoft.com/en-us/ef/core/modeling/concurrency
Is that how we really want to show Concurrency Tokens? 

SQLite doesn't have RowVersion support

Your approach is so much cleaner. It's rare you'd only want to add concurrency to one prop.  And what happens when you migrate the model and add another prop than needs concurrency checking?

Per doc: For example, we may want to configure `LastName `on `Person `to be a concurrency token.

That sounds like bad advice. Why would you only care about `LastName` and not firstName, address, phone, etc? What if new properties are added that need concurrency checking and you forget to decorate them with the concurrency attribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649fbab8-b960-6873-14bf-188d14757fee
* Version Independent ID: f5ee3135-54c8-689c-e28b-b203b376bd6f
* Content: [Handling Concurrency Conflicts - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/concurrency)
* Content Source: [entity-framework/core/saving/concurrency.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by JeremyLikness** [comment]
@Rick-Anderson RowVersion is the recommended way if/when supported. For SQLite, @bricelam has [this solution](https://www.bricelam.net/2020/08/07/sqlite-and-efcore-concurrency-tokens.html).

**Comment by JeremyLikness** [comment]
@Rick-Anderson is there an action you are waiting on me for here?

**Comment by Rick-Anderson** [comment]
@JeremyLikness no, https://github.com/dotnet/AspNetCore.Docs/pull/21576 will merge in a few day. If you have time, take a look at [Part 8, Razor Pages with EF Core in ASP.NET Core - Concurrency](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-5.0&branch=pr-en-us-21576&tabs=visual-studio)

This page,  [Handling Concurrency Conflicts - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/concurrency), will link to [Conflict detection in EF Core](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-5.0&branch=pr-en-us-21576&tabs=visual-studio-code#conflict-detection-in-ef-core)

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency#conflict-detection-in-ef-core

Because it's merged, you need to remove `.review` from the URL.

**Comment by JeremyLikness** [comment]
@Rick-Anderson it looks good to me. I don't have any updates or changes to suggest.
