### ISSUE TITLE
Update Concurrency Tokens

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/EntityFramework.Docs#3161]
Outline

# Introduction

There are three commonly used (recommended?) approaches to to configure concurrency tokens. For SQL Server, `<xref:System.ComponentModel.DataAnnotations.TimestampAttribute>` or the equivalent Fluent API <xref:Microsoft.EntityFrameworkCore.Metadata.IColumn.IsRowVersion> is the  recommended approach.

Move Configuration down, it shouldn't be featured.

Timestamp divided by rowversion doesn't make sense, doesn't MT. Change to

# Timestamp Attribute and the IsRowVersion method

Clean up discussion
[rowversion ](https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql)

# ConcurrencyCheck attribute and IsConcurrencyToken method.

This approach has the following problems:

* Concurrency is only verified for the specified property.
* Does not automatically protect the entity when new properties are added.
* Can be applied to multiple properties, but that generates a `Where` clause for each property that can lead to performance issues.
*  `<xref:Microsoft.EntityFrameworkCore.Metadata.IProperty.IsConcurrencyToken>`

# Using a GUID or other unique identifier

This approach works with any provider.

Show the approach used [here](https://github.com/dotnet/AspNetCore.Docs/pull/21576/files#r595461419) in the updated RP/EF tutorial.

#3160 is related and has similar problems

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041e7a47-a632-132a-3c9e-db46e3782a63
* Version Independent ID: a5de9c4c-56fe-416e-0801-f6acd061f25e
* Content: [Concurrency Tokens - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/concurrency?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/concurrency.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
@AndriySvyryd please review. cc @JeremyLikness

**Comment by JeremyLikness** [comment]
Looks good to me, as well as the linked proposal.

**Comment by JeremyLikness** [comment]
@Rick-Anderson LGTM. Recommend we can close this issue.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson LGTM. Recommend we can close this issue.

Can you keep it open? I'd like to update it with my outline above with `@AndriySvyryd` approved. Suggesting ` [ConcurrencyCheck]` is problematic as I outlined above.

I'll try to get this completed in the next month.

**Comment by JeremyLikness** [comment]
Yes. Makes sense, thanks.

**Comment by roji** [comment]
@Rick-Anderson I think I've done the above in #4093, so I'll be closing this. Of course post back if you think anything is still missing/bad.
