### ISSUE TITLE
Availability of HTML version of the documantion

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/EntityFramework.Docs#3164]
Is it possible to download an HTML version of the documantion? Since the PDF version has an issue with viewing sections using Javascript.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ffc114-df51-0be7-8972-6fcead14e011
* Version Independent ID: 94c34571-7314-aab1-7898-93ac6d0f3430
* Content: [Tracking vs. No-Tracking Queries - EF Core](https://docs.microsoft.com/en-gb/ef/core/querying/tracking)
* Content Source: [entity-framework/core/querying/tracking.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/tracking.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
@PingPongSet  can you open this issue in https://github.com/MicrosoftDocs/feedback/issues ?
Or I can transfer it for you. This impacts all https://docs.microsoft.com/ docs and is a site issue, not repro specific. Any easy way to open a site issue is by selecting **Site Feedback** at the bottom of the page.

![image](https://user-images.githubusercontent.com/3605364/111857508-0a2c8200-88d6-11eb-84fa-6586bdc45239.png)

I'm pretty sure there's currently an open issue for this.

**Comment by PingPongSet** [comment]
Thanks. An issue created https://github.com/MicrosoftDocs/feedback/issues/3577
