### ISSUE TITLE
AsQueryable() with or without in Removing relationships

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/EntityFramework.Docs#3166]
The line below without `AsQueryable()` also works.

                var post = blog.Posts.First();

Is `AsQueryable()` optonal in the code below?

            #region RemovingRelationships
            using (var context = new BloggingContext())
            {
                var blog = context.Blogs.Include(b => b.Posts).First();
                **var post = blog.Posts.AsQueryable().First();**

                blog.Posts.Remove(post);
                context.SaveChanges();
            }
            #endregion

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f0fb981-4dec-7ff7-817b-6606f620b875
* Version Independent ID: c7517e7d-f011-a24c-53da-913771913998
* Content: [Saving Related Data - EF Core](https://docs.microsoft.com/en-gb/ef/core/saving/related-data)
* Content Source: [entity-framework/core/saving/related-data.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
The AsQueryable above doesn't do anything and can be removed - will search and remove these occurrences in the samples.
