### ISSUE TITLE
Self referencing link

### ISSUE THREAD

**Issue by Rubidium37** [dotnet/EntityFramework.Docs#3175]
At the beginning of "Enabling Migrations" chapter, a note ends with a link ("http://go.microsoft.com/fwlink/?LinkId=238269"), that when clicked redirects to the source page (landing to "https://docs.microsoft.com/en-US/ef/ef6/modeling/code-first/migrations/?redirectedfrom=MSDN")
The link is immediately after "Consider using Code First Migrations to update the database".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002d162b-8595-ad48-7ef8-2cd10194a3b4
* Version Independent ID: a29d6e0c-f9eb-86d9-f82e-0e9fc41b5a0d
* Content: [Code First Migrations - EF6](https://docs.microsoft.com/en-US/ef/ef6/modeling/code-first/migrations/?redirectedfrom=MSDN#feedback)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
