### ISSUE TITLE
IEntityMaterializerSource has breaking changes which aren't listed

### ISSUE THREAD

**Issue by ryoder42** [dotnet/EntityFramework.Docs#3179]
The interface Microsoft.EntityFrameworkCore.Query.IEntityMaterializerSource has lost a method, CreateReadValueExpression, which wasn't even declared as deprecated in 3.1. 

The associated implementation, Microsoft.EntityFrameworkCore.Query.EntityMaterializerSource, has moved into the Microsoft.EntityFrameworkCore.Query.Internal namespace and now indicates it shouldn't be used.

I had been using CreateReadValueExpression to automatically specify all our DateTime fields as Utc. After upgrading to v5, this is broke and I'm not sure how to resolve.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf4e07c-25f8-ad59-fde6-3629e2c4e8d7
* Version Independent ID: df8c8aea-9f7d-db72-18b3-bac134acfd9a
* Content: [Breaking changes in EF Core 5.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes)
* Content Source: [entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Based on the latest version right before 3.x - 2.2.8/2.1.16 This is what docs say about it
https://github.com/dotnet/efcore/blob/01da710cdeff0431fc60379580aa63f335fbc165/src/EFCore/Metadata/Internal/IEntityMaterializerSource.cs#L17-L32

The XML docs clearly indicate that the API can be removed at any point without any notice or obsolete. It shouldn't be used from user code. If you feel that you have genuine use of that particular API, file an issue on https://github.com/dotnet/efcore repository with problem you are trying to solve, (the larger problem which caused to use the API, not the problem of not having that particular API).

**Comment by ryoder42** [comment]
That's interesting, but I'm using 3.x and trying to upgrade to 5.x. It appears in 3.x it moved and does not have that warning and the method is not marked obsolete https://github.com/dotnet/efcore/blob/release/3.1/src/EFCore/Query/IEntityMaterializerSource.cs

So it still seems like going from 3.x to 5.x it is a breaking change. Strangely it would seem going from 2.x to 5.x this would not be a breaking change.

**Comment by ajcvickers** [comment]
@ryoder42 See [Specify the DateTime.Kind when reading dates](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#specify-the-datetimekind-when-reading-dates) for how to manipulate DateTime values as they come out of the database.

**Comment by ryoder42** [comment]
@ajcvickers That's exactly what I was looking for, thank you!

**Comment by ajcvickers** [comment]
Discussed in triage; this was never intended to be public before it was removed.
