### ISSUE TITLE
Mention DbSet is optional when entity is configured in OnModelCreating

### ISSUE THREAD

**Issue by mrlife** [dotnet/EntityFramework.Docs#3183]
When calling `modelBuilder.Entity()` in `OnModelCreating()`, the related `DbSet` is not required. Can this be mentioned here? If it is mentioned somewhere in the docs, I couldn't find it.

Also note that [this docs page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.onmodelcreating?view=efcore-5.0) implies that it's required.

e.g. the following is sufficient to create the table for `MyEntity`

```
//public DbSet<MyEntity> MyEntities { get; set; }

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity(typeof(MyEntity)).HasOne(nameof(MyEntity2)).WithMany();
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3437af67-630b-d28f-7fbd-3eedf647f22a
* Version Independent ID: 6c44f987-19a7-c256-e8fa-10378e61cf6e
* Content: [Creating and configuring a model - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/)
* Content Source: [entity-framework/core/modeling/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
See https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#including-types-in-the-model
