### ISSUE TITLE
highlighted wrong line

### ISSUE THREAD

**Issue by DickBaker** [dotnet/EntityFramework.Docs#3189]
on Partition keys https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli#partition-keys
the text describes the WithPartitionKey call, but code highlights the Console.Write statement after that invocation

BTW rather than having 3 separate Console.Write* statements imho it would also be better to have just one using \n formatters
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738deb7b-d752-f628-3860-fe53891cadb0
* Version Independent ID: e0a18db9-d605-2a78-b77a-d22375dcfd4e
* Content: [Azure Cosmos DB Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/cosmos/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/cosmos/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks, submitted #3190 to clean this up.
