### ISSUE TITLE
Dynamically constructed queries

### ISSUE THREAD

**Issue by snappyfoo** [dotnet/EntityFramework.Docs#3196]
https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics

I found this well written and interesting, thank you. 

I have a suggestion about the dynamic constructed query section. I found the comparison between the constant version and the parametrised version slightly misleading, as it gives the impression that the reason the constant one is poorer is because of the use of expression factory methods rather than the much simpler compile-time expression that the parametrised version uses. In reality the former approach can be rewritten to parametrise the url too.*

I fully appreciate that the example is presented just for simplicity and not as an actual good use case, but few would actually use the factory method when the type is known at compile time. Therefore by introducing the concept of building expressions in such a way and then writing it off as the poorer approach, doesn’t help those who might have a genuine need for constructing an expression that way. And for them, knowing how to correctly parametrise the expression would be more useful than to point to a compile-time expression which they can’t use. 

So, to be clear, I fully appreciate that even the former approach rewritten to parametrise the url would be unnecessary in that example- the other parameterised version is always simpler. But since we are suspending our disbelief for this example, I don’t think it’s right to leave it ‘hanging’ there without also mentioning how you could improve the former, should there be some reason to stick with that approach. For me, comparing the performance of the two differently-constructed-but-both-parameterised versions would then be yet even more interesting!

Thanks for reading

\* I think something like:
`Expression<Func<string>> urlExp = () => url;`
and `urlExp.Body` instead of the ConstantExpression

**Comment by roji** [comment]
Thanks for the feedback!

> it gives the impression that the reason the constant one is poorer is because of the use of expression factory methods

I've indeed tried to make it clear that dynamically-constructed queries (with expression factory methods) don't inherently cause performance issues, though it's very easy to do so. See the following sentence:

> In principle, if done correctly, dynamically-constructed queries can be just as efficient as regular ones (although it's not possible to use the compiled query optimization with dynamic queries). In practice, however, they are frequently the source of performance issues, since it's easy to accidentally produce expression trees with shapes that differ every time.

Does that not more or less address your concerns? The reason this section is somewhat negative on dynamic queries, is that in  the history of EF Core we've seen many users constructing expression trees manually - and get themselves into all sorts of problems - when that approach wasn't necessary at all. This is also why I didn't find it necessary to show proper parameterization with dynamically-constructed trees.

> For me, comparing the performance of the two differently-constructed-but-both-parameterised versions would then be yet even more interesting!

If the dynamically-constructed expression tree is identical in shape to the non-dynamic one produced by the compiler, then there would be no perf difference at all; EF Core would see the exact same incoming query tree, and translate it it the same way.

**Comment by snappyfoo** [comment]
Thank you, yes on reading more closely and with your reply, I think you have covered it well enough- sorry to have wasted a bit of time. The comment about the shame shaped queries being equal is good to know too. I tried to do my own benchmarking after this and found the same, though new to benchmarking so the extra confirmation is appreciated.

**Comment by roji** [comment]
@snappyfoo no worries, good to have people reading this with a critical eye and asking questions. At the end of the day, as far as querying goes, EF Core is a LINQ provider; that means that its input is an expression tree. How that expression tree was constructed isn't very important (EF doesn't even know anything about that), which is why the perf is the same.
