### ISSUE TITLE
'Unauthorized' error when installing dotnet-ef tools

### ISSUE THREAD

**Issue by NotUnlikeTheWaves** [dotnet/EntityFramework.Docs#3199]
Hello, trying to install the dotnet-ef with the supplied command `dotnet tool install --global dotnet-ef` gives me the following error message:

```
PS C:\dev\CIT> dotnet tool install --global dotnet-ef
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/garansys/_packaging/GaransysNuGet%40Local/nuget/v3/index.json. [C:\Users\myname\AppData\Local\Temp\mj5ooqru.4k4\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\Hidde\AppData\Local\Temp\mj5ooqru.4k4\restore.csproj]
The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```
However, installing a [specific version](https://www.007ffflearning.com/post/dotnet-tool-install-dotnet-ef-failing-with-unauthorized/) worked fine for me:

```
PS C:\dev\CIT> dotnet tool install --global dotnet-ef --version 3.1.13
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.1.13') was successfully installed.
```

My request is to review the install instructions and see if they still hold up

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1bdeea-0ebc-04ff-5b58-1020ad9cd72a
* Version Independent ID: 847fe92a-2940-afbf-b2ee-e68f8a8060be
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/cli/dotnet)
* Content Source: [entity-framework/core/cli/dotnet.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment]
Looks like something's wrong with your NuGet config. Add `--ignore-failed-sources` to work around the issue.

The command with `--version` is short-circuiting (due to either a cache or by finding the exact version in another package source first), so it succeeds.

**Comment by NotUnlikeTheWaves** [comment]
Sorry for the late reply, but thanks! That works!
