### ISSUE TITLE
Multiple parameter examples for FromSqlRaw and related

### ISSUE THREAD

**Issue by eino-makitalo** [dotnet/EntityFramework.Docs#3203]
You should have examples also with multiple parameters FromSqlRaw...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1289d5-8364-18a4-3445-6bba05c6854b
* Version Independent ID: 2680e647-f64a-7991-f821-3b5e2a845960
* Content: [Raw SQL Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters)
* Content Source: [entity-framework/core/querying/raw-sql.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/raw-sql.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by Rezakazemi890** [comment]
Fixed in [This PR](https://github.com/dotnet/EntityFramework.Docs/pull/4660)

**Comment by ajcvickers** [comment]
Closing as this change does not add value.
