### ISSUE TITLE
Typo in link "https://ak.ms/AA6h122"

### ISSUE THREAD

**Issue by vabka** [dotnet/EntityFramework.Docs#3206]
Typo in link "https://ak.ms/AA6h122" -> "https://aka.ms/AA6h122"

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: b21434a2-9f80-b04b-f8d7-b63eee000407
* Version Independent ID: 78f0bdb8-6553-a7cf-450f-167d522160d0
* Content: [SqlServerDbContextOptionsBuilder.UseRowNumberForPaging Метод (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/ru-ru/dotnet/api/microsoft.entityframeworkcore.infrastructure.sqlserverdbcontextoptionsbuilder.userownumberforpaging?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs.ru-ru/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Fixing directly in API docs here https://github.com/dotnet/EntityFramework.ApiDocs/pull/99
