### ISSUE TITLE
Typo in docs for AddInterceptors(IEnumerable<IInterceptor>)

### ISSUE THREAD

**Issue by cesarsouza** [dotnet/EntityFramework.Docs#3211]
"I will be registered as an interceptor"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da293bba-ddc0-d2b6-347d-6b6763f287a3
* Version Independent ID: aa68fce0-82e7-679d-c76a-77ae34ea0055
* Content: [DbContextOptionsBuilder.AddInterceptors Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder.addinterceptors?view=efcore-5.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
This has already been [fixed in the source](https://github.com/dotnet/efcore/blob/main/src/EFCore/DbContextOptionsBuilder.cs#L590), but xmldoc changes are typically only pushed live at release.
