### ISSUE TITLE
Document how to make owned types non-nullable

### ISSUE THREAD

**Issue by lostincomputer** [dotnet/EntityFramework.Docs#3215]
I suggest documenting how to make an owned type non-nullable and what the impact is. The biggest advantage of making an owned type non-nullable is Entity Framework makes the columns of the owned type non-nullable as well.

For example if I let Entity Framework to generate the DB schema for this:

```
[Owned]
class OwnedType
{
   public int Value { get; set; }
}

class Entity
{
    [Required]
    public OwnedType NonNullableOwnedType { get; set; }

    public OwnedType NullableOwnedType { get; set; }
}
````

The schema will be

```
CREATE TABLE Entity (
    NonNullableOwnedType_Value int NOT NULL,
    NonNullableOwnedType_Value int NULL
)
```

The second advantage of having a non-nullable column is it gives me the ability to set the column's default value thru EF's `.HasDefaultValue()` method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
We do have this tip in the article: "The owned entity type can be marked as required, see [Required one-to-one dependents](https://docs.microsoft.com/en-us/ef/core/modeling/relationships#one-to-one) for more information."
