### ISSUE TITLE
I cannot the DB first wizard to work, following the directions on the docs.microsoft.com site.

### ISSUE THREAD

**Issue by BrianMinister** [dotnet/EntityFramework.Docs#3221]
Something is missing because I am now on my 3rd computer, with up-to-date libraries, using .Net Core 5, the database first process fails with 
![image](https://user-images.githubusercontent.com/4028832/115782180-fc5c9780-a380-11eb-851c-71f869897ee0.png)

I have added all the possible libraries and I still cannot get this to run.

![image](https://user-images.githubusercontent.com/4028832/115782344-3168ea00-a381-11eb-8bff-8f03257e8bfa.png)

What is missing, and where was it mentioned in the document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63be9b09-2dde-819c-72a9-874182a92113
* Version Independent ID: 0ef66141-904a-34b2-b2a1-b090c5d62339
* Content: [Database First - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/workflows/database-first)
* Content Source: [entity-framework/ef6/modeling/designer/workflows/database-first.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/designer/workflows/database-first.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
You are looking at EF 6 documentation but using EF Core 5.0, those are different products.
