### ISSUE TITLE
Suggestion to add note about EF Core Power Tools to this page

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/EntityFramework.Docs#3229]
As a Tip perhaps?

**Comment by roji** [comment]
@ErikEJ which page are we on? :)

**Comment by ErikEJ** [comment]
https://docs.microsoft.com/da-dk/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli 

I reported via the Feedback link, but went into the Android app.. so I guess that caused the context to lost.
