### ISSUE TITLE
Using for Point datatype unclear

### ISSUE THREAD

**Issue by sterneric** [dotnet/EntityFramework.Docs#3235]
[Enter feedback here]
For this line of code

    public Point Location { get; set; }

When I include it in my project Point is not defined.  I'm assumming

using System.Drawing;

but really I don't know 

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dcf82b-f177-e91b-96a5-67f2f57bd6c4
* Version Independent ID: 89c0803f-570f-07a6-6dc2-285678712c86
* Content: [Spatial Data - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/spatial)
* Content Source: [entity-framework/core/modeling/spatial.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/spatial.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment]
The namespace (`NetTopologySuite.Geometries`) is mentioned earlier in the article

**Comment by sterneric** [comment]
thanks Brice
