### ISSUE TITLE
InitializeComponent and Grid_Loaded

### ISSUE THREAD

**Issue by VKChiuselli** [dotnet/EntityFramework.Docs#3239]
Hi,
I took your code but it gives some errors:
  InitializeComponent(); doens't load the window
productsDataGrid and categoryDataGrid aren't linked from the xaml, it says that they don't exist in the current context.
(first two maybe are connected).
Chapter: "Add Code that Handles Data Interaction"
In your code, you don't show the method:
   private void Grid_Loaded(object sender, RoutedEventArgs e)
        { }

       
It appears when I do double click on "Loaded" on grid.

Cheers
Vittorio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a691101f-b7ea-4539-3745-6d9b0f5e317f
* Version Independent ID: 8f488a69-cedf-9c45-f977-23b3d8abd3df
* Content: [Get Started with WPF - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/wpf)
* Content Source: [entity-framework/core/get-started/wpf.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/wpf.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by JeremyLikness** [comment]
Hi @VKChiuselli can you provide more details about your setup? I just re-walked the tutorial and followed it exactly, and it worked fine.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
