### ISSUE TITLE
Feddback on Page : https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.addasync?view=efcore-5.0

### ISSUE THREAD

**Issue by smaldos64** [dotnet/EntityFramework.Docs#3241]
Hi

It goes beyound my understanding, why you don't provide us readers of your documentation with some useful examples on calling your functions. Liker here I am caught in details I can't use to much. Unfortunately I have faced this problem on numerous occasions. 
As I am not an expert in Asp.Net Core / Entity Framework Core details (I am a programmer using Asp.Net Core), I very often give up reading your documenation and tend to read it elsewhere, where people being more clever than me on Asp.Net Core details have provided useful examples for a specific interface function. 
As I see it to be able to read your documentation you have to be an expert on Asp.Net Core / Entity Framework Core isssues before diving into yopur dodumentation. I am a teacher in Denmark teaching young people in Asp.Net Core issues, and this is quite a difficult job, when I am not able to read your documentation on my own. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 116fe70c-699e-7e75-0132-3e41c81f862b
* Version Independent ID: 4f5b845c-3094-8653-0e75-8ad85b2c949c
* Content: [DbContext.AddAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.addasync?view=efcore-5.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
Have you looked at the docs page rather than the API docs?

https://docs.microsoft.com/da-dk/ef/core/saving/basic#adding-data

**Comment by ajcvickers** [comment]
See also https://github.com/dotnet/efcore/issues/17508
