### ISSUE TITLE
Document behavior of AsSplitQuery() when subquery has unstable ordering

### ISSUE THREAD

**Issue by angelaki** [dotnet/EntityFramework.Docs#3242]
I'm sorry I cannot fully reproduce this error yet, but as I already described in a just created stackoverflow (https://stackoverflow.com/questions/67169707/azure-sql-queries-with-same-order-returning-different-resultsets) Azure SQL _somehow_ seams to have problem _keeping_ the order for some queries. This sure breaks the logic of your "AsSplitQuery()" so that I needed to remove it completely and live with the performance decrease.

Is this maybe an already known misbehavior? Is there something I can do to make it work? Anyways, I thought you should know this.

Edit: I now know that SQL Server is not guaranteed to keep the order between queries for not unique columns! The order is determined based on indexes, columns etc.. But what to do in these cases? Guess I'm not the last one to fall in this pit. I now append a `.ThenBy(e => e.UniqueIdentifier)` everytime a order is attached. But it's a pretty technical reason causing this issue and will sure confuse several persons out there!

I don't know how complex this could be under the hood, but would it be possible to always order by entities PK **last** if any / no orders are used? Guess it's getting pretty tricky right now but it is a terrible pitfall right now!

**Comment by angelaki** [comment]
Yes, guess you're right. But since this problem only occurs with `AsSplitQuery` and **is** hard for users to understand why not just add an opt-in overload that will ensure deterministic results for the `AsSplitQuery` method? I think that would be a nice solution.

**Comment by angelaki** [comment]
Ok, you're absolutely right. But still: how about an opt-in extension method to ensure the order for inner and outer queries independent on the use sortings? But I'm already noticing ... you don't like the idea of it 😉

**Comment by smitpatel** [comment]
As you know - we don't like the idea of it because it doesn't educate users to write proper queries. Instead it introduce a hack for users so that they can continue writing bad queries and EF Core correcting under the hood. And an opt-in extension method means they still have to learn which method to use. So if we are educating users then why not send them in right direction rather than in a hack direction. So we will update docs to mention this so users write nicer queries.
