### ISSUE TITLE
Update-Database -Migration 0

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/EntityFramework.Docs#3253]
Is [this ](https://stackoverflow.com/a/50657539/502537) worth mentioning? 

```
Update-Database -Migration 0
Remove-Migration
Remove-Migration
Remove-Migration  // Repeat for each migration
```

Then create new migration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d4bb699-8a1f-b908-65f8-3c3dbbea25e7
* Version Independent ID: 9d82c393-ac60-0526-1779-f51c8ce16102
* Content: [Managing Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/managing.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/managing.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment]
[The accepted answer](https://stackoverflow.com/a/16082497/475031) is a much simpler solution to the problem and the one I'd recommend.
