### ISSUE TITLE
M1 Mac VS2019 + EF CLI Migrations Error 35 while updating database

### ISSUE THREAD

**Issue by Jamiermusic** [dotnet/EntityFramework.Docs#3254]
I hope this is posted at the right place. If not please shoo me. 
Googled the issue, but couldn't find any relatable solutions and after a few hours of being stuck... Here I am. 

Any help would be greatly appreciated!  

**Setup**
1. Successfully added migrations to project, but get error 35 when trying to update database. 
2. Connected fine to docker server via azure and used the same credentials. 
3. I tried with both hard coded username and password into the connection string.

**Tools**
- Visual Studio 2019 | M1 Mac | v8.9.10 (build 4)
- Microsoft.AspNetCore.Razor.Runtime (2.2.0)
- EntitiyFrameworkCore (5.0.6)
- EntitiyFrameworkCore.SqlServer (5.0.6)
- EntitiyFrameworkCore.Tools (5.0.6)

**Connection String**

```
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=localhost:1433; Database=InAndOutMVC; Trusted_Connection=True; MultipleActiveResultSets=True;"
  },
```

**Terminal Error**

`A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)`

**Comment by AndriySvyryd** [comment]
@Jamiermusic Are you able to connect to it without EF Core, using just SqlClient for example?

If yes, then please provide a small repro project and dockerfile.

**Comment by Jamiermusic** [comment]
@AndriySvyryd Do you mean a normal SQL connection in VS or via an SQL client outside of VS?

**Comment by AndriySvyryd** [comment]
In VS, in your project.

**Comment by Jamiermusic** [comment]
I  managed to solve it :) Was just a case of wrong seperation between the server and port. 

`localhost:1433` should have been `localhost,1433`.

Thank you for your time either way! Hope you have a good weekend :)

**Comment by danilozanaga** [comment]
I am having this problem too

Mac M1 Mini
Docker desktop
Azure data studio connects ok to localhost (without) port

appsettings

"ConnectionStrings": {
    "Default": "Server=localhost,;Database=ProEventos;User Id=sa;Password=123456@a;"
  },

If i put this con string in azure data studio, with master database, it connects with no problem 

when executing in terminal dotnet ef database update, throws connection error
