### ISSUE TITLE
Basic Inheritance: Had a bit of a mare trying to Ignore a base class to get EF inheritance of same named classes to work.

### ISSUE THREAD

**Issue by tyeth** [dotnet/EntityFramework.Docs#3270]
Useful guide, but the big issue some people will come up against regarding Inheritance is trying to use a common model with the same type name + collection from different projects. 

I had a Scanlog class and dbcontext in all projects (shared project) and then a project specific replacement (context and scanlog), both with contexts with collections called ScanLogs. **_The contexts point at different databases!!!_** I wanted my Super classes ScanLog to inherit from shared class.
I could not get EF to play ball until I used modelBuilder.Ignore(typeof(SharedProject.Scanlog) as the base context was initialising it's scanlog collection/entities first and then complaining the two collections weren't related by a primary key.
 By using NEW on my super classes collection, and modelBuilder.Ignore in that classes onModelCreating method I was able to achieve the desired result of basic inheritance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10898c5-abee-1843-cfff-b2707f8a079a
* Version Independent ID: d9399618-488e-20b1-f707-35a191b95cc1
* Content: [Inheritance - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance)
* Content Source: [entity-framework/core/modeling/inheritance.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/inheritance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@tyeth Can you post code showing what you ultimately ended up doing?
