### ISSUE TITLE
Command is not working

### ISSUE THREAD

**Issue by ajaypathak** [dotnet/EntityFramework.Docs#3272]
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues
i am getting following error
C:\Users\desktop\source\repos>dotnet tool install --global dotnet-ef
error NU1101: Unable to find package dotnet-ef. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

C:\Users\desktop\source\repos>

**Comment by roji** [comment]
@ajaypathak the dotnet-ef tool is [available on nuget.org](https://www.nuget.org/packages/dotnet-ef) - it seems your nuget configuration somehow excludes that default feed. Check your nuget configuration ([this page should help](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)).
