### ISSUE TITLE
Document pre-convention model configuration

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/EntityFramework.Docs#3278]
See https://github.com/dotnet/efcore/issues/12229, https://github.com/dotnet/efcore/issues/3867, https://github.com/dotnet/efcore/issues/10784

**Comment by ajcvickers** [comment]
Note: Update https://aka.ms/efcore-docs-pre-convention when this is done.

**Comment by ajcvickers** [comment]
Updated AKA link
