### ISSUE TITLE
Error in EF Tutorial

### ISSUE THREAD

**Issue by JN-LT** [dotnet/EntityFramework.Docs#3285]
Do I just ignore the "SQLite Error 14: 'unable to open database file'" error message, or was that not supposed to happen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488629d4-9bd2-42b5-4644-34e3f2baee59
* Version Independent ID: b38b9d14-6bad-12e0-8d2d-24b50bc4977e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/overview/first-app.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/first-app.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by JN-LT** [comment]
![image](https://user-images.githubusercontent.com/55243838/121053787-54106000-c781-11eb-947a-254b87ea5260.png)

**Comment by Cameron-Gonzalez** [comment]
Did you ever figure this out? I was having the same issue.

**Comment by JN-LT** [comment]
> 
> 
> Did you ever figure this out? I was having the same issue.

Nope. I'm looking for a better tutorial.

**Comment by Rick-Anderson** [comment]
Is that a valid path for your OS? That's a windows path. 

change `=> options.UseSqlite(@"Data Source=C:\blogging.db");` to 
`=> options.UseSqlite(@"Data Source=blogging.db");`

**Comment by JN-LT** [comment]
I am on Windows, so that should be a valid path.

I am not an expert on Entity Framework, nor on GitHub. I was just trying to follow the tutorial on “https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=visual-studio”, but it didn’t work. So I entered my feedback as requested at the bottom of that page. I didn’t see anything in the tutorial about any other changes I would need to make.

Jeff Nygren
Software Engineer II

**Comment by ajcvickers** [comment]
@JN-LT Is it possible that you don't have permissions to create files in the root of C:?

**Comment by JN-LT** [comment]
I would guess that’s quite likely. Maybe the tutorial could be updated to suggest a better path for the db. Then noob users of the tutorial wouldn’t get stuck on this issue.

Jeff Nygren
Software Engineer II

**Comment by ErikEJ** [comment]
The issue is that there is no good general path, that cannot be misunderstood.

Like: C:\Users\<YourName>\<FolderName>

Opens up for a universe of misunderstandings.

**Comment by ErikEJ** [comment]
Or add code that detects the platform and sets a suitable connection string? 😂

**Comment by smitpatel** [comment]
Or just put a dummy path which never works so user can put a path which they have access to in the OS they have.
