### ISSUE TITLE
It doesn't work with EF 5.0

### ISSUE THREAD

**Issue by tetradog** [dotnet/EntityFramework.Docs#3295]
[Enter feedback here]
when i set HasForeignKey(intId) it doesn't work and only work with HasForeignKey(objNavigation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
@tetradog Could you provide more context on what `intId` and `objNavigation` are, what outcome you obtained with the former approach and what should we change in the documentation?
