### ISSUE TITLE
 Multiple DBContexts for Multiple Providers run at the same time

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/EntityFramework.Docs#3302]
Can Multiple DBContexts for Multiple Providers run at the same time for each of the scenario below mentioned on the article?

Using multiple context types
Using one context type

From the article, it seems only one DbContext, either SqlBlogContext or SqliteBlogContext, run at a time, not both.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b011c7a-3534-78e3-b491-addd96fb5ba1
* Version Independent ID: 371826c5-3ef2-4eef-32e9-d55c777cd9d3
* Content: [Migrations with Multiple Providers - EF Core](https://docs.microsoft.com/en-gb/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/providers.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/providers.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
Yes, you can use Multiple DBContexts for Multiple Providers at the same time
