### ISSUE TITLE
Request for code example for cases of memory leak in client evaluation via EF Core

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/EntityFramework.Docs#3304]
Is it possible to provide code examples for each case in the section "Potential memory leak in client evaluation", given its importance?

"Common causes and their solutions are as follows"
https://docs.microsoft.com/en-gb/ef/core/querying/client-eval#potential-memory-leak-in-client-evaluation

I read a few times, but cannot get it fully.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd35b912-445c-e801-7f70-de73839db80d
* Version Independent ID: e558a081-5397-1e3f-1d58-abea3f72cad6
* Content: [Client vs. Server Evaluation - EF Core](https://docs.microsoft.com/en-gb/ef/core/querying/client-eval)
* Content Source: [entity-framework/core/querying/client-eval.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/client-eval.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
@PingPongSet You don't need to understand exactly when it happens, just be aware of it. If EF Core detects code that can lead to a memory leak it will throw an exception.
