### ISSUE TITLE
Updating code generation for data binding results in error

### ISSUE THREAD

**Issue by PeterAdam** [dotnet/EntityFramework.Docs#3306]
Vague referring to edit points is useless.

Additional Steps in Visual Studio 2010 -> Find and replace the first occurrence of “HashSet” with “ObservableListSource”. This occurrence is located at approximately line 50. Do not replace the second occurrence of HashSet found later in the code.

Of course now there is only one occurence. Changing that leads to:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Compiling transformation: The type or namespace name 'ObservableListSource<>' could not be found (are you missing a using directive or an assembly reference?)	TTO4I3A	P:\Visual Studio Projects\2017\TTO4\TTO4\TTO4I3A\mTTO4I3A.Context.tt	509	

I can't believe it is so hard to databind to EF 6 with visual tools, anyway. Give back the sqlite dataset editor, and you will not see me again ever!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93ad154e-e7a6-0ce7-4bb3-8ea56532624b
* Version Independent ID: 19a924ea-6e54-0df8-ace6-702a5bdbb2bc
* Content: [Databinding with WinForms - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/winforms)
* Content Source: [entity-framework/ef6/fundamentals/databinding/winforms.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/databinding/winforms.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)

**Comment by PeterAdam** [comment]
I have made a bug report from the documentation web site via the Feedback button. What do you want to pull? I don't have a solution. Neither do I git mumbo-jumbo.
