### ISSUE TITLE
Just not smart enough to figure out how to add two options.  

### ISSUE THREAD

**Issue by sterneric** [dotnet/EntityFramework.Docs#3308]
[Enter feedback here]

Azure gives me a warning "Compiling a query which loads related collections for more than one collection navigation either via 'Include' or through projection but no 'QuerySplittingBehavior' has been configured"

So I find this page and I want to set the UseQuerySplittingBehavior  but I'm already setting UseNetTopologySuite

Current code

                optionsBuilder
                .UseSqlServer("...connectionstring...",
                x => x.UseNetTopologySuite());

And I'm lost.  I can't find an example or guess the correct syntax to set UseNetTopologySuite AND UseQuerySplittingBehavior  

Resorted to setting the option on each query but a global option, and a documented solution for others, will be great.

thanks
Eric 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43baa9f3-c415-c328-6c10-53aabaaec652
* Version Independent ID: 4e789a1b-aa88-d194-dc2e-0a23251250d7
* Content: [Single vs. Split Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries)
* Content Source: [entity-framework/core/querying/single-split-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/single-split-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
You can simply chain UseQuerySplittingBehavior after UseNetTopologySuite, as follows:

```c#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.UseSqlServer(@"<CONNECTION STRING>", o => o
        .UseNetTopologySuite()
        .UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery));
}

**Comment by sterneric** [comment]
thanks for the answer Andriy.  Sorry I was slow responding.  Including an
example will help other confused people (like me).

Eric
