### ISSUE TITLE
ef is not installable 

### ISSUE THREAD

**Issue by probabilty** [dotnet/EntityFramework.Docs#3310]
VS2019 windows 10
could not install ef
Install-Package : Could not install package 'Microsoft.EntityFrameworkCore.Sqlite 5.0.7'. You are trying to install this package into a project that 
targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that 
framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Sqlite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488629d4-9bd2-42b5-4644-34e3f2baee59
* Version Independent ID: b38b9d14-6bad-12e0-8d2d-24b50bc4977e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/overview/first-app.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/first-app.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
You need to target your application to .NET Core 3.0 or later, see https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms

If you need to target 4.7.2 then you need to specify 3.1.* as the Microsoft.EntityFrameworkCore.Sqlite package version when installing it.
