### ISSUE TITLE
Typo in Migrations Overview

### ISSUE THREAD

**Issue by bartoszluka** [dotnet/EntityFramework.Docs#3316]
There is a typo in [this section](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#excluding-parts-of-your-model) in a "Note". 
"This feature was introduced **EF in Core** 5.0" and I think it should be **in EF Core**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations Overview - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
@bartoszluka Could you make the change and submit a PR?

**Comment by bartoszluka** [comment]
sure
