### ISSUE TITLE
Typo in Designer TPH Inheritance

### ISSUE THREAD

**Issue by gusseleet** [dotnet/EntityFramework.Docs#3320]
In the last section (https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/inheritance/tph#use-the-model) the code reference `People`:

```
foreach (var person in context.People)
```

But there is no `People class`. I guess it should be `Person`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f84fb0-74ca-eae6-a9cf-7d1885af4573
* Version Independent ID: a8f7914d-65d3-68f9-8e39-5aaab67ef597
* Content: [Designer TPH Inheritance - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/inheritance/tph)
* Content Source: [entity-framework/ef6/modeling/designer/inheritance/tph.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/designer/inheritance/tph.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by gusseleet** [comment]
This is a bit off topic, but still somewhat related to the docs. Is it not possible to use "Generated database from model" when using the example project and inheritance? Nothing is mention in the docs, but when I followed the guide everything worked, but later generated the database from the model it stopped working (it seems it expect an extra table between the inheritance).

**Comment by AndriySvyryd** [comment]
> But there is no People class. I guess it should be Person?

DbSet property names on the context are pluralized versions of the corresponding class name.

> Nothing is mention in the docs, but when I followed the guide everything worked, but later generated the database from the model it stopped working (it seems it expect an extra table between the inheritance).

There might be an error in the model. Review it carefully or start from scratch.

**Comment by gusseleet** [comment]
I am certain there was no problem in the model. It is rather ready to reproduce. After creating the model as in the guide, you pick the option to generate database from model. When files are generated the maps to property changes and expect a table to exist (Person_Student for example).

**Comment by AndriySvyryd** [comment]
@ryanbrandenburg cc
