### ISSUE TITLE
Scenarios on defining and setting state of an entity 

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/EntityFramework.Docs#3322]
The state of an entity has been defined like below in the article and code sample, is it possible to elaborate on when it is required with examples.

    public abstract class EntityBase
    {
        [NotMapped]
        public bool IsNew { get; set; }

        [NotMapped]
        public bool IsDeleted { get; set; }

        [NotMapped]
        public bool IsChanged { get; set; }
    }

https://docs.microsoft.com/en-gb/ef/core/saving/disconnected-entities#trackgraph

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9826f28-46b2-e845-f1bf-5cbc2d940208
* Version Independent ID: 9c4a46cf-daa2-0e14-7ff1-c195db237cd0
* Content: [Disconnected Entities - EF Core](https://docs.microsoft.com/en-gb/ef/core/saving/disconnected-entities)
* Content Source: [entity-framework/core/saving/disconnected-entities.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/disconnected-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@PingPongSet It's for this, "For example, let's assume that when the client sends back a graph of entities it sets some flag on each entity indicating how it should be handled. TrackGraph can then be used to process this flag." The idea is that the client sets these flags before sending the entity back to the server. The server then uses these flags to determine entity state. However, these flags should not be persisted to the database and so they are marked as NotMapped.
