### ISSUE TITLE
Migration recommendation reasoning seems to be incorrect.

### ISSUE THREAD

**Issue by alphabet5** [dotnet/EntityFramework.Docs#3333]
[Enter feedback here]

"The SQL commands are applied directly by the program, without giving the developer a chance to inspect or modify them. This can be dangerous in a production environment."

This doesn't seem correct. DB migration code should be inspected by the developer before committing to your code repo based on the recommendation:

"While EF Core generally creates accurate migrations, you should always review the code and make sure it corresponds to the desired change; in some cases, it is even necessary to do so."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06b35eff-79e4-2068-6d1c-f9079d43f903
* Version Independent ID: 6c575b10-048c-349c-397e-0d9c11d47235
* Content: [Applying Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/applying.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/applying.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@alphabet5 the above sentence which you quote describes the "apply migrations at runtime" approach - how is it incorrect? This is precisely the reason why this approach is discouraged.
