### ISSUE TITLE
EF Core extensions

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/EntityFramework.Docs#3338]
Hi,

Can you please add [this](https://github.com/weitzhandler/FluentValidation.EntityFrameworkCore) extension as well?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8875eb79-99ff-662b-c189-86eb8cdb5488
* Version Independent ID: fa03a7fa-1922-7aa1-acda-b0d216ef37cb
* Content: [Tools & Extensions - EF Core](https://docs.microsoft.com/en-us/ef/core/extensions/)
* Content Source: [entity-framework/core/extensions/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/extensions/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ErikEJ
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@weitzhandler To add an extension, please submit a PR following the same format as the existing extensions.
