### ISSUE TITLE
Always use Using Blocks

### ISSUE THREAD

**Issue by RichMcQuillen** [dotnet/EntityFramework.Docs#3342]
These are poor programming practices that can break a production system.  You should be using "Using" blocks, so you can close your connections.

Wrong:
"var blogs = context.Blogs
    .FromSqlRaw("SELECT * FROM dbo.Blogs")
    .ToList();"
    
Correct:    
var blogs;
Using (var db = new context() )  {
    blogs = db.Blogs.FromSqlRaw("SELECT * FROM dbo.Blogs").ToList();
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1289d5-8364-18a4-3445-6bba05c6854b
* Version Independent ID: 2680e647-f64a-7991-f821-3b5e2a845960
* Content: [Raw SQL Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql)
* Content Source: [entity-framework/core/querying/raw-sql.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/raw-sql.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
The sample code contains many "using" statements: https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core/Querying/RawSQL

**Comment by RichMcQuillen** [comment]
Ok. I reviewed the sample code.  The sample code always has "using" statements and is top-notch.  Great stuff.

The page does not list these; the page is technically correct, but I see programmers googling this stuff and using these commands as is, and breaking their programs.  
https://docs.microsoft.com/en-us/ef/core/querying/raw-sql?fbclid=IwAR03RuV8sCbVhGXcoZpLj_hZPPBbqgw9qNI2MzrAeabgY22B8EpII7xFJCE
