### ISSUE TITLE
Unclear action item from warning

### ISSUE THREAD

**Issue by joecjdi** [dotnet/EntityFramework.Docs#3344]
[Enter feedback here]
I am getting a warning from my .NET 5 / EF Core 5 app (after upgrading my app from .NET Core 3.1 / EF Core 3.1) at runtime that references this page. This page seems more informational and doesn't tell me how to resolve the warning explicitly. The exact text of that warning is:

"Compiling a query which loads related collections for more than one collection navigation either via 'Include' or through projection but no 'QuerySplittingBehavior' has been configured. By default Entity Framework will use 'QuerySplittingBehavior.SingleQuery' which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'"

If the runtime warning should really reference this page, I would expect this page to be structured more like the "breaking changes" page here https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes, where old behavior, new behavior, why, mitigations, etc are all very, very clearly spelled out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a3ce6e-43ab-e0af-01b3-a82fdaf3cb31
* Version Independent ID: 320e7305-e0a3-a1c6-77f2-1d3029b660b1
* Content: [Eager Loading of Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#single-and-split-queries)
* Content Source: [entity-framework/core/querying/related-data/eager.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/related-data/eager.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Updated the link in exception message to point to correct page. It should be refreshed in a short while. 
This is the correct page https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries

**Comment by joecjdi** [comment]
Thank you - I will have another look when the next version is released.
