### ISSUE TITLE
Install Entity Framework

### ISSUE THREAD

**Issue by SyedTaqiRizvi110** [dotnet/EntityFramework.Docs#3345]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0f15cd1-d242-5c8d-c96d-104663423395
* Version Independent ID: 0e623627-7738-1005-3d2c-d099d6ebd929
* Content: [Get Entity Framework - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/install)
* Content Source: [entity-framework/ef6/fundamentals/install.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/install.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@SyedTaqiRizvi110 Did you have any specific question or comment?

**Comment by SyedTaqiRizvi110** [comment]
The issue is that when I'm trying to enable migrations, the console says
context not found

**Comment by AndriySvyryd** [comment]
Make sure that the DbContext-derived class is public, has a public parameterless constructor and is located in the project chosen as "Default project" in the console. Also try adding `–verbose` flag to the command to get more information.
