### ISSUE TITLE
Please clarify and quantify statements regarding DbContext pooling

### ISSUE THREAD

**Issue by joecjdi** [dotnet/EntityFramework.Docs#3369]
[Enter feedback here]
Please further describe and quantify this statement:
"DbContext pooling can increase performance in high-throughput scenarios by re-using context instances. However, for most application this performance gain is very small."

What is meant by "most applications"? Are you referring to user-interactive applications? How small is "very small"? Clearly some research/benchmarking has been done to come to that conclusion. Can you share the results, even if it is a broad range?

I have a NON-user-interactive application that does a lot of background processing and, because of the vague documentation, I have no way of knowing if connection pooling would benefit me. I cannot easily benchmark my app because it has a constructor that takes more than 1 arg.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b8ef11-d408-f9d6-29eb-f7d2ac1aa530
* Version Independent ID: 483c34e9-4534-7b3b-653e-ac88e32d62f3
* Content: [EntityFrameworkServiceCollectionExtensions.AddDbContextPool Method (Microsoft.Extensions.DependencyInjection)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontextpool?view=efcore-5.0)
* Content Source: [dotnet/xml/Microsoft.Extensions.DependencyInjection/EntityFrameworkServiceCollectionExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.Extensions.DependencyInjection/EntityFrameworkServiceCollectionExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@joecjdi The only real way to know is to test your specific scenarios. That being said, we're putting this on the backlog to try to make the documentation a bit more helpful.

**Comment by roji** [comment]
Added some explanations and a simple benchmark in #3460.
