### ISSUE TITLE
What is Point ? System.Drawing ??????

### ISSUE THREAD

**Issue by albutta** [dotnet/EntityFramework.Docs#3376]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dcf82b-f177-e91b-96a5-67f2f57bd6c4
* Version Independent ID: 89c0803f-570f-07a6-6dc2-285678712c86
* Content: [Spatial Data - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/spatial)
* Content Source: [entity-framework/core/modeling/spatial.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/spatial.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@albutta It's from NetTopologySuite, as shown at the [top of the doc](https://docs.microsoft.com/en-us/ef/core/modeling/spatial#nettopologysuite).

**Comment by albutta** [comment]
Thanks, I found it on another article. NetTopologySuite.Geometries.Point
