### ISSUE TITLE
Documentation for ‘RollbackTransactionAsync’ seems to be incorrect 

### ISSUE THREAD

**Issue by wsimf** [dotnet/EntityFramework.Docs#3382]
Documentation specifies:
> Applies the outstanding operations in the current transaction to the database.

This has to be incorrect, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70e2f357-b4ca-c3e8-bf45-26fa30d6293c
* Version Independent ID: 06541100-723b-b8da-c71b-51b120c5c0ef
* Content: [DatabaseFacade.RollbackTransactionAsync(CancellationToken) Method (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.rollbacktransactionasync?view=efcore-5.0#Microsoft_EntityFrameworkCore_Infrastructure_DatabaseFacade_RollbackTransactionAsync_System_Threading_CancellationToken_)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/DatabaseFacade.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/DatabaseFacade.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Duplicate of #23933

**Comment by roji** [comment]
Thanks, this has already been fixed, but we only publish API documentation changes every release - so this will go out with EF Core 6.0.
