### ISSUE TITLE
Eager Loading of Related Data – bad model naming

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/EntityFramework.Docs#3383]
At [Include on derived types](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#include-on-derived-types)

is several times used type/property `People` but sample model declares `Person`.

---

```c#
public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```
> Contents of `School` navigation of all **People** who are Students can be eagerly loaded using a number of patterns:

```c#
context.People.Include(person => ((Student)person).School).ToList()
        ⮙⮝⮝⮙
``` 
… … … …

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a3ce6e-43ab-e0af-01b3-a82fdaf3cb31
* Version Independent ID: 320e7305-e0a3-a1c6-77f2-1d3029b660b1
* Content: [Eager Loading of Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager)
* Content Source: [entity-framework/core/querying/related-data/eager.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/related-data/eager.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Uzivatel919 The `DbSet` property on the `SchoolContext` shown in the document is called `People`.

**Comment by Uzivatel919** [comment]
I am victim of visual hallucinations likely due my preoccupation. My apology and thanks, @ajcvickers.
