### ISSUE TITLE
MUDDIED, OVER-COMPLICATED ISSUE; INCOMPLETE REFERENCE; LACKING EXAMPLES

### ISSUE THREAD

**Issue by m-montagne** [dotnet/EntityFramework.Docs#3386]
[Enter feedback here]

I'm returning to Visual Studio after a long while. I got my feet wet in OOP in the very first days of Borland Delphi and C++Builder; and I just can't believe how complicated Microsoft has made OOP. Do you know, I never had to create a model (struct) or list or collection across my entire career in the Borland IDE? If you had to connect to a database programmatically, you passed a path, and optionally a username and password, to a TDataSource object. Simple. As it should be.

Twenty-five years ago, I was light years ahead of using XML files to initialize an application. I developed practically codeless means of sustaining the state and focus of an application in tables; and I'll be damned if I'm going to reject all the advantages of my personal development patterns because Microsoft practically forces me to do something really stupid -- which is to keep all my connection strings in an XML file associated alike, with every application installation. Why is this so inappropriate?

I'm writing an industrial application which inventories everything from machines to machine designs to machine setups to cutter designs and cutter instances, projected work cycle lifespans, and performed work-cycles. The database resides on a server. Applications are installed all over the shop. Which of course is blatantly customary. The path to the server-side database is different all over the shop, depending upon the configuration of the specific machine. For each user, and for each potentially dedicated purpose of a particular application (which may run a particular machine), application states may be stored either locally (to the installation) or to the user records of the server. 

OK. So I can use a local XML file to open the local table. But I cannot configure a common connection string to open the server database from every machine, because the ostensible connection string differs. So, the proper thing to do is to store the connection string for the server database to a column of the local state table.

Back in 1995, no person and no document would be required to inform us how to do so. If the database was securitized with users and passwords, we would store each in fields of each user in the local state table, and pass these strings to the properties of our datasource object, together with the path to the database. Three string or text fields, and we're in. No instruction.

Effectively, an ostensible connection string passes the very same data, in conjunction with a "providerName." On the one hand, Microsoft is pretending to enforce OO principles by forcing perfectly legitimate global variables and so forth to be members of classes, while at the same time engaging in this utter nonsense of an XML App.config file. Worse, the documentation is so poor that rocket scientists might visit dozens of pages before they encounter even an example of what programmatic form the connection string must be passed in, at run time.

Make up your minds. Either we're object oriented or we are not. Give us a GD connection string object; and document everything we need to know to use it... meaning... explain exactly how and why it's designed as it is, and how to deploy it. You're drooling over yourselves how you've sewn some wonderfully complex thing together. Good design would eliminate the whole need for the fruitless search I'm presently engaged in. Which is about as bad a job as can be done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f431e6c-6c5f-9056-1486-99ba6b02c954
* Version Independent ID: 37943f43-c279-f190-b134-48f54ead1e38
* Content: [Connection strings and models - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/configuring/connection-strings)
* Content Source: [entity-framework/ef6/fundamentals/configuring/connection-strings.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/configuring/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@m-montagne there are many things in the above post - I'll try to answer some of them as I understood them.

> I never had to create a model (struct) or list or collection across my entire career in the Borland IDE

Creating a model - a set of classes/structs which represent your database structure - is part of Entity Framework, which is in no way mandatory. You can use other data access methods which do not involve a model: [Dapper](https://github.com/DapperLib/Dapper) is one "lighter" option, [DataAdapter/DataSet](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/populating-a-dataset-from-a-dataadapter) is another model-less option, and you can always go low-level and use raw ADO.NET and [read results directly from a DbDataReader](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/retrieving-data-using-a-datareader). Entity Framework is a full-fledged object-relational mapper (O/RM), so if you choose to use it you're opting into using an object model.

The rest of your comment seems to be about connection string management with Entity Framework 6, and against the use of XML files (by which I think you're referring to app.config/web.config). Keeping your connection strings in XML files is just one option, which nobody forces you to use; the doc section [Other DbContext constructor options](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/configuring/connection-strings#other-dbcontext-constructor-options) includes the following:

> You can pass a full connection string to DbContext instead of just the database or connection string name. By default this connection string is used with the System.Data.SqlClient provider; this can be changed by setting a different implementation of IConnectionFactory onto context.Database.DefaultConnectionFactory.

In other words, you can store (or generate) your connection strings in whatever way makes sense for your application, and then pass them to your DbContext's constructor. Another way is to fetch the connection string internally in your DbContext's constructor from some other service.

Finally, please note that it is no longer recommended to use Entity Framework 6 for new applications - Entity Framework Core is where all development focus has been for the past few years (we are also no longer actively maintaining the EF6 docs). The different options for managing connection strings with EF Core can be found [on this page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings). Unless you're maintaining a legacy EF6 application, it's recommended to consider using EF Core.

I hope I've addressed your questions above; if you have any more questions or suggestions please feel free to post them here.
