### ISSUE TITLE
Wrong typo in note of Shared Columns section

### ISSUE THREAD

**Issue by tnasan** [dotnet/EntityFramework.Docs#3395]
To whom who involves with this issue,

From the note of Shared Columns section:

> **Note**
>
> Relational database providers, such as SQL Server, will not automatically use the discriminator predicate when querying shared columns when using a cast. The query `Url = (blob as RssBlog).Url` would also return the `Url` value for the sibling `Blog` rows. To restrict the query to `RssBlog` entities you need to manually add a filter on the discriminator, such as `Url = blob is RssBlog ? (blob as RssBlog).Url : null`.

I believe that `blob` using in the note is refer to `Blog` class of an earlier context. Maybe I'm wrong.

T. Kittimethee,
Developer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10898c5-abee-1843-cfff-b2707f8a079a
* Version Independent ID: d9399618-488e-20b1-f707-35a191b95cc1
* Content: [Inheritance - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance)
* Content Source: [entity-framework/core/modeling/inheritance.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/inheritance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks @tnasan, submitted #3399 to fix. In the future you can directly submit a PR to fix as well.
