### ISSUE TITLE
Unable to create an object of type 'xxxContext'. For the different patterns supported at design time

### ISSUE THREAD

**Issue by gitlcl** [dotnet/EntityFramework.Docs#3408]
【Unable to create an object of type 'xxxContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728 】
 **I'm following this page's  recommendation**,Use Di,Inherit DbContext, register scoped xxxContext as service ,  run command in terminal 【dotnet ef migrations add DbInit1】,**It always return this error message ,
 i googled another solution** : providing a no parameter constructor of xxxContext and override OnConfiguring  method to specified my connection string, then run command in terminal【dotnet ef migrations add DbInit1】.  
**this solution works, but it is not elegant ,  the recommendation solution should work, otherwise this page shall be revised(remove the not working solution)**
Here is my config
OS:MacOS
using .net core 3.1.403,
using Microsoft.EntityFrameworkCore 3.1.18
using Microsoft.EntityFrameworkCore.Tools 3.1.18
using Microsoft.EntityFrameworkCore.Design 3.1.18
using Microsoft.EntityFrameworkCore.PostgresSQL 3.1.18

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459d20e7-ba25-c162-5721-359ef3562999
* Version Independent ID: d988e806-cb86-19f5-7f76-6ce3bfcd94ed
* Content: [Design-time DbContext Creation - EF Core](https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/cli/dbcontext-creation.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/cli/dbcontext-creation.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@gitlcl Please post your DbContext code in the form that doesn't work so that we can investigate.

**Comment by gitlcl** [comment]
@ajcvickers Thank you for your reply , i will post my code after work when i get home( about 4 hours later).

**Comment by gitlcl** [comment]
-  My xxxDbContext can be simplified as below:
`public class PgContext : DbContext
    {
        public PgContext(DbContextOptions<PgContext> options) : base(options)
        {
        }

        public DbSet<MyTable> MyTables { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<MyTable>(entity =>
            {
                entity.HasComment("xxx");
                entity.Property(e => e.MyField).HasComment("xxxx");
            });
        }
`
`        
//startup.cs -> public void ConfigureServices(IServiceCollection services)
        services.AddDbContext<PgContext>((options) =>
                {
                    options.UseNpgsql(connectionString).UseSnakeCaseNamingConvention();
                });
`
`  
//program.cs
      public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
        }
`

**Comment by gitlcl** [comment]
I figured out the reason, because startup.cs and PgContext.cs are stored in 2 different projects of my solution. In this case , i have to  add ' -s StartUpProjectName'  to my command【dotnet ef migrations add DbInit1】
