### ISSUE TITLE
What about scaffolding database stored procedures and functions - especially table-functions

### ISSUE THREAD

**Issue by eagle275** [dotnet/EntityFramework.Docs#3424]
I've read the article about scaffolding entities from the database and while it sure seems useful, why dont include stored procedures and functions? I mainly interact with our database through functions and stored procedures because when entering data those need to be cross checked and validated. How do I include those? Also I may add .. not being able to use edmx diagrams is a huge drawback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1601c3e-3f29-5d84-6350-2b38eeaf6adc
* Version Independent ID: 92a856d6-c5da-e215-46ac-d67c411f3ff9
* Content: [Reverse Engineering - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/scaffolding.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
@eagle275 EF Core Power Tools allows you to reverse engineer stored procedures and functions.
