### ISSUE TITLE
Defining a Join entity without additional navigation properties not explained

### ISSUE THREAD

**Issue by marwalsch** [dotnet/EntityFramework.Docs#3434]
For regular 1-N relationships there is an overload of `WithOne()` taking no parameters in case the N-side does not need to navigate to its parent entity. However, it is not explained whether or how this can be achieved for an explicitly defined join entity.
Applied to the given example that would equal the `PostTag` looking like this:

```
public class PostTag
{
    public DateTime PublicationDate { get; set; }

    public int PostId { get; set; }
    //public Post Post { get; set; }

    public string TagId { get; set; }
    //public Tag Tag { get; set; }
}
```

The foreign keys are given but the inverse navigation is not necessary.

Is this even possible? or does the this configuration always require these? The docs could be more clear here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#many-to-many)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@marwalsch The join entity type does not need to have navigations. However, it's not clear to me what the confusion is here. Can you show the code you are using to configure the relationships and point to where it's not clear what to do?

**Comment by marwalsch** [comment]
Of course. My relationship configuration looks quite exactly like the one defined in the section _Join entity type configuration_. But, as shown above, the navigations inside the `BlogPost` are not necessary. I couldn't work out a suitable FluentAPI configuration. Below is the one used in the example including navigation properties:

```
 modelBuilder.Entity<Post>()
            .HasMany(p => p.Tags)
            .WithMany(p => p.Posts)
            .UsingEntity<PostTag>(
                j => j
                    .HasOne(pt => pt.Tag)
                    .WithMany(t => t.PostTags)
                    .HasForeignKey(pt => pt.TagId),
                j => j
                    .HasOne(pt => pt.Post)
                    .WithMany(p => p.PostTags)
                    .HasForeignKey(pt => pt.PostId),
                j =>
                {
                    j.Property(pt => pt.PublicationDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
                    j.HasKey(t => new { t.PostId, t.TagId });
                });
```

However, `.HasOne()` requires the navigation as a parameter which is not present. How does this need to be changed?

**Comment by ajcvickers** [comment]
@marwalsch The navigation is not required as a parameter. Maybe it seems like it is because you need to specify the generic parameter explicitly if it cannot be inferred? (Note that this is the same for HasOne when used in other places.) For example:

```C#
modelBuilder.Entity<Post>()
            .HasMany(p => p.Tags)
            .WithMany(p => p.Posts)
            .UsingEntity<PostTag>(
                j => j
                    .HasOne<Tag>()
                    .WithMany(t => t.PostTags)
                    .HasForeignKey(pt => pt.TagId),
                j => j
                    .HasOne<Post>()
                    .WithMany(p => p.PostTags)
                    .HasForeignKey(pt => pt.PostId),
                j =>
                {
                    j.Property(pt => pt.PublicationDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
                    j.HasKey(t => new { t.PostId, t.TagId });
                });
```

Is that the cause of confusion?

**Comment by marwalsch** [comment]
Ah, that did it. I completely missed out on the `HasOne<T>()` overload. Thanks for shedding light on this.
