### ISSUE TITLE
Error When Creating second migration with same name 

### ISSUE THREAD

**Issue by khalifima** [dotnet/EntityFramework.Docs#3457]
Following this guide to produce the migrations and after creating the first migration with sqlite I cannot create a second migration with the same name with another provider **I get the error The name 'Initial' is used by an existing migration** even though the first migration is in another folder.
If I change the name, the result would be a scaffolded migration which base is the first one and not a completely new migration. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Using a Separate Migrations Project - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@khalifima you probably want to read the docs on migrations with multiple providers. If you're still running into trouble, can you please post detailed, step-by-step instructions on what your doing? For example, which method are you using to manage migrations - multiple context types, or one?
