### ISSUE TITLE
Wrong text

### ISSUE THREAD

**Issue by voroninp** [dotnet/EntityFramework.Docs#3483]
[Enter feedback here]
Should be `Discards the outstanding operations in the current transaction.` instead of `Applies the outstanding operations in the current transaction to the database.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70e2f357-b4ca-c3e8-bf45-26fa30d6293c
* Version Independent ID: 06541100-723b-b8da-c71b-51b120c5c0ef
* Content: [DatabaseFacade.RollbackTransactionAsync(CancellationToken) Method (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.rollbacktransactionasync?view=efcore-5.0&source=docs)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/DatabaseFacade.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/DatabaseFacade.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks for flagging this - [we've already fixed this in the code](https://github.com/dotnet/efcore/blob/main/src/EFCore/Infrastructure/DatabaseFacade.cs#L351), but the APIs docs only get refreshed when a new version goes live (6.0).
