### ISSUE TITLE
LazyLoader null check missing

### ISSUE THREAD

**Issue by MaximMikhisor** [dotnet/EntityFramework.Docs#3522]
What will happen if object will be created by this constructor

`public Post() {}`

and after that this property will be accessed:

```
public Blog Blog
{
    get => LazyLoader.Load(this, ref _blog);
    set => _blog = value;
}
```

LazyLoader in this situation will be null. Right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 956653a9-3acf-e361-94a7-2eff333619c9
* Version Independent ID: 7c665098-afcc-1ba0-d6a2-0262ae921575
* Content: [Lazy Loading of Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data/lazy#lazy-loading-without-proxies)
* Content Source: [entity-framework/core/querying/related-data/lazy.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/related-data/lazy.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@MaximMikhisor The `Load` extension method is designed to no-op when the LazyLoader is null.
