### ISSUE TITLE
 SQLite Spatial Instructions for macOS Mac Ports

### ISSUE THREAD

**Issue by neliason0** [dotnet/EntityFramework.Docs#3532]
macOS Mac Ports users can also configure SQLite to use SpatialLite.

# Install SpatiaLite

    sudo port install spatialite

# Configure SpatialLite

Create a soft link for mod_spatialite.dylib

    sudo ln -s /opt/local/lib/mod_spatialite.so /opt/local/lib/mod_spatialite.dylib

Note: the Mac Ports install will create mod_spatialite.so but SQLite expects the name to be mod_spatialite.dylib.  /opt/local/lib is the default Mac Ports lib directory.

# Configure runsettings

Create a .runsettings file and set an environmental variable for **DYLD_FALLBACK_LIBRARY_PATH** (do not use DYLD_LIBRARY_PATH) which points to the Mac Ports lib location.

    <RunSettings>
        <RunConfiguration>
            <EnvironmentVariables>            
                <DYLD_FALLBACK_LIBRARY_PATH>/opt/local/lib</DYLD_FALLBACK_LIBRARY_PATH>
            </EnvironmentVariables>
        </RunConfiguration>
     </RunSettings>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a748bc8-6a4c-3263-171d-fadc8cd96594
* Version Independent ID: 45a01f08-fe92-bc98-2991-75554b0d8a67
* Content: [SQLite Database Provider - Spatial Data - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/spatial)
* Content Source: [entity-framework/core/providers/sqlite/spatial.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/sqlite/spatial.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by neliason0** [comment]
@ajcvickers MacPorts is an alternate package management system for macOS. I don't know that MacPorts is better or recommended for SQLite. I've never used Homebrew. I chose MacPorts for myself based on some advantages to that system based on my research. So, in my opinion MacPorts is better.

I think both MacPorts and Homebrew generally work the same. MacPorts is an older system than Homebrew. But, Homebrew seems to be more popular. Homebrew may be perceived as easier to use.

As a MacPorts user I'd like for dotnet instructions to include MacPorts. But, I realize that may be less important than having Homebrew instructions due to Homebrew being more popular.

**Comment by ajcvickers** [comment]
@neliason0 Since most people seem to use Homebrew, and we're not really familiar with the was MacPorts works, we would rather keep the documentation simple and not confuse it with additional instructions for MacPorts. That being said, if there is a concrete reason why using MacPorts is a better experience, then we could reconsider.
