### ISSUE TITLE
Stop pushing auto-translated pages on technical documentations

### ISSUE THREAD

**Issue by Maskime** [dotnet/EntityFramework.Docs#3548]
Hi,

I really appreciate the effort that you're making to make your documentation accessible to everyone, but when looking at automatic translation on technical documentation, at best, it doesn't really make any sense, in worst case can be simply misleading.

When you got caught once by some bad translation, you don't trust it anymore and you just look for the link that will put it back in english.

Most of the concept that we're using have english name anyway, so when I'm confronted with its literal translation in my language it takes me a bit of time to be able to make the connection with the concept and translate it back to english in my head anyway.

So again, I really appreciate the effort, but it's my feeling that it does not really work, at least for french.

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f06ab560-1ce6-a745-dd2f-0d50ce99e180
* Version Independent ID: a658e312-7580-f5a7-c33c-441515738095
* Content: [DbContext.UpdateRange Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.updaterange?view=efcore-5.0#Microsoft_EntityFrameworkCore_DbContext_UpdateRange_System_Object___)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
@Maskime - Thank you for the feedback on machine translation. If you have a particular case in the mind where tool translated something incorrectly then if you let us know we can either improve translation in the tool, or mark certain words which should not get translated (like actual APIs which are always going to be in English).
Beyond that while machine translation is not as accurate and quality content as original content written by someone who is fluent in the language, it is still helping out people whose native language is not English and we have received positive feedback about it. So we are not going to discontinue it.

To change the locale of any doc on docs.microsoft.com to English (US)
- Convert locale part to "en-us" (for French locale part would be fr-fr) or,
- At the end of page on left bottom corner current locale is mentioned which is clickable link to allow user to pick a different locale.

All EF Core docs (API and conceptual) are written in English (US).

**Comment by ArneDoering** [comment]
Nothing has been fixed. I still get fed with autotranslated garbage. Yes I can go to the english version of a page like you said by entering "en-us" in there. And I have to do that 100 times a day? Is that your solution? Manually inserting "en-us" every time I look something up?
