### ISSUE TITLE
Building dynamic generic linq queries

### ISSUE THREAD

**Issue by AlirezaDadrass** [dotnet/EntityFramework.Docs#3561]
Hi,
I have a question and it would be my pleasure if you answer it.

I'm working on an organizational application framework, and there is a dynamic reporting engine with EF core that I have to build.( 3rd party reporting tools are denied to use)
The problem is that I want to make a fully dynamic linq expressions for generic DBSet without hard coding any Entities and expressions like 'where, join or select'. I couldn't find any solution for.
I'll be appreciated if you help me.

**Comment by roji** [comment]
@AlirezaDadrass EF Core may not be the best tool for a fully dynamic scenario where nothing is known in advance. You would have to dynamically configure the model (calling e.g. `modelBuilder.Entity<T>()` to add entity types to the model), and dynamically generate LINQ query operators for all your queries etc. This is bound to be quite laborious and probably error-prone. I'm personally not sure I'd pick EF Core as the too for this.

**Comment by AlirezaDadrass** [comment]
Hi tanks for response.
So in this situation what would you suggest?
Is it a good idea to build a query generator?

**Comment by roji** [comment]
Yes, a SQL generator is certainly an option here. Other ORMs/data layers may work better in such a fully dynamic scenario, but I don't know any specific details.
