### ISSUE TITLE
Document support for nullable reference types in scaffolding

### ISSUE THREAD

**Issue by pekspro** [dotnet/EntityFramework.Docs#3562]
In **Limitations** this article currently says:

    The C# 8 nullable reference type feature is currently unsupported in reverse engineering

It is supported in EF Core 6 - finally :-).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1601c3e-3f29-5d84-6350-2b38eeaf6adc
* Version Independent ID: 92a856d6-c5da-e215-46ac-d67c411f3ff9
* Content: [Reverse Engineering - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/scaffolding.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Issue: https://github.com/dotnet/efcore/issues/15520
