### ISSUE TITLE
[foreign] key attribute

### ISSUE THREAD

**Issue by rupeshPlant** [dotnet/EntityFramework.Docs#3571]
[Why I always can't find the things that I'm looking for in the official page.
I should always surf hours for a simple learn. I was looking for a new attribute [foreign] which will make a property foreign
I have seen application in many other places but can't find here when I wanted to learn in detail.
And why the documentation goes round and round why don't have simply a next button where a beginner can know how and what to learn. I must say it's very bad documentation or at least not a beginner friendly]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@rupeshPlant The description and example for adding the `[ForeignKey]` attribute is on the page you reference: https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cdata-annotations-simple-key%2Csimple-key#foreign-key

![image](https://user-images.githubusercontent.com/1430078/142418956-4d43bf36-916a-48b5-92be-2a12b8efc17c.png)

If you have concrete suggestions how we improve this they are most welcome. As it is, I struggle to see how we make this easier to find.
