### ISSUE TITLE
Don't call base.OnConfiguring(optionsBuilder) in the getting started guide

### ISSUE THREAD

**Issue by squiddie** [dotnet/EntityFramework.Docs#3572]
[Enter feedback here]

The override of OnConfiguring calls the base function at the end. This can be cut as the base implementation does nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a691101f-b7ea-4539-3745-6d9b0f5e317f
* Version Independent ID: 8f488a69-cedf-9c45-f977-23b3d8abd3df
* Content: [Get Started with WPF - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/wpf)
* Content Source: [entity-framework/core/get-started/wpf.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/wpf.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by Maniizzle** [comment]
Hello @ajcvickers, Can i attend to this?

**Comment by roji** [comment]
@Maniizzle sure, feel free to submit a PR for this.
