### ISSUE TITLE
Path.Combine

### ISSUE THREAD

**Issue by chris835** [dotnet/EntityFramework.Docs#3579]
Noticed this line:
 DbPath = $"{path}{System.IO.Path.DirectorySeparatorChar}blogging.db";

Why not use Path.Join?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488629d4-9bd2-42b5-4644-34e3f2baee59
* Version Independent ID: b38b9d14-6bad-12e0-8d2d-24b50bc4977e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/overview/first-app.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/first-app.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@chris835 it's certainly possible - would you like to submit a PR for this?

**Comment by ajcvickers** [comment]
@roji Is this different to what was done here? https://github.com/dotnet/EntityFramework.Docs/pull/3574

**Comment by roji** [comment]
@ajcvickers good catch.
