### ISSUE TITLE
Document good pagination practices

### ISSUE THREAD

**Issue by roji** [dotnet/EntityFramework.Docs#3582]
* Warn against offset pagination, explain keyset navigation (https://use-the-index-luke.com/no-offset, https://www.slideshare.net/MarkusWinand/p2d2-pagination-done-the-postgresql-way).
* Based on the outcome of https://github.com/dotnet/efcore/issues/26822, show patterns for using row value comparisons.

This can be a new page under the performance section, linked to from relevant query docs pages.

**Comment by mrahhal** [comment]
Might be useful to talk about how to avoid skipping over data when doing keyset pagination, and also about good indexing strategies for keyset to be as fast as possible.
For reference:
https://github.com/mrahhal/MR.EntityFrameworkCore.KeysetPagination#avoiding-skipping-over-data
https://github.com/mrahhal/MR.EntityFrameworkCore.KeysetPagination#indexing

**Comment by roji** [comment]
Absolutely, thanks for the suggestion @mrahhal.
