### ISSUE TITLE
Transaction Cancellation Token

### ISSUE THREAD

**Issue by lukemason76** [dotnet/EntityFramework.Docs#3587]
The source code comment for 
```
public interface IDbContextTransaction : IDisposable, IAsyncDisposable`
[snip]
// Parameters:
//   cancellationToken:
//     A System.Threading.CancellationToken to observe while waiting for the task to
//     complete.
[snip]
// Remarks:
//     See Transactions in EF Core for more information.
        Task CommitAsync(CancellationToken cancellationToken = default(CancellationToken));
```

The mention in the code comments is more than any mention of `cancellationToken` on the **Transactions in EF Core** page.  Any chance of some more elightenment?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@lukemason76 the cancellation token to CommitAsync functions just like cancellation tokens in any other .NET context - it's a general mechanism for trying to cancel asynchronous operations before they have completed. There isn't anything special about IDbContextTransaction.CommitAsync in this context - do you have any specific questions here?
