### ISSUE TITLE
Question: Why should we not disable change tracking for add/update operations?

### ISSUE THREAD

**Issue by sjd2021** [dotnet/EntityFramework.Docs#3592]
The documentation on this page states "You should not disable change tracking if you want to manipulate entity instances and persist those changes to the database using SaveChanges()."

I am using a repository pattern which works quite well, and I usually disable change tracking so that callers are explicitly calling .Update() or .Add() which in turn call the corresponding methods on the dbsets. I am under the assumption that this is more performant as EF only needs to analyze the entities I've explicitly stated have changed. Is this an incorrect assumption? Because the documentation doesn't give much of an explanation on why we shouldn't disable it in this case, I'm not exactly sure whether to treat it as gospel or continue rolling with my implementation which I may have made under a false pretense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 356ac124-eb52-b50e-4170-487907bbd2af
* Version Independent ID: 33c19fc9-c319-5f88-794c-5b46acd1a4c9
* Content: [DbContextOptionsBuilder.UseQueryTrackingBehavior(QueryTrackingBehavior) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder.usequerytrackingbehavior?view=efcore-5.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@sjd2021 The [change tracking docs](https://docs.microsoft.com/en-us/ef/core/change-tracking/) cover this in some detail. In particular, the [Explicitly Tracking Entities](https://docs.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking) page covers when you should and should not use `Update`, etc.
