### ISSUE TITLE
Will the AddDbContextFactory connection string normally be read from config files?

### ISSUE THREAD

**Issue by RannyMeier** [dotnet/EntityFramework.Docs#3594]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055bb8db-139d-beb5-61c1-47cf1ea6ea93
* Version Independent ID: b0a3d5ad-b62c-1ff4-386a-f11e350eea0c
* Content: [DbContext Lifetime, Configuration, and Initialization - EF Core](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#using-a-dbcontext-factory-eg-for-blazor)
* Content Source: [entity-framework/core/dbcontext-configuration/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/dbcontext-configuration/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@RannyMeier There is nothing in EF Core that will automatically read a connection string from a config file. However, if you are using the default ASP.NET Core configuration and options system, then you can use the `name=` syntax, as shown in [DbContext in dependency injection for ASP.NET Core](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#dbcontext-in-dependency-injection-for-aspnet-core). Beyond that, the connection string should be read from whatever config file you have and passed to `UseSqlServer` or similar.
