### ISSUE TITLE
Can EntityFramework.Cosmos be used on Azure Functions?

### ISSUE THREAD

**Issue by John-HLC** [dotnet/EntityFramework.Docs#3595]
To date I have been using 
Nuget: Microsoft.EntityFrameworkCore.Cosmos  on a Blazor WASM Client side only app..
and 
Nuget:  Microsoft.Azure.Cosmos   on Azure Functions

to access and manipulate CosmosDB Document Entites.

This is not ideal as i need to keep two different class definitions for every class, as the C# class for each Document/Entity is different between the two nuget packages.

I need to use Microsoft.EntityFrameworkCore.Cosmos  on the Azure Functions side, 
can you confirm this is or is not possible on the Azure Functions. I can't seem to find any guidance on being able (or not).

**Comment by roji** [comment]
@John-HLC I'm not aware of any blocker for using Microsoft.EntityFrameworkCore.Cosmos on Azure Functions - it's just another .NET package.

**Comment by John-HLC** [comment]
@roji  - thank you for response.   I'll give it a try and re-open if run into any turbulence.
