### ISSUE TITLE
Great article

### ISSUE THREAD

**Issue by GuildOfCalamity** [dotnet/EntityFramework.Docs#3600]
[Enter feedback here]
Most of the code articles on Microsoft's site are not that good; they start at step 7 and don't show you how they got there. This article actually walks you through each step. I know this take more effort, but that's what makes it valuable. Bravo!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002d162b-8595-ad48-7ef8-2cd10194a3b4
* Version Independent ID: a29d6e0c-f9eb-86d9-f82e-0e9fc41b5a0d
* Content: [Code First Migrations - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Thanks.
