### ISSUE TITLE
How do you perform In-Memory tests with SQLite for ApplicationDbContext with authorization?

### ISSUE THREAD

**Issue by MiBuena** [dotnet/EntityFramework.Docs#3602]
I Have a Blazor Application. I want to perform In-Memory tests with SQLite. The application has authorization with Identity Server, therefore the ApplicationDbContext constructor has 1 additional parameter:

     public ApplicationDbContext(
            DbContextOptions options,
            IOptions<OperationalStoreOptions> operationalStoreOptions) : base(options, operationalStoreOptions)
        {
        }

In [this ](https://docs.microsoft.com/en-us/ef/core/testing/sqlite)article here there is an example how to construct DbContextOptions with SQLite. How do you construct and pass the  IOptions<OperationalStoreOptions> operationalStoreOptions parameter in order to test with SQLite?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1be65e20-7146-cc35-52cd-4f499db58a1d
* Version Independent ID: 4d93b90f-2e4f-0a2f-42d3-a4c4247f8e08
* Content: [Testing with SQLite - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/sqlite#using-sqlite-in-memory-databases)
* Content Source: [entity-framework/core/testing/sqlite.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/sqlite.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@MiBuena This question is probably best answered by the Identity Server folks, but it looks like `OperationalStoreOptions` can just be newed up normally, so it shouldn't be too hard to create a real instance or a test double for `IOptions` of it.

**Comment by MiBuena** [comment]
@ajcvickers, thank you for your comment! I followed it and I managed to get the values from the running app and create a new instance for IOptions.
        
            IOptions<OperationalStoreOptions> options = Options.Create(new OperationalStoreOptions()
            {
                DeviceFlowCodes = new TableConfiguration("DeviceCodes"),
                EnableTokenCleanup = false,
                PersistedGrants = new TableConfiguration("PersistedGrants"),
                TokenCleanupBatchSize = 100,
                TokenCleanupInterval = 3600
            });
            
            Still if you know anyone more familiar with Identity Server who could comment if this is the right approach, I would appreciate that. Otherwise, you could close the issue.
            
Thank you very much!
