### ISSUE TITLE
Where is EF 6.4 documentation?

### ISSUE THREAD

**Issue by kwaazaar** [dotnet/EntityFramework.Docs#3620]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce95f1d6-cd64-04c1-4583-8313531a490a
* Version Independent ID: 2dc552b7-738d-3a1f-e1a0-ae9c0b67b36b
* Content: [SqlAzureExecutionStrategy Class (System.Data.Entity.SqlServer)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.sqlserver.sqlazureexecutionstrategy?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity.SqlServer/SqlAzureExecutionStrategy.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.SqlServer/SqlAzureExecutionStrategy.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by kwaazaar** [comment]
I mean, when are you going to update the docs? I run into issues, only to learn that those issues are already known to you. For example I'm currently struggling with this one: #1740 

The experience when using EF6 in a .net core/5+ solution is horrible and does not seem to get attention. Does this mean EF6 is EOL? If not, being still supported also means the documention must be up to date.

**Comment by ajcvickers** [comment]
@kwaazaar EF6 is still supported in the sense that it will still get high-priority bug fixes; typically only security issues will make the bar. However, it is not getting any new features or low-priority bug fixes and we are focusing our investment on EF Core. With regard to documentation, #1740 is something we plan to document, but, as with all development teams, we have limited resources, and so must decide where we can add the most value across EF6 and EF Core for both documentation and development. So far, other work has been prioritized above this issue.

The [planning process doc](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) goes into some more detail on how we prioritize work for a release.
