### ISSUE TITLE
The code for [Index] doesn't compile

### ISSUE THREAD

**Issue by Firesong25** [dotnet/EntityFramework.Docs#3627]
[Index] throws an error along these lines.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0592	Attribute 'Index' is not valid on this declaration type. It is only valid on 'class' declarations.	Cleardragon	D:\Dropbox\Cleardragon\Models\User.cs	28	Active

The correct use is at class level:
    [Index(nameof(UserName), IsUnique = true)]
    public class FocusedUser {...}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c7bd305-ac97-ca3c-f8c0-031d8d9c7599
* Version Independent ID: 2d0b358a-5cfd-60e4-251f-c4e824bba348
* Content: [Code First Data Annotations - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/data-annotations)
* Content Source: [entity-framework/ef6/modeling/code-first/data-annotations.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/data-annotations.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Firesong25 Make sure you are using the [EF6 IndexAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.schema.indexattribute?view=entity-framework-6.2.0) with EF6, and the [EF Core IndexAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.indexattribute?view=efcore-5.0) with EF Core.
