### ISSUE TITLE
Foreign keys incorrectly named in Manual configuration section

### ISSUE THREAD

**Issue by kristijan-boskovic** [dotnet/EntityFramework.Docs#3628]
In **Manual configuration** section (**Data annotations** subsection), there is a code snippet with _Post_ and _User_ classes. In _Post_ class, foreign key properties for _Author_ and _Contributor_ navigation properties are named _AuthorUserId_ and _ContributorUserId_, which is incorrect if there are no [ForeignKey] annotations with those foreign key property names included in it. If no [ForeignKey] annotations are used, those foreign key properties should be named **_AuthorId_** and **_ContributorId_**, to make sure Entity Framework Core connects them with foreign keys declared in the Model Snapshot. 

I found this out by getting the _SQLite Error 1: 'no such table'_ exception when trying to execute SaveChanges(). In one of my entity classes, I had these properties declared, which both refer to the _Person_ entity class:
```
...
public int? OwnerPersonId { get; set; }
public Person Owner { get; set; }

public int? CurrentUserPersonId { get; set; }
public Person CurrentUser { get; set; }
...
```
I checked out the Model Snapshot class and I noticed that foreign keys were named _OwnerId_ and _CurrentUserId_, thus being disconnected from my _OwnerPersonId_ and _CurrentUserPersonId_ properties. After I renamed those properties to _OwnerId_ and _CurrentUserId_, and recreated the database, SaveChanges() executed successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@kristijan-boskovic I don't think that the property names are incorrect here; EF Core recognizes `<navigation><pk>` as a convention for FK names, which `ContributorUserId` and `AuthorUserId ` both match. However, it does seem like the _types_ are wrong, since the PK properties are strings, while thee FK properties that would match are ints. (@AndriySvyryd?)

Changing the FK properties to strings:

```C#
public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public string AuthorUserId { get; set; }
    public User Author { get; set; }

    public string ContributorUserId { get; set; }
    public User Contributor { get; set; }
}

public class User
{
    public string UserId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }

    [InverseProperty("Author")]
    public List<Post> AuthoredPosts { get; set; }

    [InverseProperty("Contributor")]
    public List<Post> ContributedToPosts { get; set; }
}
```

Results in the following model, which looks correct:

```
Model: 
  EntityType: Post
    Properties: 
      PostId (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      AuthorUserId (string) FK Index
      Content (string)
      ContributorUserId (string) FK Index
      Title (string)
    Navigations: 
      Author (User) ToPrincipal User Inverse: AuthoredPosts
      Contributor (User) ToPrincipal User Inverse: ContributedToPosts
    Keys: 
      PostId PK
    Foreign keys: 
      Post {'AuthorUserId'} -> User {'UserId'} ToDependent: AuthoredPosts ToPrincipal: Author ClientSetNull
      Post {'ContributorUserId'} -> User {'UserId'} ToDependent: ContributedToPosts ToPrincipal: Contributor ClientSetNull
    Indexes: 
      AuthorUserId 
      ContributorUserId 
  EntityType: User
    Properties: 
      UserId (string) Required PK AfterSave:Throw
      FirstName (string)
      LastName (string)
    Navigations: 
      AuthoredPosts (List<Post>) Collection ToDependent Post Inverse: Author
      ContributedToPosts (List<Post>) Collection ToDependent Post Inverse: Contributor
    Keys: 
      UserId PK
```
