### ISSUE TITLE
.NET API Browser is missing the class reference for Entity Framework Core 6.0

### ISSUE THREAD

**Issue by metoule** [dotnet/EntityFramework.Docs#3630]
I can't find the class reference for EF Core 6: the version dropdown contains all the versions from EF Core 1.0 to EF Core 5.0, but not EF Core 6.0.

> ![image](https://user-images.githubusercontent.com/24547430/146555197-e74eecfa-3ff4-4564-9b08-e24fdef130a2.png)

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 268ea068-fbe0-6a6f-4bb5-b99c662bfa9b
* Version Independent ID: 067e0714-f20b-a6ab-c840-dabbb252efd0
* Content: [Microsoft.EntityFrameworkCore Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore?view=efcore-5.0)
* Content Source: [dotnet/xml/ns-Microsoft.EntityFrameworkCore.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/ns-Microsoft.EntityFrameworkCore.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@metoule The docs team publishes these files live. Unfortunately there is a bug in their tool which is preventing this from happening. We will follow up with them again in the new year.

**Comment by smitpatel** [comment]
The mdoc tool is planning to release a new version with the bug fix some time this week. Afterwards we will generate the new docs for ef core.
