### ISSUE TITLE
Problems encountered when using `dotnet ef dbcontext info`. 

### ISSUE THREAD

**Issue by Jason446620** [dotnet/EntityFramework.Docs#3638]
When using 

`dotnet ef dbcontext info` command line, 
I get below error.

`Unable to create an object of type'OdeToFoodDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid= 851728`.

Related Link: [Why DbConnect is not found in Entity Framework Core](https://stackoverflow.com/questions/70415933/why-dbconnect-is-not-found-in-entity-framework-core/70419887#70419887)

---

**Suggestion:** 

As reminded in the documentation, the prerequisite for using this command is to add a no-argument constructor. 

The official tutorial does not mention the need for a parameterless constructor in the definition of dbcontext.

**Comment by ajcvickers** [comment]
@Jason446620 Which official tutorial are you referring to?

Note that you do not necessarily need a parameterless constructor, but it is listed as one of the options in the link from the error message above: https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#using-a-constructor-with-no-parameters
