### ISSUE TITLE
Multi-Tenancy Illustration is Lacking Clarity, Information and Seems To Be Unfinished

### ISSUE THREAD

**Issue by taylorchasewhite** [dotnet/EntityFramework.Docs#3640]
In general, my feedback from this documentation, while a good start, is that it is lacking a complete (or even close to being complete) description of how to consume global filters for supporting multi-tenancy.

A reader cannot consume this article, walk away and subsequently implement multi-tenancy via global query filters.

Here are a few _specific_ examples supporting this argument:

<ol>
<li>
Defining the <code>_tenantId</code> on the <code>Blog</code> entity. The full description and explanation of the field is:
<br/>
<blockquote>Note the declaration of a <code>_tenantId</code> field on the Blog entity. This field will be used to associate each Blog instance with a specific tenant.</blockquote>.
This <em>does not</em> explain:

- How (and when) is this field set?
- Is this field mapped/stored in an EFCore table?
<br/>
</li>
<li>
In the subsequent paragraph, this statement:

<br/>
<blockquote>
Next, configure the query filters in OnModelCreating using the HasQueryFilter API.
<pre>
modelBuilder.Entity<Blog>().HasQueryFilter(b => EF.Property<string>(b, "_tenantId") == _tenantId);
modelBuilder.Entity<Post>().HasQueryFilter(p => !p.IsDeleted);
</pre>
</blockquote>

lacks any context on passing the `_tenantId` to the OnModelCreating method. As an application developer, who knows the user's tenant only after they login, how do we pass the `_tenantId` field to the `OnModelCreating` method?

More context on how this actually works would be incredibly helpful; a working example on GitHub would also be valuable.
<br/>
</li>

<li>
The "Tip" segment following the example on the previous bullet notes the use of the EF property, <code>_tenantId</code>:
<blockquote>
Note the use of a DbContext instance level field: <code>_tenantId</code> used to set the current tenant. Model-level filters will use the value from the correct context instance (that is, the instance that is executing the query).
</blockquote>

This, however, fails to provide an example on how, where, and when this property is to be set, and thus is not helpful. An example or an explanation on how to set this property is desired.
</li>

Thanks,
Taylor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c9bd3e-4b99-9acf-48d8-e47bc53eb54e
* Version Independent ID: 220e0a6c-d227-956a-d27a-7c88804f770c
* Content: [Global Query Filters - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/filters)
* Content Source: [entity-framework/core/querying/filters.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/filters.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @maumar
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@taylorchasewhite this page wasn't intended as a full guide for implementing multi-tenancy; it documents global query filters as its own feature, which is useful for implementing things other than multitenant. You may be interested in #3632, which adds specific documentation for implementation multitenant patterns.

**Comment by taylorchasewhite** [comment]
Thanks, makes sense, I'll check that out. For what its worth, I still feel even in the scope of documenting global query filters (with totally separately dedicated topics for Soft Deleted and MultiTenancy, it's probably worth touching on some of the topics I mention that are agnostic to the purpose of the filter, like:

- where in the pipeline its best to set an EF.Property value for the use of global query filters.
- The private field on the Blog object, is this a column in EF Core table, or something else

And lastly, maybe it's worth linking from this doc to the new one in progress for people that land here looking for Multi-Tenancy documentation (not sure what philosophy is taken for cross-linking documents though).

**Comment by JeremyLikness** [comment]
Closed per PR #3632.
