### ISSUE TITLE
This page referes to EntityFramework Core 6.1.  I think that should be changed to 6.0.1

### ISSUE THREAD

**Issue by pmia** [dotnet/EntityFramework.Docs#3642]
This page referes to EntityFramework Core 6.1.  I think that should be changed to 6.0.1
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad94d68-823d-c9bf-d90c-fe2c96fc1e56
* Version Independent ID: 608f1890-2f98-3863-b49d-3bddbb6f1cc6
* Content: [Fluent API - Configuring and Mapping Properties and Types - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/fluent/types-and-properties)
* Content Source: [entity-framework/ef6/modeling/code-first/fluent/types-and-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/fluent/types-and-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@pmia that page refers to the older, non-core Entity Framework 6.1, not to Entity Framework Core.
