### ISSUE TITLE
Race condition bug in SaveChanges interceptor's post-save handler

### ISSUE THREAD

**Issue by lonix1** [dotnet/EntityFramework.Docs#3645]
The "SaveChanges interception" article shows how to detect, in the post-save handler (`SavedChanges`), which entities were just added/modified/deleted.

But I think the approach is confusing or buggy. In the ["Detecting success"](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#detecting-success) section, it says:
> The audit entity is stored on the interceptor so that it can be accessed again once SaveChanges either succeeds or fails

Say you're in an ASP.NET Core environment, the context is registered normally as scoped (i.e. per request), and the context has an instance of the interceptor. That means everything in that request uses the same context, *and the same interceptor*.

Keeping state within the interceptor leads to a race condition because something else could modify/use it.

Am I misunderstanding? (I hope so, because I'd like to use the code in that article. :smile:)

**If this is a bug, is there an alternative way to do this?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9a8e9e-a397-64b9-419d-fbcf525c3698
* Version Independent ID: f10c27f0-4b5b-c2b7-dd32-fac7b0d8060e
* Content: [Interceptors - EF Core](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#savechanges-interception)
* Content Source: [entity-framework/core/logging-events-diagnostics/interceptors.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/logging-events-diagnostics/interceptors.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@lonix1 in ASP.NET, the same DbContext instance is not shared across requests - each request typically gets its own DbContext instance. Using the same DbContext instance concurrently is not supported ([see this section](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues)).

And since each DbContext instance has its own interceptor instance, you can safely store state information on the interceptor.

**Comment by lonix1** [comment]
Hi @roji thanks for replying! Yep I agree that's why I wrote "per-request". What I meant is that within a single request that winds its way through your entire infrastructure and domain, that one context can be used many times by various parts of the system (all in the same request).

And so the same interceptor is used. And that interceptor is being used to store state for a particular call to `SaveChanges`, and there could be many more, so they would clobber each other. Am I misunderstanding?

**Comment by roji** [comment]
> What I meant is that within a single request that winds its way through your entire infrastructure and domain, that one context can be used many times by various parts of the system (all in the same request).

That's true, but never concurrently. You can of course execute multiple operation on the same DbContext instance in serial (one after the other), but there's no race condition there.

The specific docs sample you referred to ("detecting success") doesn't need to remember state beyond a single operation, so when the second operation occurs, the data from the first indeed gets "clobbered" - which is fine for this case. If for some reason you want your interceptor to remember state from previous operations which have completed, you can do that by writing your interceptor accordingly.

**Comment by lonix1** [comment]
Alright you've given me much to consider - thanks and sorry for the false alert! Happy New Year!

**Comment by lonix1** [comment]
Just to be clear I understand the underlying design, say you have this:

````cs
// make some changes
await context.SaveChangesAsync();      // this triggers interceptor's before and after handlers
// make more changes
await context.SaveChangesAsync();      // this triggers (same) interceptor's before and after handlers
````

The before and after handlers will be complete, BEFORE they are called again for the second save?

**Comment by roji** [comment]
Yep, that's correct. Each before/after pair is called for a specific invocation of SaveChangesAsync.
