### ISSUE TITLE
Updated split query notice

### ISSUE THREAD

**Issue by stap123** [dotnet/EntityFramework.Docs#3660]
The split query notice saying about the issue tracking the additional support is now closed and implemented in EF Core 6.0. I'd guess you want to just delete the "Note" but you may want to keep a note about the difference. (I'm not sure what your preference is)

![image](https://user-images.githubusercontent.com/10199083/148255519-c74e977f-f375-4894-8d9e-cac157a1f420.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43baa9f3-c415-c328-6c10-53aabaaec652
* Version Independent ID: 4e789a1b-aa88-d194-dc2e-0a23251250d7
* Content: [Single vs. Split Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries)
* Content Source: [entity-framework/core/querying/single-split-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/single-split-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks, submit #3666 to amend the note.
