### ISSUE TITLE
Guideline for Microsoft.EntityFrameworkCore.Relational.Specification.Tests

### ISSUE THREAD

**Issue by guscuate** [dotnet/EntityFramework.Docs#3664]
Hello Team,
We would like to run your test suite into our data provider (MySQL Connector/Net), is there any documentation or guide about what is the right way to use Microsoft.EntityFrameworkCore.Relational.Specification.Tests package?

Regards.

**Comment by ajcvickers** [comment]
Note from triage: put screenshot of this in docs. 😜

**Comment by guscuate** [comment]
Hi Roji, I saw you updated the documentation and you mentioned to create an Xunit project, is this strictly required or this can also work using a different test framework like Nunit?

**Comment by roji** [comment]
@guscuate the specification test suite itself is written using xunit, so you'll have to use xunit as well.

Note that this doesn't preclude you from also having an additional test project using nunit or anything else. However, for an EF provider, the specification test suite should generally be the most important testing resource - so it's worth using it even if it isn't your preferred unit testing framework.

FWIW I prefer nunit to xunit (and use nunit in Npgsql), but I use xunit in the Npgsql EF provider for the specification test suite.
