### ISSUE TITLE
NRTS and navigational properties, clarify PropertyAccessMode (or docs are out of date)?

### ISSUE THREAD

**Issue by sommmen** [dotnet/EntityFramework.Docs#3678]
Hi,

I wanted to switch to  enable NRTS and came across the handy document, however there is one thing unclear to me.
The docs say:

> Note that EF must be configured to always access the backing field and not the property, as it relies on being able to read the value even when unset; consult the documentation on backing fields on how to do this, and consider specifying PropertyAccessMode.Field to make sure the configuration is correct.

The docus for `PropertyAccessMode` state:

> The default behavior is PreferField. Prior to EF Core 3.0, the default behavior was PreferFieldDuringConstruction.

In other words - the default is already correct (after .net core 3.0) and no changes need to be made.
this should be more visible in that text (given that i read the documentation for .net3 and above)

The problem is that if i have an existing object, and i try to switch to nrt's i get a weird issue if i try to configure a property,

e.g.

``` csharp
class Order {
    public Guid DomainId { get; set; }
    public Domain {get;set;}
}
```

To:

``` csharp
class Order {
    
    public Guid DomainId { get; set; }

    private Domain? _domain;

    public Domain Domain
    {
        get => _domain ?? throw new InvalidOperationException("Uninitialized property: " + nameof(Domain) + " try loading the entity with .Include()");
        set => _domain = value;
    }

}
```

And:

``` csharp
e.Property(x => x.Domain)
                .UsePropertyAccessMode(PropertyAccessMode.Field);
```

Will result in the following error (net6 and efcore6):

``` csharp
The property or navigation 'Domain' cannot be added to the entity type 'Order' because a property or navigation with the same name already exists on entity type 'Order'.
```

However `.UsePropertyAccessMode(PropertyAccessMode.Field)` is not needed at all anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@sommmen What version of EF Core are you using?

**Comment by sommmen** [comment]
> @sommmen What version of EF Core are you using?

Ef core 6 sir.

**Comment by ajcvickers** [comment]
@sommmen Using the `Property` method configures the `Domain` member as a regular property, when it is actually intended to be a navigation. Use `Navigation` instead:

```C#
        modelBuilder
            .Entity<Order>()
            .Navigation(x => x.Domain)
            .UsePropertyAccessMode(PropertyAccessMode.Field);
```
