### ISSUE TITLE
Code Examples please

### ISSUE THREAD

**Issue by Devlynn** [dotnet/EntityFramework.Docs#3690]
There is a lack of code examples across most of the EF documentation that is posted.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22833d32-1979-01e4-f839-b74a96dbbf74
* Version Independent ID: ab56412a-464e-d13f-62b5-4831e9a61349
* Content: [IndexAttribute.IsUnique Property (System.ComponentModel.DataAnnotations.Schema)](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.schema.indexattribute.isunique?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.ComponentModel.DataAnnotations.Schema/IndexAttribute.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.ComponentModel.DataAnnotations.Schema/IndexAttribute.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@Devlynn the documentation for EF6 is no longer being actively maintained. For EF Core, most of the code samples are in our [conceptual documentation](https://docs.microsoft.com/en-us/ef/core/), with the API documentation usually linking to the relevant page.
