### ISSUE TITLE
Broken xref links in Cosmos provider docs

### ISSUE THREAD

**Issue by Darthruneis** [dotnet/EntityFramework.Docs#3693]
In [this section](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli#provisioned-throughput), there are some broken links:

![image](https://user-images.githubusercontent.com/23741837/150643753-cb16e420-c03a-428d-8a35-b9813fafa799.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738deb7b-d752-f628-3860-fe53891cadb0
* Version Independent ID: e0a18db9-d605-2a78-b77a-d22375dcfd4e
* Content: [Azure Cosmos DB Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/cosmos/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/cosmos/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
This has already been fixed in main, just not published yet.

cc @smitpatel
