### ISSUE TITLE
Please add reference on how to change the default convention for a datatype.

### ISSUE THREAD

**Issue by wdhenrik** [dotnet/EntityFramework.Docs#3695]
I'd like the EFCore default string definition to be varchar(500) not null.  However, I have a limited need for different string lengths, and for unicode strings.  Pre-model configuration doesn't work for this as it ignores any custom configurations applied in the entity.  Its an all or nothing approach.

If would be nice if this page could explain or link to instructions to change the default definition for a data type mapping.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5628451b-252f-b206-3dfc-ae91fb9224bd
* Version Independent ID: 5628451b-252f-b206-3dfc-ae91fb9224bd
* Content: [Model Bulk Configuration - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/bulk-configuration)
* Content Source: [entity-framework/core/modeling/bulk-configuration.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/bulk-configuration.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@wdhenrik 

> Pre-model configuration doesn't work for this as it ignores any custom configurations applied in the entity.

This sounds like a bug. Explicit configuration for properties should override whatever is done in pre-convention model configuration. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
