### ISSUE TITLE
Redirections for new testing docs not working

### ISSUE THREAD

**Issue by koenbeuk** [dotnet/EntityFramework.Docs#3699]
I noticed the docs regarding testing are updated. Before there was an easy to find a url that helped with the getting started experience of testing with SQLLite. A quick search brings this link up:

https://docs.microsoft.com/en-us/ef/core/testing/sqlite

which now returns a 404. The wayback machine can help us uncover a previous version over here: https://web.archive.org/web/20211010161523/https://docs.microsoft.com/en-us/ef/core/testing/sqlite

The archived link includes some sample code on how to share a connection.

The new docs include a link to a section within the docs over here: https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#sqlite-as-a-database-fake

This is useful information but it misses the 'getting started' experience. In addition, there is no quick navigation from the menu. We'll have to spot a deep link regarding SQL Lite over at this page: https://docs.microsoft.com/en-us/ef/core/testing/

This feels like a regression in the docs to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bda9745-35bb-81d2-4b57-7fbb8879eb71
* Version Independent ID: 5bda9745-35bb-81d2-4b57-7fbb8879eb71
* Content: [Choosing a testing strategy - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#sqlite-as-a-database-fake)
* Content Source: [entity-framework/core/testing/choosing-a-testing-strategy.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/choosing-a-testing-strategy.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
I'll take a look at the 404 (the TOC bug is already being handled in #3698), but have you seen [this practical section](https://docs.microsoft.com/en-us/ef/core/testing/testing-without-the-database#sqlite-in-memory) which is linked? It should contain all the information that was present in the old docs.

The general approach is to have [a more conceptual page](https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#sqlite-as-a-database-fake) comparing different strategies (to help users decide what they want), and to have [a separate practical page](https://docs.microsoft.com/en-us/ef/core/testing/testing-without-the-database#sqlite-in-memory) showing how to implement.

**Comment by koenbeuk** [comment]
@roji That was the page that I was looking for! the way I navigated this thing:

1. Google for SQL Lite and EF Core testing which brought me to that 404
2. Find the latest docs which brought me to "Introduction to testing"
3. (As I'm familiar with testing), did a page search for SQLLite and clicked on the link which brought me to an well written page that was not in the navigation tree (and hence I was not able to see the "Testing without your production database" link from that point).

I guess I should have paid more attention but perhaps my experience here helps in tweaking the docs.

Regardless, feel free to close this issue

**Comment by koenbeuk** [comment]
Update: I now see the callback to https://docs.microsoft.com/en-us/ef/core/testing/testing-without-the-database#sqlite-in-memory within the section: "SQLite as a database fake". It's well linked, might need some more standing out but I guess we can conclude that I was lazy. Will close this issue

**Comment by roji** [comment]
Thanks @koenbeuk, don't hesitate to signal anything else you see in the docs.

**Comment by smitpatel** [comment]
> https://docs.microsoft.com/en-us/ef/core/testing/sqlite

If we had link above at any point, we should add redirect for it in docs. Reopening for that.
