### ISSUE TITLE
.NET CLI Page Too Large?

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/EntityFramework.Docs#370]
https://github.com/aspnet/EntityFramework.Docs/blob/live/entity-framework/core/miscellaneous/cli/dotnet.md

I feel like the documentation here should be broken up into more pages, thoughts?

- Installation Page
- Usage: EF-Database Page
- Usage: EF-Context Page
- Usage: EF-Migrations Page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by Rick-Anderson** [comment]
@tdykstra  what's your thoughts?

**Comment by tdykstra** [comment]
@Rick-Anderson We could follow the example of [.NET Core CLI docs](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet) and link to an article for each command. I don't think it would be a high priority, but would be open to someone volunteering to do it.  The title should specify these are EF Core commands, though, not just .NET, and I'll submit a PR for that.

**Comment by Rick-Anderson** [comment]
@tdykstra  lets chat on this over triage.
