### ISSUE TITLE
"https://docs.microsoft.com/en-us/ef/core/testing/testing-sample" can't be accessed

### ISSUE THREAD

**Issue by stevenml** [dotnet/EntityFramework.Docs#3705]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33851e00-5992-c9c8-d9b6-428ba8bde6a9
* Version Independent ID: 793410c2-2e9f-e31e-7e2c-ac766eac451b
* Content: [Overview of testing applications that use EF Core - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/)
* Content Source: [entity-framework/core/testing/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@stevenml that link works for me, but where exactly are you seeing it in that page?
