### ISSUE TITLE
Sample for updating disconnected scenario has issue

### ISSUE THREAD

**Issue by TomasB** [dotnet/EntityFramework.Docs#3711]
https://github.com/dotnet/EntityFramework.Docs/blob/80c51a37ef113ca72fdf458878b8d6e56ed59275/samples/core/Saving/Disconnected/Sample.cs#L512

Imagine, Blog arrives with two *new* posts attached.  What is going to happen in ../Disconnected/Sample.cs#L512 on first iteration, is that it will not find db value, so it's going to be null, because, lets assume, there is no post with id=0, so it will add post to the context, and since id is int, post.Id will be equal to 0 in the context.
When the loop goes through 2nd post, it will *find* a new added post, since again, it will try to use postId=0, and such post now exists in the context.

**Comment by ajcvickers** [comment]
@TomasB This example is _specifically_ for entities that do not have automatically generated key values--see [Mix of new and existing entities](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities#mix-of-new-and-existing-entities) This means the application must set the key value explicitly for each entity. Explicitly setting two entities to the same key value is not a valid thing to do.
