### ISSUE TITLE
Go to the link it says to go to... And what use instead??

### ISSUE THREAD

**Issue by JHF217** [dotnet/EntityFramework.Docs#3712]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21434a2-9f80-b04b-f8d7-b63eee000407
* Version Independent ID: 78f0bdb8-6553-a7cf-450f-167d522160d0
* Content: [SqlServerDbContextOptionsBuilder.UseRowNumberForPaging Method (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.sqlserverdbcontextoptionsbuilder.userownumberforpaging?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Link is https://ak.ms/AA6h122 instead of https://aka.ms/AA6h122 (missing "a"). This is for 3.1 documentation only - we can maybe fix it directly in the docs site..

**Comment by smitpatel** [comment]
It is in draft work I have. Waiting for scoping related changes in source code.
