### ISSUE TITLE
.Include(blog => blog.Owner.AuthoredPosts) vs .Include(blog => blog.Owner).ThenInclude(x => x.AuthoredPosts)

### ISSUE THREAD

**Issue by TomasB** [dotnet/EntityFramework.Docs#3714]
"You can also load multiple navigations using a single Include method. This is possible for navigation "chains" that are all references, or when they end with a single collection."

While the "Tip" suggests that it's possible to use `.Include(entity => entity.A.B)`, I couldn't find any explanation what is the difference compared to when `.Include(entity => entity.A).ThenInclude(x =>x.B)` is used.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a3ce6e-43ab-e0af-01b3-a82fdaf3cb31
* Version Independent ID: 320e7305-e0a3-a1c6-77f2-1d3029b660b1
* Content: [Eager Loading of Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager)
* Content Source: [entity-framework/core/querying/related-data/eager.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/related-data/eager.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
There is no difference in behavior.

**Comment by TomasB** [comment]
Even when ".A" was defined as "virtual" ?

**Comment by ajcvickers** [comment]
@TomasB It makes no difference whether the navigation is virtual or not. All any of the syntax choices do is provide a "path" of navigations. You could even use a string: "A.B".

The reason that ThenInclude is preferred is that it is a consistent and type-safe API that works for both reference and collection navigations. The "dotting" shortcut only works for reference navigations.

**Comment by TomasB** [comment]
This kind of information what I was looking in docs: 
"The reason that ThenInclude is preferred is that it is a consistent and type-safe API that works for both reference and collection navigations. The "dotting" shortcut only works for reference navigations."

With links into more information related to reference vs collection navigations.

**Comment by ajcvickers** [comment]
@TomasB There is always a balance between stating everything and keeping the docs concise enough to be easily consumable. We don't think making any change here will be overall advantageous.
