### ISSUE TITLE
Not much information about the InMemory Provider

### ISSUE THREAD

**Issue by AndiRudi** [dotnet/EntityFramework.Docs#3718]
I wanted to see if the InMemory Provider supports transactions. I know it's limited, but the page doesn't really list what it can and what it can't and because it's the first page coming up in a search it should probably list that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40dffa7d-bea9-8bce-e409-3ef8bf46d08a
* Version Independent ID: 970f6835-a930-3321-212f-a9be6c17ef79
* Content: [InMemory Database Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/in-memory/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/in-memory/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/in-memory/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@AndiRudi you probably want to give our [testing docs](https://docs.microsoft.com/en-us/ef/core/testing/) a read - they give an overview of the different testing techniques, and why the in-memory provider is a bad choice.

Concretely, we will not be adding transaction support to in-memory - that would amount to asking us to write a full database implementation. The in-memory cannot and will never duplicate the functionality of your production database system. You can either use SQLite's in-memory mode - which supports transactions and is closer to a real relational database - or run tests against your real database system, ensuring full fidelity between your tests and your production application ([this doc page](https://docs.microsoft.com/en-us/ef/core/testing/testing-with-the-database) has guidance for doing that).

**Comment by roji** [comment]
[This table](https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#overall-comparison) specifically may help understand what in-memory supports and what it doesn't, compared to other testing techniques.
