### ISSUE TITLE
SqLite Transactions:Yes, but Ambient Transactions:No?

### ISSUE THREAD

**Issue by AndiRudi** [dotnet/EntityFramework.Docs#3719]
I was writing an article on how to use Transactions and while writing example code using SqLite I noticed an exception 

```
An error was generated for warning 'Microsoft.EntityFrameworkCore.Database.Transaction.AmbientTransactionWarning': An ambient transaction has been detected, but the current provider does not support ambient transactions
```

First I thought transactions may not work with SqLite but in the table it looks like it should work. I assume that this table means only internal transactions (EF-Core SaveChanges), right? Maybe the table should have a separate row for ambient transactions (`new TransactionScope()`). 

Or am I wrong completely?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bda9745-35bb-81d2-4b57-7fbb8879eb71
* Version Independent ID: 5bda9745-35bb-81d2-4b57-7fbb8879eb71
* Content: [Choosing a testing strategy - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#overall-comparison)
* Content Source: [entity-framework/core/testing/choosing-a-testing-strategy.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/choosing-a-testing-strategy.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
System.Transactions ("ambient transaction support") is indeed not supported by Microsoft.Data.SQLite, this is tracked by https://github.com/dotnet/efcore/issues/13825.

But regular (non-ambient) transactions are definitely supported, which you can control manually with APIs such as BeginTransaction. See the [transaction docs](https://docs.microsoft.com/en-us/ef/core/saving/transactions) for more details.

**Comment by AndiRudi** [comment]
Thanks @roji for clarifying. 

PS: The idea of the article was to have a transaction around SaveChanges and RabbitMQ. I wanted to ensure that a saved record is only committed when an event was added to the queue. Therefore I wanted to wrap a System.Transaction around both.

**Comment by roji** [comment]
@AndiRudi what you're describing is a distributed transaction, which again is something else; distributed transactions are currently unsupported in .NET 5+, regardless of any SQLite support (see https://github.com/dotnet/runtime/issues/715).

To summarize:
* You can use regular, non-ambient transactions today (via the BeginTransaction API), with SQLite or other relational databases.
* You can also use ambient System.Transactions.Transaction, as long as it's over a single data source - but specifically not with Microsoft.Data.SQLite. https://github.com/dotnet/efcore/issues/13825 tracks adding support for that.
* You currently cannot use ambient System.Transactions.Transaction over multiple data sources (distributed transaction), regardless of database. https://github.com/dotnet/runtime/issues/715 tracks support for that.
While ambient System.Transactions.Transaction
