### ISSUE TITLE
How to completely track entities manually? - Update Documentation

### ISSUE THREAD

**Issue by jasekiw** [dotnet/EntityFramework.Docs#3720]
This document explains the following:

> If you disable automatic detect changes then you must ensure that [DetectChanges()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.changetracker.detectchanges?view=efcore-6.0#microsoft-entityframeworkcore-changetracking-changetracker-detectchanges) is called when entity instances have been modified. Failure to do so may result in some changes not being persisted during [SaveChanges()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.savechanges?view=efcore-6.0#microsoft-entityframeworkcore-dbcontext-savechanges) or out-of-date change tracking information being returned.

If you have to call `DetectChanges` anyways, then what's the point of turning off `AutoDetectChangesEnabled`?

I have been using `context.Entry(entity).State = DesiredState` in a long running batch process that needs to run quickly. For the most, it seems to behave correctly (there has been some weirdness in some places). I don't call `DetectChanges` at all.

Is this a supported way to manually track entities? I'd much rather manually track entities than have ef core infer what I want to do (which is not always right by the way).

I also specifically don't want to track entities relates to the current entity that I am tracking. Most of my entities are there just for cache and don't need to be referenced by the change tracker to speed up saving, `context.Entry(entity).State = DesiredState` seems to prevent the auto detection of navigation properties which is what I want.

Is this a proper way of using ef core? If it is then this documentation should be updated to reflect it. A larger article about manually change tracking should be written as well and linked to from here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71dbac6c-3e0b-4986-e6de-20c9b24d3943
* Version Independent ID: b09d66fc-deef-9ae3-5048-1b27144df4ef
* Content: [ChangeTracker.AutoDetectChangesEnabled Property (Microsoft.EntityFrameworkCore.ChangeTracking)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.changetracker.autodetectchangesenabled?view=efcore-6.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.ChangeTracking/ChangeTracker.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.ChangeTracking/ChangeTracker.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by jasekiw** [comment]
Edit:
I found that checking the state of an entity calls DetectChanges which then traverses to it's related entities and marks them as modified. How can this be prevented? 

```
Context.Entry(someEntity).State != EntityState.Added
```

class SomeEntity {

  SomeOtherEntity SomeOtherEntity{get;set;} -> set to a reference
  int SomeOtherEntityId {get;set;} -> set to a value
}


I don't want SomeOtherEntity to be read at all by the change tracker. It needs to be read in other contexts but not in this one. How can this be done?

**Comment by ajcvickers** [comment]
@jasekiw If all changes made to an entity are done through EF API calls, then DetectChanges is not needed and need not be called either automatically or otherwise. However, doing this requires care--it is easy to get the graph of entities into an inconsistent state.

**Comment by jasekiw** [comment]
@ajcvickers 



> Edit: I found that checking the state of an entity calls DetectChanges which then traverses to it's related entities and marks them as modified. How can this be prevented?
> 
> ```
> Context.Entry(someEntity).State != EntityState.Added
> ```
> 
> class SomeEntity {
> 
> SomeOtherEntity SomeOtherEntity{get;set;} -> set to a reference int SomeOtherEntityId {get;set;} -> set to a value }
> 
> I don't want SomeOtherEntity to be read at all by the change tracker. It needs to be read in other contexts but not in this one. How can this be done?

I am okay with possibly getting into an inconsistent state. This is how things were managed before EF came along anyways.
I wonder why however that when the following is called, DetectChanges is called even though `AutoDetectChangesEnabled` is set to false?
 ```
Context.Entry(someEntity).State != EntityState.Added
```

What api calls do I need to call in order to prevent EF core from detecting it's own changes?
Simply doing this:

```
context.Entry(entity).State = DesiredState
```
is not enough as found from my previous post.

**Comment by ajcvickers** [comment]
@jasekiw Looks like that is a bug; I filed https://github.com/dotnet/efcore/issues/27389
