### ISSUE TITLE
Please can you show the imports at the top

### ISSUE THREAD

**Issue by Tiltimus** [dotnet/EntityFramework.Docs#3727]
As a new comer it is extremely frustrating to try and work out what package things belong to. Comparing this to Haskell which is pretty explicit this becomes mind boggling to have to work out. Would it be possible to update the code example to reflect this feedback, pretty please with a cherry on top.

Much love some random dev learning your stuff <3

**Comment by roji** [comment]
@Tiltimus this has been discussed before, and we've decided that adding imports for all code samples would make them extremely verbose. More importantly, modern IDEs automatically suggest adding those imports, so this is typically not necessary - which IDE are you using?

**Comment by Tiltimus** [comment]
"would make them extremely verbose" common... its what maybe 2 - 5 lines max but okay. Just inconsistent as some of the examples have the import (example: https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli). Using vscode as the code editor. Its not really that big of an issue just annoying as a new comer to the space.

**Comment by roji** [comment]
@Tiltimus we do show imports for very basic "getting started" apps, to help out completely new users. But the docs are littered with small code samples, and adding imports to each and every one would needlessly inflate them...

**Comment by ajcvickers** [comment]
@Tiltimus Was the issue that you didn't have the NuGet package installed, or that you had the NuGet package, but couldn't find the correct namespace to use?

**Comment by ajcvickers** [comment]
See https://github.com/dotnet/EntityFramework.Docs/pull/3681
