### ISSUE TITLE
Performance documentation page seems incorrect about a lack of adding to the cache, based on my testing

### ISSUE THREAD

**Issue by kevinpohlmeier** [dotnet/EntityFramework.Docs#3731]
In the section titled "Using the properties of a non-mapped object", it says "When a query uses the properties of a non-mapped object type as a parameter then the query will not get cached". I am not able to reproduce that issue. Did it maybe get fixed in a version of EF after the article was written? I'm using 6.4.4. 

I see that the output SQL uses @p__linq__0 for parameterization, and I used reflection to see that a LinqQueryCacheKey entry was added to the QueryCacheManager's _cacheData.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c43dbd-bc48-38f2-0eb8-52a580178d75
* Version Independent ID: 1c41b1c2-4388-c757-b8d3-e9538d17f72e
* Content: [Performance considerations for EF4, EF5, and EF6 - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/performance/perf-whitepaper)
* Content Source: [entity-framework/ef6/fundamentals/performance/perf-whitepaper.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/performance/perf-whitepaper.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
