### ISSUE TITLE
Link broken to ToInMemoryQuery sample

### ISSUE THREAD

**Issue by supermitsuba** [dotnet/EntityFramework.Docs#3744]
[Enter feedback here]
This link doesnt work.  https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core/Miscellaneous/Testing/ItemsWebApi/

Im having an issue testing a view and this is the use case I need help with.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc10f39-8fe5-e856-5839-9aa5e9d435c6
* Version Independent ID: 10ddba97-42d2-0cda-3e7f-eaeb4fda74b0
* Content: [Keyless Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/keyless-entity-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/keyless-entity-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
The sample including ToInMemoryQuery was removed as part of #3539, I just submitted #3745 which adds conceptual documentation for it as well. @supermitsuba you can examine that to see the sample.
