### ISSUE TITLE
Code examples not showing up

### ISSUE THREAD

**Issue by meeple142** [dotnet/EntityFramework.Docs#3746]
this code example is not showing up
https://github.com/dotnet/EntityFramework.Docs/blob/fffef2fe81839b51a88d4a6c3bd8ca368ac7637a/entity-framework/core/testing/testing-with-the-database.md?plain=1#L57

I think it's trying to referance the AddBlog function here
https://github.com/dotnet/EntityFramework.Docs/blob/fffef2fe81839b51a88d4a6c3bd8ca368ac7637a/samples/core/Testing/BloggingWebApi/Controllers/BloggingController.cs#L32

I believe this
```
[!code-csharp[Main](../../../samples/core/Testing/BloggingWebApi/Controllers/BloggingController.cs?name=PostBlog)]
```
should be
```
[!code-csharp[Main](../../../samples/core/Testing/BloggingWebApi/Controllers/BloggingController.cs?name=AddBlog)]
```

Also this example is not showing up but I'm not sure why
https://github.com/dotnet/EntityFramework.Docs/blob/fffef2fe81839b51a88d4a6c3bd8ca368ac7637a/entity-framework/core/testing/testing-with-the-database.md?plain=1#L75

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7fc3c3b-c859-2ad5-78f3-ce57d3c9bc2d
* Version Independent ID: b7fc3c3b-c859-2ad5-78f3-ce57d3c9bc2d
* Content: [Testing against your Production Database System - EF Core](https://docs.microsoft.com/en-us/ef/core/testing/testing-with-the-database)
* Content Source: [entity-framework/core/testing/testing-with-the-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/testing-with-the-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@meeple142 thanks - submitted #3747 to fix these. FYI you can submit a PR with fixes directly rather than issue describing the proposed fixes.
