### ISSUE TITLE
Help with the table

### ISSUE THREAD

**Issue by jsmarsch** [dotnet/EntityFramework.Docs#3753]
[Enter feedback here]
I'm sorry, I don't quite grock how to read the version table here.  Does this indicate that .Net Standard 2.1 supports EF Core 5.0? (I thought it supported EF Core 2.1)

And doe sit also indicate that you can use EF Core 3.1 with .Net Classic 4.7.2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a720e16e-991f-6802-033c-63269ad8a435
* Version Independent ID: 9d6e9856-615b-0eb0-bf04-6a7ee3d6949d
* Content: [Supported .NET implementations - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms#feedback)
* Content Source: [entity-framework/core/miscellaneous/platforms.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/platforms.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
Yes and yes

**Comment by jsmarsch** [comment]
Thank you!
