### ISSUE TITLE
Document that ADO.NET connections are not reset when using context pooling

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/EntityFramework.Docs#3761]
See https://github.com/dotnet/efcore/issues/27308

**Comment by ajcvickers** [comment]
Note from triage: This is actually not a breaking change, since code needs to be updated to use pooling to hit this case. We have also improved the cleanup in this scenario so that from EF7 onwards it is unlikely to be an issue even if an application is not cleaning up connections appropriately.
