### ISSUE TITLE
Include the models used in examples in "Explicit Loading of Related Data"

### ISSUE THREAD

**Issue by RageCage64** [dotnet/EntityFramework.Docs#3774]
Thanks for all the work on these great docs! 
The issue I am currently having with this document is that the actual models used in the examples are not specified. While it can be inferred based on the examples what exactly the models are, it would be really helpful to also see those models so there can be a more complete context of what the example is doing. Mainly my issue was that I didn't understand whether the Explicit Loading pattern required that the relating entities are nullable, i.e.:

```cs
public class Blog 
{
  public int Id { get; set; }

  // Is this supposed to be nullable? Does it start as an empty list until loaded?
  public List<Post>? Posts { get; set; }  
  
  // Is this supposed to be nullable? I assume it starts as null until loaded.
  public int? BlogId { get; set; }
  public Blog? Blog { get; set; }
}
```
I imagine this information is either obvious to those more experienced with Entity Framework Core, or is detailed in another part of the docs, but as someone who came to this doc relatively new and trying to gather context from here, I felt like I was in the dark on these specifics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc261727-1ecd-5dcb-fb88-1b1762263789
* Version Independent ID: a15c2f82-ebb7-9867-50ad-35f80366528f
* Content: [Explicit Loading of Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data/explicit#feedback)
* Content Source: [entity-framework/core/querying/related-data/explicit.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/related-data/explicit.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@RageCage64 The models are available in the referenced GitHub samples. See https://docs.microsoft.com/en-us/ef/core/querying/related-data/
