### ISSUE TITLE
Excellent work of the detailed explanation

### ISSUE THREAD

**Issue by kdaveid** [dotnet/EntityFramework.Docs#3776]
Positive Feedback: **No action required!**

Just wanted to thank you for the effort you took to (it seems) completely explain how EF works. I have used this product from the beginning and have experience with similar ORMs but these days I really _enjoy_ reading the docs. 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9ed2194-60b2-1612-7565-17b663e15acd
* Version Independent ID: 377fbb7c-597b-7203-49fa-2a4ca6319c53
* Content: [Changing Foreign Keys and Navigations - EF Core](https://docs.microsoft.com/en-us/ef/core/change-tracking/relationship-changes#relationship-fixup)
* Content Source: [entity-framework/core/change-tracking/relationship-changes.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/change-tracking/relationship-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Thanks!
