### ISSUE TITLE
Sidebar Link for "DbContext configuration and initialization">"Context pooling" Leads to this Page

### ISSUE THREAD

**Issue by erhanalankus** [dotnet/EntityFramework.Docs#3777]
Hello,

Sidebar link for "DbContext configuration and initialization">"Context pooling" leads to this page.
Having the sidebar link for "Context pooling" suggests that it is a separate page, but it isn't. It loads the "Advanced Performance Topics" page.
I think it's a mistake.
See image: [https://imgur.com/a/yiFVl9E](https://imgur.com/a/yiFVl9E)

Thanks,
Erhan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e638463f-fec2-ca39-37a4-b3580fa874d8
* Version Independent ID: e96b453f-0256-8bc9-bd21-1343f2fe246c
* Content: [Advanced Performance Topics](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling)
* Content Source: [entity-framework/core/performance/advanced-performance-topics.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/performance/advanced-performance-topics.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@erhanalankus This is because we moved things around, but still wanted people to easily be able to find info on context pooling. We may create a separate doc at some point, but for now that page is the best source of information.
