### ISSUE TITLE
No default Target location indicated after scripting migration

### ISSUE THREAD

**Issue by CutieDaisy** [dotnet/EntityFramework.Docs#3785]
[Enter feedback here]
Please at least provide the target location (directory) for the generated script in the Docs after running 'dotnet ef migrations script'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06b35eff-79e4-2068-6d1c-f9079d43f903
* Version Independent ID: 6c575b10-048c-349c-397e-0d9c11d47235
* Content: [Applying Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/applying.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/applying.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@CutieDaisy The default target is to send the script to standard out.
