### ISSUE TITLE
NRTs are enabled by default in .NET 6

### ISSUE THREAD

**Issue by marcinjahn** [dotnet/EntityFramework.Docs#3788]
The page has the following excerpt regarding NRTs:

> This feature is disabled by default, and affects EF Core's behavior in the following way:

The truth is that in .NET 6. NRTs are enabled by default, making that sentence false.

Addtional excerpts that should be changed:

> If nullable reference types are disabled (the default)

> The following example shows an entity type with required and optional properties, with the nullable reference feature disabled (the default) and enabled:

Please let me know if you want me to create a PR with appropriate changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4381838-81bb-52c6-d921-f8b9ae8163d2
* Version Independent ID: 892a8dd8-7a63-ce0b-de20-27e92b88f971
* Content: [Entity Properties - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt)
* Content Source: [entity-framework/core/modeling/entity-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/entity-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
> The truth is that in .NET 6. NRTs are enabled by default, making that sentence false.

AFAIK you still have to opt into NRTs by setting `<Nullable>enable</Nullable>` in your csproj. The project templates have been modified to do that, but with existing csproj files that don't contain the property, NRTs stay disabled. We could still amend the text to be clearer.

**Comment by marcinjahn** [comment]
Right, if you create a new project right now with .NET 6 SDK, you will have it enabled. Well, I found it a bit misleading and had a feeling that the information is outdated, but it's not something critical for sure.
