### ISSUE TITLE
Question on using DbContext pooling in a multi-tenant application

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/EntityFramework.Docs#3791]
In Performance notes section of this document you say:
> If this approach is impacting the performance of your application, consider using [DbContext pooling](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics).

The problem is when working with multi-tenant you a likely have a different connection string on every instance of the creation of the database. Won't DbContext pooling cause a problem in this case, or have you got a work around in the case of the connection string chancing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb29a2b6-c401-287f-2da9-1aeb3c633b41
* Version Independent ID: bb29a2b6-c401-287f-2da9-1aeb3c633b41
* Content: [Multi-tenancy - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/multitenancy)
* Content Source: [entity-framework/core/miscellaneous/multitenancy.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/multitenancy.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by roji** [comment]
You'd probably be interested in [this section](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#managing-state-in-pooled-contexts), which explains how to do context pooling with tenant IDs (without changing the connection string per tenant).

If you're changing connection strings per tenant, you should still be able to change the connection string on the pooled context before returning it from the factory (just like the tenant ID is changed in the sample I linked to). Do you see any particular issue with that?

**Comment by JonPSmith** [comment]
Hi @roji,

I hadn't seen that approach before and I hadn't seen `IDbContextFactory<DbContext>` before. From looking at that the `IDbContextFactory<T>` returns a pooled instance, which you then alter the instance by setting the TenantId (or in my case using `SetConnectionString` to change the connection string). Have I understood that correctly?

**Comment by roji** [comment]
Yep, that's pretty much it. The scoped IDbContextFactory is just a place where we can apply some scoped information (the tenant ID) before returning the pooled context instance to the user.

**Comment by JonPSmith** [comment]
Thanks @roji . Another learning opportunity.
