### ISSUE TITLE
TOC Show More is terrible.

### ISSUE THREAD

**Issue by peschkaj** [dotnet/EntityFramework.Docs#3805]
This one is for the docs team:

The "show more" in the table of contents is terrible UI. For the love of all that is good and holy in the universe, remove this non-feature and stop changing things just because you have a KPI of "jiggling the codebase".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace4ee8e-1c39-ceba-0e31-558c4fe6ce32
* Version Independent ID: ace4ee8e-1c39-ceba-0e31-558c4fe6ce32
* Content: [Plan for Entity Framework Core 7.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/plan)
* Content Source: [entity-framework/core/what-is-new/ef-core-7.0/plan.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-7.0/plan.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
I looked at the page linked above and few other pages to see general formatting.
- The TOC on left pane (for navigating through different doc pages) doesn't have show more button but it adds scroll bar for that pane only when the screen size is smaller.
- The TOC on right pane which shows sections on the current page has show more button. Which is working correctly. It does wrapping if the screen is not wide enough to show titles in one line.

There is nothing problematic or actionable here.

**Comment by roji** [comment]
FWIW I also think the "show more" button is bad UX. It's certainly working as intended, but all it does is added an additional click where it wasn't needed previously. But in any case, that's a general doc UI thing, and not specific to us.
