### ISSUE TITLE
Formatting is Broken

### ISSUE THREAD

**Issue by erhanalankus** [dotnet/EntityFramework.Docs#3806]
See the overloads table at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c12c8ec3-04e8-3442-110d-5d4cc9322921
* Version Independent ID: f1071d87-f76d-e8ad-7b90-568b98889c9e
* Content: [EF.CompileQuery Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.ef.compilequery?view=efcore-6.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EF.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EF.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Also for CompileQueryAsync.

**Comment by smitpatel** [comment]
I have raised issue with docs team in terms of how to improve this page.

**Comment by smitpatel** [comment]
This has been fixed by docs team last month.
