### ISSUE TITLE
Received exception when performing transaction

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/EntityFramework.Docs#3812]
Following the guidance in this section returned an exception.

```
System.InvalidOperationException: The configured execution strategy 
'SqlServerRetryingExecutionStrategy' does not support user initiated transactions. 
 Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' 
 to execute all the operations in the transaction as a retriable unit.
```

I think a note, or callout, to the other approach to addressing this issue could be added to the `Controlling transactions` section to help others find this link that resolved the exception.

https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency#execution-strategies-and-transactions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions#controlling-transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@KSchlobohm makes sense, I submitted #3814 to add such a note.
