### ISSUE TITLE
Documents without. Github link

### ISSUE THREAD

**Issue by martin-scheringa** [dotnet/EntityFramework.Docs#3815]
Why is there not an GitHub repository with the code.

Greeting,

Martin.

**Comment by roji** [comment]
@martin-scheringa all the code samples for the EF Core documentation can be found [here](https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core) - there's a single solution you can open for all samples.

On most pages, we have an explicit section linking to the samples for that page, see e.g. [this page](https://docs.microsoft.com/en-us/ef/core/querying/client-eval).
