### ISSUE TITLE
The text on the page overflow without a scrollbar

### ISSUE THREAD

**Issue by skrabbe001** [dotnet/EntityFramework.Docs#3816]
The text on the page overflows to the right, so you can't read it - and there is no scrollbar to scroll right - and selecting the text and trying to scroll that way doesn't work either.

Tested with the latest Brave chromiom browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c72944d4-5871-b0f8-8a13-56aa2aaebf72
* Version Independent ID: fc179736-e36b-2534-b37d-221ce63d38de
* Content: [RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlrawasync?view=efcore-6.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@skrabbe001 I can't reproduce this. Can you post a screenshot of what you are seeing?

**Comment by skrabbe001** [comment]
@ajcvickers I retried just now, and can't reproduce it either!?! The page renders as expected. I can see that the Brave browser upgraded Chromium to 100.0.4896.127 on the 14th of April, which must have fixed the issue: https://brave.com/latest/

**Comment by skrabbe001** [comment]
The error may have been caused by an older version of Chromium.
