### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by zanejgr** [dotnet/EntityFramework.Docs#3821]
The following links in the Remarks section are broken
[Managing database schemas with EF Core](https://aka.ms/efcore-manage-schemas) 
[Database creation APIs](https://aka.ms/efcore-ensure-created) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76d2b52-af12-f9ce-f62b-1e5adafbb277
* Version Independent ID: e793c86d-5fb2-13f8-a571-748b8a9319a1
* Content: [DatabaseFacade.EnsureCreated Method (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.ensurecreated?view=efcore-6.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/DatabaseFacade.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/DatabaseFacade.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by JeremyLikness** [comment]
Addressed in [PR #23709](https://github.com/dotnet/efcore/pull/27309).
