### ISSUE TITLE
Create data hub

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/EntityFramework.Docs#3833]
There is no centralized hub for .NET Data. Create one so .NET developers can easily navigate to our documentation for:

- relational, document, and graph databases 
- ORM (EF Core)
- distributed cache, key/value store – Orleans, Azure Redis
- blob storage 
- event management (bus, queue, event store)
- API (gRPC, SignalR, OData, GraphQL)
- serialization – Text.Json, Xml
- big data - .NET for Spark
- machine learning – ML.NET
- ETL - Synapse

**Comment by ErikEJ** [comment]
Table storage ?

**Comment by JeremyLikness** [comment]
> Table storage ?

falls under blob and key/value

**Comment by JeremyLikness** [comment]
Proposed hierarchy:

```mermaid
graph TD
A(.NET Data) --> AA[Databases]
A --> AB[Data Services]
A --> AC[APIs]
AA --> AAA[Relational]
AA --> AAB[Document]
AA --> AAC[Graph]
AA --> AAD[Distributed Key/Value]
AA --> AAE[Storage / Blob]
AA --> AAF[EF Core]
AB --> ABA[LINQ]
AB --> ABB[Big Data]
AB --> ABC[Machine Learning]
AB --> ABD[ETL]
AB --> ABE[Analytics]
AB --> ABF[Events]
AC --> ACA[REST]
AC --> ACB[OData]
AC --> ACC[GraphQL]
AC --> ACD[CoreWCF]
AC --> ACE[gRPC]
AC --> ACF[SignalR]
```

Top level is section, nodes are cards, each card will have 2 - 6 links.

**Comment by ErikEJ** [comment]
DacFX?

**Comment by JeremyLikness** [comment]
Closed per [PR 3954](https://github.com/dotnet/EntityFramework.Docs/pull/3954)
