### ISSUE TITLE
Records as owned entity types?

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/EntityFramework.Docs#3842]
Then article makes no mention of the [records introduced in C# 9.0](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#record-types).
Can a `record` be used instead of a `class` for owned entity types?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@vanillajonathan They should work okay for this scenario. Let us know how it goes.

**Comment by vanillajonathan** [comment]
@ajcvickers I would like the article to mention records.
