### ISSUE TITLE
Exclude Tables

### ISSUE THREAD

**Issue by MikeMcWilliams** [dotnet/EntityFramework.Docs#3862]
In a project, I am leveraging DataProtectionKey from using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore and unable to exclude the DataProtectionKeys table from scaffolding.   I have a partial class file that is intended not to be a part of the scaffolding.  How can the DataProtectionKeys table be ignored in the scaffolding?  (It's not optimal to maintain a table (--table option) to list the tables for scaffolding)  Please advise.

**MyContextPartial.cs**
```
using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

public partial class MyContext : DbContext, IDataProtectionKeyContext
{
   virtual public DbSet<DataProtectionKey> DataProtectionKeys { get; set; } = null!; <--This is the correct implementation from the using/namespace above.
}
```

**MyContext.cs**
This file is scaffolded by ef-core and contains all the tables  including `DataProtectionKeys` which should be skipped/ignored.
```
public partial class MyContext : DbContext, IDataProtectionKeyContext
{
    public virtual DbSet<DataProtectionKey> DataProtectionKeys { get; set; }  <--This property (table) should not be scaffolded/excluded
    ... other scaffolded tables
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1601c3e-3f29-5d84-6350-2b38eeaf6adc
* Version Independent ID: 92a856d6-c5da-e215-46ac-d67c411f3ff9
* Content: [Reverse Engineering - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/scaffolding.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
Try EF Core Power Tools, has a UI and persistence of table selection

**Comment by MikeMcWilliams** [comment]
> Try EF Core Power Tools, has a UI and persistence of table selection

Thank you for the rapid reply!  Unfortunately we need to be able to do this without a UI for our CI/CD pipeline.  Table exclusion on DataProtectionKey(s) (a microsoft .net class appears to be the best option.)
Right now, I just comment the DBSet that scaffold creates in the context and remove the DataProtectionKey scaffolded class.

**Comment by ErikEJ** [comment]
@MikeMcWilliams Design time activities during CI/CD sounds dangerous to me.

**Comment by MikeMcWilliams** [comment]
Our SQL Server Database Project, which is also in the .sln, directly drives the models via scaffolding. 

We call it “Source First” Instead of “database first” or “code first”.  The concept is that the schema  (“source code” in the database project) is king.  We will not use migrations and drive deployment through SQLPackage.exe.  Scaffolding provides the models.  Its a two or three-step process but it’s 100% scriptable. The really good news from a database perspective is that our DBAs love the approach.  The Devs are new to this process and currently do manual alter scripting.  

If I can figure out how to get this last piece in I think everything will be tied together beautifully.

**Comment by ErikEJ** [comment]
Sweet. So you are using my dacpac scaffolding library.

It is possible to use EF Core Power Tools from the command line  but not supported.

**Comment by ErikEJ** [comment]
I was referring to this package, that let's you scaffold directly from a .dacpac (with a few limitations) https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/

**Comment by bricelam** [comment]
Hmm, without https://github.com/dotnet/efcore/issues/6182, the recommend way to do this in would be, as you said, to use the `--table` option.

If you really want to avoid that, you could override the [design-time service](https://docs.microsoft.com/ef/core/cli/services) that reads from the database.

```cs
class MyDatabaseModelFactory : SqlServerDatabaseModelFactory
{
    public override DatabaseModel Create(string connectionString, DatabaseModelFactoryOptions options)
        => Fixup(base.Create(connectionString, options);

    public override DatabaseModel Create(DbConnection connection, DatabaseModelFactoryOptions options)
        => Fixup(base.Create(connection, options);

    DatabaseModel Fixup(DatabaseModel database)
    {
        var dataProtectionKeys = database.Tables.First(t => t.Name == "DataProtectionKeys");
        database.Tables.Remove(dataProtectionKeys);

        return database;
    }
}
```

It will also be able to skip over it using a custom template once we ship https://github.com/dotnet/efcore/issues/4038.

**Comment by MikeMcWilliams** [comment]
Are table exclusions available now?

**Comment by bricelam** [comment]
@MikeMcWilliams Tracked by https://github.com/dotnet/efcore/issues/6182
