### ISSUE TITLE
Alternate process for dealing with ef6 migrations with multiple developers.

### ISSUE THREAD

**Issue by rtmann** [dotnet/EntityFramework.Docs#3863]
Alternatively what you can do is have every developer work in a local branch that isn't the main branch and do whatever migration they need to do and just commit to their own local branch.

Using git

- Each developer has cloned master and checked out a new branch for their work
- Each developer has a migration
- A list "queue" is maintained of who has the migration path next.
- When the person next in line has pushed their code to master, each other developer rolls back their migration and stashes their changes and checks out master, pulls the latest code, then runs "Update-Database" from master.
-Now each developer checks their branch back out and unstashes their changes.
-Now each developer deletes and readds their migrations causing it to rescaffold the same changes they had before but in the correct order

Now each developer can continue working until the next person in the queue get's their migration in.

It takes me all of about 5 minutes to pull down all the latest migrations and do this process as an individual developer and you don't need to worry about snapshots or having blank migrations.  Just a slight annoyance of a process.

It get's even easier if you use git worktrees where you can checkout multiple branches at once.  I just keep master checked out to it's own worktree folder so I can just rollback in visual studio in my branch and run update database in the master branch.  That way I don't need to stash my changes in my branch, just need to merge in master after update database runs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b72ecde8-e983-8583-7c3f-6e0e4ff404fb
* Version Independent ID: 6ed79d63-19a7-c527-b383-c5faf4beba55
* Content: [Code First Migrations in Team Environments - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/teams)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/teams.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/migrations/teams.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.
