### ISSUE TITLE
does not seem to work with 6.0.5 as it generates a migration error 

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/EntityFramework.Docs#3867]
[Enter feedback here]

there is no way I seem to be able to make this work, is there a possibility to get a working code sample?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34d3f39-600f-0c37-a0a4-11a245d3010c
* Version Independent ID: 5b51ed49-1035-1a8f-a08e-7400d571c77b
* Content: [User-defined function mapping - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping)
* Content Source: [entity-framework/core/querying/user-defined-function-mapping.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/user-defined-function-mapping.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @maumar
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
What errors do you get? What is not working?

**Comment by PeterPann23** [comment]
```
builder.Entity<ProductForRegion>()
                   .HasNoKey()
                   .ToFunction(typeof(ShopDbContext).GetMethod(nameof(PGetroductsForRegion)), action => {
                       action.HasParameter("apiKey").HasStoreType("uniqueidentifier");
                       action.HasParameter("ClientLocation").HasStoreType("int");
                       action.HasParameter("ProductLanguage").HasStoreType("int");
                   });
```

Will generate an error like this

```
System.ArgumentNullException: Value cannot be null. (Parameter 'function')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.ToFunction(EntityTypeBuilder entityTypeBuilder, MethodInfo function, Action`1 configureFunction)
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.ToFunction[TEntity](EntityTypeBuilder`1 entityTypeBuilder, MethodInfo function, Action`1 configureFunction)
```

**Comment by PeterPann23** [comment]
Adding the name doesnt fix it
builder.Entity<ProductForRegion>()
                   .HasNoKey()
                   .ToFunction(typeof(ShopDbContext).GetMethod(nameof(PGetroductsForRegion)), action => {
                       action.HasParameter("apiKey").HasStoreType("uniqueidentifier");
                       action.HasParameter("ClientLocation").HasStoreType("int");
                       action.HasParameter("ProductLanguage").HasStoreType("int");
                       action.HasName("GetProductsForRegion");
                   });

**Comment by PeterPann23** [comment]
Also possible to get:
`The entity type 'ProductForRegion' is mapped to the 'DbFunction' named 'bom.vesnx.com.Data.ShopDbContext.PGetroductsForRegion(System.Guid,int,int)' with parameters {'apiKey', 'location', 'language'}. Ensure that the mapped function doesn't have any parameters.`

When using this
```
builder.Entity<ProductForRegion>()
                   .HasNoKey()
                   .ToFunction(typeof(ShopDbContext).GetMethod(nameof(PGetroductsForRegion)), action => {
                       action.HasParameter("apiKey").HasStoreType("uniqueidentifier");
                       action.HasParameter("location").HasStoreType("int");
                       action.HasParameter("language").HasStoreType("int");
                       action.HasName("GetProductsForRegion");
                   });
```

**Comment by PeterPann23** [comment]
The only code I can compile and use is when I map it to a nonexisting view

```
protected override void OnModelCreating(ModelBuilder builder)
{

   builder.Entity<ProductForRegion>().HasNoKey().ToView(null);

}
```

 and call it like so
```
public IQueryable<ProductForRegion> GetProductsForRegion(Guid apiKey, GeoLocation location, GeoLocation language)
{
	return ProductsForRegion.FromSqlRaw("select * from [dbo].[GetProductsForRegion](@p0,@p1,@p2)", apiKey, (int)location, (int)language);
}

```
any additional conditions with the collection will be executed in memory and not on the select statement so one needs to alter the raw query to something like this:
```
public IQueryable<ProductForRegion> GetProductsForRegion(Guid apiKey, GeoLocation location, GeoLocation language, string skuFilter)
{
     return ProductsForRegion.FromSqlRaw("select * from [dbo].[GetProductsForRegion](@p0,@p1,@p2) where SKU like @p3", apiKey, (int)location, (int)language, skuFilter);
}
```

**Comment by AndriySvyryd** [comment]
`ToFunction` can only be used with parameterless functions. Use `HasDbFunction` instead.
If you are still experiencing issues please share a small project that shows the exception you get.
