### ISSUE TITLE
Document new function translations in 7.0

### ISSUE THREAD

**Issue by roji** [dotnet/EntityFramework.Docs#3868]
* [x] https://github.com/dotnet/efcore/issues/25396
* [x] https://github.com/dotnet/efcore/issues/28078
* [x] https://github.com/dotnet/efcore/issues/28110
* [x] https://github.com/dotnet/efcore/issues/28115

**Comment by amunim** [comment]
May I ask, do we use string.Join normally or by some method defined [here](https://github.com/dotnet/efcore/issues/28264)?

**Comment by roji** [comment]
@amunim for string.Join you can just use that function as you normally would, e.g. within a Select following a GroupBy.

**Comment by amunim** [comment]
Thank you
