### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by TrifonT** [dotnet/EntityFramework.Docs#3872]
In section under the title "Explicitly Loading" please change 
"Even with lazy loading disabled it is still possible ..." to "Even with lazy loading enabled it is still possible..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9940596b-265d-8a55-f586-e544d29a5831
* Version Independent ID: b70000c7-2920-3cbe-03cd-f0b222094eee
* Content: [Loading Related Entities - EF6](https://docs.microsoft.com/en-us/ef/ef6/querying/related-data)
* Content Source: [entity-framework/ef6/querying/related-data.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@TrifonT your suggestion doesn't seem right - the "explicitly loading" section is to show how to load lazily (after the initial query) even when the lazy loading feature is disabled.

**Comment by roji** [comment]
@TrifonT I suggest fully reading that page: explicit loading is an alternative to lazy loading for loading related entities after the initial (eager) query (so there's eager, lazy and explicit loading).

Note that in any case, we're no longer actively maintaining the non-core EF6 docs, but are concentrating on EF Core.
