### ISSUE TITLE
Add a note in documentation for incorrect results involving skip without order by in split query

### ISSUE THREAD

**Issue by smitpatel** [dotnet/EntityFramework.Docs#3873]
See https://github.com/dotnet/efcore/issues/21202

**Comment by smitpatel** [comment]
This is currently target of  https://go.microsoft.com/fwlink/?linkid=2196526 
Update the link target when doc is written.

**Comment by roji** [comment]
@ajcvickers the note was added in https://learn.microsoft.com/en-us/ef/core/querying/single-split-queries#split-queries, can you update the fwlink to link there?
