### ISSUE TITLE
Cant even get the project created without running into bad information on the page.

### ISSUE THREAD

**Issue by nvnfdddddddd** [dotnet/EntityFramework.Docs#3879]
Search for "WPF," choose WPF App (.NET Core) and then choose Next.

THERE IS NO PROJECT TYPE WITH THAT NAME...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a691101f-b7ea-4539-3745-6d9b0f5e317f
* Version Independent ID: 8f488a69-cedf-9c45-f977-23b3d8abd3df
* Content: [Get Started with WPF - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/wpf)
* Content Source: [entity-framework/core/get-started/wpf.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/wpf.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by JeremyLikness** [comment]
@nvnfdddddddd what version of Visual Studio and which workloads do you have installed? It would be helpful to see a screenshot of the options that ARE available in your create new project dialog. Thanks!

**Comment by nvnfdddddddd** [comment]
Visual Studio 2022 Enterprise.  I have just about every tool installed.  From what I have gathered from an hour of searching around is that the Core designation has been dropped.  It is impossible to tell which are .NET Core and which are not.  Should I use WFP APP (.NET Framework) or WPF Application [that creates a .NET WPF Application]?

***@***.***

The basic Console apps are just as bad; which is core and which is not???
***@***.***
