### ISSUE TITLE
Business card idea with only tools or containerisation

### ISSUE THREAD

**Issue by BedamatiMohanty** [dotnet/EntityFramework.Docs#3880]
![qrcode_login docker com](https://user-images.githubusercontent.com/86350861/171349145-8cf28a5a-c231-4192-b080-ea895637f120.png)

I have created a QR code by writing only docker file yaml in Linkedin and then modifying the yaml or json file using docker advanced configuration in my local and then deployed it in remote locations(multiple) can be useful for front-end developers who are starting their carreers!

Please try by clicking on the link provided above and you should be able to reach my Linkedin page!

if you have not requested access it might differ as my account is located at a location which might not be accessible from your computer.

other repos can you find in my demo on github.com/bedamatimohanty

Please check and leave comments incase you face issues!

**Comment by roji** [comment]
@BedamatiMohanty please don't post content unrelated to Entity Framework Core in this repo.

**Comment by BedamatiMohanty** [comment]
> @BedamatiMohanty please don't post content unrelated to Entity Framework Core in this repo.

Thanks @roji : i just wanted to chekin my code and fork the code in this repo as an example! i have unsubscribed now.
