### ISSUE TITLE
Configuring owned type properties independently of the owner

### ISSUE THREAD

**Issue by wdhenrik** [dotnet/EntityFramework.Docs#3881]
I'm implementing an Owned type with EFC6.

I'd like to ensure a class can only be used as an Owned type and has a consistent data shape, regardless of the owning class.

I want to use the IEntityTypeConfigurations as I have with all my other entities.  It seems I can configure the owned class using annotations.  As an example:
```
    [Owned]
    public class Thingie
    {
        [MaxLength(50)]
        [Unicode(false)]
        [Required]
        public string Name { get; private set; }
        [MaxLength(4000)]
        [Unicode(true)]
        public string Comment { get; private set; }
    }

```
The configuration example on this page shows configuring the entity through the owning entity:
```
modelBuilder.Entity<DetailedOrder>().OwnsOne(
    p => p.OrderDetails, od =>
    {
        od.WithOwner(d => d.Order);
        od.Navigation(d => d.Order).UsePropertyAccessMode(PropertyAccessMode.Property);
        od.OwnsOne(c => c.BillingAddress);
        od.OwnsOne(c => c.ShippingAddress);
    });
```

But this seems to encourage, or at least allow, the owning type to determine the configuration for the owned type.  Without using the class and property annotations, referencing the owned type in another model throws this message:

> The entity type 'Thingie' cannot be configured as non-owned because it has already been configured as a owned.  Use the nested builder in `OwnsOne` or `OwnsMany` on the owner entity type builder to further configure this type. If you want to override previous configuration first remove the entity type from the model by calling 'Ignore'

Can you post an example of how to configure the owned type through an IEntityTypeConfiguration class, independently of the owning type?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@wdhenrik This is not currently supported--make sure to vote (👍) for https://github.com/dotnet/efcore/issues/15681, which is tracking this.
