### ISSUE TITLE
Document configuration of triggers for SaveChanges

### ISSUE THREAD

**Issue by ehsan12021** [dotnet/EntityFramework.Docs#3883]
Hi,
I installed EF core version Preview 7 when I insert new record to a table that has a trigger I,ve got below error:

EF core preview 7 - latest preview release.

Error message:

Could not save changes because the target table has database triggers. Please configure your entity type accordingly, see https://aka.ms/efcore-docs-sqlserver-save-changes-and-triggers for more information.

thank you.

**Comment by ehsan12021** [comment]
Thank you.
Mr @roji 
and 
Mr @ajcvickers .

**Comment by roji** [comment]
Reopening to also add documentation for the custom convention which adds a blank trigger everywhere, https://github.com/dotnet/efcore/pull/28749.

**Comment by AndriySvyryd** [comment]
```C#
        protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
        {
            configurationBuilder.Conventions.Add(_ => new BlankTriggerAddingConvention());
        }
```

```C#
/// <summary>
///     A convention that makes sure there is a trigger on all entity types.
/// </summary>
public class BlankTriggerAddingConvention : IModelFinalizingConvention
{
    /// <summary>
    ///     Creates a new instance of <see cref="BlankTriggerAddingConvention" />.
    /// </summary>
    public BlankTriggerAddingConvention()
    {
    }

    /// <summary>
    ///     Called when a model is being finalized.
    /// </summary>
    /// <param name="modelBuilder">The builder for the model.</param>
    /// <param name="context">Additional information associated with convention execution.</param>
    public virtual void ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext<IConventionModelBuilder> context)
    {
        foreach (var entityType in modelBuilder.Metadata.GetEntityTypes())
        {
            var table = StoreObjectIdentifier.Create(entityType, StoreObjectType.Table);
            if (table != null
                && entityType.GetDeclaredTriggers().All(t => t.GetName(table.Value) == null))
            {
                entityType.Builder.HasTrigger(table.Value.Name + "_Trigger");
            }

            foreach (var fragment in entityType.GetMappingFragments(StoreObjectType.Table))
            {
                if (entityType.GetDeclaredTriggers().All(t => t.GetName(fragment.StoreObject) == null))
                {
                    entityType.Builder.HasTrigger(fragment.StoreObject.Name + "_Trigger");
                }
            }
        }
    }
}
```

**Comment by robcyrier11** [comment]
>     /// <summary>
>     ///     Called when a model is being finalized.
>     /// </summary>
>     /// <param name="modelBuilder">The builder for the model.</param>
>     /// <param name="context">Additional information associated with convention execution.</param>
>     public virtual void ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext<IConventionModelBuilder> context)
>     {
>         foreach (var entityType in modelBuilder.Metadata.GetEntityTypes())
>         {
>             var table = StoreObjectIdentifier.Create(entityType, StoreObjectType.Table);
>             if (table != null
>                 && entityType.GetDeclaredTriggers().All(t => t.GetName(table.Value) == null))
>             {
>                 entityType.Builder.HasTrigger(table.Value.Name + "_Trigger");
>             }
> 
>             foreach (var fragment in entityType.GetMappingFragments(StoreObjectType.Table))
>             {
>                 if (entityType.GetDeclaredTriggers().All(t => t.GetName(fragment.StoreObject) == null))
>                 {
>                     entityType.Builder.HasTrigger(fragment.StoreObject.Name + "_Trigger");
>                 }
>             }
>         }
>     }
> }
> ```

Trying to implement this but seems things have changed - IConventionTrigger no longer implements GetName(StoreObjectIdentifier). @AndriySvyryd do you have an alternative? Thanks!

**Comment by roji** [comment]
@robcyrier11 GetName has been renamed to GetDatabaseName - [here are the docs](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/misc) for that convention.
