### ISSUE TITLE
Entity Framework Core 6 - How to use Check Constraint in Fluent API (relation to another table)

### ISSUE THREAD

**Issue by Diaz15h** [dotnet/EntityFramework.Docs#3889]
Hello everyone,

I don't know how to make a constraint on a column which is relation with column of another table

Here is an example.

```c#
[Index(nameof(LevelName),IsUnique = true)]
    public class Level
    {
        public int LevelId { get; set; }
        public string LevelName { get; set; }
        public int GradeMax { get; set; }
    }
 
    [Index(nameof(LevelId),nameof(Grade), IsUnique = true)]    
    public class DetailsLevel
    {
        public int DetailsLevelId { get; set; }
        public int LevelId { get; set; }
        
        public int Grade { get; set; }
        public Level Level { get; set; }
    }
   

    public class EcoleContext : DbContext
    {
        public EcoleContext(DbContextOptions<EcoleContext> options)
            : base(options)
        {
        }

        public DbSet<Level> Levels { get; set; }

        public DbSet<DetailsLevel> DetailsLevels { get; set; }
        
        protected override void OnModelCreating(ModelBuilder 
            modelBuilder) 
       { 
           modelBuilder.Entity<DetailLevel>() 
                  .HasCheckConstraint("CK_Grade", "[Grade] < [Levels].[GradeMax]", c => c.HasName("CK_DetailLeve_Grade")) ; 
       }

    } 
 ```

SeedDatabase
1. table [level]
 - id:1 | name:lvl1 | max:5
 - id:2 | name:lvl2 | max:10  

2.   table [DetailsLevel]
 - id:1 | levelId:2 | garade: 8 // Must not exceed “10”.
 - id:2 | levelId:1 | garade: 4 // Must not exceed “5”. 
 
I would like to constrain the column [DetailsLevels].[Grade] < [Levels].[GradeMax]

If you can help me write the OnModelCreating part
Thanks.

**Comment by roji** [comment]
Check constraints can generally only refer to columns within the single table on which they are defined - this is a database limitation that has nothing to do with EF (in some databases it may be possible to call a user function which performs more checks, see e.g. [this SO question](https://stackoverflow.com/questions/28172719/how-to-enforce-a-check-constraint-across-multiple-tables)). However, I'd look more at triggers for doing this kind of thing.

**Comment by Diaz15h** [comment]
Thank you for your answer, Entity Framework has a ToFunction method can we use it in my case? how should i do it?

**Comment by roji** [comment]
You can create a function in the database by including [raw SQL in your migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#arbitrary-changes-via-raw-sql). After that you may be able to use that function in a check constraint - but this may not or may not work well depending on the database you're using (see the SO question above for some more info).
