### ISSUE TITLE
Sync-over-sync in EF6 code sample

### ISSUE THREAD

**Issue by daonguyen120688** [dotnet/EntityFramework.Docs#3898]
I have a concern about the below code block:

```c#
using (var context = new BlogContext())
{
    context.Database.Log = Console.Write;

    var blog = context.Blogs.First(b => b.Title == "One Unicorn");

    blog.Posts.First().Title = "Green Eggs and Ham";

    blog.Posts.Add(new Post { Title = "I do not like them!" });

    context.SaveChangesAsync().Wait();
}
```

Why do you provide an example that use .Wait()? I think it's a bad practice and can make developers misunderstand and go the wrong way while using asynchronous programming. In my opinion, you should provide a sample code that follows the best practice in order to make it more helpful to the reader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97eca854-650c-5c9e-25f2-e5e92e91c310
* Version Independent ID: be1279e0-ce03-8b44-bdf7-d9d173aba9b7
* Content: [Logging and intercepting database operations - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/logging-and-interception)
* Content Source: [entity-framework/ef6/fundamentals/logging-and-interception.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/logging-and-interception.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks, submitted #3899 to make this use simple, sync-only code.
