### ISSUE TITLE
Streaming with Stored Procedures

### ISSUE THREAD

**Issue by xenophilios** [dotnet/EntityFramework.Docs#3910]
Would appreciate some guidance on how to achieve streaming when using a stored procedure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e33b6d9-4d54-138e-7ba2-a1cfbda8b233
* Version Independent ID: a079c83a-fa76-efb6-e744-d01177379fce
* Content: [Efficient Querying - EF Core](https://docs.microsoft.com/en-us/ef/core/performance/efficient-querying)
* Content Source: [entity-framework/core/performance/efficient-querying.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/performance/efficient-querying.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@xenophilios you'll have to provide more context on exactly what you're trying to do.

**Comment by roji** [comment]
Stored procedures are no different than regular queries in this respect: both return a resultset, and that resultset can either be streamed (e.g. with foreach) or buffered entirely into memory (with ToList).

**Comment by xenophilios** [comment]
Thank you for this very helpful information!
