### ISSUE TITLE
Request for reviewing this page

### ISSUE THREAD

**Issue by MoamenShehata** [dotnet/EntityFramework.Docs#3924]
Hello,
Can you please review/update the first section of this article as it mentions this "If EF Core detects an expression, in any place other than the top-level projection, which can't be translated to the server, then it throws a runtime exception".

As I tried this in EF Core 6.0.6 and it did not throw an exception.

Thanks a lot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd35b912-445c-e801-7f70-de73839db80d
* Version Independent ID: e558a081-5397-1e3f-1d58-abea3f72cad6
* Content: [Client vs. Server Evaluation - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/client-eval)
* Content Source: [entity-framework/core/querying/client-eval.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/client-eval.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@MoamenShehata Can you elaborate on "I tried this?" Currently, this issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by smitpatel** [comment]
The expression tree construction used in that pattern causes to use enumerable operation. EF Core doesn't see there is client method.
