### ISSUE TITLE
CLI command out of date

### ISSUE THREAD

**Issue by cjdutoit** [dotnet/EntityFramework.Docs#3925]
All the CLI commands need updating.   dotnet ef tool is no longer part of the .NET Core SDK and can be installed via 
`dotnet tool install --global dotnet-ef`

which means commands change from `dotnet ef migrations add InitialCreate` to `dotnet-ef migrations add InitialCreate`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations Overview - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@cjdutoit The syntax for using the `dotnet-ef` command after it is installed is `dotnet ef`.

**Comment by bricelam** [comment]
Both invocations are valid. We recommend `dotnet ef` so that's what we show users.
