### ISSUE TITLE
Can you add a connection string example for Authentication=Active Directory Integrated?

### ISSUE THREAD

**Issue by ezelliott** [dotnet/EntityFramework.Docs#3931]
Could we add a connection string example for Azure Active Directory Integrated Authentication? I was able to get this connection string running locally:
_connectionString = "Server=xxxxxxx.database.windows.net,1433; Authentication=Active Directory Interactive; Database=xxxxxxx; User Id=xxxxxxx@microsoft.com;";

However, I tried many variations of this string and could not get it to work. I would like to log into the server with the Azure Managed Identity.  
_connectionString = "Server=tcp:xxxxxxx.database.windows.net,1433;Initial Catalog=xxxxxxx;Authentication=Active Directory Integrated;";
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
@ezelliott  The docs for that belong to SqlClient, you can find them here: https://docs.microsoft.com/sql/connect/ado-net/sql/azure-active-directory-authentication

**Comment by ezelliott** [comment]
Thanks! Any my apologies for the mistake. 

For some reason I thought there was a setting I was missing in the options builder and not a connection string error. 

The actual connection string I was looking for was this: 
Server=xxxxxx.database.windows.net;Database=xxxxxxx;Authentication=ActiveDirectoryMsi;

That is slightly misleading because the azure connection string page only shows ADO.NET (SQL authentication), ADO.NET (Active Directory password authentication), and ADO.NET (Active Directory integrated authentication). 

I feel like more of our documentation should highlight the power of Active Directory and using logged in users for security. Could we possibly add a DB context example like this to show others how to use Azure Active Directory to control SQL access? I feel like it was difficult for me to piece all this together and it might be helpful to others :) 

With these two connection strings I can control access to all of our applications with one (or multiple security groups) and the security group will change access of the users on the server and locally at the same time: 
Server: 
Server=xxxxxx.database.windows.net;Database=xxxxxx;Authentication=ActiveDirectoryMsi;
Local:
Server=xxxxxx.database.windows.net,1433; Authentication=Active Directory Interactive; Database=xxxxxx;

Here is what the database context looks like:

        public GlobalSupportSharedSqlContext()
        {
#if DEBUG
            _connectionString = "Server=xxxxxx.database.windows.net,1433; Authentication=Active Directory Interactive; Database=xxxxxx;";
            try
            {
                var databaseCreator = (Database.GetService<IDatabaseCreator>() as RelationalDatabaseCreator);
                databaseCreator.CreateTables();
            }
            catch (System.Exception e)
            {
                System.Console.WriteLine(e);
            }
#else
        _connectionString = "xxxxxx.database.windows.net;Database=xxxxxx;Authentication=ActiveDirectoryMsi;";
#endif
        }

**Comment by ErikEJ** [comment]
@ezelliott Not sure advice like that belongs in the EF Core docs repo. The linked location above seems a better place.
There is also this guide (not an easy read, but it's there) : https://docs.microsoft.com/en-us/azure/app-service/tutorial-connect-msi-sql-database?tabs=windowsclient%2Cefcore%2Cdotnet
I also have a blog post: https://erikej.github.io/efcore/azure/2021/04/20/efcore-managed-identity.html

>> That is slightly misleading because the azure connection string page only shows ADO.NET (SQL authentication), ADO.NET (Active Directory password authentication), and ADO.NET (Active Directory integrated authentication).

I assume you mean the page for the database in the portal? Suggestions for that should probably be directed to: https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0
