### ISSUE TITLE
Out of date page, not useful in current version:

### ISSUE THREAD

**Issue by robertwygreen** [dotnet/EntityFramework.Docs#3937]
[Enter feedback here]
I'm trying to use entity framework database first workflow in VS2022 with Entity Framework 6, with a blazor server project template, and none of the information in this page seems to apply anymore - I can't find any section in the "add new item" UI labeled Data, and in addition, the page wasn't even updated enough to change a version number from entity framework 5.x to 6.x. Can we get a new version of this that is actually useful in following the database first workflow in new tools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63be9b09-2dde-819c-72a9-874182a92113
* Version Independent ID: 0ef66141-904a-34b2-b2a1-b090c5d62339
* Content: [Database First - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/workflows/database-first)
* Content Source: [entity-framework/ef6/modeling/designer/workflows/database-first.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/designer/workflows/database-first.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
The designer is not supported in new project types... workaround is to add a Classic csproj to your solution https://erikej.github.io/ef/dotnetcore/2020/06/15/ef6-use-edmx-dotnetcore.html

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
