### ISSUE TITLE
No VB Examples

### ISSUE THREAD

**Issue by MadnessSoftware** [dotnet/EntityFramework.Docs#3938]
Microsoft Docs example for VB are getting scarce. Not sure why, VB is still as revelant as C# if not more so. Some docs do offer the opportunity to switch languages for the examples, however they are few and far inbetween. Tons of apps out there are still VB and new ones are still being developed using VB. Please provide examples for documention in both popular languages.

Makes it harder to learn new technologies with examples using code containing a superfluous and terse language base with excessive characters that has no function. Don't get me started on variables that are case sensitve. Not a bright idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8be815-df51-dc77-fb5b-ccfa7f742e10
* Version Independent ID: 353c54e3-b7c9-fcdd-ca71-2a11beab19fd
* Content: [Code First to a New Database - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/new-database?source=docs)
* Content Source: [entity-framework/ef6/modeling/code-first/workflows/new-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/workflows/new-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
