### ISSUE TITLE
Error in the parameter in OnModelCreating method

### ISSUE THREAD

**Issue by JoseAP89** [dotnet/EntityFramework.Docs#3942]
protected override void OnModelCreating(DBModelBuilder modelBuilder) should be:
protected override void OnModelCreating(ModelBuilder modelBuilder)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1251b7a8-a4d4-7664-d1f3-5447f47315a8
* Version Independent ID: bf0ecf4c-1dd9-6cfd-32ea-86fcc619164e
* Content: [Fluent API - Relationships - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/fluent/relationships)
* Content Source: [entity-framework/ef6/modeling/code-first/fluent/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/fluent/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
@JoseAP89 You are looking the the Entity Framework 6 docs, not EF Core
