### ISSUE TITLE
this is not what dotnet new gives you, so, when I look at  CreateModel, it is pretty much irrelevant

### ISSUE THREAD

**Issue by jhoney92021** [dotnet/EntityFramework.Docs#3949]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8be815-df51-dc77-fb5b-ccfa7f742e10
* Version Independent ID: 353c54e3-b7c9-fcdd-ca71-2a11beab19fd
* Content: [Code First to a New Database - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/new-database)
* Content Source: [entity-framework/ef6/modeling/code-first/workflows/new-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/workflows/new-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
