### ISSUE TITLE
Seed data that Id = 0

### ISSUE THREAD

**Issue by anchurcn** [dotnet/EntityFramework.Docs#3952]
What I want:
```csharp
builder.Entity<AEnumTable>().HasData(0, "None");
builder.Entity<AEnumTable>().HasData(1, "A");
builder.Entity<AEnumTable>().HasData(2, "B");
builder.Entity<AEnumTable>().HasData(3, "C");
```
But it throws System.InvalidOperationException: The seed entity for entity type 'AEnumTable' cannot be added because a non-zero value is required for property 'Id'. Consider providing a negative value to avoid collisions with non-seed data.

How can I achieve this? If the answer is No, we hope there is a way to set a value as the default value,  0 sometimes is a valid value in that scenario.

  -- Sincerely Anchurcn

**Comment by ajcvickers** [comment]
@anchurcn The answer depends on whether or not you are using generated key values. Can you post the database schema for the table?

**Comment by anchurcn** [comment]
I didn't specify a auto generated key, this is my Migration.
```csharp
    public partial class AddAEnumTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AEnumTable",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StructureProducts", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AEnumTable");
        }
    }
```
Thank you for your reply^_^

**Comment by roji** [comment]
@anchurcn your Id column is a SQL Server identity column, which is auto-generated; this happens by convention for numeric Id properties. [See the docs](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#primary-keys) for more info, as well as how to disable this if you want to explicitly provide ID values.

**Comment by anchurcn** [comment]
Thank you, have a good day.

**Comment by anchurcn** [comment]
I think there can be a tip on exception message to help somebody like me.
