### ISSUE TITLE
Wrong grammar in all sections

### ISSUE THREAD

**Issue by martinbrabec** [dotnet/EntityFramework.Docs#3953]
It happens in all sections. Both Developers (#1 and #2) are reffered to as "they". It is grammatically incorrect, because "they" indicates there is more than one.

e.g.:
"Now it’s time for Developer #2 to submit. **They** aren’t so lucky. Because someone else has submitted changes since **they** synced, **they** will need to pull down the changes and merge"

It is very important to use correct language, especially in exact documentation, where this kind of error can lead to misunderstanding of explained feature. Either change they to he/she, or change "Developer #1" to "Developer Team #1". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b72ecde8-e983-8583-7c3f-6e0e4ff404fb
* Version Independent ID: 6ed79d63-19a7-c527-b383-c5faf4beba55
* Content: [Code First Migrations in Team Environments - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/teams)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/teams.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/migrations/teams.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
