### ISSUE TITLE
Asynchronous example throws an exception

### ISSUE THREAD

**Issue by ZombiesWithCoffee** [dotnet/EntityFramework.Docs#3967]
`var blogs = await service.GetAllBlogsAsync();`

Using the example exactly as written, gives me

System.InvalidOperationException: The provider for the source 'IQueryable' doesn't implement 'IAsyncQueryProvider'. Only providers that implement 'IAsyncQueryProvider' can be used for Entity Framework asynchronous operations.

Also received a compilation issue.  The last line should be `blog.Entity`.

```c#
       public Blog AddBlog(string name, string url)
            {
                var blog = _context.Blogs.Add(new Blog { Name = name, Url = url });
                _context.SaveChanges();

                return blog.Entity;
            }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a04a5e4-3060-2331-f78d-8b45064b8983
* Version Independent ID: 673d9406-3fa1-a9eb-f5cc-a431155e0260
* Content: [Testing with a mocking framework - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/testing/mocking)
* Content Source: [entity-framework/ef6/fundamentals/testing/mocking.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/testing/mocking.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
You know you are looking at Entity Framework 6 (Classic) docs - not EF Core?

**Comment by ZombiesWithCoffee** [comment]
:D Well, that certainly explains that! :)
