### ISSUE TITLE
EntityFramework connection to a Azure Database too hard

### ISSUE THREAD

**Issue by Johnvan** [dotnet/EntityFramework.Docs#3980]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1601c3e-3f29-5d84-6350-2b38eeaf6adc
* Version Independent ID: 92a856d6-c5da-e215-46ac-d67c411f3ff9
* Content: [Reverse Engineering - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/scaffolding.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by Johnvan** [comment]
What was wrong with ADO, why is it sooo hard to connect to an existing Azure Database. What is Microsoft doing to Visual Studio, it supposed to make programming easy while doing the exact opposite.

**Comment by Johnvan** [comment]
Reverse Engineering the Scaffolding System, what a joke.

**Comment by ErikEJ** [comment]
Have you tried EF Core Power Tools?

**Comment by Johnvan** [comment]
Thanks for the response, but I have no idea what a Power Tool is and why should we have to use them anyway.

**Comment by ErikEJ** [comment]
I was trying to address the topic of your issue - https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools

**Comment by ajcvickers** [comment]
@Johnvan Can you provide some more details on what exactly you are trying to do and why it is difficult?

**Comment by Johnvan** [comment]
I have a SQLServer Database on Azure and want to connect to an Updated New MVC ASPNETEntityFrameCore6 Web page using VS22. The system is to be used as a phone/PC Website, no problem there. The instructions for connecting a Database to this system only covers Local Databases and uses this thing called SCAFFOLDING to create all that is needed for a Web site Database. However, I want to connect this site to an existing database on Azure and come up with this Reverse Engineered Scaffold system!!!!!!! I have been programming for over 30 years and seen Visual Studio being developed and was quite happy with the way they went, but now I believe the system has lost the plot, Scaffolding for starters, but also lost the Drag/Drop system. I have been maintaining Websites that used DataSets and found that quite acceptable, and even Xamarin using SQLight. But Reverse Engineering, Scaffolding is nice but you don't know what is happening. 
All I want to do is connect an Azure Database into my new Website using MVC but it's too complex.

**Comment by roji** [comment]
@Johnvan first, you're free to continue using DataSets and/or ADO.NET - these continue to work just as before.

Beyond that, it's not clear what your concrete complaint here is; EF Core 6.0 allows you to scaffold (or reverse engineer) an existing database, creating a code model from it. The concepts and process are described [in our docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli); users typically encounter no issues doing this, as it's usually a matter of pointing EF Core to your database and getting the code model generated for you. From that point, you use regular EF patterns to interact with the database.

Can you please provide more concrete details on what you find complex or difficult? A general "it's too complex" complaint doesn't really help us know what the problems are, and how to fix them. Is the document insufficient, or is the process itself somehow problematic?

**Comment by Johnvan** [comment]
You present the typical response that not enough information is presented, this, I feel, is your lack of the procedure that I have described and the miss reading of that. 
I am having problems with connecting an Azure Database to Visual Studio for including it in my code. End of story:
https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli supplies an answer that I cannot implement in any way, I do not understand what is being said. 
Now ErikEJ has suggested EF Core Power Tools which I have viewed his Video but no step by step written procedure as there are decisions to be made along setting up need more description.
I am sorry if I sound a bit upset about this but every time I ask for assistance I get fogged off by GITHIB.

**Comment by Johnvan** [comment]
Oh, and by the way, my Visual Studio **does not have** DataSets and/or ADO.NET when using EF Core.

**Comment by roji** [comment]
@Johnvan DataSets/ADO.NET and EF Core are different data access technologies. You can either use DataSets/ADO.NET, or you can use EF Core; but if you choose to use EF Core, you're not using DataSets/ADO.NET.

I'd like to help out, but it sounds like you're simply new to EF Core, and may need to master the basic concepts. Have you gone through the Getting Started part of our docs, in particular [Your first EF Core App](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)? This should provide a general intro to how EF Core works, and once that's done, hopefully it will become apparent what scaffolding means. We'll be here to help out with any questions.

If, on the other hand, you already understand the concepts of DbContext and entity types, then it would be good to know more about what you're not understanding in the scaffolding doc page.

**Comment by Johnvan** [comment]
Again you don't understand EF Core either, otherwise you would know what I am talking about.
Don't worry, I don't need GitHub on this matter as @ErikEJ has given me all the information I need.
This still doesn't satisfy my problems with the the use of Frameworks are being used, the accuracy of Microsoft's Documentation now that GitHub has taken over, and Microsoft's reliance now on external Extensions to fix their Framework problems.
Huge thanks to @ErikEJ although it's a fix for bad Frameworks.

**Comment by roji** [comment]
@Johnvan unless you provide more specific information on where our documentation is inaccurate or lacking, there's nothing really we can do to help; general "your docs are bad" comments aren't really helpful in any way. We spend a lot of time on our documentation and generally get very positive feedback on it from users; we definitely have not abandoned or compromised on documentation quality because GitHub exists.

**Comment by Johnvan** [comment]
No, you can close this thing, I give up on EF Core and going back to EF, although I think VS22 seems to have trouble with EF Datasets as well.
Thanks for your assistance on this matter but maybe I am getting too old for this being 75 years.
You have done a good job on fixing this GitHub site, well done.

**Comment by Johnvan** [comment]
Can anyone give me a link to **NON**-EF CORE Tutorial on MVC Web Site Building
