### ISSUE TITLE
Documentation only lists some of the error codes handled

### ISSUE THREAD

**Issue by tjrobinson** [dotnet/EntityFramework.Docs#3981]
The documentation currently states that "This execution strategy will retry the operation on [TimeoutException](https://docs.microsoft.com/en-us/dotnet/api/system.timeoutexception) and [SqlException](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlexception) if the [Errors](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlexception.errors#system-data-sqlclient-sqlexception-errors) contains any of the following error numbers: 40613, 40501, 40197, 10929, 10928, 10060, 10054, 10053, 233, 64 and 20"

But if you look at the source code, there are other error codes which it will also check for, including 1205 (deadlock):

https://github.com/dotnet/ef6/blob/main/src/EntityFramework.SqlServer/SqlAzureRetriableExceptionDetector.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce95f1d6-cd64-04c1-4583-8313531a490a
* Version Independent ID: 2dc552b7-738d-3a1f-e1a0-ae9c0b67b36b
* Content: [SqlAzureExecutionStrategy Class (System.Data.Entity.SqlServer)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.sqlserver.sqlazureexecutionstrategy?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity.SqlServer/SqlAzureExecutionStrategy.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.SqlServer/SqlAzureExecutionStrategy.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by tjrobinson** [comment]
See also: https://github.com/dotnet/ef6/issues/83

**Comment by ErikEJ** [comment]
You are looking at EF 6 (Classic) docs which are no longer maintained...

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
