### ISSUE TITLE
"Multiple databases and connection strings" section doesn't seem quite right

### ISSUE THREAD

**Issue by nick-moodevelop** [dotnet/EntityFramework.Docs#4004]
I have probably missed the point but the multiple databases bit doesn't seem right to me.

An ITenantService is injected into the constructor and a _tenantService member variable is set to contain it.

The _tenantService is accessed in the OnConfiguring() but the OnConfiguring() is called by the base constructor which happens before
the _tenantService variable is set so won't it always be null in the OnConfiguring()?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb29a2b6-c401-287f-2da9-1aeb3c633b41
* Version Independent ID: bb29a2b6-c401-287f-2da9-1aeb3c633b41
* Content: [Multi-tenancy - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/multitenancy)
* Content Source: [entity-framework/core/miscellaneous/multitenancy.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/multitenancy.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by ajcvickers** [comment]
@nick-moodevelop The base constructor should not be calling `OnConfiguring`. `OnConfiguring` is called when the context is _used_ for the first time, not when it is created.

**Comment by nick-moodevelop** [comment]
Ah yes, of course. Thanks.
