### ISSUE TITLE
Video file format is different from what is listed

### ISSUE THREAD

**Issue by 0014** [dotnet/EntityFramework.Docs#4009]
There is an .mp4 file which can be downloaded in order to show entity framework enum operations. When you download the file, it gets downloaded in .m4v format.

I had to rename m4v to mp4 to run the video.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f542fca8-b394-3bb7-9ae9-07e36c8616a1
* Version Independent ID: c7844dd8-7888-946b-bf95-c2027b05a179
* Content: [Enum Support - EF Designer - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/data-types/enums)
* Content Source: [entity-framework/ef6/modeling/designer/data-types/enums.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/designer/data-types/enums.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
