### ISSUE TITLE
I hate broken links!   https://go.microsoft.com/fwlink/?linkid=2101038

### ISSUE THREAD

**Issue by Snappee** [dotnet/EntityFramework.Docs#4011]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e788e366-d94c-8aa1-3167-72af27a1c23d
* Version Independent ID: 85363d2a-1051-ec35-21a8-2c11fd5c6727
* Content: [CoreStrings.TranslationFailedWithDetails(Object, Object) Method (Microsoft.EntityFrameworkCore.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.corestrings.translationfailedwithdetails?view=efcore-6.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Diagnostics/CoreStrings.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Diagnostics/CoreStrings.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by Snappee** [comment]
When working with new technology, folks like me are much more productive when links in your webpages and in the VS UI actually work.  When they don't work, then we have to embark on a dang "fishing trip" . . . and those get expensive in terms of time and treasure.

**Comment by roji** [comment]
@Snappee which link exactly is broken? Clicking above gets me to the CoreStrings.TranslationFailedWithDetails API doc page, and the only external link there gets me to the [Client vs. Server Evaluation](https://docs.microsoft.com/en-us/ef/core/querying/client-eval) page, which is where it's supposed to lead.
