### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by geetmenon** [dotnet/EntityFramework.Docs#4014]
Very poor documentation! Please explain the sample codes. Please also provide scenarios where it could be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32360b50-1129-b3d2-2d71-c6b89cd9f2c6
* Version Independent ID: 4f18f8dc-5cd5-cb37-0f59-fb1767609b2b
* Content: [What's New in EF Core 5.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew)
* Content Source: [entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@geetmenon thanks for the feedback, but we need more concrete feedback, on where specifically you think sample code is missing.

More importantly, note that this page is a "what's new in EF Core 5.0" page, which only briefly shows new features in that version; it isn't meant to be an exhaustive documentation page. Try to take a look at the dedicated documentation pages for each subject, there's more explanations and code samples there.
