### ISSUE TITLE
Unable to follow the documentation

### ISSUE THREAD

**Issue by BusHero** [dotnet/EntityFramework.Docs#4021]
I'm not able to follow the documentation. The documentation doesn't describe all the components a project should have to successfully use the commands described in the documentation. Apparently, it's not enough to just have a model and a Context in your project.

I have a model that looks like this
```c#
public class Schema
{
    public int Id { get; set; }
    public string Namespace { get; set; }
    public string Xsd { get; set; }
}
```

and a Context class that looks like this
```c#
public class SchemaContext : DbContext
{
    public SchemaContext(DbContextOptions<SchemaContext> options) : base(options)
    {
    }

    public DbSet<Schema> Schemas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Schema>().ToTable("Schemas");
    }
}
```
and when I run:

```powershell
dotnet ef migrations add InitialCreate
```
I get: `Unable to create an object of type 'SchemaContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations Overview - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@BusHero Would it help if instead of "Let's assume you've just completed your first EF Core application" it was more explicit that an application that uses the context in some way is needed?

**Comment by BusHero** [comment]
I guess this will help. A link to a sample GitHub project will also help, or at least links to other resources.

**Comment by BusHero** [comment]
**Chapter 9.4** from the **Entity Framework Core in Action, Second edition** book worked for me! It turns out that my project needs to be an Asp.net core project, while my project is a library project. Adding a class to my project that implements `IDesignTimeDbContextFactory<TContext>`  solves the issue. It would be nice if the documentation also mention this.
