### ISSUE TITLE
OwnedNavigationBuilder Does not Have Option to Specify Backing Field 

### ISSUE THREAD

**Issue by jakingmsft** [dotnet/EntityFramework.Docs#4031]
Say my model has parent-children relations where children are considered owned by parent, and say I want to represent as JSON like 

```
{
    // ... 
   "children": [ ... ]
}
```

and my C# model like 

```
public class Parent
{
     // ...

      public IReadOnlyCollection<Child> Children => this._children;

      private List<Child> _children;
}
```

This works because of conventionally named `_children` matching `Children`. However, if I wanted to customize, there appears to be no way, like there is with normal properties. 

Cannot do

```
builder.OwnsMany(p => p.Children, onb =>
{
     onb.ToJsonProperty("children");
     // ...
})
.Property(p => p.Children).HasField(...);
```

because owned entities are incompatible with properties (Error at runtime).

Also cannot do 

```
builder.OwnsMany(p => p.Children, onb =>
{
     onb.HasField(...);
     onb.ToJsonProperty("children");
     // ...
});
```

because there is no such method on `OwnedNavigationBuilder` .

Note that this is more like a feature request to make the model building a litttttllllle more flexible :)

**Comment by ajcvickers** [comment]
@jakingmsft 

Try `.Navigation(p => p.Children).HasField(...);`

**Comment by jakingmsft** [comment]
> @jakingmsft
> 
> Try `.Navigation(p => p.Children).HasField(...);`

Thank you!
