### ISSUE TITLE
I'm struggling here ar FRomExpression seems not to exist in DbContaxt in EF 6.4.4 and I can't find the documentation of why or what to use instead.  I assume its perhaps no longer needed to map a TVF?

### ISSUE THREAD

**Issue by ianonahillroad** [dotnet/EntityFramework.Docs#4036]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34d3f39-600f-0c37-a0a4-11a245d3010c
* Version Independent ID: 5b51ed49-1035-1a8f-a08e-7400d571c77b
* Content: [User-defined function mapping - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping?source=recommendations)
* Content Source: [entity-framework/core/querying/user-defined-function-mapping.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/user-defined-function-mapping.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @maumar
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@ianonahillroad the documentation you're linking to above is for EF Core, but you seem to be using the old (non-Core) EF 6. It's highly recommended to use the new EF Core in any new development, but the older [EF6 docs are available here](https://learn.microsoft.com/en-us/ef/ef6/).
