### ISSUE TITLE
Cover additional ways to load related data 

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#404]
Currently in https://docs.microsoft.com/en-us/ef/core/querying/related-data we only cover eager loading and explicit loading. 

It is very common to execute 2 or more tracked queries in the same context instance and leverage EF Core's ability to fixup navigation properties. This works very well in general and provides a lot of control (e.g. results can be filtered on every query). 

Referencing navigation properties in the projection can also become a compelling alternative, assuming it doesn't lead to inefficient queries in common cases after the work we are doing in 2.0.

**Comment by ajcvickers** [comment]
Discuss with @smitpatel

**Comment by smitpatel** [comment]
Covered in https://docs.microsoft.com/en-us/ef/core/querying/related-data/explicit#explicit-loading
