### ISSUE TITLE
Mistake in reference to Include extension method

### ISSUE THREAD

**Issue by malbruk** [dotnet/EntityFramework.Docs#4049]
Include is an extension method in the Microsoft.EntityFrameworkCore namespace  and not in the System.Data.Entity namespace as written.

**Comment by ajcvickers** [comment]
@malbruk Which document are you referring to?

**Comment by malbruk** [comment]
Sorry,
This one: https://learn.microsoft.com/en-us/ef/ef6/querying/related-data
in the first Note

**Comment by ErikEJ** [comment]
That page if EF 6 Classic docs

**Comment by ajcvickers** [comment]
EF Core docs are here: https://learn.microsoft.com/en-us/ef/core/
