### ISSUE TITLE
WHEREless please

### ISSUE THREAD

**Issue by DickBaker** [dotnet/EntityFramework.Docs#4060]
please change the over-decorated "DELETE FROM [Blogs] WHERE 1=1;" to "DELETE FROM [Blogs];"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7fc3c3b-c859-2ad5-78f3-ce57d3c9bc2d
* Version Independent ID: b7fc3c3b-c859-2ad5-78f3-ce57d3c9bc2d
* Content: [Testing against your Production Database System - EF Core](https://learn.microsoft.com/en-us/ef/core/testing/testing-with-the-database)
* Content Source: [entity-framework/core/testing/testing-with-the-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/testing-with-the-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@DickBaker you can simply submit a PR for this.

**Comment by DickBaker** [comment]
@roji thanks for teaching me this simple trick. Have duly raised #4066 to close our loop
