### ISSUE TITLE
Backing Field convention for camelCase property missing in docs?

### ISSUE THREAD

**Issue by chrispaynter** [dotnet/EntityFramework.Docs#4061]
The documentation for Backing Fields states that the follow conventions are used to determine the backing field for a property:

```
_<camel-cased property name>
_<property name>
m_<camel-cased property name>
m_<property name>
```

However, non prefixed `camelCase` also works.

This lead me to some confusion as to why my backing field was still being picked up.

I want to clarify whether non prefixed camel case needs to be added to the documentation before I create a PR, or whether I'm seeing some magic that isn't officially supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e162696-b19f-d73f-8b1f-d1b4c3048b62
* Version Independent ID: a83e4fb5-e4ae-a46f-7248-487ea2679ac5
* Content: [Backing Fields - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/backing-field.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/backing-field.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@chrispaynter Yes, the documentation is incomplete here. A PR would be appreciated.

Previously reported as #2532.

**Comment by chrispaynter** [comment]
https://github.com/dotnet/EntityFramework.Docs/pull/4071
