### ISSUE TITLE
Pooled DbContext and multiple models with the same DbContext type

### ISSUE THREAD

**Issue by nearlyheadlessarvie** [dotnet/EntityFramework.Docs#4062]
Hi, is this possible while using Pooled DbContext?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47e9155e-a702-17a1-848c-09a7d9a52bb5
* Version Independent ID: 23d9d8f5-b309-3a1e-cf3e-428d1edc0fdf
* Content: [Alternating between multiple models with the same DbContext type - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/dynamic-model)
* Content Source: [entity-framework/core/modeling/dynamic-model.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/dynamic-model.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@nearlyheadlessarvie A context instance is bound to a single model, so a single pool cannot be used with contexts that have different models. However, you should be able to use a pool-per-model by managing the pools yourself--see [Without dependency injection](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=without-di%2Cwith-constant#dbcontext-pooling) docs.

**Comment by nearlyheadlessarvie** [comment]
Got it, guess no context pooling for me then. Thanks!
