### ISSUE TITLE
Injecting DbContext in Entity does not work

### ISSUE THREAD

**Issue by nearlyheadlessarvie** [dotnet/EntityFramework.Docs#4063]
RE: https://learn.microsoft.com/en-us/ef/core/modeling/constructors#injecting-services

Is there any special step to make this work? 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ecc7aedf-6301-7ec7-4f65-81749b1f54c8
* Version Independent ID: d0774ffa-c841-e6df-72de-d7f53c0d6f6f
* Content: [Entity types with constructors - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/constructors)
* Content Source: [entity-framework/core/modeling/constructors.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/constructors.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Nothing special. Here's a runnable example:

```C#
public class Blog
{
    public Blog()
    {
    }
    
    public Blog(SomeDbContext context)
    {
        Context = context;
    }
    
    public SomeDbContext Context { get; }

    public int Id { get; set; }
    public string Name { get; set; } = default!;
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString, b => b.MaxBatchSize(1))
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<Blog> Blogs => Set<Blog>();
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new SomeDbContext())
        {
            await context.Database.EnsureDeletedAsync();
            await context.Database.EnsureCreatedAsync();
        
            var blog = new Blog { Name = "MyBlog" };
            await context.Blogs.AddAsync(blog);
            await context.SaveChangesAsync();

            await context.SaveChangesAsync();
        }
        
        using (var context = new SomeDbContext())
        {
            var blog = await context.Blogs.SingleAsync();
            Console.WriteLine(blog.Context);
        }
    }
}
```

**Comment by nearlyheadlessarvie** [comment]
Yeah, I am able to run mine as well but the dbcontext is never getting set. Supposed using the dbcontext in DI is not a problem?

**Comment by nearlyheadlessarvie** [comment]
@ajcvickers I was using it with [Hotchocolate](https://github.com/ChilliCream/hotchocolate) graphql middleware, guessing that played a part why it is not working. 

Got it working in MVC. However, still hit a brick wall on my use case: was trying to call a scalar dbfunction using the injected context, thinking it would translate to:

```sql
select prop1, MyScalarFunction(prop2) from table
```

Instead it gets called separately, not wrapped in IQueryable, obviousbly throws notsupported error. Is this not possible?

**Comment by ajcvickers** [comment]
> However, still hit a brick wall on my use case: was trying to call a scalar dbfunction using the injected context

Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by nearlyheadlessarvie** [comment]
[EF4063.zip](https://github.com/dotnet/EntityFramework.Docs/files/9689362/EF4063.zip)

Here's an example. Obviously concat simulates a real business logic udf in the database. If we could get EF to generate command like below, it would be super! 
```sql
 SELECT "b"."Id", "b"."Name", CONCAT(Name, @p0) as Test
      FROM "Blogs" AS "b"
```

```
info: 01/10/2022 10:28:31.890 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "b"."Id", "b"."Name"
      FROM "Blogs" AS "b"
Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at SomeDbContext.Concat(String first, String second) in C:\Source\Repos\EF4063\EF4063\Program.cs:line 29
   at Blog.get_Test() in C:\Source\Repos\EF4063\EF4063\Program.cs:line 23
   at Program.Main() in C:\Source\Repos\EF4063\EF4063\Program.cs:line 69
   at Program.<Main>()
```

**Comment by ajcvickers** [comment]
@nearlyheadlessarvie User defined functions are intended to be used as part of a LINQ query, not called directly from a context. See [User defined function mapping](https://learn.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping) for more info.

**Comment by nearlyheadlessarvie** [comment]
Hi @ajcvickers,

Yeah, I know it works well in LINQ. Was just wishfully thinking it was supported inside an entity. Don't they both, linq and entity, go the same processing, in expressionvisitor or something. Anyways, closing this now, thanks!
