### ISSUE TITLE
Error in Table Splitting sample

### ISSUE THREAD

**Issue by yulObraz** [dotnet/EntityFramework.Docs#4069]
`.HasRequired(t => t.OfficeAssignment)` - there is no such field in the instructor class.

I have a problem with table splitting because it works only on mssql (not postgresql). So I search for workable samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad94d68-823d-c9bf-d90c-fe2c96fc1e56
* Version Independent ID: 608f1890-2f98-3863-b49d-3bddbb6f1cc6
* Content: [Fluent API - Configuring and Mapping Properties and Types - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/fluent/types-and-properties)
* Content Source: [entity-framework/ef6/modeling/code-first/fluent/types-and-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/fluent/types-and-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
