### ISSUE TITLE
Confusing, unclear where to put the code

### ISSUE THREAD

**Issue by hcprobst** [dotnet/EntityFramework.Docs#4073]
[Enter feedback here]
Confusing, unclear where to put the code.
For all the pages about loading related data it is not clear where the code should be placed in which program.

I seem to be puting it in the wrong places because of all the errors I get attempting to add to my site

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc261727-1ecd-5dcb-fb88-1b1762263789
* Version Independent ID: a15c2f82-ebb7-9867-50ad-35f80366528f
* Content: [Explicit Loading of Related Data - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/related-data/explicit)
* Content Source: [entity-framework/core/querying/related-data/explicit.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/related-data/explicit.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@hcprobst can you be more specific, and possibly show a program of yours where you're putting the code in the wrong place? The code samples in that page can generally be used anywhere where one wants to execute a database query with EF Core.

**Comment by hcprobst** [comment]
Sorry, I think I have it now.

Thank you

Carey
Carey Probst  |  Application Developer
Information Technology Department
Lock Haven University
Smith Hall, B 2
401 North Fairview Street, Lock Haven, PA   17745
Phone: 570.484.3020 |  ***@***.******@***.***>  |  www.lockhaven.edu<http://www.lockhaven.edu/>
