### ISSUE TITLE
Using default values does not work as expected on non-nullable types

### ISSUE THREAD

**Issue by antonthomas** [dotnet/EntityFramework.Docs#4077]
When using the HasDefaultValue() method on fields that are non-nullable, EF does not behave as expected. When explicitly providing a different value for a non-nullable field, the provided value is overridden by the default value. Changing the field to be nullable does however work as expected.

Please make sure to include this in the documentation or possibly file a bug report.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [Generated Values - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#default-values)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@antonthomas Currently the default value is used whenever the property is set to the CLR default. Configuration of this is tracked by https://github.com/dotnet/efcore/issues/701. Please vote for that issue if this is something you need.
