### ISSUE TITLE
Using external DbTransactions

### ISSUE THREAD

**Issue by imamulkarim** [dotnet/EntityFramework.Docs#4086]
[In this example you showed the same transaction is used in two separate DbContext. but is it possible to use a different type DbContext? like here used BloggingContext two times. if I used BloggingContext  and XyzContext ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://learn.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@imamulkarim yes, you can use UseTransaction with two different context types, providing the same DbTransaction. UseTransaction simply means that everything done via the context (e.g. SaveChanges) will be done on that transaction. Be sure to share the connection as well.
