### ISSUE TITLE
SQLite EF Core Database Provider Limitations - examples

### ISSUE THREAD

**Issue by suatsuphi** [dotnet/EntityFramework.Docs#4087]
Hi,

Why are there no examples for UInt64, DateTimeOffset and TimeSpan only for Decimal

Is it possible to share an example for all data types?

```
modelBuilder.Entity<MyEntity>()
    .Property(e => e.DecimalProperty)
    .HasConversion<double>();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbc4d900-28a8-9c04-2443-7407f15a684f
* Version Independent ID: 545bb0b5-f15b-584e-cef7-7283a0e0729f
* Content: [SQLite Database Provider - Limitations - EF Core](https://learn.microsoft.com/en-us/ef/core/providers/sqlite/limitations)
* Content Source: [entity-framework/core/providers/sqlite/limitations.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/sqlite/limitations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@suatsuphi Examples showing what, exactly?

**Comment by suatsuphi** [comment]
> @suatsuphi Examples showing what, exactly?

What do I need to do for UInt64, DateTimeOffset and TimeSpan ? 

there is an example for DecimalProperty

```
modelBuilder.Entity<MyEntity>()
    .Property(e => e.DecimalProperty)
    .HasConversion<double>();
```

**Comment by ajcvickers** [comment]
@suatsuphi Right, but how are you planning on using those data types? What properties are important in the resulting database? For example, you could easily convert a `uint64` to an `int64`, but it would have different semantics in the database. You could instead convert to a `string`, but that would again have other implications. There isn't any one right answer here, or even any common patterns, so it's really going to depend on what your goals are.

**Comment by ajcvickers** [comment]
@suatsuphi For `unint64`, there is no conversion that will work in all situations. SQLite simply doesn't support it.

For `DateTimeOffset`, the doc already says:

> Instead of DateTimeOffset, we recommend using DateTime values. When handling multiple time zones, we recommend converting the values to UTC before saving and then converting back to the appropriate time zone.

Again, there is no conversion that will "just-work".

(Also, note that, as the doc says, the conversion of decimal to double also doesn't work in all cases.)

**Comment by suatsuphi** [comment]
thank you
