### ISSUE TITLE
Code highlighting missing and/or F# and VB.NET example missing

### ISSUE THREAD

**Issue by RichardPoes** [dotnet/EntityFramework.Docs#4091]
There is no code highlighting on lines 758-761 (as can be seen by clicking on [this link](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml#L758-L761).
I believe the code listed in that block is C# specific. So it is desirable to have the same styling as the example below.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8243b953-5de7-3123-0737-9be4ca3c08fd
* Version Independent ID: 1d1c0196-70ac-a45e-d1b7-48c55963f612
* Content: [RelationalDatabaseFacadeExtensions.ExecuteSqlInterpolatedAsync Method (Microsoft.EntityFrameworkCore)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlinterpolatedasync?view=efcore-6.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
As far as we are aware, syntax highlighting is not supported for code in the API docs.
