### ISSUE TITLE
Code doesn't work

### ISSUE THREAD

**Issue by ianpowell2017** [dotnet/EntityFramework.Docs#4095]
Hello, I am trying to follow the steps defined.

I think you're missing a step where you instruct version 7 of the tools to be installed.  The default tools being installed are version 6, so I get 

```
info : Restoring packages for /Users/ianpowell/git/entityframework/EFGett/EFGett.csproj...
error: NU1605: Detected package downgrade: Microsoft.EntityFrameworkCore.Design from 7.0.0-rc.2.22472.11 to 6.0.10. Reference the package directly from the project to select a different version. 
error:  EFGett -> Microsoft.EntityFrameworkCore.Tools 7.0.0-rc.2.22472.11 -> Microsoft.EntityFrameworkCore.Design (>= 7.0.0-rc.2.22472.11) 
error:  EFGett -> Microsoft.EntityFrameworkCore.Design (>= 6.0.10)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 488629d4-9bd2-42b5-4644-34e3f2baee59
* Version Independent ID: b38b9d14-6bad-12e0-8d2d-24b50bc4977e
* Content: [Getting Started - EF Core](https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/overview/first-app.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/first-app.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
@ianpowell2017  why do you say the code doesn't compile when it downgrades.
> I think you're missing a step where you instruct version 7 of the tools to be installed. 
Where does it say that?

I'm guessing you installed .NET 7 RC2 and followed the instructions. The install instructions then bring in the lasted released version which is 6.
