### ISSUE TITLE
NRT DbSet default seems incorrect in example.

### ISSUE THREAD

**Issue by Gateswong** [dotnet/EntityFramework.Docs#4105]
Possible related PR: https://github.com/dotnet/EntityFramework.Docs/commit/db7df54678a225da9ebb85371be59263b46068c0#diff-c98f9d4ab6f3584846cc2f188a8ecea77bbfe34fe592d217b907f765763a5b46

In this PR, the example code was changed to:

```
        public DbSet<Customer> Customers => Set<Customer>();
        public DbSet<Order> Orders => Set<Order>();
```

What are `Set`s in above snippet? The most commonly possible classes are `DbSet` or `HashSet` but neigher works when replaced `Set` in above.

<EDIT> Neigher `new DbSet<Customer>()` works because `DbSet` is abstract class.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Gateswong `Set` is a call to the `Set` method on  DbContext.

**Comment by Gateswong** [comment]
Oh. That's it. I typed wrong `=` instead of `=>`. Thank you for helping.
