### ISSUE TITLE
Mark Properties optional afaik not possible

### ISSUE THREAD

**Issue by AndreasHoersken** [dotnet/EntityFramework.Docs#4106]
Hi all,
in the last paragraph of https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#navigating-and-including-nullable-relationships it states: "...configure them as optional via the Fluent API or Data Annotations...". I did not find a way to do this.  

Is there an optional-Attribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@AndreasHoersken Optional properties are properties that are not required. This typically doesn't need any configuration other than the property being nullable, but can be configured explicitly with `IsRequired(false)` if needed.
