### ISSUE TITLE
Please make SQL server backend async performance issue more prominent

### ISSUE THREAD

**Issue by kevbry** [dotnet/EntityFramework.Docs#4109]
It would be ideal if the known performance issues with using the sqlclient provider in async were noted more prominently. There is a small and easy to miss note on the general async programming docs page ( https://learn.microsoft.com/en-us/ef/core/miscellaneous/async ), but I don't think a single note in that section aligns with the potentially extreme impact of the issue.

I understand that efcore is not responsible for the underlying issue, but it is very definitely impacting users of efcore, especially given that efcore samples and tutorials make use of async patterns against the sqlclient provider and would lead users to trip over this issue. The primary intro tutorial specifically encourages users to make use of async patterns when using efcore against sql server, which is in opposition to the recommendations from the SqlClient bugs below.
https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-6.0&tabs=visual-studio#asynchronous-ef-methods-in-aspnet-core-web-apps

Reading through comments on several dozen issues raised in the efcore and sql provider repos show that many users of efcore are encountering this issue and having to spend (presumably) a lot of time tracking it down.

https://github.com/dotnet/SqlClient/issues/601
https://github.com/dotnet/SqlClient/issues/593

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ef8271d-8d22-fb0c-240d-0ff9c97d38b3
* Version Independent ID: af433371-e282-4b89-7b09-6caf43af83e0
* Content: [Microsoft SQL Server Database Provider - EF Core](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/sql-server/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/sql-server/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@kevbry what kind of "prominent message" do you have in mind? We could add another note on the [SQL Server provider overview page](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/?tabs=dotnet-core-cli), but I'm generally skeptical of the value of this...

For this kind of perf issue/limitations, users don't generally systematically read all the docs, and then go and write the programs, taking all of the limitations/notes into account. I understand and appreciate with the pain that this SqlClient issue causes, and with how hard it is to track down the root cause in these cases; I also share the desire to save other users this pain. But IMHO past experience has shown that adding such a note would do very little to help there; I believe users would mostly still run into the issue, and only discover the doc note after having gone through the pain of diagnosing the issue.

Users don't generally read all the docs up-front, discovering limitations and avoiding

**Comment by kevbry** [comment]
@roji That's a good point. My inclination would be to plaster it in as many places as possible, just to give people a decent chance of happening across it. As-is it isn't very discoverable being only in the github issues on sqlclient, and mostly in closed tickets in the efcore repo. With async being considered best practice for cases like this involving remote I/O also makes it a lot harder to track down, since "maybe it's because I'm using async" doesn't enter easily into mind as a possible cause.

There are a few places in the existing docs that to me seem like decent candidates
- https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-6.0&tabs=visual-studio#asynchronous-ef-methods-in-aspnet-core-web-apps
  - The intro tutorial has an "async methods in asp.net core web apps" section that describes async efcore as a best practice. The tutorial is using sqlclient provider, and one or more models that could possibly fall victim to this issue as they'll map to nvarchar(max). While the fields in question are things like "title" that are unlikely to be long enough to cause a noticeable problem, it's probably worth a note 
  - You probably have better metrics than I do, but whichever sqlclient-consuming sample projects are out there might also be good candidates for an inline comment on usages of async.
- https://learn.microsoft.com/en-us/ef/core/performance/
  - Even though it isn't specific to sqlclient provider, this section seems like a likely spot someone would end up if they were seeing major perf problems. It's the first place I looked. My limited experience (3 independent teams) with this issue has been that everyone assumes either efcore or some environment configuration is to blame. Their assumption is that the sqlclient library wouldn't have this kind of a bug in the async path given async's "best practice" status and sqlclient being a fairly core component in a lot of codebases.

**Comment by roji** [comment]
@kevbry thanks for these suggestions!

Submitted #4161 to add notes in the [SQL Server main provider page](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/?tabs=dotnet-core-cli) and in the [async section of the querying performance docs](https://learn.microsoft.com/en-us/ef/core/performance/efficient-querying#asynchronous-programming). Also opened https://github.com/dotnet/AspNetCore.Docs/pull/27747 to add the note to the ASP.NET docs as you suggested.
