### ISSUE TITLE
Dynamic SQL and parameters: you can use FormattableStringFactory.Create and still use FromSqlInterpolated

### ISSUE THREAD

**Issue by jess-rod** [dotnet/EntityFramework.Docs#4111]
In the section [Dynamic SQL and parameters](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#dynamic-sql-and-parameters), it is stated:

> If you've decided you do want to dynamically construct your SQL, you'll have to use [FromSqlRaw](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalqueryableextensions.fromsqlraw) [...].

There is another alternative to still using FromSqlInterpolated:
```
var propertyName = "User";
var propertyValue = "johndoe";
var query = FormattableStringFactory.Create($"SELECT * FROM [Blogs] WHERE {propertyName} = {{0}}", propertyValue);
var blogs = context.Blogs
    .FromSqlInterpolated(query)
    .ToList();
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98b01ef5-24a5-5f59-30c9-af264f739815
* Version Independent ID: 98b01ef5-24a5-5f59-30c9-af264f739815
* Content: [SQL Queries - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries)
* Content Source: [entity-framework/core/querying/sql-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/sql-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@jess-rod yes, it's possible to piece together a FormattableString via FormattableStringFactory, but where do you see the advantage of that over just using FromSqlRaw? The two techniques are almost identical - neither offers automatic protection against SQL injection (which you do get when using FormattableString literals), etc.

**Comment by jess-rod** [comment]
It's just an alternative. I don't see any important advantage. I'd point out though that using FromSqlRaw is more error-prone in my opinion. In fact, you'd get a run-time error with the code below because _propertyValue_ is misspelled when creating a new SqlParameter.

### Using FromSqlInterpolated
```
var query = FormattableStringFactory.Create($"SELECT * FROM [Blogs] WHERE {propertyName} = {{0}}", propertyValue);
var blogs = context.Blogs
    .FromSqlInterpolated(query)
    .ToList();
```
### Using FromSqlRaw
```
var propertyValue = new SqlParameter("propretyValue", "Some value"); // propertyValue is misspelled
var blogs = context.Blogs
    .FromSqlRaw($"SELECT * FROM [Blogs] WHERE {propertyName} = @propertyValue", propertyValue)
    .ToList();
```

**Comment by ajcvickers** [comment]
Note from triage: we don't think it makes sense to direct people down this path, because it makes SQL injection more likely.
