### ISSUE TITLE
Situation not contemplated

### ISSUE THREAD

**Issue by Cerebrado** [dotnet/EntityFramework.Docs#4116]
I have a project where I need to scaffold from one database, continue work with migrations in this database, and then  apply all changes into another database. So we have a conflict:
1) We scaffold to get the model
2) We add InitialMigration (to use migrations): Migrations does not work, as the tables already exist in this db. So, we go into 3.
3) We clear the UP and DOWN methods in the migration, but now we cannot run these migrations in another database that does not have these tables, because the tables are not created (even though they are listed in the ModelSnapshot).

So, I think some simple intelligence should be added to EF. 
If the database does not exists, create it. 
If the table does not exist create it, but if it exists, calculate differences to update!

Hope it helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30985321-a087-4ba8-1ef2-1311532ceaf5
* Version Independent ID: 97a0e081-b208-8042-5964-02bccb4a1db0
* Content: [Code First Migrations with an existing database - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/existing-database)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/existing-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/migrations/existing-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
