### ISSUE TITLE
broken efcore-docs-sqlserver-save-changes-and-computed-columns link

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/EntityFramework.Docs#4129]
here https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs#L215 there is a link to  https://aka.ms/efcore-docs-sqlserver-save-changes-and-computed-columns which is broken

**Comment by ajcvickers** [comment]
Fixed.
