### ISSUE TITLE
Document the incompatibility of the new 7.0 SaveChanges with certain computed column types

### ISSUE THREAD

**Issue by rkone** [dotnet/EntityFramework.Docs#4130]
After upgrading to EFCore 7.0, I ran into difficulty trying to save an update to my table with a computed column, it's directing me to the following link for further guidance:
https://aka.ms/efcore-docs-sqlserver-save-changes-and-computed-columns
(the link is broken). 

This table also has a trigger, giving the table a .HasTrigger("SomeTrigger") configuration has also fixed the computed column error, but I'd like to know when I review / remove the trigger - what should I do about the computed column?  I don't see any guidance for it.

**Comment by roji** [comment]
Leaving #4129 to track the broken aka.ms link, will use this to track amending the notes.

**Comment by gbiellem** [comment]
@roji  that aligns with our experience.  We've migrated 4  projects from EF6 to EF7.  Only the tables that had computed columns calling user defined functions required the HasTrigger() workaround.

**Comment by rkone** [comment]
We were also in the UDF boat. Thanks for the info and doc updates!
