### ISSUE TITLE
It should be disclosed that PrimaryKey(nameof() is a EF Core #7 only attribute

### ISSUE THREAD

**Issue by StijnOttenVMT** [dotnet/EntityFramework.Docs#4133]
In this page it says 

> You can also configure multiple properties to be the key of an entity - this is known as a composite key. Conventions will only set up a composite key in specific cases - like for an owned type collection.

And then show this code
```
[PrimaryKey(nameof(State), nameof(LicensePlate))]
Internal class Car
{
    public string State { get; set; }
    public string LicensePlate { get; set; }

    public string Make { get; set; }
    public string Model { get; set; }
}
```

But the `PrimaryKey` attribute is not part of EF Core.

Either this code block should be removed and only show the Fluent API code or there should be a note/comment added that `PrimaryKey` attribute is not part of EF Core and then a link to the correct package. (Tbh best solution i feel like is adding it to EF Core, but code first and only then documentation)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0a084df-15c4-ab25-26ca-83c8bdf6f026
* Version Independent ID: f1fba5b2-eb2e-da0a-fce0-d492855c1777
* Content: [Keys - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/keys?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/keys.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/keys.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by StijnOttenVMT** [comment]
Sorry was unaware this was part of the revision 7.0 update. But tbh things like ASP net core have revisions in their doc maybe EF Core should too

**Comment by roji** [comment]
@StijnOttenVMT we've discussed this in the past, and decided that it's better to have a single version of the docs, and to call out in specific places where a new API was introduced, etc. I've submitted #4136 to do that here.
