### ISSUE TITLE
"We plan" is wrong

### ISSUE THREAD

**Issue by AntonC9018** [dotnet/EntityFramework.Docs#4134]
[Here](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/value-conversions.md#composite-value-objects), it says "We plan to add support ... in EF Core 6.0", which is already out. I'm not sure of the current state of things, so I can't do a PR to fix this, but I think it was pushed to version 8.

**Comment by AntonC9018** [comment]
The second note [here](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/value-conversions.md#value-objects-as-keys) should also be reviewed.

**Comment by roji** [comment]
@AntonC9018 thanks, submitted #4135 to fix these.
