### ISSUE TITLE
"&" instead of "and"

### ISSUE THREAD

**Issue by web-activtradesbr** [dotnet/EntityFramework.Docs#4138]
Hello
I'm using EF with MySql and when it generates the select it looks like this:

  SELECT `n`.`Id`, `n`.`NotificationId`, `n`.`Readed`, `n`.`UserId`
           FROM `NotificationUsers` AS `n`
           WHERE NOT (`n`.`Readed`) & ((`n`.`UserId` = 5) AND `n`.`UserId` IS NOT NULL)

But the correct would be

  SELECT `n`.`Id`, `n`.`NotificationId`, `n`.`Readed`, `n`.`UserId`
           FROM `NotificationUsers` AS `n`
           WHERE NOT (`n`.`Readed`) AND ((`n`.`UserId` = 5) AND `n`.`UserId` IS NOT NULL)

"&" instead of "and"

Can you help me?

**Comment by ajcvickers** [comment]
@web-activtradesbr Which MySQL provider NuGet package are you using?

**Comment by web-activtradesbr** [comment]
@ajcvickers 
MySql.Data.EntityFramework "8.0.28"
MySqlConnector "2.1.8"

**Comment by web-activtradesbr** [comment]
@ajcvickers 
Thank you very much, I will follow your advice :)
Bye
