### ISSUE TITLE
Issue #27372: workaround for SQL Server tables with triggers now require special EF Core configuration does not compile

### ISSUE THREAD

**Issue by hbulens** [dotnet/EntityFramework.Docs#4142]
The workaround on [this](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#mitigations-2) page contains code that doesn't compile with EF Core 7:

> 'IConventionTrigger' does not contain a definition for 'GetName' and the best extension method overload 'RelationalKeyExtensions.GetName(IReadOnlyKey, in StoreObjectIdentifier)' requires a receiver of type 'IReadOnlyKey'	

In the `BlankTriggerAddingConvention` class, the following method is problematic in both `GetName` method calls:

```csharp
public virtual void ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext<IConventionModelBuilder> context)
  {
      foreach (IConventionEntityType entityType in modelBuilder.Metadata.GetEntityTypes())
      {
          StoreObjectIdentifier? table = StoreObjectIdentifier.Create(entityType, StoreObjectType.Table);

          if (table != null && entityType.GetDeclaredTriggers().All(t => t.GetName(table.Value) == null))
              entityType.Builder.HasTrigger(table.Value.Name + "_Trigger");


          foreach (IConventionEntityTypeMappingFragment fragment in entityType.GetMappingFragments(StoreObjectType.Table))
          {
              if (entityType.GetDeclaredTriggers().All(t => t.GetName(fragment.StoreObject) == null))
              {
                  entityType.Builder.HasTrigger(fragment.StoreObject.Name + "_Trigger");
              }
          }
      }
  }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1b683ae-c697-ebc8-d0aa-648d7573136e
* Version Independent ID: f1b683ae-c697-ebc8-d0aa-648d7573136e
* Content: [Breaking changes in EF Core 7.0 (EF7) - EF Core](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes)
* Content Source: [entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@hbulens your code looks different from the one in [our docs](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#sqlserver-tables-with-triggers): our code sample uses GetDatabaseName, whereas you're using GetName.

**Comment by hbulens** [comment]
You are right. Makes me wonder where I got the original code snippet from. Either way, all is well then!
