### ISSUE TITLE
Suggest using required members for non-nullable properties

### ISSUE THREAD

**Issue by NetherGranite** [dotnet/EntityFramework.Docs#4146]
In the section titled "Non-nullable properties and initialization" would it be appropriate to suggest marking these properties as `required` in C# 11+?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@NetherGranite yep, thanks - that was on my todo list. Submitted #4148, let me know what you think.

**Comment by NetherGranite** [comment]
@roji Wow that was so fast, looks great! Now for the ASP team to consider supporting required members as an alternative to constructor binding in dependency injection, haha.
