### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by RARomano** [dotnet/EntityFramework.Docs#4158]
The link available at the bottom of the page redirects to Bing and not to the expected location:
https://aka.ms/efcore-docs-bulk-operations

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8098ba96-ac74-63cb-8269-608719bfb4c4
* Version Independent ID: 8098ba96-ac74-63cb-8269-608719bfb4c4
* Content: [RelationalQueryableExtensions.ExecuteDelete&lt;TSource&gt; Method (Microsoft.EntityFrameworkCore)](https://learn.microsoft.com/en-us/dotnet/api/Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteDelete?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/RelationalQueryableExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalQueryableExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@ajcvickers until we have docs for bulk update, maybe we should redirect that aka.ms link to the relevant section in what's new?

**Comment by ajcvickers** [comment]
Done.
