### ISSUE TITLE
Can I contribute an introduction of a tool for StronglyTypedId in EFCore?

### ISSUE THREAD

**Issue by yangzhongke** [dotnet/EntityFramework.Docs#4160]
Hi,
I created an open-source project, which can generate StronglyTypedId types for EFCore 7.
According to the documentation of 'What's New in EF Core 7.0', the 'Value generation for DDD guarded types' requires a lot of code to be written. With my project, developers just need to a [HasStronglyTypedId] to the entity type. Therefore, the project can facilitate the use of "guarded keys"  in EF Core.
The repository: https://github.com/yangzhongke/LessCode.EFCore.StronglyTypedId

Can I add it to the EntityFramework.Docs?
If permitted, I'd like to add it to https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew

Regards
Zack

**Comment by ErikEJ** [comment]
You should add it to the bottom of this list https://learn.microsoft.com/en-us/ef/core/extensions/

**Comment by ajcvickers** [comment]
Here's an example of a recent PR: https://github.com/dotnet/EntityFramework.Docs/pull/4152

**Comment by yangzhongke** [comment]
Thanks, I have created a PR.
