### ISSUE TITLE
Database created, but no such table as "Blogs" displays...

### ISSUE THREAD

**Issue by kkkristo** [dotnet/EntityFramework.Docs#4170]
Good job!

***EDIT restoring deleted meta data see Edit history***

![image](https://user-images.githubusercontent.com/3605364/205358827-03ab3f6d-47b2-4b19-8dc0-6f2461280815.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 488629d4-9bd2-42b5-4644-34e3f2baee59
* Version Independent ID: b38b9d14-6bad-12e0-8d2d-24b50bc4977e
* Content: [Getting Started - EF Core](https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/overview/first-app.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/first-app.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@kkkristo can you provide more details? Which doc page are you looking at?

**Comment by Rick-Anderson** [comment]
@kkkristo try again, the instructions are correct.

**Comment by kkkristo** [comment]
Hello, sorry for bothering you. I cancelled my post as it finally worked fine.  Just beginner&#39;s impatience.   Thanks for your reply.   Best regards,  Krzysztof  
            
          
     
      
       
        Dnia 2 grudnia 2022 19:13 Rick Anderson ***@***.***&gt; napisał(a):
       
    
       
         
 github.com @kkkristo  try again, the instructions are correct.

**Comment by kkkristo** [comment]
Hello, sorry for bothering you. I cancelled my post as it finally worked fine.  Just beginner&#39;s impatience.  Thanks for your reply.   Best regards,  Krzysztof   
            
          
     
      
       
        Dnia 2 grudnia 2022 17:21 Shay Rojansky ***@***.***&gt; napisał(a):
       
    
       
         
 github.com @kkkristo  can you provide more details? Which doc page are you looking at?
