### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by theredwing** [dotnet/EntityFramework.Docs#4173]
dotnet ef database update is what you wrote on this page but we say Update-database.  If you guys are going to change the syntax (which you always do)  can't you update the documentation!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 459d20e7-ba25-c162-5721-359ef3562999
* Version Independent ID: d988e806-cb86-19f5-7f76-6ce3bfcd94ed
* Content: [Design-time DbContext Creation - EF Core](https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?source=recommendations&tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/cli/dbcontext-creation.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/cli/dbcontext-creation.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@theredwing It depends on whether you are using the Visual Studio Package Manager Console, or the .NET command line. Notice there are two tabs:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/1430078/205497378-8d94307e-7132-4c8e-8629-79cfb97e528f.png">

<img width="731" alt="image" src="https://user-images.githubusercontent.com/1430078/205497395-40b4ae55-7976-42a8-94da-c83d08b91487.png">
