### ISSUE TITLE
Clarify the package(s) needed for this to work

### ISSUE THREAD

**Issue by CoolDadTx** [dotnet/EntityFramework.Docs#4175]
The provided code is designed to allow you to drop this into an existing codebase. However it relies on extension methods that aren't in the core package and therefore someone needs to search for the correct package as even Quick Actions doesn't provide any help here. From my understanding the following package reference is also needed: `Microsoft.EntityFrameworkCore.Relational`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17ec8149-1d9e-92bf-7933-0b570eda382f
* Version Independent ID: 17ec8149-1d9e-92bf-7933-0b570eda382f
* Content: [Miscellaneous - Microsoft SQL Server Database Provider - EF Core](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/misc)
* Content Source: [entity-framework/core/providers/sql-server/misc.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/sql-server/misc.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@CoolDadTx No additional packages are required here. `Microsoft.EntityFrameworkCore.Relational` is brought in transitively by the `Microsoft.EntityFrameworkCore.SqlServer` package and so does not need to be referenced explicitly.

**Comment by CoolDadTx** [comment]
@ajcvickers But `SqlServer` package is only needed on the host project where you are configuring your context to use SQL Server. In all other cases (such as libraries used across applications) the only dependencies are the core primitive/interface assemblies of EF Core. Specifically the sample code all work against the primitive types of EF Core except the 2 extension methods mentioned.

**Comment by ajcvickers** [comment]
@CoolDadTx Fair point.

**Comment by ajcvickers** [comment]
We discussed this, and agreed that while this is technically true, the reality is that some level of basic understanding must be assumed for any docs page, otherwise the size and complexity of the page hides the primary content and makes it unapproachable for the average user. Therefore, we are not going to make any change here.
