### ISSUE TITLE
ValueConverters called in OnModelCreating not working for inserts and updates

### ISSUE THREAD

**Issue by sf1984** [dotnet/EntityFramework.Docs#4179]
ValueConverters called in OnModelCreating are not working for inserts and updates.
It works only when reading from the database.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by sf1984** [comment]
If I came from a webpage tutorial, it just means I am referring to the code in the tutorial.

Try it for yourself inserting a value in the database.
No method work. It works only when reading from the database.

https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations
"Value converters allow property values to be converted when reading from or **writing** to the database"

protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
    configurationBuilder
        .Properties<Currency>()
        .HaveConversion<CurrencyConverter>();
}

**Comment by ajcvickers** [comment]
@sf1984 I just ran all the sample code for that page, and it all works for me.

**Comment by sf1984** [comment]
Sure, see how it works

Just a little example for the property Title of the model Post

            modelBuilder.Entity<Post>()
                .Property(e => e.Title)
                .HasConversion(
                v => v,
                v => v.ToUpper());

I insert the title as Lowercase

![image](https://user-images.githubusercontent.com/45759523/206551565-356bcd7b-732c-4723-9a37-41848bb27af8.png)

It's not stored in the db as uppercase

![image](https://user-images.githubusercontent.com/45759523/206551741-5abd751a-ad89-463c-a76d-42e146b10ec3.png)

The select works, it's uppercase

![image](https://user-images.githubusercontent.com/45759523/206551812-1b7157ee-81e9-4967-a5ba-e4386c7c3f17.png)

**Comment by ajcvickers** [comment]
@sf1984 In your converter, the expression for converting from the client value to the database value is `v => v`. So you are telling the converter to not do any conversion when sending the value to the database.

**Comment by sf1984** [comment]
Got it, thanks. But it wasn't so obvious (at least for me).

So basically I can build my own custom rule and override the ConfigureConventions to change the case of all the strings:

```
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
 configurationBuilder.Properties<string>().HaveConversion<ToUpperConverter>();
}
```

```
public class ToUpperConverter : ValueConverter<string, string>
    {
        public ToUpperConverter() : base(v => v.Trim().ToUpper(), v => v.Trim().ToUpper())
        {
        }
    }
```
