### ISSUE TITLE
Can Identity setup be included too

### ISSUE THREAD

**Issue by future81** [dotnet/EntityFramework.Docs#4181]
Can setup method of Identity UserManger and RoleManager be Included in this document too

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7fc3c3b-c859-2ad5-78f3-ce57d3c9bc2d
* Version Independent ID: b7fc3c3b-c859-2ad5-78f3-ce57d3c9bc2d
* Content: [Testing against your Production Database System - EF Core](https://learn.microsoft.com/en-us/ef/core/testing/testing-with-the-database)
* Content Source: [entity-framework/core/testing/testing-with-the-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/testing-with-the-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by future81** [comment]
Identity UserManager and RoleManager

**Comment by ajcvickers** [comment]
Yes, but what do you mean by "included"?

**Comment by Softwaresell** [comment]
in this example in docs

**Comment by ajcvickers** [comment]
This documentation is about the process of testing EF applications in different ways--in this case, using the same database system as is used in production. It is not about testing any particular EF model or domain. If you want help testing against the ASP.NET Core Identity model, then I would suggest asking for help on the ASP.NET Core repo.
