### ISSUE TITLE
Code sample for 'Temporal tables support owned entities' does not work

### ISSUE THREAD

**Issue by Tim-Hodge** [dotnet/EntityFramework.Docs#4207]
The given sample for 'Temporal tables support owned entities' does not work out-the-box.

In a clean project with the `Employee` and `EmployeeInfo` classes, a new DbContext with the supplied config fails to compile.

The initial error is:
```
Ambiguous invocation: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder ToTable(this Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder, string, System.Action<Microsoft.EntityFrameworkCore.Metadata.Builders.TableBuilder>) (in class RelationalEntityTypeBuilderExtensions) Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<ef_temporal_tables.Employee> ToTable<Employee>(this Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<ef_temporal_tables.Employee>, string, System.Action<Microsoft.EntityFrameworkCore.Metadata.Builders.TableBuilder<ef_temporal_tables.Employee>>) (in class RelationalEntityTypeBuilderExtensions) match
```

Some further fiddling both in a test project and a real one hasn't produced anything working; perhaps some missing extensions/usings, or there is some other way to write this?

In lieu of https://github.com/dotnet/efcore/issues/29303 it would be great to have this working.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8aad46-30fc-c5ef-8be2-5b94a0ded8eb
* Version Independent ID: 9c8aad46-30fc-c5ef-8be2-5b94a0ded8eb
* Content: [What's New in EF Core 7.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#temporal-tables-support-owned-entities)
* Content Source: [entity-framework/core/what-is-new/ef-core-7.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-7.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by Tim-Hodge** [comment]
After further investigation it was inclusion of the `Microsoft.EntityFrameworkCore.SqlServer` package that was required to get this working.

**Comment by ajcvickers** [comment]
@Tim-Hodge Remember that all the samples are available to download. So if it's not working in your project, then downloading the runnable sample is a good way to check what's wrong.
