### ISSUE TITLE
API Documentation - Fail

### ISSUE THREAD

**Issue by clockwiseq** [dotnet/EntityFramework.Docs#4226]
Could someone please expand on the API Documentation site for Entity Framework?  All it currently has is the methods and namespace info.  No details on what it does or what it expects or what it returns.

**Comment by roji** [comment]
Which site are you looking at exactly? [Here's the documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext?view=efcore-7.0) for EF Core's DbContext, there's lots of text there discussing various aspects.

Though we generally recommend starting on the conceptual docs ([here](https://learn.microsoft.com/en-us/ef/core/)), and only using the API docs for specific APIs/advanced usage etc.

**Comment by clockwiseq** [comment]
https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.query.queryablemethods.anywithoutpredicate?view=efcore-7.0

**Comment by roji** [comment]
That's a pretty internal method that shouldn't be needed/used by users. It's exposed mainly for other EF providers.

**Comment by clockwiseq** [comment]
Ok, then what about any of the other methods?

https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.query.queryablemethods.contains?view=efcore-7.0

**Comment by roji** [comment]
@clockwiseq anything on QueryableMethods. As its [docs say](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.query.queryablemethods?view=efcore-7.0), it's a "class that provides reflection metadata for translatable LINQ methods".

Is there any particular reason you're looking at this class? EF exposes many APIs which aren't meant for end-user consumption (but rather for database providers), and those APIs aren't always fully documented.

**Comment by clockwiseq** [comment]
I guess I'm looking in the wrong spot then.  I'm looking for the public end-user consumable extension methods for a DbSet such as Where, Any, Contains, Count, etc.

**Comment by roji** [comment]
Right, those would be the general .NET LINQ operators - this isn't really specific to EF Core. You can find these here: https://learn.microsoft.com/en-us/dotnet/api/system.linq.queryable?view=net-7.0

**Comment by clockwiseq** [comment]
Ok, that helps, but I was looking for something related to EF.  For instance, is there a sample documentation page that explains how a join works for a DbSet?

**Comment by roji** [comment]
I think you're looking for [this page](https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager).

If you want to, you can also use the standard LINQ [Join](https://learn.microsoft.com/en-us/dotnet/api/system.linq.queryable.join?view=net-7.0#system-linq-queryable-join-4(system-linq-iqueryable((-0))-system-collections-generic-ienumerable((-1))-system-linq-expressions-expression((system-func((-0-2))))-system-linq-expressions-expression((system-func((-1-2))))-system-linq-expressions-expression((system-func((-0-1-3)))))) operator, though that's usually not how people want to load related entities with EF Core.
