### ISSUE TITLE
Bulk Updates section on the Efficient Updating page refers to 'single roundtrip' even though it depends on batch size.

### ISSUE THREAD

**Issue by davepcallan** [dotnet/EntityFramework.Docs#4231]
Some confusion is possible on the efficient updating page regards batch size and number of roundtrips -> 
https://learn.microsoft.com/en-us/ef/core/performance/efficient-updating

Specifically in the Bulk Updates section -> https://learn.microsoft.com/en-us/ef/core/performance/efficient-updating#bulk-updates section the following paragraph, refers to 'all the changes' and 'single roundtrip thanks to batching'... 

> A second database roundtrip is performed to save all the changes. While all changes are done in a single roundtrip thanks to batching, EF Core still sends an UPDATE statement per employee, which must be executed by the database. 

... but doesn't it depend on batch size (for SQL Server at least) and in the case of the example given ... 

```
foreach (var employee in context.Employees)
{
    employee.Salary += 1000;
}

context.SaveChanges();
```

the number of employees? 
If there is 1000 employees and batch of 42, won't 24 update roundtrips be required? I'm using EF 6 and 7.

Apologies if wrong here. 

![ef-updates](https://user-images.githubusercontent.com/106764096/215285059-b434c5bc-68af-4af4-a387-c36ecd83f1af.png)

**Comment by ajcvickers** [comment]
@davepcallan 

> Some confusion is possible 

Were you confused? Or are you just suggesting that, hypothetically, some people might be confused?

**Comment by davepcallan** [comment]
Hi Arthur, it was confusing for me (and caused me to doubt my understanding) as I understood it would only be single update roundtrip if num records to update <= batch size. Based on something I saw yesterday on LinkedIn it might be confusing / misleading to others too..  

![image](https://user-images.githubusercontent.com/106764096/215319810-354a7b0f-4d28-4e64-b261-0fafd4d2aa90.png)



Batching section at top of page explains it perfectly well but bulk updates section doesn't refer back to the amount of roundtrips being impacted by records and batch size. It could be just an interpretation thing. 

Maybe a change from ... 

> A second database roundtrip is performed to save all the changes. While all changes are done in a single roundtrip thanks to batching, EF Core still sends an UPDATE statement per employee, which must be executed by the database.

to ..

> One or more additional database roundtrips are performed to save all the changes. The exact number of roundtrips depends on how many employee records are being updated and the batch size (if set). While all changes per batch are done in a single roundtrip EF Core still sends an UPDATE statement per employee, which must be executed by the database.

might clarify further.  
Pardon the nitpicking.

**Comment by roji** [comment]
Submitted #4232 to hopefully clarify this a bit.

**Comment by davepcallan** [comment]
It reads well 👍🏻. 
Thanks guys.
