### ISSUE TITLE
Typo in description for Cartesian Explosion

### ISSUE THREAD

**Issue by MorganJay** [dotnet/EntityFramework.Docs#4235]
I noticed a typo in the description of the "Cartesian Explosion term, as shown in the image below

<img width="445" alt="image" src="https://user-images.githubusercontent.com/32873262/215403455-046d5945-b6c8-4ff7-8dc9-ac8e9ea2e946.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43baa9f3-c415-c328-6c10-53aabaaec652
* Version Independent ID: 4e789a1b-aa88-d194-dc2e-0a23251250d7
* Content: [Single vs. Split Queries - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/single-split-queries)
* Content Source: [entity-framework/core/querying/single-split-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/single-split-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by MorganJay** [comment]
I noticed something weird, the typo is shown on the website but not present in the content source

**Comment by ErikEJ** [comment]
I was fixed yesterday but not published yet.

**Comment by MorganJay** [comment]
Okay cool. Thanks
