### ISSUE TITLE
EF Core bulk update

### ISSUE THREAD

**Issue by tibitoth** [dotnet/EntityFramework.Docs#4247]
This quote below is no longer valid in EF Core 7 

> Unfortunately, EF doesn't currently provide APIs for performing bulk updates. Until these are introduced, you can use raw SQL to perform the operation where performance is sensitive:
> 
> ```csharp
> context.Database.ExecuteSqlRaw("UPDATE [Employees] SET [Salary] = [Salary] + 1000");
> ```

See more: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f37e820a-137f-92c9-6662-06fafeac097a
* Version Independent ID: 0df73aed-692f-0e53-7562-ed3d8b89c6df
* Content: [Efficient Updating - EF Core](https://learn.microsoft.com/en-us/ef/core/performance/efficient-updating)
* Content Source: [entity-framework/core/performance/efficient-updating.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/performance/efficient-updating.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
We're indeed behind on updating docs - I'll be working on this soon.
