### ISSUE TITLE
DbContext.Set() seems to be missing

### ISSUE THREAD

**Issue by ericallenpaul** [dotnet/EntityFramework.Docs#4249]
This does not seem to match what shows up in intellisense.
I see:

```DbSet<TEntity> DbContext.Set<TEntity>()```

and

```DbSet<TEntity> DbContext.Set<TEntity>(string name)```

There is no

```DbSet<TEntity> DbContext.Set()```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86d308d2-9653-9cd5-2313-e60ea0e70fdf
* Version Independent ID: e8e3611f-8d9c-d9c6-1879-55ae9ed33e84
* Content: [DbContext.Set Method (System.Data.Entity)](https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext.set?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity/DbContext.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DbContext.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@ericallenpaul You're looking at the [EF6 documentation put likely using EF Core](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/).

**Comment by ericallenpaul** [comment]
Yep that's exactly the problem. Now I'm sad that they removed the method I needed. I need to create a generic version of "context.Customers" where "Customers" would be derived from a string. Can't use a variable between the "<>" so I guess I'll have to find another less generic approach.

**Comment by ajcvickers** [comment]
See #21066.

**Comment by ericallenpaul** [comment]
Yep I need a working version of GetDbSetForClrType.
I've been trying to figure out the MethodInfo/MakeGenericMethod but I can't seem to come up with a working version.
I know I need something like:

```
string namespaceName = "mynamespace.models";
var myModel = Activator.CreateInstance($"{namespaceName}, {"Customer}", namespaceName);
var type = myModel?.GetType();
var listType = typeof(List<>);

if (type != null)
{
     var constructedListType = listType.MakeGenericType(type);
     var instance = Activator.CreateInstance(constructedListType);
     string json = File.ReadAllText(file.FullName);

     JsonSerializerOptions options = new JsonSerializerOptions();
     var seedList = JsonSerializer.Deserialize(json, type, options);

     MethodInfo method = typeof(DbContext).GetMethod("AddRange");
     MethodInfo generic = method.MakeGenericMethod(myType);
     generic.Invoke(this, null, seedList);

}
```

**Comment by ajcvickers** [comment]
@ericallenpaul Note that you can call `AddRange`, etc. directly on the `DbContext`. You don't need a `DbSet` for that.

**Comment by ericallenpaul** [comment]
hmm...
So:
```
await context.AddRangeAsync(seedList);
await context.SaveChangesAsync();
```
It will figure out which table to add them to based on the type?

**Comment by ajcvickers** [comment]
Yes

**Comment by ericallenpaul** [comment]
OK Wow. Thanks for you help.
