### ISSUE TITLE
Show how to take a DataAccess obj and save as keyless

### ISSUE THREAD

**Issue by wayneh654** [dotnet/EntityFramework.Docs#4250]
[Enter feedback here]
What your not showing is how to Create a entry with a keyless from a DTO
EG

//convert the DTO to  a obj that has no key, (keyless)            
var obj = _mapper.Map<KeylessDTOTable, KeylessTable>(objDTO);
_dbWaterConsentsSamples.Add(obj);
//Then add and bingo - a error. 
//How do I add a keyless obj to EF Core. That's what I and many want to know how
int status = _dbWaterConsentsSamples.SaveChanges();
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3ffc114-df51-0be7-8972-6fcead14e011
* Version Independent ID: 94c34571-7314-aab1-7898-93ac6d0f3430
* Content: [Tracking vs. No-Tracking Queries - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/tracking)
* Content Source: [entity-framework/core/querying/tracking.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/tracking.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This is tracked by https://github.com/dotnet/efcore/issues/29897
