### ISSUE TITLE
Bundle-Migration is buggy at the moment (Feb 2023)

### ISSUE THREAD

**Issue by patrickjlee** [dotnet/EntityFramework.Docs#4261]
I tried Bundle-Migration in a very simple .NET 7 project. I got an error:

Build started...
Build succeeded.
Building bundle...
Build failed. Use --verbose to see errors.

I then tried 
Bundle-Migration --verbose
but that isn't recognised! I got:
Bundle-Migration : A positional parameter cannot be found that accepts argument '--verbose'.

Bundle-Migration -verbose  did seem to give a bit more information:

Error NETSDK1112: The runtime pack for Microsoft.NETCore.App.Runtime.win-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'win-x64'.

Please will you fix the bugs and update this article? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06b35eff-79e4-2068-6d1c-f9079d43f903
* Version Independent ID: 6c575b10-048c-349c-397e-0d9c11d47235
* Content: [Applying Migrations - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=vs)
* Content Source: [entity-framework/core/managing-schemas/migrations/applying.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/applying.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Tracked by https://github.com/dotnet/sdk/issues/30466
