### ISSUE TITLE
Make reference to EF7 [Owned]

### ISSUE THREAD

**Issue by tbasallo** [dotnet/EntityFramework.Docs#4262]
It might be useful and helpful to add a mention that in EF7 this is now covered by the [Owned](https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities) entity. Took me a bit to figure it out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36558c08-d35c-8748-547b-17b1d609d11b
* Version Independent ID: 66917019-3d75-c691-bfaa-14fd3d8bbc31
* Content: [Complex Types - EF Designer - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/designer/data-types/complex-types)
* Content Source: [entity-framework/ef6/modeling/designer/data-types/complex-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/designer/data-types/complex-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
