### ISSUE TITLE
Switching Tenant Gotcha

### ISSUE THREAD

**Issue by hammypants** [dotnet/EntityFramework.Docs#4268]
The "Switching Tenants" section leaves out a pretty big gotcha considering an `OnModelCreating` query filter is recommended in a section above it: regardless of lifetime, said query filter will never be updated.

It should probably recommend a per-tenant `IModelCacheKeyFactory`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb29a2b6-c401-287f-2da9-1aeb3c633b41
* Version Independent ID: bb29a2b6-c401-287f-2da9-1aeb3c633b41
* Content: [Multi-tenancy - EF Core](https://learn.microsoft.com/en-us/ef/core/miscellaneous/multitenancy)
* Content Source: [entity-framework/core/miscellaneous/multitenancy.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/multitenancy.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by ajcvickers** [comment]
@hammypants The query filter should not change for different tenants. Instead, it should use a value obtained from the current context instance to indicate the current tenant.

**Comment by roji** [comment]
To add to @ajcvickers's answer, the assumption is that different tenants use the same database table schema (and indeed, the same database); that means that there shouldn't be different models for different tenants.

In some cases, different tenants may indeed have different databases/schemas, and in those cases a different model would be required per tenant; but those scenarios are significantly more complicated and are not covered here.

**Comment by danpadmore** [comment]
Hi @ajcvickers @roji 

Do you consider applying query filters conditionally a case that warrants having different models? (by using IModelCacheKeyFactory)

```C#
// Example
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    if (!tenantService.IsAdmin)
    {
        modelBuilder.Entity<TenantEntity>()
            .HasQueryFilter(x => x.TenantId == tenantService.TenantId);
    }
}
```

Because in that scenario the database/schema is the same, but the query filter would differ depending on the type of tenant for example.

This doesn't work however, the code below demonstrates this:
1. Create context as tenant 1: can create and read own data
2. Create context as tenant 2 which is an "admin": should be allowed to read all data, but cannot since model of regular tenant is cached and so wrong query filter is used

Can you confirm this behaves as expected and shouldn't be used this way, or is this an issue?

```C#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

var createApplicationDbContextInMemory = (ITenantService tenantService) =>
{
    var connection = new SqliteConnection("DataSource=:memory:");
    connection.Open();

    var inMemoryOptions = new DbContextOptionsBuilder<ApplicationDbContext>().UseSqlite(connection).Options;

    var context = new ApplicationDbContext(inMemoryOptions, tenantService);
    context.Database.EnsureCreated();

    return context;
};

// Setup entity linked to my tenant
var myTenantService = new TenantService(tenantId: 1, isAdmin: false);
var myTenantEntity = new TenantEntity { Id = 1, TenantId = myTenantService.TenantId };

using var myApplicationDbContext = createApplicationDbContextInMemory(myTenantService);
myApplicationDbContext.Add(myTenantEntity);
myApplicationDbContext.SaveChanges();
myApplicationDbContext.ChangeTracker.Clear();

// Confirm can query entity linked to my tenant
myApplicationDbContext.TenantEntities.Single(x => x.Id == myTenantEntity.Id);

// Problem => cannot query entity as admin, because OnModelCreating is not triggered again since model is cached
var otherTenantService = new TenantService(tenantId: 2, isAdmin: true);
using var otherApplicationDbContext = createApplicationDbContextInMemory(otherTenantService);
otherApplicationDbContext.TenantEntities.Single(x => x.Id == myTenantEntity.TenantId);   // crashes, sequence empty

Console.ReadLine();


public class ApplicationDbContext : DbContext
{
    public readonly ITenantService tenantService;

    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options, ITenantService tenantService)
        : base(options)
    {
        this.tenantService = tenantService;
    }

    public DbSet<TenantEntity> TenantEntities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        if (!tenantService.IsAdmin)
        {
            modelBuilder.Entity<TenantEntity>()
                .HasQueryFilter(x => x.TenantId == tenantService.TenantId);
        }
    }
}

public interface ITenantService
{
    int TenantId { get; }
    bool IsAdmin { get; }
}

public class TenantService : ITenantService
{
    public int TenantId { get; }
    public bool IsAdmin { get; }

    public TenantService(int tenantId, bool isAdmin)
    {
        TenantId = tenantId;
        IsAdmin = isAdmin;  
    }
}

public class TenantEntity
{
    public int Id { get; set; }
    public int TenantId { get; set;}
}

/*
Project file:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="7.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.3" />
  </ItemGroup>

</Project>

*/
```

**Comment by roji** [comment]
@danpadmore a changing tenant ID should not be the reason for having two different models; you should only need different models if the *structure* of your query filter differs. The multi-tenant example in our [query filter docs](https://learn.microsoft.com/en-us/ef/core/querying/filters) shows this: simply store the tenant ID on your context instance (as a private field) and reference it from your query filter; everything should work.

**Comment by danpadmore** [comment]
@roji thanks for your reply, I understand now that I should rewrite my example so the structure of the query filter stays the same across models:
```C#
 protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    // Do not apply query filter for certain cases, this would require separate model per case
    // if (!tenantService.IsAdmin)
    // {
    //    modelBuilder.Entity<TenantEntity>()
    //        .HasQueryFilter(x => x.TenantId == tenantService.TenantId);
    // }

    // Instead use single query filter for all cases
    modelBuilder.Entity<TenantEntity>()
        .HasQueryFilter(x => tenantService.IsAdmin || x.TenantId == tenantService.TenantId);
}
```

I didn't take into account that *DbContext.OnModelCreating* 's result might be cached, which set me on the wrong path.
