### ISSUE TITLE
You could write that tojson only works for sqlserver. 

### ISSUE THREAD

**Issue by mattiasw2** [dotnet/EntityFramework.Docs#4275]
[Enter feedback here]

After some googling I found https://github.com/dotnet/efcore/issues/28816

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9d2e5f-2165-1142-5002-a0123b04648f
* Version Independent ID: 7c9d2e5f-2165-1142-5002-a0123b04648f
* Content: [RelationalOwnedNavigationBuilderExtensions.ToJson Method (Microsoft.EntityFrameworkCore)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalownednavigationbuilderextensions.tojson?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/RelationalOwnedNavigationBuilderExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalOwnedNavigationBuilderExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@mattiasw2 this is called out quite clearly in our [What's new section for ToJSON](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#json-columns); the XML documentation for the ToJSON API isn't really the appropriate place to go into which provider is supported and which isn't...

**Comment by mattiasw2** [comment]
Thank you! I missed that.
