### ISSUE TITLE
PlanetaryDocs: Better example of keeping database integrity across containers.

### ISSUE THREAD

**Issue by maximecaron** [dotnet/EntityFramework.Docs#4279]
When updating document,  one entry in Documents container and many entry in Meta  container is updated.
All those entry need to be updated atomically (either all are updated or none are updated). 
Otherwise the 2 container will become out of sync if the service crash after calling HandleMetaAsync but before updating the Document container.

How can this be designed to not leave the data in the DB corrupted?

**Comment by roji** [comment]
Which database are you using?

**Comment by maximecaron** [comment]
this would be CosmosDB.
And by "corrupted" what I mean is the Tag table would refer to document that have been deleted or the document have tag that have not been inserter in the tag table.

In both of those situation it make searching a Document by tag not work correctly.

**Comment by roji** [comment]
If you're looking for EF using [transactions on Cosmos](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/transactional-batch?tabs=dotnet), that's tracked by #17308.
