### ISSUE TITLE
If you don't want to expose a DbSet... ensure they are included?

### ISSUE THREAD

**Issue by mastry** [dotnet/EntityFramework.Docs#4284]
This paragraphs seems to have a typo (or else the meaning is very unclear). I'm guessing `included in` should be `excluded from`.

```
If you don't want to expose a DbSet for one or more entities in the hierarchy, you can also use the Fluent API to ensure they are included in the model.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a10898c5-abee-1843-cfff-b2707f8a079a
* Version Independent ID: d9399618-488e-20b1-f707-35a191b95cc1
* Content: [Inheritance - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance)
* Content Source: [entity-framework/core/modeling/inheritance.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/inheritance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
No, that's accurate. If you have a DbSet property, then there's no need to use the Fluent API: the DbSet property already ensures that the entity is included in the model. If you **don't** want to have a DbSet property, then you need to use the Fluent API to ensure that the entity type is included.
