### ISSUE TITLE
Cannot find referenced file EntityTypeConfiguration.t4

### ISSUE THREAD

**Issue by chassq** [dotnet/EntityFramework.Docs#4285]
[Enter feedback here]
Hey, this doc (see: https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli) references a file called EntityTypeConfiguration.t4 but I cannot seem to locate it in the efcore src nor the ef core power tools src. Was wondering if I needed to pull it from (see: https://github.com/R4ND3LL/EntityFrameworkRuler/blob/main/src/EntityFrameworkRuler.Design/Resources/EntityTypeConfiguration.t4) for now?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cae415b7-c0ea-4d96-9d17-7e7d3163c09d
* Version Independent ID: cae415b7-c0ea-4d96-9d17-7e7d3163c09d
* Content: [Custom Reverse Engineering Templates - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/scaffolding/templates.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding/templates.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@chassq There is no default version of the "EntityTypeConfiguration.t4". This template that can be used, but it isn't used in anything EF does automatically. Issue #4088 tracks adding an example for this.

**Comment by chassq** [comment]
Thank you @ajcvickers !
