### ISSUE TITLE
example code please

### ISSUE THREAD

**Issue by dlwiii** [dotnet/EntityFramework.Docs#4286]
In general, it is helpful to show one or two lines of example code. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 124ced74-e710-4567-898c-50fe0beebc67
* Version Independent ID: b51788cd-a3aa-e165-4f5c-7908731a1534
* Content: [EntityCommand.ExecuteReader Method (System.Data.Entity.Core.EntityClient)](https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.core.entityclient.entitycommand.executereader?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity.Core.EntityClient/EntityCommand.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.Core.EntityClient/EntityCommand.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
