### ISSUE TITLE
How to configure json serialization options ?

### ISSUE THREAD

**Issue by wmarfil** [dotnet/EntityFramework.Docs#4288]
How to configure json serialization options that ef core use to serialize the DAO proprety into a json column?
I need to not escape certains non ASCII unicode characters, even though I know the deserialization works fine I need to have "as-is" data in the database 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8aad46-30fc-c5ef-8be2-5b94a0ded8eb
* Version Independent ID: 9c8aad46-30fc-c5ef-8be2-5b94a0ded8eb
* Content: [What's New in EF Core 7.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew)
* Content Source: [entity-framework/core/what-is-new/ef-core-7.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-7.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by maumar** [comment]
currently there is no way to customize the serializer. Support for it is tracked here: https://github.com/dotnet/efcore/issues/28043
