### ISSUE TITLE
Example app doesn't populate Products datagridview

### ISSUE THREAD

**Issue by Falconeer** [dotnet/EntityFramework.Docs#4291]
[Enter feedback here]
Running the example app as specified does not display data in the dataGridViewProducts datagrid.

You need to add:

this.productBindingSource.DataSource = dbContext.Products.Local.ToBindlingList();

after the line:

this.categoryBindingSource.DataSource = dbContext.Categories.Local.ToBindingList();

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed8b20d5-5fe5-a2c9-e024-8c24ff0846a1
* Version Independent ID: ed8b20d5-5fe5-a2c9-e024-8c24ff0846a1
* Content: [Get Started with Windows Forms - EF Core](https://learn.microsoft.com/en-us/ef/core/get-started/winforms)
* Content Source: [entity-framework/core/get-started/winforms.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/winforms.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Falconeer I just downloaded and ran the sample project and it is working as expected. Are you perhaps missing the `dataGridViewCategories_SelectionChanged` code?

**Comment by Falconeer** [comment]
I copied the code from the article, not from source control.

**Comment by ajcvickers** [comment]
Well, then I'm guessing you made a mistake.
