### ISSUE TITLE
Documentation does not say what this does or why to use it vs. alternatives

### ISSUE THREAD

**Issue by StevenMorrisonBeneficientcom** [dotnet/EntityFramework.Docs#4293]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88b09d38-1c58-6121-0705-32a1a3c36f69
* Version Independent ID: 4684a778-8d37-4bfa-7117-0716cc04008f
* Content: [EntityTypeBuilder.FindRelatedEntityType Method (Microsoft.EntityFrameworkCore.Metadata.Builders)](https://learn.microsoft.com/en-us/dotNet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder.findrelatedentitytype?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@StevenMorrisonBeneficientcom as the documentation states, this is an internal API that isn't meant to be consumed by users.
