### ISSUE TITLE
Highlight a warning that if adding a collation to a column it may make unit testing with SQLite down the line harder

### ISSUE THREAD

**Issue by ttony678** [dotnet/EntityFramework.Docs#4296]
I took the advice here to fix the collation on my database. However now I'm getting `Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'no such collation sequence: SQL_Latin1_General_CP1_CS_AS'.` exceptions in my unit tests since I use the SQLite testing provider that was a recommendation from https://learn.microsoft.com/en-us/ef/core/testing/#involving-the-database-or-not. An option I still have is to test against a clone database though. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b27be469-3758-941c-0c5d-3a54b1545493
* Version Independent ID: d89924aa-668e-229c-8170-5731c3fff4c1
* Content: [Collations and case sensitivity - EF Core](https://learn.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity)
* Content Source: [entity-framework/core/miscellaneous/collations-and-case-sensitivity.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/collations-and-case-sensitivity.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@ttony678 collation names are definitely database-specific, and a SQL Server collation name such as SQL_Latin1_General_CP1_CS_AS cannot be used with SQLite, much like various other features which are SQL Server-specific. The doc page on testing you link to above makes this point precisely - whenever you test against a database that isn't the same as what you use in production (a test double or fake), these discrepancies occur. Therefore, that page recommends to test against you production database system: if you run your production application against SQL Server, then it's suggested to run your tests against SQL Server as well; that's the only way to be sure that your tests will work, and also that your program behaves the same way under testing as it does on production.

If you'd still rather test against SQLite, you can supply a SQLite-specific model configuration, where the collation wouldn't be set (or where a SQLite-specific collation would be set).
