### ISSUE TITLE
Add Warning about SQLite Limitations

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/EntityFramework.Docs#430]
I think it would be a good idea to add a **warning** with a link to the [SQLite limitations](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations) towards the top of the documentation about [Testing with SQLite](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite).  What do you think?

My reason is, as the developer, I don't want to start the guide only to find out later on that I won't be able to use this w/o writing more code.

We have a fairly basic database, 25 tables, some PKs, Some FKs, nothing fancy but we do use schemas to organize stuff.  I probably wouldn't have started the guide if knew about this limitation.

Btw, I'm happy to make the edit to the docs 😃

**Comment by ajcvickers** [comment]
Triage: Add more guidance about what provider to use for testing to: https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/
