### ISSUE TITLE
TransactionScope async limitations

### ISSUE THREAD

**Issue by ProTip** [dotnet/EntityFramework.Docs#4306]
It may be worth discussing in limitations the apparent footgun with transaction scopes in that they do not support asynchronously committing or rolling back transactions.

In asp.net "async everything" is highly encouraged so the absence of `await using` or `await scope.CompleteAsync()` sent me down an internet rabbit hole trying to figure out if committing was blocking(yes of course).

This issue on dotnet seems to be requesting the API be extended for async complete/dispose: https://github.com/dotnet/runtime/issues/1420 .

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://learn.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
I've submitted #4307 to add a note on this.
