### ISSUE TITLE
Incomplete code sample

### ISSUE THREAD

**Issue by InteXX** [dotnet/EntityFramework.Docs#4321]
[Enter feedback here]

The second code sample [here](https://learn.microsoft.com/en-us/ef/core/testing/testing-without-the-database#repository-pattern) contains an incomplete class:
```
public class BloggingRepository : IBloggingRepository
{
    private readonly BloggingContext _context;

    public BloggingRepository(BloggingContext context)
        => _context = context;

    public Blog GetBlogByName(string name)
        => _context.Blogs.FirstOrDefault(b => b.Name == name);
```
The closing bracket is omitted, leaving the reader unsure as to whether additional code should exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81f8f42b-311c-6dbb-925a-281ef5a4e694
* Version Independent ID: 81f8f42b-311c-6dbb-925a-281ef5a4e694
* Content: [Testing without your Production Database System - EF Core](https://learn.microsoft.com/en-us/ef/core/testing/testing-without-the-database#repository-pattern)
* Content Source: [entity-framework/core/testing/testing-without-the-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/testing-without-the-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Note for triage: the full code is [included in the sample](https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Testing/BusinessLogic/BloggingRepository.cs?name=BloggingRepository), but only part of the code is, intentionally, shown in the docs. Should we change this?

**Comment by InteXX** [comment]
Suggestion: you might consider closing the bracket and including a comment alluding to the existence of further code.

e.g.
```
public class BloggingRepository : IBloggingRepository
{
    private readonly BloggingContext _context;

    public BloggingRepository(BloggingContext context)
        => _context = context;

    public Blog GetBlogByName(string name)
        => _context.Blogs.FirstOrDefault(b => b.Name == name);

    // See the sample code for the complete class
}
```
That said, it appears you're using region directives as parsing instructions, in which case it wouldn't be that simple.

Just an idea...
