### ISSUE TITLE
Add reference to required library to use the Extensions Methods

### ISSUE THREAD

**Issue by jonaramos** [dotnet/EntityFramework.Docs#4323]
The methods presented in the page are not included in the core library.  A Nuget package with extensions methods is a requirement to use them.

Library reference: https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98b01ef5-24a5-5f59-30c9-af264f739815
* Version Independent ID: 98b01ef5-24a5-5f59-30c9-af264f739815
* Content: [SQL Queries - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries)
* Content Source: [entity-framework/core/querying/sql-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/sql-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@jonaramos adding an explicit nuget reference to the Relational package isn't needed in general, since your provider's nuget package (e.f. Microsoft.EntityFrameworkCore.SqlServer) automatically brings that in. If you're seeing a different case, can you please post a minimal, runnable code sample of that?

**Comment by ajcvickers** [comment]
Duplicate of #4175.

**Comment by jonaramos** [comment]
Thanks for the quick answer. My context is in a shared library as well, so I did not have the Microsoft.EntityFrameworkCore.SqlServer package installed in the current project. Adding the reference to Relational is enough in this particular case.
I have read the response and conclusion for the request in the #4175 duplicate. Thanks.
