### ISSUE TITLE
GetStartedWinForms

### ISSUE THREAD

**Issue by amasys46** [dotnet/EntityFramework.Docs#4326]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed8b20d5-5fe5-a2c9-e024-8c24ff0846a1
* Version Independent ID: ed8b20d5-5fe5-a2c9-e024-8c24ff0846a1
* Content: [Get Started with Windows Forms - EF Core](https://learn.microsoft.com/en-us/ef/core/get-started/winforms)
* Content Source: [entity-framework/core/get-started/winforms.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/winforms.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by amasys46** [comment]
GetStartedWinForms will not show bindings when using glyphs; and therefore the program will not work?

**Comment by ajcvickers** [comment]
@amasys46 Not sure what you are referring to. Please provide a lot more details.

**Comment by amasys46** [comment]
Sorry for not doing this, first time i posted a problem about MS Learn.
Running Windows 11 22621 with Vs2022 17.5.4. 
https://learn.microsoft.com/en-us/ef/core/get-started/winforms
According to the "walkthrough" using NuGet Microsoft.EntityFrameworkCore.Sqlite 7.0.5; after adding 
Define the DbContext step, you are required to build. Then in the Data binding step you are  to add  Object Data Source; where you can select and update object data sources. However, none appear and therefore cannot "bind" the DataGridView to a class! There is even a TIP which says: 
If no data source types appear here, then make sure that Product.cs, Category.cs and ProductsContext.cs have been added to the project and the solution has been built.
I have run this step 20 to 30 times (fools always do this) even on different computers and w/o virus enabled. Personally, I would prefer the C# code to bind programmatically. Thanks for the help! Mike
