### ISSUE TITLE
Question regarding complex path to entities

### ISSUE THREAD

**Issue by EternaleapFromPit** [dotnet/EntityFramework.Docs#4336]
Hi

It's not obvious whether it's possible to provide complex path like that somehow:
`builder.HasIndex(entity => new { entity.UpperLevelField, entity.InternalMappedInstance.Field }).IsUnique()`
Wheh I use it like that it gives the error. Providing char array doesn't work too.

Regards,
Vlad.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d7751b1-4430-a31c-bf32-0839f5f885b8
* Version Independent ID: 438949c9-1a1e-5bea-0bbe-ecd17de33865
* Content: [EntityTypeBuilder&lt;TEntity&gt;.HasIndex Method (Microsoft.EntityFrameworkCore.Metadata.Builders)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1.hasindex?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder`1.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder`1.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
As you found out, that syntax is not supported.

**Comment by ajcvickers** [comment]
Issue is tracked here: https://github.com/dotnet/efcore/issues/11336
