### ISSUE TITLE
Need to document mystery attributes

### ISSUE THREAD

**Issue by Loophole62ndFF** [dotnet/EntityFramework.Docs#4353]
The page states...
"You can also apply certain attributes..."
That's nice to know.  What attributes? What can they apply to?? What do they do???  Where can I find out more????

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3437af67-630b-d28f-7fbd-3eedf647f22a
* Version Independent ID: 6c44f987-19a7-c256-e8fa-10378e61cf6e
* Content: [Creating and Configuring a Model - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/)
* Content Source: [entity-framework/core/modeling/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
That's all documented in the other documentation pages on modeling - right below this overview page. For example, the [entity properties page](https://learn.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#column-names) shows how to control column names, length, etc.

**Comment by Loophole62ndFF** [comment]
Perhaps add a short sentence in the original section that clarifies that the attributes are described in the various relevant detail topics?  That would give the reader direction as to where to find out more.

**Comment by roji** [comment]
@Loophole62ndFF this really is just an overview page for the entire section - a sample of two data annotations is provided right below the sentence (`[Table]` and `[Required]`), and it really seems reasonable to assume that users go deeper by looking at the other pages after the overview. At some point, we can't make everything 100% explicit, and need to keep documentation a bit short/readable (especially the overview pages).
