### ISSUE TITLE
Can EF6 source code annotations be provided in Chinese?

### ISSUE THREAD

**Issue by gallop1** [dotnet/EntityFramework.Docs#4354]
Can EF6 source code annotations be provided in Chinese?(EF6 源代码注释是否可以提供中文？)。I want to go to the definition like the DLL file of EF 6, so that I can directly see the Chinese content information in the source code.（我想像EF 6的dll文件那样转到定义那样可以直接在源代码里面看到中文内容信息。）

**Comment by roji** [comment]
@gallop1 it's possible to view the entire EF API documentation in Chinese (and many other languages), see [this page as an example](https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.entityframeworkcore?view=efcore-7.0).

If you're referring to adding documentation comments in multiple languages **inside** the source code, then no - that's not feasible; we'd have to do that for all languages, making the source code impossible to work with.
