### ISSUE TITLE
No mention of TransactionScopeAsyncFlowOption

### ISSUE THREAD

**Issue by simeyla** [dotnet/EntityFramework.Docs#4359]
There is no mention of [TransactionScopeAsyncFlowOption ](https://learn.microsoft.com/en-us/dotnet/api/system.transactions.transactionscopeasyncflowoption?view=net-7.0) on this page and how it pertains to `TransactionScope`.

The example for [Using System.Transactions](https://learn.microsoft.com/en-us/ef/core/saving/transactions#using-systemtransactions) should mention this option. Without it you can easily end up not using a transaction when using async methods.

I think also the explanation of 'ambient transaction' could be expanded.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://learn.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@simeyla thanks for raising this.

As with most of our code samples, this code sample shows synchronous code, and so TransactionScopeAsyncFlowOption isn't relevant. But I agree that it's important to mention this, so I'm adding a note.

> I think also the explanation of 'ambient transaction' could be expanded.

I'm also adding a reference to the [System.Transactions documentation](https://learn.microsoft.com/en-us/dotnet/framework/data/transactions/implementing-an-implicit-transaction-using-transaction-scope). Ambient transactions aren't an EF feature, so I don't think it makes sense to go too much into the details in our docs when ample dedicated documentation already exists for it.
