### ISSUE TITLE
Why do the extension methods return OperationBuilder<T>?

### ISSUE THREAD

**Issue by martingbrown** [dotnet/EntityFramework.Docs#4363]
I'm confused. Why does each of the extension methods on this page return OperationBuilder&lt;T>?

I took a look at the OperationBuilder&lt;T> class's documentation and it is just described as "Reference" what ever that's supposed to mean.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c13eb107-79c2-7824-12c1-e637d2a92add
* Version Independent ID: aafc9673-c635-3cf2-6235-8577ff15d19c
* Content: [Custom Migrations Operations - EF Core](https://learn.microsoft.com/en-gb/ef/core/managing-schemas/migrations/operations)
* Content Source: [entity-framework/core/managing-schemas/migrations/operations.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/operations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
So that multiple method calls can be chained.

**Comment by martingbrown** [comment]
Wouldn't that mean that the passed in MigrationBuilder should be returned instead?
