### ISSUE TITLE
Partial update is not supported but not mentioned in this page

### ISSUE THREAD

**Issue by alperenbelgic** [dotnet/EntityFramework.Docs#4365]
I think it should be mentioned that partial update is not supported by Ef core Cosmos db driver.  (https://github.com/dotnet/efcore/issues/13559)

Also, ExecuteUpdate can be specifically mentioned that it is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a102d2e4-41d0-4619-a463-3e3862311a01
* Version Independent ID: a80b35f2-09dc-da67-df83-253ca5fd78cb
* Content: [Azure Cosmos DB Provider - Limitations - EF Core](https://learn.microsoft.com/en-us/ef/core/providers/cosmos/limitations)
* Content Source: [entity-framework/core/providers/cosmos/limitations.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/cosmos/limitations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
> Also, ExecuteUpdate can be specifically mentioned that it is not supported.

There are many relational-only features that Cosmos doesn't support - I don't think it makes sense to document each and every one of them. ExecuteUpdate specifically is defined in the Microsoft.EntityFrameworkCore.Relational package, so if you're just using Cosmos, the method shouldn't even show up.

**Comment by AndriySvyryd** [comment]
We only list by-design limitations. Partial update (along with many other features) is just not implemented yet https://github.com/dotnet/efcore/issues/13559
