### ISSUE TITLE
college student database

### ISSUE THREAD

**Issue by Sabarijothi** [dotnet/EntityFramework.Docs#4367]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dba1f3f2-8c1f-c913-dcfb-4c3332ef9c22
* Version Independent ID: 273274cb-72b7-1696-32eb-a5d2f7d6c0dd
* Content: [School Sample Database - EF6](https://learn.microsoft.com/en-us/ef/ef6/resources/school-database)
* Content Source: [entity-framework/ef6/resources/school-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/resources/school-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@Sabarijothi do you have a question or an issue to be raised?
