### ISSUE TITLE
Can this query cause a cartesian explosion? 

### ISSUE THREAD

**Issue by saynurAltinn** [dotnet/EntityFramework.Docs#4371]
This query completed in 20000 ms for a few samples.  Is it beause of the cartesian explosion ? or What is the reason for this delay? .
```
await   context.Schools.Where(x => x.Id == schoolId)
                    .Include(x => x.Faculties)
                        .ThenInclude(x => x.Departments)
                              .ThenInclude(x => x.Teachers)
                                   .ThenInclude(x => x.Lectures)
                    .Include(x => x.Faculties)
                        .ThenInclude(x => x.Departments)
                              .ThenInclude(x => x.Teachers)
                                   .ThenInclude(x => x.Courses)
                    .Include(x => x.Faculties)
                        .ThenInclude(x => x.Departments)
                              .ThenInclude(x => x.Teachers)
                                   .ThenInclude(x => x.Projects)
                   .FirstOrDefaultAsync();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43baa9f3-c415-c328-6c10-53aabaaec652
* Version Independent ID: 4e789a1b-aa88-d194-dc2e-0a23251250d7
* Content: [Single vs. Split Queries - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/single-split-queries)
* Content Source: [entity-framework/core/querying/single-split-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/single-split-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Yes, this is exactly the scenario described in [the docs](https://learn.microsoft.com/en-us/ef/core/querying/single-split-queries#cartesian-explosion); try executing the SQL generated by EF and seeing how many rows are returned. The docs describe how to deal with this, e.g. use split queries.
