### ISSUE TITLE
This page on creating the __EFmigratory table

### ISSUE THREAD

**Issue by jbsloan49** [dotnet/EntityFramework.Docs#4373]
This part is very confusing.  It does not tell me where the copied code i supposed to be applied.

You can change the schema and table name using the MigrationsHistoryTable() method in OnConfiguring() (or ConfigureServices() on ASP.NET Core). Here is an example using the SQL Server EF Core provider.

C#

Copy
protected override void OnConfiguring(DbContextOptionsBuilder options)
    => options.UseSqlServer(
        _connectionString,
        x => x.MigrationsHistoryTable("__MyMigrationsHistory", "mySchema

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 390f9258-6f7c-dbe8-3e79-c83446ba6192
* Version Independent ID: 38896138-0566-d481-2c91-8158f6d8f274
* Content: [Custom Migrations History Table - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/history-table)
* Content Source: [entity-framework/core/managing-schemas/migrations/history-table.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/history-table.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
OnConfiguring() is a method on your DbContext, and is a very basic EF concept. You can get familiar with it in [DbContext Lifetime, Configuration, and Initialization](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/)
