### ISSUE TITLE
With circular dependency, need to LoadFromAssemblyPath

### ISSUE THREAD

**Issue by Tridy** [dotnet/EntityFramework.Docs#4374]
in the part with the, `If this causes a circular dependency, you can update the base output path of the migrations project instead`,

since now the reference is not added from the original project to the migrations project directly (due to the circular dependency), the original project will not know about the migrations project, and migration projects assembly needs to be loaded manually:

` AssemblyLoadContext.Default.LoadFromAssemblyPath(migrationDllPath);`

Otherwise on the startup the `... x.MigrationsAssembly("MigrationsAssemblyName")` will throw an exception that assembly was not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Using a Separate Migrations Project - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Tridy Can you post your .sln and .csproj files?

**Comment by Tridy** [comment]
Sure, here it comes.
[sln_proj_issue_4374.zip](https://github.com/dotnet/EntityFramework.Docs/files/11788191/sln_proj_issue_4374.zip)

The _Migrations_ project needs to reference the _WebApi_ project since it is the _WebApi_ project that contains all the domain classes. The _Migrations_ project only contains the migrations, nothing else.
