### ISSUE TITLE
Note about Save Points and MARS is unclear

### ISSUE THREAD

**Issue by ascott18** [dotnet/EntityFramework.Docs#4377]
In the text that states the following:
> Savepoints are incompatible with SQL Server's Multiple Active Result Sets, and are not used. If an error occurs during SaveChanges, the transaction may be left in an unknown state.

The statement "are not used" is unqualified and therefore seems to imply that Savepoints are _never_ used under any circumstance. It would be nice if this could be clarified. For example, "... and are not used when the connection to SQL Server has Multiple Active Result Sets enabled", or some other appropriate description of what the actual functionality is here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://learn.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Are you saying that it's not clear when savepoints are not used? Give the first part of the sentence, which explicitly specifies them being incompatible with MARS, is that not clear?

**Comment by ascott18** [comment]
I suppose my issue here is mostly a grammar nitpick. Its formatted like a compound sentence, but the second clause in the sentence "are not used" is not a complete sentence on its own.

Consider an alternate phrasing that fixes the grammar issue and makes it more clear that this is an exception to the previous paragraph:

> Savepoints are incompatible with SQL Server's Multiple Active Result Sets (MARS). Savepoints will not be created by EF when MARS is enabled on the connection, even if MARS is not actively in use. If an error occurs during SaveChanges, the transaction may be left in an unknown state.

**Comment by roji** [comment]
@ascott18 if you'd like to submit that as a PR, I'll merge it - though I find the current wording clear enough.
