### ISSUE TITLE
Multi-tenancy with EF Core: Should IModelCacheKeyFactory be replaced?

### ISSUE THREAD

**Issue by JandosHk** [dotnet/EntityFramework.Docs#4387]
I found the following page: https://learn.microsoft.com/en-us/ef/core/modeling/dynamic-model.
Is replacing IModelCacheKeyFactory is needed if I use HasQueryFilter to dynamically set tenant id for queries?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb29a2b6-c401-287f-2da9-1aeb3c633b41
* Version Independent ID: bb29a2b6-c401-287f-2da9-1aeb3c633b41
* Content: [Multi-tenancy - EF Core](https://learn.microsoft.com/en-us/ef/core/miscellaneous/multitenancy)
* Content Source: [entity-framework/core/miscellaneous/multitenancy.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/multitenancy.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by JandosHk** [comment]
OnModelCreating was executing just once, where I use HasQueryFilter to change tenant id. So, I thought it caches whole model configuration with the first tenant id.

**Comment by roji** [comment]
Have you looked at the example in the query filter docs above? The tenant ID is stored as a simple instance field on your DbContext instance, and the query filter definition looks at that to apply the filter.
