### ISSUE TITLE
No usage examples for NotParameterizedAttribute

### ISSUE THREAD

**Issue by samueldjack** [dotnet/EntityFramework.Docs#4390]
In the Remarks section of the NotParameterizedAttribute doc page there is a link to [Querying data with EF Core](https://aka.ms/efcore-docs-query) with a promise that usage examples may be found there.

However, the linked page does not even mention NotParameterizedAttribute. I've not been able to find examples anywhere else either.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad641e7-eaa6-aab5-12f0-4de14dfc9f16
* Version Independent ID: b55e8adf-f36e-65b5-e203-763be5895f5a
* Content: [NotParameterizedAttribute Class (Microsoft.EntityFrameworkCore.Query)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.query.notparameterizedattribute?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Query/NotParameterizedAttribute.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Query/NotParameterizedAttribute.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
[NotParameterized] is a low-level mechanism mostly intended for EF provider writers, it's very rarely needed by users; we unfortunately don't have the capacity to create usage examples for every feature, and concentrate on user-facing ones.

**Comment by samueldjack** [comment]
> [NotParameterized] is a low-level mechanism mostly intended for EF provider writers, it's very rarely needed by users; we unfortunately don't have the capacity to create usage examples for every feature, and concentrate on user-facing ones.

That's understandable.

But in that case, could you remove the link from the Remarks section so as not to raise false hopes?!

**Comment by roji** [comment]
The link in the remarks is a general link to the corresponding EF sections which we have in many API docs. It's true that we'd ideally document [NotParamerized] in that section of the docs, but the link is generally meant to make people aware that conceptual docs exist as a generally better alternative for understanding how things work at the high level. We've seen quite a few people stuck trying to understanding general query concepts by looking at API docs - these links are meant to help with that.
