### ISSUE TITLE
xref on Deleting Data is referencing to wrong DbSet method

### ISSUE THREAD

**Issue by omelyanyuk-andrey** [dotnet/EntityFramework.Docs#4400]
### Issue Description
On this line we can see that its referencing to DbSet.Remove, but inspecting the browser or [seeing in the doc](https://learn.microsoft.com/en-us/ef/core/saving/basic#deleting-data), we have DbSet<TEntity>.Add instead of DbSet<TEntity>.Remove
https://github.com/dotnet/EntityFramework.Docs/blob/61e0637edeec2980ebb8481c10d65f94050c95c1/entity-framework/core/saving/basic.md?plain=1#L34

<img width="671" alt="image" src="https://github.com/dotnet/EntityFramework.Docs/assets/111755102/d23ce43c-1b71-4edf-ac8a-d7f47a93ff36">

### Expected Result
Reference to [DbSet<TEntity>.Remove](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.remove?view=efcore-7.0)

**Comment by ajcvickers** [comment]
Already done in #4362.
