### ISSUE TITLE
Wrong link to async linq.

### ISSUE THREAD

**Issue by yulObraz** [dotnet/EntityFramework.Docs#4409]
https://aka.ms/efcore-docs-async-linq leads to page https://learn.microsoft.com/en-us/ef/core/querying/. There is nothing about async linq.

I have issues with ToListAsync with in memory database but this link from ToListAsync method description does not helps.

--
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91606b46-d8a2-8824-a1ae-522f35362ec4
* Version Independent ID: 22a92f99-5e43-96d7-82d1-cd02ccdc5af8
* Content: [Querying Data - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/)
* Content Source: [entity-framework/core/querying/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@ajcvickers [aka.ms/efcore-docs-async-linq](https://aka.ms/efcore-docs-async-linq) should probably point to our [async page](https://learn.microsoft.com/en-us/ef/core/miscellaneous/async).

**Comment by ajcvickers** [comment]
Updated.
