### ISSUE TITLE
Document IProperty.DeclaringEntityType, ValueGenerator and IEntityTypeIgnoredConvention breaking change

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/EntityFramework.Docs#4412]

**Comment by ajcvickers** [comment]
@AndriySvyryd What is the `ValueGenerator` breaking change?

**Comment by AndriySvyryd** [comment]
> @AndriySvyryd What is the `ValueGenerator` breaking change?

IValueGeneratorSelector and some related API now take `IProperty, ITypeBase` as arguments.
