### ISSUE TITLE
Document break to Contains if the SQL Server compatibility level is too low

### ISSUE THREAD

**Issue by roji** [dotnet/EntityFramework.Docs#4423]
Users running on really old (unsupported) versions of SQL Server - as well as those who have set the compatibility level to a low value - will break when upgrading to EF Core 8.0, since the translation of Contains now relies on OPENJSON (see https://github.com/dotnet/efcore/issues/31323 for an example). We should add a breaking change note for this.

The same happens if using SQLite versions older than 3.38.0. This is more rare as usually people use the bundled SQLite, but it could happen.

**Comment by stevendarby** [comment]
Regarding "unsupported", SQL Server 2014 and 2016 both have extended support for a few more years yet. I get that support here probably can't mean guaranteeing it continues to work with external tools & libraries, but given EF is also Microsoft, I just wondered if there is a full end-to-end customer support experience to consider here?

To be clear, I don't want EF to be held back by SQL Server's differing support cycle, just seeing if you have a good response prepared for potential grumbles 😀

**Comment by ErikEJ** [comment]
@stevendarby see https://github.com/dotnet/efcore/issues/31362#issuecomment-1652920760

**Comment by stevendarby** [comment]
Brilliant, so they are supported?

**Comment by roji** [comment]
Documentation: #4428

**Comment by ajcvickers** [comment]
@roji Did you file an issue to check the compat level the first time we open a connection?

**Comment by roji** [comment]
No, I'm still thinking about it :)
