### ISSUE TITLE
What is the default?

### ISSUE THREAD

**Issue by rschiefer** [dotnet/EntityFramework.Docs#4435]
you should list the default method on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb8fc08f-b736-56e5-b040-6718c622182c
* Version Independent ID: a9fc2365-f8b7-8877-a7b2-5c88b3823e43
* Content: [Loading Related Data - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/related-data/)
* Content Source: [entity-framework/core/querying/related-data/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/related-data/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
There's no real default method, the right choice depends on your needs; there are scenarios where one method makes more sense than another, but you have to understand them first.
