### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by jicecubes** [dotnet/EntityFramework.Docs#4436]
Where can we find examples? This text w/t it is close to worthless...

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c12c8ec3-04e8-3442-110d-5d4cc9322921
* Version Independent ID: f1071d87-f76d-e8ad-7b90-568b98889c9e
* Content: [EF.CompileQuery Method (Microsoft.EntityFrameworkCore)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.ef.compilequery?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EF.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EF.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
You're probably looking for [these conceptual docs](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cexpression-api-with-constant#compiled-queries).
