### ISSUE TITLE
Please consider current Moq privacy issues and replace with something else

### ISSUE THREAD

**Issue by r-pankevicius** [dotnet/EntityFramework.Docs#4443]
Article: https://learn.microsoft.com/en-us/ef/ef6/fundamentals/testing/mocking

Privacy issues with SponsorLink, starting from version 4.20:
https://github.com/moq/moq/issues/1372

Video "Remove Moq From Your .NET Projects Right NOW!" with more details:
https://www.youtube.com/watch?v=A06nNjBKV7I

I won't expect Microsoft will continue to advice using of Moq considering this info.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
