### ISSUE TITLE
Please consider current Moq privacy issues and replace with something else

### ISSUE THREAD

**Issue by r-pankevicius** [dotnet/EntityFramework.Docs#4444]
Privacy issues with SponsorLink, starting from version 4.20:
https://github.com/moq/moq/issues/1372

Video "Remove Moq From Your .NET Projects Right NOW!" with more details:
https://www.youtube.com/watch?v=A06nNjBKV7I

I won't expect Microsoft will continue to advice using of Moq considering this info.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a04a5e4-3060-2331-f78d-8b45064b8983
* Version Independent ID: 673d9406-3fa1-a9eb-f5cc-a431155e0260
* Content: [Testing with a mocking framework - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/testing/mocking)
* Content Source: [entity-framework/ef6/fundamentals/testing/mocking.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/testing/mocking.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by r-pankevicius** [comment]
Still this is in Microsoft page and nobody reads REDME :)

**Comment by ajcvickers** [comment]
This PR has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by srijken** [comment]
This only changes suggestions in the documentation, and doesn't affect the codebase?

**Comment by r-pankevicius** [comment]
@srijken Yes. Delete this topic and add the reference to "Moq is dangerours" topic. No code affected.

See also: https://github.com/Azure/azure-sdk-for-net/issues/38111#issuecomment-1671961470

**Comment by cmjdiff** [comment]
@ajcvickers I think your autoclose script tripped up here.  Can you reopen this?
