### ISSUE TITLE
EF Core does not support point to read queries

### ISSUE THREAD

**Issue by stevozilik** [dotnet/EntityFramework.Docs#4445]
Currently due to an [open bug](https://github.com/dotnet/efcore/issues/27679) (without a ETA commitment) EF Core does not support [Point Reads](https://learn.microsoft.com/en-us/azure/cosmos-db/optimize-cost-reads-writes#point-reads)

This has a signifficant impact on cost and hence should be documented in limitations. I've seen teams investing days into EF Core with Cosmos DB just to find out the hard way and wasting time migrating to native client

The current lack of transparency is damaging the reputation of EF Core (== slow) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a102d2e4-41d0-4619-a463-3e3862311a01
* Version Independent ID: a80b35f2-09dc-da67-df83-253ca5fd78cb
* Content: [Azure Cosmos DB Provider - Limitations - EF Core](https://learn.microsoft.com/en-us/ef/core/providers/cosmos/limitations)
* Content Source: [entity-framework/core/providers/cosmos/limitations.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/cosmos/limitations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@stevozilik the EF provider does support point reads - but you need to use EF's [Find/FindAsync APIs](https://learn.microsoft.com/en-us/ef/core/change-tracking/entity-entries#find-and-findasync), rather than regular LINQ queries. It's true that this is missing from our Cosmos provider docs - we should improve those.

**Comment by stevozilik** [comment]
@roji no point reads don’t work even with Find as per the open bug (without any plans to fix this)

**Comment by roji** [comment]
@stevozilik you mean specifically because there's a partition key, right? Because AFAIK Find does work well with point reads if there isn't one.

If so, then you're right and we should definitely document this limitation.

**Comment by stevozilik** [comment]
Not aware if presence of the PK plays a role (it def does not work with PK)

Every sensible Cosmos DB has PKs defined, without a PK the owner probably does not care about performance/cost at all. Also the [ability to create non-partitioned containers is being deprecated](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/migrate-containers-partitioned-to-nonpartitioned?tabs=dotnetv3) so not much point in discussing this option
