### ISSUE TITLE
Reaching the Catch Block with an in-memory approach

### ISSUE THREAD

**Issue by kmarler18** [dotnet/EntityFramework.Docs#4447]
I have a TestController class where I'm performing unit tests on a Controller class.

The Controller class creates an instance of a Service class named `_service`. The Controller class has a method with the following implementation:

    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> Get(CancellationToken ct)
    {
        try
        {
            return Ok(await _service.GetAll(ct));
        }
        catch (Exception e)
        {
            _logger.LogError(e.Message);
            return StatusCode(StatusCodes.Status500InternalServerError, "There was an error processing your request.");
        }
    }

In my TestController class I create a Moq'ed instance of the Service class named `_mockService`. One of the methods in the TestController class uses `_mockService `and sets it up to throw an exception so I can test the return statement in the catch block of the Controller class:

    [Fact]
    public async void Get_ReturnsIActionResult_InternalServerError()
    {
        // Setup mock
        CancellationToken ct = default(CancellationToken);
        _mockService.Setup(ms => ms.GetAll(ct)).Throws(new TaskCanceledException());

        // Test class
        var result = await _controller.Get(ct);

        // Assert results
        var objectResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(500, objectResult.StatusCode);
    }

Similarly, I have a TestRepository class where I'm performing unit tests on a Repository class.

The Repository class creates an instance of a DbContext class named `_dbContext`. The Repository class has a method with the following implementation:

    public async Task<IEnumerable<SomeDbSetProperty>> GetAll(CancellationToken ct = default)
    {
        try
        {
            return await _dbContext.SomeDbSetProperty.Where(p => p.IsActivated == true).ToListAsync(ct);
        }
        catch (Exception e)
        {
            _logger.LogError($"Error in GetAll: {e}");
            throw;
        }
    }

Rather than Moq'ing the DbContext class (which would be a similar approach to how we Moq'ed the Service class in the TestController class), my team has opted to use an in-memory approach as outlined in [this article](https://learn.microsoft.com/en-us/ef/core/testing/testing-without-the-database#in-memory-provider). (I realize it's a discouraged approach, but the decision was not up to me.)

My goal is to create a test method in my TestRepository class that tests the code in the catch block of the Repository class (similarly to the method in my TestController class that tested the catch block in the Controller class).

My issue is that I can't figure out how to do that with the in-memory approach. It was easy to do with Moq by using the Setup and Throws methods, but I don't know of how to replicate that concept with the in-memory approach. Perhaps I'm experiencing why they don't recommend the in-memory approach, or perhaps, I'm overlooking something.

Any help is appreciated.

**Comment by ajcvickers** [comment]
> My issue is that I can't figure out how to do that with the in-memory approach. 

I don't believe that there is any way to do this _using the in-memory database_. It would require that the in-memory database have some kind of mechanism to force it to generate errors. If you need this kind of test where you can't get the database to generate the error condition, then a test double is probably the only way to go.
