### ISSUE TITLE
A sanpshot of created DB will help

### ISSUE THREAD

**Issue by prasadd75** [dotnet/EntityFramework.Docs#4448]
[Enter feedback here]

A snap shot of the created table in DB will save time. Otherwise one has to implement all this to see what is actually stored in DB.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e27eb8f2-79a1-5d29-1b44-daf9ec65a8bb
* Version Independent ID: c6cc4c8a-fa27-295a-5618-6fc0ab532134
* Content: [Enum Support - Code First - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/data-types/enums)
* Content Source: [entity-framework/ef6/modeling/code-first/data-types/enums.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/data-types/enums.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
