### ISSUE TITLE
EF6: Testing with your own test doubles - TestDbSet definition invalid

### ISSUE THREAD

**Issue by aamir0** [dotnet/EntityFramework.Docs#4472]
The document has sample code to copy for creating a `TestDbSet` class with the following definition:

```cs
public class TestDbSet<TEntity> : DbSet<TEntity>, IQueryable, IEnumerable<TEntity>, IDbAsyncEnumerable<TEntity>
	where TEntity : class
{
	ObservableCollection<TEntity> _data;
	IQueryable _query;

	public TestDbSet()
	{
		_data = new ObservableCollection<TEntity>();
		_query = _data.AsQueryable();
	}

	public override TEntity Add(TEntity item)
	{
		_data.Add(item);
		return item;
	}

	public override TEntity Remove(TEntity item)
	{
		_data.Remove(item);
		return item;
	}

	public override TEntity Attach(TEntity item)
	{
		_data.Add(item);
		return item;
	}

	public override TEntity Create()
	{
		return Activator.CreateInstance<TEntity>();
	}

	public override TDerivedEntity Create<TDerivedEntity>()
	{
		return Activator.CreateInstance<TDerivedEntity>();
	}

	public override ObservableCollection<TEntity> Local
	{
		get { return _data; }
	}

	Type IQueryable.ElementType
	{
		get { return _query.ElementType; }
	}

	Expression IQueryable.Expression
	{
		get { return _query.Expression; }
	}

	IQueryProvider IQueryable.Provider
	{
		get { return new TestDbAsyncQueryProvider<TEntity>(_query.Provider); }
	}

	System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
	{
		return _data.GetEnumerator();
	}

	IEnumerator<TEntity> IEnumerable<TEntity>.GetEnumerator()
	{
		return _data.GetEnumerator();
	}

	IDbAsyncEnumerator<TEntity> IDbAsyncEnumerable<TEntity>.GetAsyncEnumerator()
	{
		return new TestDbAsyncEnumerator<TEntity>(_data.GetEnumerator());
	}
}
```
This generates the following compiler errors:
> CS0534: 'TestDbSet<TEntity>' does not implement inherited abstract member 'DbSet<TEntity>.EntityType.get'
> CS0535: 'TestDbSet<TEntity>' does not implement interface member 'IDbAsyncEnumerable.GetAsyncEnumerator()'
> CS0508: 'TestDbSet<TEntity>.Add(TEntity)': return type must be 'EntityEntry<TEntity>' to match overridden member 'DbSet<TEntity>.Add(TEntity)'
> CS0508: 'TestDbSet<TEntity>.Remove(TEntity)': return type must be 'EntityEntry<TEntity>' to match overridden member 'DbSet<TEntity>.Remove(TEntity)'
> CS0508: 'TestDbSet<TEntity>.Attach(TEntity)': return type must be 'EntityEntry<TEntity>' to match overridden member 'DbSet<TEntity>.Attach(TEntity)'
> CS0115: 'TestDbSet<TEntity>.Create()': no suitable method found to override
> CS0115: 'TestDbSet<TEntity>.Create<TDerivedEntity>()': no suitable method found to override
> CS1715: 'TestDbSet<TEntity>.Local': type must be 'LocalView<TEntity>' to match overridden member 'DbSet<TEntity>.Local'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9696766-8f5f-f762-e4f1-1d403b0b3276
* Version Independent ID: a6df7c92-facc-8fd5-d8c6-ac3d2668d9e8
* Content: [Testing with your own test doubles - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/testing/writing-test-doubles)
* Content Source: [entity-framework/ef6/fundamentals/testing/writing-test-doubles.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/testing/writing-test-doubles.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
