### ISSUE TITLE
large seed data example missing

### ISSUE THREAD

**Issue by scottjibben** [dotnet/EntityFramework.Docs#4487]
It would be nice to have an example that shows how a large dataset could be used as seed data.

For example, if the table is primarily used as a look up table that should be pre-populated with data.  That is, data is not added/edited/removed except for when the table is created and the dataset is approximately 500,000 records.  A zip code table is mentioned but not shown as an example.

Another example, is having a static database with a table of static data.  Could a seed data example be added that shows how to populate a new DbContext/database with data from this other static database table?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/data-seeding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@scottjibben we explicitly discourage using the seeding feature for large data:

> Data that is large (seeding data gets captured in migration snapshots, and large data can quickly lead to huge files and degraded performance).

Especially if your data never changes, there's little advantage in using this feature over simply manually seeding it yourself (that is, check if the table exists, and if not, create and populate it).

> Another example, is having a static database with a table of static data. Could a seed data example be added that shows how to populate a new DbContext/database with data from this other static database table?

That's not something that's supported by EF's seeding feature ("Data that depends on database state"), but again - it should be quite easy to do this yourself.

**Comment by scottjibben** [comment]
I didn’t expect my comments to result in a response.  Thanks for the follow up and clarification.  

 

In my test  environment I added an empty migration.  Then added one SQL query to copy data from one table to another.  It takes about 2~3 seconds from a clean init.  

 

Although it is convenient now, I doubt that the production environment will have this extra database table in it so I will take your advice and probably build a PowerShell script to copy the data manually.  The data is static when used, but the source data may change.

 

Thanks for your time & advice!

 

sj


Scott Jibben
Jibben Consulting Services, Inc.
[Email]  ***@***.***> ***@***.***
[Web]  <http://www.jibben.com/> http://www.jibben.com
[Voice] 763-551-2510

**Comment by roji** [comment]
Happy this worked out for you. You can manage things via a PowerShell script, or simply add code inside your program on startup, to check whether your table is up to date (based on whatever criteria is right for you), and then sync it if not.
