### ISSUE TITLE
In the Code for update in Program.cs,

### ISSUE THREAD

**Issue by chandansomani** [dotnet/EntityFramework.Docs#4489]
In Program.cs Code Sample 

db.Blog.Update(blog); // statement is missing for the Update part 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 488629d4-9bd2-42b5-4644-34e3f2baee59
* Version Independent ID: b38b9d14-6bad-12e0-8d2d-24b50bc4977e
* Content: [Getting Started - EF Core](https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/overview/first-app.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/first-app.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@chandansomani `Update` is not needed here. See [Change Tracking](https://learn.microsoft.com/en-us/ef/core/change-tracking/) for more details.
