### ISSUE TITLE
Stored Procedures

### ISSUE THREAD

**Issue by pcapozzi** [dotnet/EntityFramework.Docs#4499]
How about if I told you how to build a car but left out the part about the engine?   This document does not even mention Stored Procedures which are integral to using a database.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1bdeea-0ebc-04ff-5b58-1020ad9cd72a
* Version Independent ID: 847fe92a-2940-afbf-b2ee-e68f8a8060be
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://learn.microsoft.com/en-us/ef/core/cli/dotnet#common-options)
* Content Source: [entity-framework/core/cli/dotnet.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#stored-procedure-mapping
