### ISSUE TITLE
Missing information and examples

### ISSUE THREAD

**Issue by EFEaglehouse** [dotnet/EntityFramework.Docs#4500]
For the code-first situation, this page doesn't explain how the database connection string is generated. How is it able to provide credentials? How does it determine which database to use? How does it determine which database server to connect with? 

For the database-first situation, this page doesn't explain how the metadata for the model is chosen. The metadata seems to be some sort of XPath query, but that's only an assumption. What is it? There was an example, but the metadata used in the example did not refer to anything in the text.

If the connection string is stored in a configuration file, how do you construct it? What keywords are used and what data should they take as values?

For as long as it was, this article did not have much concrete information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f431e6c-6c5f-9056-1486-99ba6b02c954
* Version Independent ID: 37943f43-c279-f190-b134-48f54ead1e38
* Content: [Connection strings and models - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/configuring/connection-strings)
* Content Source: [entity-framework/ef6/fundamentals/configuring/connection-strings.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/configuring/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
