### ISSUE TITLE
How would one obtain a reference to this class? How would one use it?

### ISSUE THREAD

**Issue by DougAtClir** [dotnet/EntityFramework.Docs#4503]
[Enter feedback here]
How would I obtain a reference to this class? How would I use it? It is non inheritable and has no public constructors. If there is a factory that should be called, it should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e498c39b-568a-0d35-91a6-37409b473018
* Version Independent ID: 3c894d25-631e-cf25-ec27-ae6fae7e832f
* Content: [EntitySqlParser Class (System.Data.Entity.Core.Common.EntitySql)](https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.core.common.entitysql.entitysqlparser?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity.Core.Common.EntitySql/EntitySqlParser.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.Core.Common.EntitySql/EntitySqlParser.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
