### ISSUE TITLE
misspelled having

### ISSUE THREAD

**Issue by upendrasinghgusain** [dotnet/EntityFramework.Docs#4504]
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

misspelled having :)
"without havnig to constantly"

**Comment by roji** [comment]
@upendrasinghgusain which page is the typo on?

**Comment by upendrasinghgusain** [comment]
[without havnig to constantly](https://learn.microsoft.com/en-us/ef/core/performance/modeling-for-performance#materializedindexed-views)

**Comment by roji** [comment]
Thanks, submitted #4505 to fix. FYI in the future you can just submit a PR fixing the typo, this can be done very easily in the UI (click the edit button at the top of the page).
