### ISSUE TITLE
Please specify where those code snippets should be placed

### ISSUE THREAD

**Issue by shamyratpashiyev96** [dotnet/EntityFramework.Docs#4513]
Can you please specify where those example code snippets should be used

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding#model-seed-data)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/data-seeding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
The docs have this above the code snippets:

> As an example, this will configure seed data for a Blog in OnModelCreating:

Is that not sufficient?

**Comment by AndriySvyryd** [comment]
Also, below the snippets there's a link to the [full sample project](https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core/Modeling/DataSeeding)
