### ISSUE TITLE
How to handle nested objects across Entity Framework and MVC Core with the new nullable reference types

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/EntityFramework.Docs#4524]
I am reading this documentation and struggling with nested objects. Imagine I have three  Entity Framework classes

```
public class Student
{
[Key}
public long StudentId {get; set;}
public string Name {get; set;}
public virtual ICollection<Enrolment> Courses {get; set;}
}

public class Course
{
[Key]
public long CourseId {get; set;}
public string CourseName {get; set;} 
public virtual ICollection<Enrolment> Students {get; set;}
}

public class Enrolment
{
public long CourseId {get; set;}
public long StudentId {get; set;}

[ForeignKey(nameof(StudentId)]
public virtual Student {get; set;}

[ForeignKey(nameof(CourseId)]
public virtual Course {get; set;}
}
```
When I use these classes as the view model in a page post handler it is expecting the Student and Course properties to be populated but I don't want to do that on this page.
I can make the `ICollection<...>` objects nullable but then I get warnings 

`Argument of type 'IIncludableQueryable<Country, ICollection<Enrolment>?>' cannot be used for parameter 'source' of type 'IIncludableQueryable<Course, IEnumerable<Enrolment>>'`

What am I expected to do here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by MCFHTAGENTS** [comment]
Arthur,
Thank you - project sample uploaded. 

If I compile this I get the following warning:
`Argument of type 'IIncludableQueryable<Country, ICollection<CountryProperty>?>' cannot be used for parameter 'source' of type '  due to differences in the nullability of reference types`

This relates to the Properties property of the Country collection which is coded as
`public virtual ICollection<CountryProperty>? Properties { get; set; } = null!;`

Pre nullable reference types I would have defined this as:
`public virtual ICollection<CountryProperty> Properties { get; set; };`

and accepted the fact it could be null.

If I turn this round and code it as `public virtual ICollection<CountryProperty> Properties { get; set; };`. The warning goes away, as you would expect. However, when I then use the Country object in the post handler
(see `public IActionResult Edit(int id, [Bind("CountryId,CountryName")]Country country, Dictionary<long, string> P)`) in the `CountryController`.

The modelstate validation fails as the Properties object is not supplied (and I don't want to supply it in this edit use case as I am only interested in editing the parent object not the child).

Which pattern is the 'correct' one. I don't want to have to write a custom binder for each object as that seems wrong too?

Thank you
Mark




[CPEProvisionMSFT.zip](https://github.com/dotnet/EntityFramework.Docs/files/12877860/CPEProvisionMSFT.zip)

**Comment by ajcvickers** [comment]
@MCFHTAGENTS You just need to assert to the compiler since, this is only creating an expression tree. For example:

```C#
var data = this.context.Countries
    .Include(a => a.Sites!)
    .Include(a => a.Properties!)
...
```
