### ISSUE TITLE
Type in Sql Example

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/EntityFramework.Docs#4528]
var user = new SqlParameter("**user**", "johndoe");

var blogs = context.Blogs
    .FromSql($"EXECUTE dbo.GetMostPopularBlogsForUser **@filterByUser**={user}")
    .ToList();

I think in the above example, the SqlParameter 'user' does not match the parameter name of "@filterByUser".

I think it should be:

var blogs = context.Blogs
    .FromSql($"EXECUTE dbo.GetMostPopularBlogsForUser **@user**={user}")
    .ToList();

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98b01ef5-24a5-5f59-30c9-af264f739815
* Version Independent ID: 98b01ef5-24a5-5f59-30c9-af264f739815
* Content: [SQL Queries - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries)
* Content Source: [entity-framework/core/querying/sql-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/sql-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@gregoryagu `@filterByUser` is the name of the parameter on the SQL Server stored procedure; its name depends on how the stored procedure is actually defined in the database. So there's no wrong or right here, this is just a sample. I think it's useful to have a name different from `@user` to prevent ambiguity and confusion (as `user` is also the C# variable name).

**Comment by gregoryagu** [comment]
If "@filterByUser" is the name of the parameter on SQL Server, would it not then be correct to create the parameter using that name, like this?

var user = new SqlParameter("filterByUser", "johndoe");

The first parameter per the docs to the constructor is "The parameter name" so why would you not use the parameter name?

**Comment by roji** [comment]
@gregoryagu you don't have to do that; AFAIK T-SQL allows you to specify the stored procedure name in SQL, and then have a different DbParameter name (note that difference between these two concepts).

Have you tried the SQL and does it fail for you?

**Comment by ajcvickers** [comment]
We discussed this and agreed that since the parameter name defined in the stored procedure is a different name than whatever is used by SqlClient, then it helps that these are shown as different so people don't assume they are the same.
