### ISSUE TITLE
Example uses LocalDB instead of recommended SQL Server Developer Edition

### ISSUE THREAD

**Issue by antmdvs** [dotnet/EntityFramework.Docs#4529]
In this page, it's stated that:

> We generally recommend installing SQL Server Developer edition rather than LocalDB, since it provides the full SQL Server feature set and is generally very easy to do.

..which is preceded by several bullets about why SQL Server Developer edition > LocalDB:

> - It doesn't support everything that [SQL Server Developer Edition](https://learn.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-version-15#-editions) does.
> - It's only available on Windows.
> - It can cause lag on first test run as the service is spun up.

However, the example that follows uses LocalDB, which seems a bit contradictory.

![image](https://github.com/dotnet/EntityFramework.Docs/assets/17127310/b0100b44-ab0f-4c0a-893d-097aca8bba88)

Would it make more sense to show an example that uses SQL Server Developer edition per the recommendation?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7fc3c3b-c859-2ad5-78f3-ce57d3c9bc2d
* Version Independent ID: b7fc3c3b-c859-2ad5-78f3-ce57d3c9bc2d
* Content: [Testing against your Production Database System - EF Core](https://learn.microsoft.com/en-us/ef/core/testing/testing-with-the-database)
* Content Source: [entity-framework/core/testing/testing-with-the-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/testing/testing-with-the-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@antmdvs switching between LocalDB and SQL Server is a matter of changing the connection string, nothing more. And despite the recommendation, LocalDB is particularly suited for code samples because it doesn't require installation - it's just already there, and the connection string will always work. In contrast, for SQL Server users need to set it up and tailor the connection string to the user they created, etc.

So I think things are OK as they are.

**Comment by antmdvs** [comment]
Thanks for the quick reply. I understand, I'm just pointing out that this surprised me somewhat. As it currently flows, it's like:

- Here's a drawback of LocalDB
- Another drawback
- " "

> **So we recommended XYZ instead**

## Example using LocalDB 
😕

Maybe a transitional sentence or two would help alleviate that surprise factor, or it could be just me.
