### ISSUE TITLE
Improve query hint documentation

### ISSUE THREAD

**Issue by kevinarthurackerman** [dotnet/EntityFramework.Docs#4531]
The documentation for query hints on this page is slightly misleading https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#example-command-interception-to-add-query-hints

It says "This tag can then be detected in the interceptor as it will always be included as a comment in the first line of the command text." which is not entirely true since if you call TagWith multiple times it will put each comment on it's own line (see https://learn.microsoft.com/en-us/ef/core/querying/tags)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de9a8e9e-a397-64b9-419d-fbcf525c3698
* Version Independent ID: f10c27f0-4b5b-c2b7-dd32-fac7b0d8060e
* Content: [Interceptors - EF Core](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#example-command-interception-to-add-query-hints)
* Content Source: [entity-framework/core/logging-events-diagnostics/interceptors.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/logging-events-diagnostics/interceptors.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@kevinarthurackerman the example in that page discusses the case of a single tag, which is also the vast majority of use-cases; it's accurate for that usage scenario.

I don't think anyone using multiple tags would actually be misled here; at the very least, in this feature's history nobody has signalled any confusion on it. So to me the docs seem fine as they are.

**Comment by kevinarthurackerman** [comment]
I may be an edge case but I was mislead because the documentation is incorrect for the case of more than one tag, which is a case supported by the framework. The example code [at the bottom of this page](https://learn.microsoft.com/en-us/ef/core/querying/tags) is factually incorrect.

Is the intended use case for query tags just to add some comments to a query for things like traceability, or is it intended to be used [as described here here](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#before-execution) an interceptor performs logic based off of the tags that have been applied to a query? Is there a better way to do this? That is what I am really trying to accomplish. For instance, in an application that generally applied row level security being able to instruct it for this one query to bypass the security.

**Comment by roji** [comment]
@kevinarthurackerman you can identify query tags in interceptors and perform special logic, but I don't see how multi-line support is necessary for that.

**Comment by ajcvickers** [comment]
> Is the intended use case for query tags just to add some comments to a query for things like traceability, or is it intended to be used [as described here here](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#before-execution) an interceptor performs logic based off of the tags that have been applied to a query?

Either or both. It's up to the application to define and use query tags in whatever way makes sense.
