### ISSUE TITLE
Could use Direct Information on TrackedChanges

### ISSUE THREAD

**Issue by tjHol888** [dotnet/EntityFramework.Docs#4535]
Will a subsequent SaveChanges after a Rollback try all tracked changes again?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://learn.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@tjHol888 It depends on how the transaction was started and what overload of SaveChanges is called. Can you provide more details?
