### ISSUE TITLE
Wrong lambda parameter names?

### ISSUE THREAD

**Issue by DaveCousineau** [dotnet/EntityFramework.Docs#4541]
The parameter order in the `UsingEntity` overloads is right and then left (even though the type parameters are left and then right (edit: oops, no they're not, the type parameters are right and then left, too; I figured that out later)).

However the examples use the letters l (L) and then r, instead of r and then l (L). The left and right -ness is already extremely confusing, before being reversed in the parameters (ie: right first), and then even more so with the wrong or misleading examples.

Note that I think the passed arguments are otherwise correct, it is just the naming of the lambda parameter that is backwards, giving the indication that the order is left and then right, when it is the reverse.

Thanks

EDIT:

Actually I am not 100% sure about the type parameters either.

I was under the impression that in the code:

```
modelBuilder.Entity<T1>().HasMany(one => one.Twos).WithMany(two => two.Ones)...
```

That `T1`/`one` was the "left" entity and `T2`/`two` was the "right" entity, but I see now that that is the opposite of the types that I get in the resulting `CollectionCollectionBuilder`. So I'm not really sure what is or isn't correct here.

After some more fiddling I guess it was me that was naming the type paramters `TLeft` and `TRight` in my extension method, but otherwise yes, the `CollectionCollectionBuilder` type parameters are also in "reverse" order, being right and then left. Once I realized that both the parameters and the type parameters are right first and left second, everything works.

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9234f104-802f-8ee0-8a54-ff3b8f49857e
* Version Independent ID: 9234f104-802f-8ee0-8a54-ff3b8f49857e
* Content: [Many-to-many relationships - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many?source=recommendations)
* Content Source: [entity-framework/core/modeling/relationships/many-to-many.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships/many-to-many.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@DaveCousineau This is being tracked by #4339. I agree the naming is very confusing here; it's going to require some investigation.
