### ISSUE TITLE
Clarity in explanation

### ISSUE THREAD

**Issue by programmation** [dotnet/EntityFramework.Docs#4546]
It's not clear from this document whether values entered in a [Key] column will be replaced by generated values.

For example, if I have a field

```
[Key]
[DatabaseGenerated(DatabaseGenerated.Identity)]
public int Id { get; set; }
```

and I assign a value to it before calling `SaveChanges()`, what happens? Does my assigned value get replaced by a database-generated value? If would help if this could be stated explicitly in this document.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [Generated Values - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@programmation 

> By convention, non-composite primary keys of type short, int, long, or Guid are set up to have values generated for inserted entities _if a value isn't provided by the application_.

So if a value is provided, then a value is not generated, and the provided value is used instead.

**Comment by programmation** [comment]
Thank you.
