### ISSUE TITLE
Another example for "Client evaluation in the top-level projection"

### ISSUE THREAD

**Issue by lonix1** [dotnet/EntityFramework.Docs#4551]
This is originally from a question I asked [on SO](https://stackoverflow.com/q/77467754). I think the page needs another example to clarify behaviour.

Suppose I perform a query and need to project into a concrete type.

Option 1: map results into concrete type:

```cs
var people = (await context
  .People
  .OrderBy(x => x.Name)
  .Select(x => new { x.Id, x.Surname, x.Forename })
  .ToListAsync())
  .Select(x => new PersonDto(x.Id, x.Surname, x.Forename));
```

Option 2: use concrete type in *"top-level projection"*:

```cs
var people = await context
  .People
  .OrderBy(x => x.Name)
  .Select(x => new PersonDto(x.Id, x.Surname, x.Forename));
  .ToListAsync()
```

About (2), [the docs](https://learn.microsoft.com/en-us/ef/core/querying/client-eval#client-evaluation-in-the-top-level-projection) state that in a top-level projection, some evaluation is performed in the database and some on the client. *But they show an example of a client function in an anonymous type, so it differs to my use case.*

In this specific example, am I right in assuming that **all evaluation is performed on the server**, and that (2) is just a short-cut for (1), i.e. they are functionally equivalent?

If so, please consider adding another example to that section, showing this use case? It is just as common.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd35b912-445c-e801-7f70-de73839db80d
* Version Independent ID: e558a081-5397-1e3f-1d58-abea3f72cad6
* Content: [Client vs. Server Evaluation - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/client-eval)
* Content Source: [entity-framework/core/querying/client-eval.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/client-eval.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
> In this specific example, am I right in assuming that all evaluation is performed on the server, and that (2) is just a short-cut for (1), i.e. they are functionally equivalent?

This is something that's very easy to check - simply run your code with logging enabled and check the SQL that gets generated. Did you run into trouble doing that?

**Comment by roji** [comment]
> But it's such a common pattern that the example block should have both forms:

This section of the docs is about explaining the concept of client vs. server evaluation - it's not supposed to enumerate all the cases where server evaluation is possible or not. The difference between an anonymous type and a DTO doesn't seem important here, and IMHO would only make the docs longer, distracting the user from the main conceptual point.

**Comment by roji** [comment]
Thanks for the suggestion and for understanding! Writing docs is a constant balance between not providing enough detail and providing too much.
