### ISSUE TITLE
Needs a concrete example of the use of a sequence and what to do with an existing sequence

### ISSUE THREAD

**Issue by TDSoft-JoeKelly** [dotnet/EntityFramework.Docs#4557]
Unfortunately this documentation is only partially helpful .

All that is shown here is how to create a sequence. It would be greatly improved by including a concrete example in how to use the sequence and also what to do if a sequence already exists in the database.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acf3bd16-1954-0974-500a-8f04d0a5ed5f
* Version Independent ID: 2818db16-6495-65ca-fe64-7792d6a2d1b5
* Content: [Sequences - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/sequences)
* Content Source: [entity-framework/core/modeling/sequences.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/sequences.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
We do have this explanatory, albeit short sentence:

> A sequence generates unique, sequential numeric values in the database. Sequences are not associated with a specific table, and multiple tables can be set up to draw values from the same sequence.

I don't believe it's the job of the EF documentation to explain all the basic concepts of relational databases. Using sequences isn't something that most users will need - most databases have identity columns which cover basic usage - so users ending up here likely know what they want. 

But I agree we could add a couple sentences clarifying the relationship between sequences and identity columns, and showing a more end-to-end code sample.

> what to do if a sequence already exists in the database.

That doesn't have anything to do with sequences, and is more of a general question on how to manage database schemas with EF. That's covered in the docs on Migrations - we cannot discuss this everywhere where we mention some database thing (tables, columns...).

**Comment by TDSoft-JoeKelly** [comment]
Hi Shay,

 

Thanks for getting back so promptly. 

 

I agree it’s not up to EF docs to explain RDBMS concepts. I do think an end to end example would be great. I would rather be using an Identity column but have been constrained to use a sequence.

 

Thanks,

Joe
