### ISSUE TITLE
GitHub Action - The type or namespace name 'EntityFrameworkCore' does not exist in the namespace 'Microsoft'

### ISSUE THREAD

**Issue by AltuMedSupport001** [dotnet/EntityFramework.Docs#4564]
My project is building fine on visual studio on my machine but I am getting below errors when my workflow triggers and runner runs the GitHub action for repository. When Build jobs run it is failing due to not finding entity frame work core references.

![image](https://github.com/dotnet/EntityFramework.Docs/assets/145130705/92a285ed-2ce3-478d-a6d3-e7c8525a82ab)

Here is my .csproj file

![Build-2](https://github.com/dotnet/EntityFramework.Docs/assets/145130705/b176b989-ed50-4110-ac56-c85191f609c3)

Here is my GitHub action script

![image](https://github.com/dotnet/EntityFramework.Docs/assets/145130705/d1b20532-0ff0-498a-bca7-d22c25d05a6e)

Please help me out what is the problem here with entity frame work.

**Comment by roji** [comment]
It's not really possible for us to help here without some sort of minimal repro. Can you reproduce this error when building locally? If not, your CI is building differently in some way, or not building the same code. If you can reproduce this locally, then please point us to a project that shows this happening.

As a side note, EF Core 2.2.x is out of support. Please plan for upgrading to a supported version

**Comment by AltuMedSupport001** [comment]
Thanks Roji for reply here.. This is building fine locally without any build error. It might be not able to restore EF nugget packages when building on GitHub Action.

Thanks

**Comment by roji** [comment]
@AltuMedSupport001 that's unfortunately something we can help you with... I'm also seeing error messages for the [JsonIgnore](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonignoreattribute?view=net-7.0) attribute, which is part of .NET and has nothing to do with EF Core.

I'd check the build environment, networking and nuget setup.

**Comment by ErikEJ** [comment]
@AltuMedSupport001 Is the .NET 2.2 SDK installed on your self hosted build server?
