### ISSUE TITLE
PS Command does not work.

### ISSUE THREAD

**Issue by Johns-305** [dotnet/EntityFramework.Docs#4565]
Install-Package : A parameter cannot be found that matches parameter name 'Version'.
At line:1 char:33
+ Install-Package EntityFramework -Version 6

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0f15cd1-d242-5c8d-c96d-104663423395
* Version Independent ID: 0e623627-7738-1005-3d2c-d099d6ebd929
* Content: [Get Entity Framework - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/install?source=recommendations)
* Content Source: [entity-framework/ef6/fundamentals/install.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/install.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
