### ISSUE TITLE
Fix Grammer - IDbSet Extension Methods

### ISSUE THREAD

**Issue by Trianglium** [dotnet/EntityFramework.Docs#4566]
# IDBSet Grammatical Errors (5.0.0)
I couldn't find the page that needs to be edited. Is it possible to update the grammar on [this](https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.idbset-1?view=entity-framework-5.0.0) page? If yes, I'd be happy to open a PR instead. 

## Proposed Changes
![image](https://github.com/dotnet/EntityFramework.Docs/assets/70343977/884db62b-056b-4844-b405-7748ffb7fb61)

> *"Adds or updates entities by key when SaveChanges is called. Equivalent to an "upsert" operation from database terminology. This method can **be** useful when seeding data using Migrations."*

> *"Adds or updates entities by a custom identification expression when SaveChanges is called. Equivalent to an "upsert" operation from database terminology. This method can **be** useful when seeding data using Migrations."*

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19177bfd-a106-96ce-eb88-fd4099a3fa24
* Version Independent ID: 3f3304f0-2a4d-c457-4fff-9ff74c6ddc75
* Content: [IDbSet&lt;TEntity&gt; Interface (System.Data.Entity)](https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.idbset-1?view=entity-framework-5.0.0)
* Content Source: [EF/xml/System.Data.Entity/IDbSet`1.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/IDbSet`1.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
