### ISSUE TITLE
Lazy-loading for no-tracking queries is not just a feature, but breaking change

### ISSUE THREAD

**Issue by YehudahA** [dotnet/EntityFramework.Docs#4568]
It can lead to a lot of problems with serialization.
Please provide a way to disable this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97203c5d-fe52-b71e-dcb3-71c9492b4e04
* Version Independent ID: 97203c5d-fe52-b71e-dcb3-71c9492b4e04
* Content: [What's New in EF Core 8](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew)
* Content Source: [entity-framework/core/what-is-new/ef-core-8.0/whatsnew.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-8.0/whatsnew.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Covered by https://github.com/dotnet/efcore/issues/12895
