### ISSUE TITLE
Não há diferencia

### ISSUE THREAD

**Issue by bercaio** [dotnet/EntityFramework.Docs#4572]
Não há diferencia entre:
Cascade | 3 | Para entidades que estão sendo controladas pelo contexto, as entidades dependentes serão excluídas quando a entidade relacionada for excluída.
-- | -- | --
ClientCascade | 4 | Para entidades que estão sendo controladas pelo contexto, as entidades dependentes serão excluídas quando a entidade relacionada for excluída.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação de problema do learn.microsoft.com ➟ GitHub.*

* ID: 2df9f508-7992-183c-a909-5b27316e3efd
* Version Independent ID: 8e25c165-0abc-9990-ef58-f0ac29c130e3
* Content: [DeleteBehavior Enumeração (Microsoft.EntityFrameworkCore)](https://learn.microsoft.com/pt-br/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-7.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DeleteBehavior.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Duplicate of https://github.com/dotnet/efcore/issues/29261
