### ISSUE TITLE
How to generate additional files Using T4?

### ISSUE THREAD

**Issue by paulhbr** [dotnet/EntityFramework.Docs#4573]
Hi,

It's great that you have an example of what the T4 code would look like to generate additional files (in the example, a mermaid diagram). However, in my brief look at [TextTemplatingModelGenerator](https://github.com/dotnet/efcore/blob/b96c768116efdf70e950ac956b39e483493b80fa/src/EFCore.Design/Scaffolding/Internal/TextTemplatingModelGenerator.cs), it seems that when the scaffolder runs, it's hardcoded to only look for three known files. How could I actually get an additional T4 template to be processed?

Thanks,

PBR

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cae415b7-c0ea-4d96-9d17-7e7d3163c09d
* Version Independent ID: cae415b7-c0ea-4d96-9d17-7e7d3163c09d
* Content: [Custom Reverse Engineering Templates - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/scaffolding/templates.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding/templates.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
@paulhbr This is not currently possible with the built-in tooling, but you can do it with [EF Core Power Tools](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#customize-code-using-t4-templates)
