### ISSUE TITLE
When is it ok to drop a migration which has already been applied to multiple production instances

### ISSUE THREAD

**Issue by virzak** [dotnet/EntityFramework.Docs#4591]
There is a warning to not remove migrations applied to production:

https://github.com/dotnet/EntityFramework.Docs/blob/18b2704c5051d85808268cbb742c3a2e1fd720ee/entity-framework/core/managing-schemas/migrations/managing.md?plain=1#L189-L190

Scenario:

- Desktop app, installed on machines I have no control over - reverting to a previous migration through `dotnet ef database update` is impossible. The table is huge (5GB in size).
- N<sup>th</sup> migration drops certain index and recreates it with more included columns
- (N+1)<sup>th</sup> does the same, but has even more included columns than previous migration
- All these included columns were available prior to N<sup>th</sup> migration

The advantages of dropping N<sup>th</sup> migration are:
- Executing 1 migration instead of multiple
- Smaller DLL
- Smaller code base

I don't see any disadvantages in this scenario. Are there any?

**Comment by ajcvickers** [comment]
@virzak You'll need to make sure that the two migrations and their models are combined. This is non-trivial. See https://github.com/dotnet/efcore/issues/2174
