### ISSUE TITLE
The InMemory and Sqlite does not work for jsonb columns

### ISSUE THREAD

**Issue by prasanna32** [dotnet/EntityFramework.Docs#4598]
I was referring the unit tests for BloggingController. Seems like the InMemory and Sqlite databases does not support jsonb columns. Is there a solution for this ?

This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

**Comment by roji** [comment]
@prasanna32 that's very much expected - jsonb is a PostgreSQL-only feature, and isn't supported by these two providers. It's highly recommended to simply test again PostgreSQL, e.g. using [testcontainers](https://dotnet.testcontainers.org/modules/postgres/)). For more information on testing against fakes (sqlite/inmemory) vs. your real database system, [see the docs](https://learn.microsoft.com/en-us/ef/core/testing/).

**Comment by prasanna32** [comment]
Oh! ok. Thanks for your response..
