### ISSUE TITLE
 Correction Needed: Incorrect Information Regarding UseLazyLoadingProxies Implementation in EF Core

### ISSUE THREAD

**Issue by bananaback** [dotnet/EntityFramework.Docs#4603]
Dear Maintainers,

I hope this message finds you well. I'd like to draw attention to a statement within the documentation that might mislead users regarding the implementation of UseLazyLoadingProxies in Entity Framework (EF) Core.

In the current documentation, there's a line that reads: "The UseLazyLoadingProxies call tells EF Core to implement lazy-loading, so child entities are automatically loaded when accessed from the parent."

Proposed Correction:
"The UseLazyLoadingProxies call tells EF Core to implement lazy-loading, so child entities aren't automatically loaded when accessed from the parent."

The existing statement suggests that child entities are automatically loaded when, in fact, using UseLazyLoadingProxies enables lazy-loading, preventing the automatic loading of child entities when accessed from the parent.

I believe correcting this information is essential to prevent potential confusion among users relying on the documentation to understand EF Core's behavior when utilizing lazy-loading proxies.

Thank you for your attention to this matter. I'm willing to contribute to updating the documentation if needed.

Best regards,
bananaback

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a691101f-b7ea-4539-3745-6d9b0f5e317f
* Version Independent ID: 8f488a69-cedf-9c45-f977-23b3d8abd3df
* Content: [Get Started with WPF - EF Core](https://learn.microsoft.com/en-us/ef/core/get-started/wpf)
* Content Source: [entity-framework/core/get-started/wpf.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/wpf.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by ajcvickers** [comment]
@bananaback But lazy-loading _does_ result in child entities being loaded automatically.

**Comment by bananaback** [comment]
Dear @ajcvickers,

Thank you for your response and clarification regarding the UseLazyLoadingProxies functionality in Entity Framework Core.

I appreciate your input and understand that my initial understanding have been incorrect. I apologize for any confusion caused by my suggestion to alter the documentation.

Once again, I apologize for any confusion caused by my previous comment, and I'm grateful for your assistance in ensuring the accuracy of the documentation.

Thank you for your time and help.

Best regards,

bananaback
