### ISSUE TITLE
SQL Trigger example is wrong

### ISSUE THREAD

**Issue by Peled-Zohar** [dotnet/EntityFramework.Docs#4604]
The SQL Trigger shown in the [Update timestamp](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#update-timestamp) paragraph as a major flaw in it as it assumes the update can only work on a single row, where as in the real world, SQL Server triggers are statemet-based, not row-based, meaning that the inserted (or deleted) auto-generated table can contain multiple rows. Therefor, a statement such as `SELECT @Id = INSERTED.BlogId
    FROM INSERTED` will cause the trigger to fail in the update was made over multiple rows.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [Generated Values - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#datetime-value-generation)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@Peled-Zohar would you like to submit a PR fixing this?

**Comment by Peled-Zohar** [comment]
@roji Yeah, sure, why not? I'll start working on that within the next 30 minutes

**Comment by Peled-Zohar** [comment]
@roji Done. [PR #4606](https://github.com/dotnet/EntityFramework.Docs/pull/4606)
