### ISSUE TITLE
A typo, Blogs should be Posts

### ISSUE THREAD

**Issue by mann-codes2014** [dotnet/EntityFramework.Docs#4614]
![image](https://github.com/dotnet/EntityFramework.Docs/assets/97145056/7fe45f68-9193-4f47-9724-851c76fcbd06)
Highlighted word `Blogs `should be `Posts`, as foreign key is added in `Posts` table,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Introduction to relationships - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/relationships)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks @mann-codes2014, submitted #4615 to fix.

In the future, for small typos like this it's very easy to just submit a PR fixing it (there's an "edit page" button that allows you to do this effortlessly in the UI).
