### ISSUE TITLE
Add guidance on retrieving TotalCount with paginated query

### ISSUE THREAD

**Issue by adamal** [dotnet/EntityFramework.Docs#4620]
When paging queried data, we often need to know the totalt count of the filtered data before paging.
The straight-forward approach causes two roundtrips to the database. One for the data one for the count.

In Dapper, this is easily achievable using `QueryMultiple`.

On Stackoverflow I have only found very old or low quality answers, with solutions that are hacky at best. Chat-GPT provides broken answers. Would be great if you could provide an authoritative answer. This specific article on paging seems an ideal location.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14420c94-0cae-1648-b734-633a1cac6624
* Version Independent ID: 14420c94-0cae-1648-b734-633a1cac6624
* Content: [Pagination - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/pagination)
* Content Source: [entity-framework/core/querying/pagination.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/pagination.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by dsgordeev** [comment]
@ajcvickers, @roji, if there is a way to get total count and page items in single query then how to share it?
To create issue to dotnet/EntityFramework.Docs repo, right?

**Comment by roji** [comment]
@dsgordeev in SQL, you can get page items and a total count in the same query by using window functions, but EF doesn't currently support expressing that via LINQ (see https://github.com/dotnet/efcore/issues/12747). Otherwise, you can batch two separate queries in a single roundtrip, but that causes more processing on the database side, and unfortunately also isn't supported by EF yet (https://github.com/dotnet/efcore/issues/10879).

**Comment by dsgordeev** [comment]
@roji, yeah, it would be very nice to have API of window functions in Linq Expressions, thank you for the link. 
But in some specific cases there is option to include a window function into the game via interceptors.
