### ISSUE TITLE
How Unit of Work implement in Transient  DbContext 

### ISSUE THREAD

**Issue by KashifFaraz** [dotnet/EntityFramework.Docs#4626]
[Enter feedback here]

 one disadvantage of Transient DbContext is, that you lose the Unit of Work functionality
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb29a2b6-c401-287f-2da9-1aeb3c633b41
* Version Independent ID: bb29a2b6-c401-287f-2da9-1aeb3c633b41
* Content: [Multi-tenancy - EF Core](https://learn.microsoft.com/en-us/ef/core/miscellaneous/multitenancy)
* Content Source: [entity-framework/core/miscellaneous/multitenancy.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/multitenancy.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by roji** [comment]
The lifetime of the DbContext (transient or not) is orthogonal to how unit of work operates. With unit of work, you use a single DbContext instance to e.g. query some entities, make changes to them and then persist those changes back to the database via SaveChanges; this can be done with a transient DbContext instance just as well as with a non-transient one.
