### ISSUE TITLE
Microsoft.EntityFrameworkCore.Design has been depreciated. Please update page.

### ISSUE THREAD

**Issue by SDmorgan** [dotnet/EntityFramework.Docs#4631]
Microsoft.EntityFrameworkCore.Design has been depreciated. Please update this page with more insightful up-to-date information.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94ec1534-845d-2003-053d-7ed6785369fc
* Version Independent ID: 94ec1534-845d-2003-053d-7ed6785369fc
* Content: [Reverse Engineering - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/managing-schemas/scaffolding/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@SDmorgan "Microsoft.EntityFrameworkCore.Design has been depreciated." This is not true; where did you read this?

**Comment by SDmorgan** [comment]
My apologies. Misread Microsoft.EntityFrameworkCore.Relational.Design.

Please close.


Simon Morgan
VP Information Technology
e: ***@***.*** | w: DAN.org
t: 919-684-2948 Ext.1338
a: 6 W Colony Place, Durham, NC  27705

​This message (including any attachments) may contain confidential, proprietary, privileged and/or private information. The information is intended to be for the use of the individual or entity designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is prohibited.
