### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by McGregorsoft** [dotnet/EntityFramework.Docs#4676]
### Type of issue

Typo

### Description

Manually update the entity types amd EF c...

### Page URL

https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/?tabs=dotnet-core-cli

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding/index.md

### Document Version Independent Id

94ec1534-845d-2003-053d-7ed6785369fc

### Article author

@bricelam

**Comment by roji** [comment]
Thanks, submitted #4677 to fix.
