### ISSUE TITLE
Code-Firts

### ISSUE THREAD

**Issue by ACken12** [dotnet/EntityFramework.Docs#4682]
### Type of issue

Typo

### Description

[Escriba sus comentarios aquí]
Code-Firts C#

### Page URL

https://learn.microsoft.com/es-es/ef/ef6/modeling/code-first/workflows/existing-database

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/workflows/existing-database.md

### Document Version Independent Id

c5280888-67b5-4c13-bdc6-3a0ec6bfbe20

### Article author

@ajcvickers

**Comment by roji** [comment]
@ACken12 I can't see the typo ("Firts") in the linked-to pages.
