### ISSUE TITLE
Problem with instslling Entity Framework SQL Server

### ISSUE THREAD

**Issue by Vanzo777** [dotnet/EntityFramework.Docs#4686]
### Type of issue

Other (describe below)

### Description

[Введите отзыв здесь]
Hello, I'm trying to install EntityFrameworkCore.SqlServer, after clicking on Install, I got a list of errors, I really need help..
![image](https://github.com/dotnet/EntityFramework.Docs/assets/149005731/c212057a-93f4-412b-8727-4b27c520bd09)
 

### Page URL

https://learn.microsoft.com/ru-ru/ef/core/get-started/overview/install

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/install.md

### Document Version Independent Id

f58fcb81-a0a9-b042-72bb-f4823b097f63

### Article author

@bricelam

**Comment by ErikEJ** [comment]
Your package sources are broken

**Comment by Vanzo777** [comment]
Ok, but how can I fix it?

**Comment by Vanzo777** [comment]
> Your package sources are broken

Ok, but how can I fix it?
