### ISSUE TITLE
StringToNumberConverter

### ISSUE THREAD

**Issue by luizmirandati** [dotnet/EntityFramework.Docs#4688]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.valueconversion.stringtonumberconverter-1?view=efcore-8.0

### Content source URL

https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Storage.ValueConversion/StringToNumberConverter`1.xml

### Document Version Independent Id

62b8b7d1-47d6-880d-0127-e31714179b75

### Article author

@dotnet-bot

**Comment by roji** [comment]
@luizmirandati what typo are you referring to here?
