### ISSUE TITLE
Unable to create a 'DbContext' of type ''. The exception 'Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[mywebsite.Data.ApplicationDbContext]' while attempting to activate 'mywebsite.Data.ApplicationDbContext'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

### ISSUE THREAD

**Issue by DemozeDan1** [dotnet/EntityFramework.Docs#4692]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/cli/dbcontext-creation.md

### Document Version Independent Id

d988e806-cb86-19f5-7f76-6ce3bfcd94ed

### Article author

@bricelam

**Comment by DemozeDan1** [comment]
how can I resolve this error?

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by DemozeDan1** [comment]
<img width="524" alt="Screenshot 2024-03-24 133646" src="https://github.com/dotnet/EntityFramework.Docs/assets/157909577/58e39591-f0af-4527-b94a-a3a4c0e1d155">

**Comment by DemozeDan1** [comment]
<img width="486" alt="Screenshot 2024-03-24 133706" src="https://github.com/dotnet/EntityFramework.Docs/assets/157909577/1167f96b-c9bc-418e-b5b4-9fd9982cd28e">

**Comment by DemozeDan1** [comment]
<img width="561" alt="Screenshot 2024-03-24 133941" src="https://github.com/dotnet/EntityFramework.Docs/assets/157909577/4fce2c1f-1cad-46f6-b483-c557abb64efd">

**Comment by roji** [comment]
@DemozeDan1 I'm sorry, but a couple screenshots do not constitute "a small, runnable code listing". Please put together a minimal program/project that shows the problem.
