### ISSUE TITLE
Document ListValueComparer breaking change

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/EntityFramework.Docs#4699]
### Issue or suggestion

See https://github.com/dotnet/efcore/pull/33456

**Comment by roji** [comment]
@AndriySvyryd am not sure exactly which breaking change this refers to... Do you mind taking this one as reviewed the PR etc.?

**Comment by AndriySvyryd** [comment]
This breaking change was fixed in https://github.com/dotnet/efcore/pull/34312
