### ISSUE TITLE
missing defaults information

### ISSUE THREAD

**Issue by vitorrubio** [dotnet/EntityFramework.Docs#4707]
### Type of issue

Missing information

### Description

the article does not mention defaults for constructor parameters maxRetryCount and maxDelay nor the default behavior when they arent informed.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.sqlserver.sqlazureexecutionstrategy?view=entity-framework-6.2.0

### Content source URL

https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.SqlServer/SqlAzureExecutionStrategy.xml

### Document Version Independent Id

2dc552b7-738d-3a1f-e1a0-ae9c0b67b36b

### Article author

@dotnet-bot

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
