### ISSUE TITLE
I cant make use of the Entity.FrameworkCore

### ISSUE THREAD

**Issue by Norrlan** [dotnet/EntityFramework.Docs#4708]
### Type of issue

Typo

### Description

[Enter feedback here]
Install-Package : NU1202: Package Microsoft.EntityFrameworkCore 8.0.4 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package 
Microsoft.EntityFrameworkCore 8.0.4 supports: net8.0 (.NETCoreApp,Version=v8.0)
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'IAP-CW'.
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception

### Page URL

https://learn.microsoft.com/en-gb/ef/core/

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/index.md

### Document Version Independent Id

f4681bc6-57be-6e69-cad9-776ce64d93bd

### Article author

@ajcvickers

**Comment by roji** [comment]
As the error message says, you seem to be trying to use EF Core 8.0 from a project targeting .NET 7.0 - this is not supported. Update your .NET project to target .NET 8.0.
