### ISSUE TITLE
Please provide some code samples how to use it in reality. 

### ISSUE THREAD

**Issue by Esterl-Christian** [dotnet/EntityFramework.Docs#4717]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.design.designtimeservicecollectionextensions.addentityframeworkdesigntimeservices?view=efcore-8.0

### Content source URL

https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Design/DesignTimeServiceCollectionExtensions.xml

### Document Version Independent Id

d9473c7d-9660-8f76-1b59-25ddac8a2c41

### Article author

@dotnet-bot

**Comment by ajcvickers** [comment]
@Esterl-Christian See https://learn.microsoft.com/en-us/ef/core/cli/services
