### ISSUE TITLE
EntityTypeAttributeConventionBase disappeared

### ISSUE THREAD

**Issue by doboczyakos** [dotnet/EntityFramework.Docs#4737]
EntityTypeAttributeConventionBase disappeared without being documented as breaking change and possible replacement
It's unacceptable to remove public features (not internal API, not marked as obsolete) silently, under the radar

https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.conventions.entitytypeattributeconventionbase-1

https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes

**Comment by roji** [comment]
Transferred to the docs repo. Sure, we can add a breaking change note for this, though in the future it's probably better to just leave a stub type with [Obsolete(error=true)] that points to the new type.
