### ISSUE TITLE
dbcontext class code in c# .net core8

### ISSUE THREAD

**Issue by mohdarraj** [dotnet/EntityFramework.Docs#4746]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext.configuration?view=entity-framework-6.2.0#system-data-entity-dbcontext-configuration

### Content source URL

https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DbContext.xml

### Document Version Independent Id

2453e831-7b38-4e49-a916-c8d8debec545

### Article author

@dotnet-bot

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
