### ISSUE TITLE
What platform exactly ?

### ISSUE THREAD

**Issue by Gluups** [dotnet/EntityFramework.Docs#4755]
### Type of issue

Typo

### Description

Hello,
Several platforms exist with EntityFramework: Microsoft.EntityFrameworkCore, DotNetCore.EntityFrameworkCore ...
Not knowing which one has to be referenced to use a documentation can lead to exceptions like "The type or namespace 'Entity' does not exist in the namespace 'System.Data'"

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.data.entity?view=entity-framework-6.2.0

### Content source URL

https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/EF/xml/ns-System.Data.Entity.xml

### Document Version Independent Id

d0843f07-3bbe-fe82-7d99-5c3d27e73ed9

### Article author

@dotnet-bot

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by Gluups** [comment]
Well, I am not interested in using EF6.
When you search "MVC pagination", the first answer (at least with DuckDuckGo) is there:
[https://learn.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/sorting-filtering-and-paging-with-the-entity-framework-in-an-asp-net-mvc-application](https://learn.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/sorting-filtering-and-paging-with-the-entity-framework-in-an-asp-net-mvc-application)
Only after clicking on two or three links to go to "previous page", you discover that the tutorial is based on EF6.
