### ISSUE TITLE
Outdated tutorial

### ISSUE THREAD

**Issue by PicassoCT** [dotnet/EntityFramework.Docs#4758]
### Type of issue

Code doesn't work

### Description

Tutorial is outdated and not working anymore. SQLite batteries are not include and commands are not resulting in working version.

### Page URL

https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/first-app.md

### Document Version Independent Id

b38b9d14-6bad-12e0-8d2d-24b50bc4977e

### Article author

@Rick-Anderson

**Comment by ajcvickers** [comment]
@PicassoCT Can you post the specific error you are seeing and indicate at which stage it happens?

**Comment by PicassoCT** [comment]
@ajcvickers  Its me. I added the wrong package: Microsoft.Data.Sqlite.Core instead of Microsoft.EntityFrameworkCore.Sqlite.Core. Just the universal background noise of noobs finding out. Thanks for caring.
