### ISSUE TITLE
SQL Injection Example

### ISSUE THREAD

**Issue by AppFzx** [dotnet/EntityFramework.Docs#4770]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
The example provided demonstrates how to create a textbook SQL injection vulnerability. This should be modified to show how to parameterize or get rid of the unnecessary demonstration of bad practice. I just stopped a PR where someone had copied your example and they argued that Microsoft said to do it.

```var searchTerm = "Lorem ipsum";

var blogs = context.Blogs
    .FromSql($"SELECT * FROM dbo.SearchBlogs({searchTerm})")
    .AsNoTracking()
    .ToList();```

### Page URL

https://learn.microsoft.com/en-us/ef/core/querying/sql-queries

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/sql-queries.md

### Document Version Independent Id

98b01ef5-24a5-5f59-30c9-af264f739815

### Article author

@smitpatel

**Comment by ajcvickers** [comment]
@AppFzx The SQL generated is parameterized. Here's the log output from EF:

```
info: 7/31/2024 08:00:27.116 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (54ms) [Parameters=[p0='Lorem ipsum' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SELECT * FROM dbo.SearchBlogs(@p0)
```

I don't believe there is any SQL injection attack possible here.
