### ISSUE TITLE
No Primary Key causes issue during InitialCreate

### ISSUE THREAD

**Issue by NKCSS** [dotnet/EntityFramework.Docs#4778]
### Type of issue

Code doesn't work

### Description

The example does not talk or specify how to specify a primary key for your objects. If you run the `migrations add InitialCreate`, you'll get this error

`Unable to create a 'DbContext' of type ''. The exception 'The entity type 'OrderDbEntry' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728`

### Page URL

https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/overview/first-app.md

### Document Version Independent Id

b38b9d14-6bad-12e0-8d2d-24b50bc4977e

### Article author

@Rick-Anderson

**Comment by roji** [comment]
@NKCSS if you follow the sample, you get the BlogId and PostId implicitly as EF does this for your by convention. More information about when keys are discovered by convention and how to configure them explicitly can be found in the [dedicated doc page on keys](https://learn.microsoft.com/en-us/ef/core/modeling/keys) - I don't think that belongs in the very first "getting started" sample.

**Comment by NKCSS** [comment]
Yes, I found that out later @roji but, as you can see, as soon as you try to use the example to build a solution yourself, you'll run into this when you don't have a datamodel that follows this, so at least making note of that would have been helpful 😊These examples are meant to get people started, so information you might need to transfer this to a real-world solution is key.
