### ISSUE TITLE
Bug in Client Evaluation sample code

### ISSUE THREAD

**Issue by mamdos** [dotnet/EntityFramework.Docs#4793]
### Issue or suggestion

I reached to a bug in this address https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Querying/ClientEvaluation/Program.cs#ClientMethod

**Comment by mamdos** [comment]
when the entry URL starts with https:// it also adds another http:// to it and return it, and this produces bugs

**Comment by roji** [comment]
This sample is just a demonstration of a method that executes client-side; this particular code just adds an http:// prefix if there isn't one; it's not meant to be a fully usable method for handling URLs, just a minimal demo. Feel free to change it in your own code to detect https:// or anything else.
