### ISSUE TITLE
add : The term 'add' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name,  or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by mahmoudkeshar** [dotnet/EntityFramework.Docs#4796]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/ef/core/managing-schemas/ensure-created

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/ensure-created.md

### Document Version Independent Id

777c4acb-f5c7-3b99-950e-e5265006182a

### Article author

@bricelam

**Comment by AndriySvyryd** [comment]
Please provide additional details.
