### ISSUE TITLE
Multiple db contexts in retryable transaction

### ISSUE THREAD

**Issue by dazinator** [dotnet/EntityFramework.Docs#4807]
### Type of issue

Missing information

### Description

Suppose my database has different schema's and I have seperate DbContext's for those schemas.

Given the retry policy / execution strategy is configured per DB context, how should I
Execute a "resilient transaction" that spans multiple Db Contexts?

Also given people have standardised on using polly for resiliency - can it be mentioned why polly isn't used here? Or is there a way to use polly for this use case instead that could be linked to for those that adopt Polly for resiliency already?  Polly is such a big part of the resiliency story in dotnet that I feel it should atleast be mentioned.

Also, should there be some guidance around not putting "side effects" in the delegate that is "retried". I think anything in this method should be idempotent right?

### Page URL

https://learn.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/miscellaneous/connection-resiliency.md

### Document Version Independent Id

29002343-fa42-2f49-3362-53592039b26d

### Article author

@AndriySvyryd

**Comment by AndriySvyryd** [comment]
> Execute a "resilient transaction" that spans multiple Db Contexts?  

Unless they share the same connection object it would need to be a distributed transaction. It's possible to implement via a `TransactionScope`, but few providers support it and it's generally not recommended.

> can it be mentioned why polly isn't used here?

- IExecutionStrategy was introduced in before polly became widely used
- We prefer to avoid additional dependencies when possible
- You can create an `IExecutionStrategy` adapter for a polly `ResiliencePipeline`

**Comment by roji** [comment]
Note #30552 which tracks EF and Polly integration. I do believe it may make sense to do something here, possibly as an additional package (Microsoft.EntityFrameworkCore.Polly?).

**Comment by dazinator** [comment]
> but few providers support it and it's generally not recommended.

Most ado.net providers do support TransactionScope for local transactions as far as I am aware. For example SqlServer, MySql, Postgres to name just the first few I checked. If there is a list somewhere showing which ones don't that would be useful to know.

Let's treat the guidance on Distributed transactions as seperate because I agree these are generally not recommended.

However TransactionScope only attempted to upgrade to a distributed transaction when you attempt to use  transaction spanning multiple different data stores. I'd argue that this isn't the only use case for TransactionScope and that it's actually very beneficial to use it for local transaction against a single data source. Consider the following common pattern - the transactional outbox pattern. In this pattern you often have to update some records using EFCore as one subsystem, and say, MassTransit participating in the same transaction as another subsystem - as it wants to write to an outbox table. Because both subsystems support Transaction Scope, its very easy to wrap them in a transaction scope, and because both subsystems are writing to the same data store, there is no distributed transaction that comes into play, and the code is also more solid because we didn't have to modify any of our repository code to manually hook up the mass transit transaction with the dbcontext database transaction.

So my thoughts are: the narrative that most providers don't support Transaction Scope and that in general its not recommended should be refined to: Most providers support TransactionScope for local transactions / i.e transactions spanning a single connection string or data store; but its not recommended to use them in situations where you will be spanning potentially multiple data stores giving rise toa  distributed transaction, because in general eventual consistency patterns are favoured over distributed transactions due to better scalability etc.

**Comment by roji** [comment]
@dazinator I'd recommend not conflating things. EF's retrying strategy can be used with multiple contexts without TransactionScope; you need to ensure to use the same connection and transaction by all contexts, but this is the case regardless of whether you use TransactionScope or not (otherwise you get a distributed transaction). 

Of course, if you want to use Polly rather than EF's retrying strategy, that's totally fine - but as far as I'm aware there's nothing related to "multiple db context" which favors one over the other. Similarly, if you want to use TransactionScope you may do that, but that's again orthogonal.

**Comment by dazinator** [comment]
@roji 
Thanks. I think I was just attempting to dispute the idea that TransactionScope isn't widely supported. I was also trying to make a point that it makes more sense to handle transaction resiliency at a transaction level in dotnet using polly, than it does to use something dbcontext specific. Just looking at what is going on it here, EF does not provide a transaction - the underlying data store does. Therefore having a sensible polly resilience policy per data store provider for its transactions would be the logical scope I'd want to address this at - and I'd want EF core to honour that,> don't thing EF should  own this key abstraction as its resilience transactions are needed in dotnet with the data store whether you use EF core or now. For example if I was using ado.net directly with azure sql I'd want resilience. So for me it makes sense to create polly resilience policies at that level and then EF core can just benefit from them rather than enforce its own abstractions into the situation around resilience. 

The short of it is I'd love to see like, Polly resilience library for Azure sql in general, and then be able to plug that in to EF dbcontext, or Ado.Net or Dapper etc.

**Comment by dazinator** [comment]
> Re TransactionScope specifically, It's true that it's supported by most provider (IIRC Microsoft.Data.Sqlite is the notable exception). However, the API doesn't support asynchronous I/O (for commit/rollback), for example.

I hadn't considered that. I wonder if async support can be added!

**Comment by roji** [comment]
>  think the short of it is I'd love to see, Polly resilience policies available, per data store (azure sql, postgres etc) and then be able to use EF as a participant in a resilient transaction, rather than EF owning the resilience, and thus also the need to initiate the transaction within that.

As far as I know, there's nothing stopping you from doing that today. There's no nice integration with Polly (that's what https://github.com/dotnet/efcore/issues/30552 tracks), but you're definitely free to do all the things you want - EF, dapper, raw ADO.NET) - within a single retriable code block that's managed by Polly. Give it a try.

> I wonder if async support can be added!

See https://github.com/dotnet/runtime/issues/1420. This is a pretty complex thing to do, requiring also changes in database drivers implementing the System.Transactions interfaces. It most likely won't be done any time soon.

I'll go ahead and close this as I don't think there's anything actionable here that isn't already tracked elsewhere.

**Comment by dazinator** [comment]
@roji Thanks much appreciated
