### ISSUE TITLE
Provide ROPC warning on connections strings per SFI learn.microsoft.com mandate

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/EntityFramework.Docs#4809]
### Issue or suggestion

This issue is a copy of https://github.com/dotnet/AspNetCore.Docs/issues/33226

See the warning just above [SQL Server Express LocalDB](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?branch=main&branchFallbackFrom=pr-en-us-33542&view=aspnetcore-8.0&tabs=visual-studio#sql-server-express-localdb) and follow see [Secure authentication flows](https://learn.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-8.0#secure-authentication-flows).

That's how we're handing potential ROPC risks. Ultimately customers will deploy apps to production. Most of the work is done in a few include files to choose from

**dotnet_EntityFramework_Docs**

- [ ]  [Connection Strings](https://learn.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
- [ ] [Connection strings and models](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/configuring/connection-strings)
- [ ] [Scaffolding (Reverse Engineering)](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/?tabs=dotnet-core-cli)
- [ ] [Configuration File Settings](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/configuring/config-file)
- [ ] [EF Core tools reference (Package Manager Console) - EF Core](https://learn.microsoft.com/en-us/ef/core/cli/powershell)
- [ ] [EF Core tools reference (.NET CLI) - EF Core](https://learn.microsoft.com/en-us/ef/core/cli/dotnet)
- [ ] [Multi-tenancy - EF Core](https://learn.microsoft.com/en-us/ef/core/miscellaneous/multitenancy)
- [ ] [Azure Cosmos DB Provider - EF Core](https://learn.microsoft.com/en-us/ef/core/providers/cosmos/)
- [ ] [What's New in EF Core 5.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew)
- [ ] [Entity Framework 6 SQL Server provider based on Microsoft.Data.SqlClient](https://learn.microsoft.com/en-us/ef/ef6/what-is-new/microsoft-ef6-sqlserver)
- [ ] [Visual Studio Releases - EF6](https://learn.microsoft.com/en-us/ef/ef6/what-is-new/visual-studio)
- [ ] [Applying Migrations - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying)
- [ ] [Port from EF6 to EF Core - Detailed Cases](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-detailed-cases)
- [ ] [Using migrate.exe - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/migrate-exe)
- [ ] [Database Providers - EF Core](https://learn.microsoft.com/en-us/ef/core/providers/)
- [ ] [Porting from EF6 to EF Core - Porting a Code-Based Model - EF](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-code)
- [ ] [Tools & Extensions - EF Core](https://learn.microsoft.com/en-us/ef/core/extensions/)
- [ ] [DbContext Lifetime, Configuration, and Initialization - EF Core](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/)
- [ ] [Enum Support - EF Designer - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/designer/data-types/enums)
- [ ] [Code First Conventions - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/conventions/built-in)
- [ ] [Interceptors - EF Core](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors)
- [ ] [Database First - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/designer/workflows/database-first)
- [ ] [What's New in EF Core 6.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew)
- [ ] [Code First to an Existing Database - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/existing-database)
- [ ] [Advanced Performance Topics](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics)
- [ ] [Entity Framework Designer Keyboard Shortcuts - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/designer/keyboard-shortcuts)
- [ ] [Breaking changes in EF Core 7.0 (EF7) - EF Core](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes)
- [ ] [Databinding with WinForms - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/databinding/winforms)
- [ ] [Databinding with WPF - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/databinding/wpf)
- [ ] [The Entity Framework 6 provider model - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/providers/provider-model)
- [ ] [Overview of Entity Framework Core - EF Core](https://learn.microsoft.com/en-us/ef/core/)
- [ ] [Upgrading from previous versions to EF Core 2 - EF Core](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0/upgrade)
- [ ] [Get Started with Windows Forms - EF Core](https://learn.microsoft.com/en-us/ef/core/get-started/winforms)
- [ ] [Dependency resolution - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/configuring/dependency-resolution)
- [ ] [Porting from EF6 to EF Core - Behavior changes](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-behavior)
- [ ] [Porting from EF6 to EF Core - Porting an EDMX-Based Model - EF](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-edmx)

CS effort for repos:
**dotnet_EntityFramework_Docs**

For details see:
[SFI info in Teams](https://teams.microsoft.com/l/message/19:49ff5836203f4b358334bfcfa593f252@thread.tacv2/1722361260037?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8d8475c9-f864-4ed0-825e-b2e419026017&parentMessageId=1722361260037&teamName=Content%20Team%20%7C%20C%2BE%20Skilling&channelName=General&createdTime=1722361260037)

**Comment by Rick-Anderson** [comment]
@roji  @ajcvickers @AndriySvyryd  please review

**Comment by AndriySvyryd** [comment]
For EF6 pages consider putting a link to [Entity Framework 6 SQL Server provider based on Microsoft.Data.SqlClient](https://learn.microsoft.com/en-us/ef/ef6/what-is-new/microsoft-ef6-sqlserver) in the warning as using it is required to be able to follow the guidance.

I don't think that the warning is relevant on these pages:
- [What's New in EF Core 5.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew)
- [What's New in EF Core 6.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew)
- [Breaking changes in EF Core 7.0 (EF7) - EF Core](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes)
- [Upgrading from previous versions to EF Core 2 - EF Core](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0/upgrade)
- [Porting from EF6 to EF Core - Behavior changes](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-behavior)
- [Porting from EF6 to EF Core - Porting a Code-Based Model - EF](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-code)
- [Porting from EF6 to EF Core - Porting an EDMX-Based Model - EF](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-edmx)
- [Database Providers - EF Core](https://learn.microsoft.com/en-us/ef/core/providers/)
- [Tools & Extensions - EF Core](https://learn.microsoft.com/en-us/ef/core/extensions/)
- [Applying Migrations - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying)
- [DbContext Lifetime, Configuration, and Initialization - EF Core](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/)
- [Interceptors - EF Core](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors)
- [Advanced Performance Topics](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics)

**Comment by AndriySvyryd** [comment]
Related:

- https://github.com/dotnet/EntityFramework.Docs/issues/3071
- https://github.com/dotnet/EntityFramework.Docs/issues/3877
- https://github.com/dotnet/EntityFramework.Docs/issues/1083
- https://github.com/dotnet/EntityFramework.Docs/issues/2075
- https://github.com/dotnet/EntityFramework.Docs/issues/2926
- https://github.com/dotnet/EntityFramework.Docs/issues/4101

**Comment by Rick-Anderson** [comment]
Fixed in #4849
