### ISSUE TITLE
Revisit walkthroughs

### ISSUE THREAD

**Issue by ryanmendoza** [dotnet/EntityFramework.Docs#481]
It would be nice to see some more documentation in the EF section targeted to users who do not use Visual Studio as an IDE. 

I am mainly referencing this walkthrough - https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db

**Comment by ajcvickers** [comment]
Note from triage: consider:
* Are the walkthroughs are still useful?
* Do they pivot on the correct dimensions?
* How to link to content such as #506 and vice/versa

**Comment by divega** [comment]
Here is one possible high level perspective on where we could steer things:

1. Expand the overview page to really explain the basic concepts and the initial steps to use EF. E.g. create a derived DbContext with DbSet properties, override this and that, etc., with simple code snippets.
2. Have short How-To sections in some topics. E.g. for different .NET implementations, command line vs. Visual Studio vs. other IDEs, new vs. existing database, or different application models that make you use EF Core differently. The guides can cover what is specific to each case, without going step-by-step

**Comment by ajcvickers** [comment]
Note: duplicate issues can act as a validation here that the re-worked walk-throughs are covering what people need.

**Comment by ajcvickers** [comment]
Priority for 3.0:
* Simple Console or Try.NET based walkthrough for .NET Core
* Reference to ASP.NET Core tutorial

**Comment by ajcvickers** [comment]
Revisit this towards the end of the 5.0 cycle.

**Comment by Rick-Anderson** [comment]
@ajcvickers  consider closing this. The link provided
> I am mainly referencing this walkthrough - https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db

Goes to my RP/EF tutorial that has both VS and  VSC. Even if you don't want to use VSC, it's easy to follow with CLI

https://docs.microsoft.com/en-us/ef/core/get-started has both CLI and VS tabs.  If you had other docs in mind, add them to this issue and I can probably add the CLI instructions.

**Comment by JeremyLikness** [comment]
I propose close.

- We have walkthroughs for all major platforms linked from TOC and hub page
- There are examples using VS, VSC, and CLI
- Per @Rick-Anderson note above. We have separate issues open for specific walkthroughs.

Jeremy
