### ISSUE TITLE
Add a section to cover that native database-generated concurrency tokens aren't supported for SQLite

### ISSUE THREAD

**Issue by guardrex** [dotnet/EntityFramework.Docs#4827]
### Type of issue

Missing information

### Description

See if I've made a mistake in my reasoning on this, but this article might include a short section on this subject.

I was investigating why concurrency wasn't working OOB with our Blazor-EF Core sample app, and I found the following remark at [Handling Concurrency Conflicts: Native database-generated concurrency tokens](https://learn.microsoft.com/ef/core/saving/concurrency?tabs=fluent-api#native-database-generated-concurrency-tokens) (emphasis added):

> The rowversion type shown above is a SQL Server-specific feature; the details on setting up an automatically-updating concurrency token differ across databases, and some databases don't support these at all ***(e.g. SQLite)***.

*Indeed!* Our Blazor-EF Core sample app (built by Jeremy Likness) that uses SQLite [calls `IsRowVersion`](https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorWebAppEFCore/Data/ContactContext.cs#L31) to use automatic concurrency tokens.

In our Blazor article that accompanies the sample app, I'll call this out, which is tracked by https://github.com/dotnet/AspNetCore.Docs/issues/33799 and resolved by https://github.com/dotnet/AspNetCore.Docs/pull/33800.

My ask here is if you would like to add a short section to this article on SQLite limitations that native database-generated concurrency tokens aren't supported for SQLite? Just in case devs don't see the concurrency article that I mentioned above, they might catch this limitation in this special limitations-focused article.

### Page URL

https://learn.microsoft.com/en-us/ef/core/providers/sqlite/limitations

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/sqlite/limitations.md

### Document Version Independent Id

545bb0b5-f15b-584e-cef7-7283a0e0729f

### Article author

@SamMonoRT

**Comment by roji** [comment]
Sure, I submitted #4829 to add a sentence to the SQLite limitations page. I'm skeptical this would actually help people catch a problem like this up-front, but it doesn't hurt.
