### ISSUE TITLE
Me

### ISSUE THREAD

**Issue by Woodyy00** [dotnet/EntityFramework.Docs#4841]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/ef/core/providers/sql-server/?tabs=dotnet-core-cli&WT.mc_id=email

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/sql-server/index.md

### Document Version Independent Id

af433371-e282-4b89-7b09-6caf43af83e0

### Article author

@

**Comment by roji** [comment]
Closing as no detail was provided in the issue.
