### ISSUE TITLE
Split query warning refers to EF version 10, a version that does not exist.

### ISSUE THREAD

**Issue by SamInfosoft** [dotnet/EntityFramework.Docs#4851]
### Type of issue

Typo

### Description

"Warning
When using split queries with Skip/Take on EF versions prior to 10"

What version 10?

This is possibly a spelling mistake, or should have a link to the details of version 10 that describe how the behaviour changes.

![Image](https://github.com/user-attachments/assets/46f2cea2-b828-445a-bcac-e4c9be3272fb)

### Page URL

https://learn.microsoft.com/en-nz/ef/core/querying/single-split-queries

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/single-split-queries.md

### Document Version Independent Id

4e789a1b-aa88-d194-dc2e-0a23251250d7

### Article author

@roji

**Comment by roji** [comment]
This isn't a spelling mistake - see #4831, it s change that was merged recently, and will be made available when the first preview of EF 10 is released.

**Comment by SamInfosoft** [comment]
I think it may need some clarification attached to it then, this is the only place in MS web based documentation that I found reference to an EF version greater than 9.
