### ISSUE TITLE
Aggregate functions over subqueries and aggregates on SQL Server: Empty code block

### ISSUE THREAD

**Issue by Sebazzz** [dotnet/EntityFramework.Docs#4871]
### Type of issue

Missing information

### Description

![Image](https://github.com/user-attachments/assets/a1eb8455-f0f0-46ed-87f0-a71f75b614c2)

That is a complex query 😜

### Page URL

https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-9.0/whatsnew

### Content source URL

https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-9.0/whatsnew.md

### Document Version Independent Id

ae1218ea-8c17-49d5-1ef8-ebdc5082c2e8

### Article author

@ajcvickers

**Comment by roji** [comment]
>That is a complex query 😜

🤣
