### ISSUE TITLE
New feature topic: DbContext pooling

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#501]
Originally from #447.

**Comment by ajcvickers** [comment]
Add known limitations of pooling:
* Context configuration/connection string cannot be changed
* Context cannot depend on additional services
* Context is never really disposed (see https://github.com/aspnet/EntityFrameworkCore/issues/11308 and https://github.com/aspnet/EntityFrameworkCore/issues/11309)

**Comment by AndriySvyryd** [comment]
Related: https://github.com/aspnet/EntityFramework.Docs/issues/1181

**Comment by ajcvickers** [comment]
Also, document what the max pool size means--see https://github.com/dotnet/efcore/issues/19940
