### ISSUE TITLE
New feature topic: pluralization hook for reverse engineering

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#503]
Originally from #447.

**Comment by paulovila** [comment]
Hi, is there any equivalent of **IPluralizer** in 2.1.0?

**Comment by bricelam** [comment]
Instead of mentioning the hook, we should show how to install a Humanizer language package to get pluralization for additional languages.

**Comment by paulovila** [comment]
Would it be possible to differientate when it is generating a navigation property, reverse navigation property, so that they can even be filtered out of the navigation?

**Comment by bricelam** [comment]
You can customize the generated code using templates. See my [EFCore.TextTemplating](https://github.com/bricelam/EFCore.TextTemplating) sample to get started.

Here is the part that generates the navigation properties.

https://github.com/bricelam/EFCore.TextTemplating/blob/c6cbb7f6ff707330c30df890e6494681f678d9e3/EFCore.TextTemplating/MyEntityTypeGenerator.tt#L78-L91
