### ISSUE TITLE
Document DbContext constructor pattern when context to be inherited 

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/EntityFramework.Docs#594]
See discussion here: https://github.com/aspnet/EntityFrameworkCore/issues/7533

In a nutshell:
* A DbContext to be inherited from should have a protected constructor that takes a non-generic DbContextOptions. For example:

```C#
public abstract class MyAbstractContext : DbContext
{
    protected MyAbstractContext(DbContextOptions options)
        : base(options)
    {
    }
}
```

* A DbContext that will be instantiated should have typed, generic DbContextOptions. For example:

```C#
public sealed class MySealedContext : DbContext
{
    public MySealedContext(DbContextOptions<MyContext> options)
        : base(options)
    {
    }
}
```

* A DbContext that might be used in both ways should have both. For example:

```C#
public class MyContext : DbContext
{
    public MyContext(DbContextOptions<MyContext> options)
        : base(options)
    {
    }

    protected MyContext(DbContextOptions options)
        : base(options)
    {
    }
}
```

**Comment by whizkidwwe1217** [comment]
This approach doesn't work. I always getting errors as shown below:
`System.InvalidOperationException: The DbContextOptions passed to the DbContext constructor must be a DbContextOptions<DbContext>. When registering multiple DbContext types make sure that the constructor for each context type has a DbContextOptions<TContext> parameter rather than a non-generic DbContextOptions parameter.`

**Comment by JLunda** [comment]
> See discussion here: [dotnet/efcore#7533](https://github.com/dotnet/efcore/issues/7533)
> 
> In a nutshell:
> 
> * DbContext to be inherited from should have a protected constructor that takes a non-generic DbContextOptions.

According to the discussion in the link provided, I think this first bullet point should say that the protected constructor should take a **generic** DbContextOptions, not a non-generic DbContextOptions.

**Comment by rudiv** [comment]
@JLunda but it is non-generic, ie. it's not `DbContextOptions<..>` (which _is_ generic). The documentation would only not make sense to someone without technical knowledge, which I don't think would be appropriate for this article.

**Comment by JLunda** [comment]
Thanks, @ajcvickers. I reviewed it after the reply @rudiv made, and I can see now that you were talking about generics from the C# language documentation point of view, while I was thinking of non-generic as including generics that were explicitly typed. Thank you for taking the time to add some clarifying examples.
