### ISSUE TITLE
Document simple patterns for custom DDL in migrations with examples

### ISSUE THREAD

**Issue by divega** [dotnet/EntityFramework.Docs#694]
The section at https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations#using-migrationbuildersql shows a very nice pattern that uses MigrationsBuilder.Sql inside an extension method to reuse part of the logic. 

However today I just needed to explain to a customer how to simply call Sql() to maintain stored procedures in migrations and it seems we don't have any basic examples of this in our docs, or even any example that shows that migrations can be customized.

**Comment by ajcvickers** [comment]
See discussion in https://github.com/dotnet/efcore/issues/19740
