### ISSUE TITLE
Please include SQL samples

### ISSUE THREAD

**Issue by JeanCollas** [dotnet/EntityFramework.Docs#756]
Please include in this doc some generated SQL statements, or TSQL models corresponding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* GitHub Login: @julielerman
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Note from team discussion: I looked at the page again and I think it would be useful to show how some of these things map to queries in a relational database. This will make it easier for people to connect the  dots on what is going on.
