### ISSUE TITLE
Clarify what entity states result from Add/Attach/Update on a graph

### ISSUE THREAD

**Issue by JaimeStill** [dotnet/EntityFramework.Docs#786]
## Overview
In the [docs](https://docs.microsoft.com/en-us/ef/core/saving/related-data), it demonstrates how to add an entity with new related entities. What is the recommended method for adding a new entity that is related to an already existing entity?  

***Note***: I wasn't sure whether this issues is more relevant to the EF project itself, or the documentation. As it is more geared towards clarification of best practices, I decided to start here.

## Scenario
Say I am adding an `Item` that is dependent on a `Category`. My categories already exist, but the item that is being added does not. The entities have the following basic structure:

**Item.cs**
``` cs
public class Item
{
    public int Id { get; set; }
    public int CategoryId { get; set; }
    public string Name { get; set; }
    public Category Category { get; set; }
} 
```  

**Category.cs**
```  cs
public class Category
{
    public int Id { get; set; }
    public string Label { get; set; }
    public List<Item> Items { get; set; }
}
```  

The `Item` that I am providing has the following structure:  

``` js
{
    CategoryId: 1,
    Name: "Some Item",
    Category: {
        Id: 1,
        Label: "Some Category"
    }
}
```  

## Problem  
I have the following method for adding an `Item` to the database:  

``` cs
public static async Task AddItem(this AppDbContext db, Item item)
{
    if (item.Validate())
    {
        await db.Items.AddAsync(item);
        await db.SaveChangesAsync();
    }
}
```  

Whenever I try to save this way, it acts as though the related `Category` entity does not exist and tries to add a new instance to the database. In this case, it throws the following error:  

![add-entity-error](https://user-images.githubusercontent.com/14102723/41731390-510d73d2-754c-11e8-95b4-31eb69a8cbcc.png)  

And the following is logged to the Output console in Visual Studio:  

``` cmd
EfAddFromApi.Web> Error Number:544,State:1,Class:16
EfAddFromApi.Web> fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
EfAddFromApi.Web>       Failed executing DbCommand (7ms) [Parameters=[@p0='?' (DbType = Int32), @p1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
EfAddFromApi.Web>       SET NOCOUNT ON;
EfAddFromApi.Web>       INSERT INTO [Category] ([Id], [Label])
EfAddFromApi.Web>       VALUES (@p0, @p1);
EfAddFromApi.Web> System.Data.SqlClient.SqlException (0x80131904): Cannot insert explicit value for identity column in table 'Category' when IDENTITY_INSERT is set to OFF.

```

## Current Workaround  
I can get around this issue by setting any navigation properties to `null` before adding. When I do this, it works as expected.  

**Example**
``` cs
private static void ClearNavProps(this Item item)
{
    item.Category = null;
}

public static async Task AddItem(this AppDbContext db, Item item)
{
    if (item.Validate())
    {
        item.ClearNavProps();
        await db.Items.AddAsync(item);
        await db.SaveChangesAsync();
    }
}
```  

## Demo Application  
[Add to EF Core from Web API](https://github.com/JaimeStill/add-to-ef-from-api)

* `Item` is received from the `AddItem` method in the [`AppController`](https://github.com/JaimeStill/add-to-ef-from-api/blob/master/EfAddFromApi.Web/Controllers/AppController.cs)  
* `AddItem` extension method is defined in [`EntityExtensions`](https://github.com/JaimeStill/add-to-ef-from-api/blob/master/EfAddFromApi.Web/Extensions/EntityExtensions.cs#L30)

**Comment by ajcvickers** [comment]
@JaimeStill Have you read through the [disconnected entities](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities) documentation?

**Comment by JaimeStill** [comment]
@ajcvickers, [disconnected entities - mix of new and existing entities](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities#mix-of-new-and-existing-entities) says  

> Update will mark any entity in the graph, blog or post, for insertion if it does not have a key value set, while all other entities are marked for update.

Will an update for an existing entity be triggered if it has not been modified? I don't need the existing entity to be updated, I just want it to be associated with the new entity.

**Comment by ajcvickers** [comment]
@JaimeStill Attach does the same as update, but marks all the entities as Unchanged--that is, existing in the database but not changed.

**Comment by ajcvickers** [comment]
@JaimeStill What kind of check are you referring to?

**Comment by ajcvickers** [comment]
@JaimeStill Yes, but how is it determined whether it should be added, updated, or attached?

**Comment by JaimeStill** [comment]
@ajcvickers, the [docs](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities#trackgraph) state:

> Internally, Add, Attach, and Update use graph-traversal with a determination made for each entity as to whether it should be marked as Added (to insert), Modified (to update), Unchanged (do nothing), or Deleted (to delete). This mechanism is exposed via the TrackGraph API.  

For auto-generated keys at least, I would propose that if adding a new entity using `Add` that contains an existing entity, if the entity has an ID, then it shouldn't attempt to add the existing entity as shown by the error in the initial post. This would prevent having to nullify navigation properties for existing entities before the new entity is added.

**Comment by ajcvickers** [comment]
@JaimeStill I think what is not clear from the docs is that Attach does what you are asking. That is, if the entity is using store-generated keys and the key value is not set, then it will be marked as Added, otherwise it will be marked as Unchanged.

The reason Add does not do this is because inserting entities with explicit key values can be useful even when the entities are setup to use store-generated keys--for example, in data seeding scenarios. So this means that we can't safely say that because the key is set, then the entity must already exist. However, it is true to say that if the key is not set, then the entity cannot exist, which is why Attach/Update can work the way they do.

**Comment by JaimeStill** [comment]
@ajcvickers, I've been able to get the initial sample working with the below method:

``` cs
public static async Task AddAttach(this AppDbContext db, Item item)
{
    if (item.Validate())
    {
        db.Attach(item);
        await db.SaveChangesAsync();
    }
}
```  

I can see how there is utility in being able to seed new values from the `Add` method, and I really appreciate you taking the time to explain all of this. Just my two cents, there should at least be a way for you to explicitly tell `Add` that you are seeding a complex graph with keys being explicitly provided. Seeding feels more like a one off use case than adding objects from your application.

**Comment by JaimeStill** [comment]
@ajcvickers this is great to see. The information provided by this update is invaluable and much appreciated. Many thanks to you and the EF team.
