### ISSUE TITLE
Xamarin Getting Started Tutorial

### ISSUE THREAD

**Issue by Anil86** [dotnet/EntityFramework.Docs#92]
Similar to what we have for the other platforms in https://docs.microsoft.com/en-us/ef/core/get-started/

**Comment by rowanmiller** [comment]
Xamarin.Forms is currently not supported. Support is tracked by https://github.com/aspnet/EntityFramework/issues/4269

**Comment by JeremyLikness** [comment]
Addressed by [PR 2519](https://github.com/dotnet/EntityFramework.Docs/pull/2519)
