### ISSUE TITLE
Link to Microsoft.Data.Sqlite docs from EF docs where appropriate

### ISSUE THREAD

**Issue by habib-developer** [dotnet/EntityFramework.Docs#934]
Actually, I'm using Entity Framework core 1.0 with my WinForms application and using Sqlite3. I've to ask that is there any way to encrypt SQLite DB and use with EF Core 1.0?

**Comment by ajcvickers** [comment]
@bricelam to respond.

**Comment by bricelam** [comment]
No easy way in EF Core 1.0, but these docs cover [using encryption with Microsoft.Data.Sqlite](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/encryption?tabs=netcore-cli) 3.0. Here's the gist of it:

``` cmd
dotnet remove package Microsoft.EntityFrameworkCore.Sqlite
dotnet add package Microsoft.EntityFrameworkCore.Sqlite.Core
dotnet add package SQLitePCLRaw.bundle_e_sqlcipher
```

``` csharp
options.UseSqlite("Data Source=my.db;Password=myKey");
```

**Comment by ajcvickers** [comment]
See also #2056 for linking the in-memory mode.
