### ISSUE TITLE
Clarify `Effect on dependent/child in memory` column vs `Effect on dependent/child in database`

### ISSUE THREAD

**Issue by ggirard07** [dotnet/EntityFramework.Docs#998]
Does `in memory` refers to entities loaded by the current context instance or to the type of database configured for the context?

- If it refers to entities loaded in memory, then the described behavior for `ClientSetNull (Default)` in optional relationships does not match the behavior of [EF Core saving sample](https://github.com/aspnet/EntityFramework.Docs/blob/master/samples/core/Saving/Saving/CascadeDelete/Sample.cs#L18). FK on child entities are set to NULL in the database by this sample, which means `ClientSetNull` and `SetNull` have the same behaviors for optional relationships.

```
Test using DeleteBehavior.ClientSetNull with optional relationship:

  After loading entities:
    Blog '1' is in state Unchanged with 2 posts referenced.
      Post '1' is in state Unchanged with FK '1' and reference to blog '1'.
      Post '2' is in state Unchanged with FK '1' and reference to blog '1'.

  After deleting blog '1':
    Blog '1' is in state Deleted with 2 posts referenced.
      Post '1' is in state Unchanged with FK '1' and reference to blog '1'.
      Post '2' is in state Unchanged with FK '1' and reference to blog '1'.

  Saving changes:
    UPDATE [Posts] SET [BlogId] = NULL WHERE [PostId] = 1
    UPDATE [Posts] SET [BlogId] = NULL WHERE [PostId] = 2
    DELETE FROM [Blogs] WHERE [BlogId] = 1

  After SaveChanges:
    Blog '1' is in state Detached with 2 posts referenced.
      Post '1' is in state Unchanged with FK 'null' and no reference to a blog.
      Post '2' is in state Unchanged with FK 'null' and no reference to a blog.
```

- If it refers to an in memory database, I don't understand what is the point to have a different behavior based on your documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Cascade Delete - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ggirard07** [comment]
After spending some times with EF delete behavior and the content of this documentation, my current understanding is:

- `in memory` refers to the behavior of EF Core client while handling entities in memory and sending requests to the underlying database.
- `in database` refers to the behavior of EF Core while generating database migrations.

Can you confirm this is the right interpretation?

**Comment by ajcvickers** [comment]
@ggirard07 Correct interpretation.
